// Biology — full curriculum dataset. Module-level content for every topic.
// Organised around a few big models (cell theory, evolution, energy/information flow).
export default {
  subject: 'biology',
  topics: [
    // ================= F1 =================
    { tier: 'F1', order: 1, slug: 'characteristics-classification', title: 'What is Life? Characteristics & Classification',
      summary: 'The characteristics shared by living things, and classification as an organising principle.',
      outcomes: ['List the characteristics of life', 'Explain why we classify organisms', 'Use basic classification groups'],
      concepts: [
        ['Signs of life', 'Living things share features — movement, respiration, sensitivity, growth, reproduction, excretion, nutrition (MRS GREN). These distinguish life from non-life.'],
        ['Classification as a tool', 'Grouping organisms by shared features (not memorising a list) reveals relationships and makes the diversity of life manageable and predictable.'],
      ],
      mistakes: ['Treating classification as a list to memorise rather than a system.', 'Forgetting that plants also respire.', 'Confusing "movement" with only animals.'],
      tricks: ['MRS GREN summarises the seven life processes.', 'Classify by shared features, working from broad to specific.', 'Ask "does it show all life processes?" to test if something is alive.'],
      memory: ['"MRS GREN" — the seven characteristics of life.', '"Group by shared features."', 'Classification reveals relationships.'],
      board: { CBSE: ['Cl.6-7 Living World', 'Cl.9 Diversity in Living Organisms'], ICSE: ['Cl.6-8 Classification'], IB: ['MYP Sciences'] },
      comp: ['NEET'], keywords: ['life', 'classification', 'MRS GREN', 'characteristics', 'organisms'],
      quiz: [
        { lvl: 1, type: 'mcq', prompt: 'Which is NOT one of the seven life processes?', choices: ['magnetism', 'respiration', 'reproduction', 'growth'], answer: 0, explanation: 'MRS GREN lists movement, respiration, sensitivity, growth, reproduction, excretion, nutrition.' },
        { lvl: 2, type: 'mcq', prompt: 'We classify organisms mainly to:', choices: ['reveal relationships and organise diversity', 'make them extinct', 'change their DNA', 'count atoms'], answer: 0, explanation: 'Classification organises and shows evolutionary relationships.' },
      ] },
    { tier: 'F1', order: 2, slug: 'the-cell', title: 'The Cell',
      summary: 'Cell theory, cell structure, and the differences between plant and animal cells.',
      outcomes: ['State cell theory', 'Identify cell structures', 'Compare plant and animal cells'],
      concepts: [
        ['Cell theory', 'All living things are made of cells; the cell is the basic unit of life; cells come from pre-existing cells. This unifying model underlies all of biology.'],
        ['Structure and function', 'Organelles have jobs: the nucleus controls, mitochondria release energy, chloroplasts (plants) capture light. Plant cells add a wall, chloroplasts and a large vacuole.'],
      ],
      mistakes: ['Thinking animal cells have cell walls (only plants do).', 'Confusing the roles of organelles.', 'Forgetting cells come only from existing cells.'],
      tricks: ['Plant extras: wall, chloroplasts, big vacuole.', 'Nucleus = control; mitochondria = energy; chloroplast = photosynthesis.', 'Cell theory: units of life, from pre-existing cells.'],
      memory: ['"Cells are the units of life."', '"Plants add wall, chloroplast, vacuole."', 'Cells come from cells.'],
      board: { CBSE: ['Cl.8 Cell', 'Cl.9 Fundamental Unit of Life'], ICSE: ['Cl.8-9 Cell'], IB: ['DP Cell Biology'] },
      comp: ['NEET'], keywords: ['cell', 'cell theory', 'organelles', 'nucleus', 'mitochondria'],
      quiz: [
        { lvl: 1, type: 'mcq', prompt: 'Which structure is found in plant cells but NOT animal cells?', choices: ['cell wall', 'nucleus', 'mitochondria', 'cell membrane'], answer: 0, explanation: 'Plant cells have a cellulose cell wall; animal cells do not.' },
        { lvl: 2, type: 'mcq', prompt: 'The "powerhouse" organelle that releases energy is the:', choices: ['mitochondrion', 'nucleus', 'vacuole', 'ribosome'], answer: 0, explanation: 'Mitochondria carry out respiration to release energy.' },
      ] },
    { tier: 'F1', order: 3, slug: 'nutrition-digestion', title: 'Nutrition & the Human Digestive System',
      summary: 'Nutrients, a balanced diet, and how the digestive system breaks down food for energy.',
      outcomes: ['Identify major nutrient groups', 'Trace food through digestion', 'Link nutrition to energy'],
      concepts: [
        ['Nutrients and energy', 'Carbohydrates, proteins, fats, vitamins and minerals each have roles; food is the body\'s energy input — linking to the energy accounting seen in physics.'],
        ['Digestion', 'Digestion breaks large food molecules into small absorbable ones, mechanically and by enzymes, as food passes through the gut.'],
      ],
      mistakes: ['Thinking digestion happens only in the stomach.', 'Confusing mechanical and chemical digestion.', 'Forgetting the role of enzymes.'],
      tricks: ['Enzymes chemically break food; teeth and muscles do it mechanically.', 'Absorption mainly happens in the small intestine.', 'Balance the diet across all nutrient groups.'],
      memory: ['"Big molecules → small, absorbable ones."', '"Small intestine = absorption."', 'Food is energy input.'],
      board: { CBSE: ['Cl.7 Nutrition', 'Cl.10 Life Processes'], ICSE: ['Cl.7-9 Nutrition & Digestion'], IB: ['DP Physiology'] },
      comp: ['NEET'], keywords: ['nutrition', 'digestion', 'enzymes', 'nutrients', 'small intestine'],
      quiz: [
        { lvl: 1, type: 'mcq', prompt: 'Most nutrient absorption occurs in the:', choices: ['small intestine', 'stomach', 'mouth', 'large intestine'], answer: 0, explanation: 'The small intestine is adapted for absorption.' },
        { lvl: 2, type: 'mcq', prompt: 'Chemical digestion is carried out mainly by:', choices: ['enzymes', 'teeth', 'bones', 'blood cells'], answer: 0, explanation: 'Enzymes break bonds in food molecules.' },
      ] },
    { tier: 'F1', order: 4, slug: 'living-environment-i', title: 'Living Things & Their Environment I',
      summary: 'Food chains and webs as energy flow, and how organisms depend on each other.',
      outcomes: ['Construct food chains and webs', 'Explain energy flow', 'Describe interdependence'],
      concepts: [
        ['Energy flows through ecosystems', 'Food chains trace energy from producers (plants) to consumers. Energy is lost at each step, so chains are short — an ecological version of energy accounting.'],
        ['Interdependence', 'Organisms depend on each other and their environment; removing one affects many, shown by food webs linking multiple chains.'],
      ],
      mistakes: ['Drawing arrows from consumer to food (they point in the direction of energy flow).', 'Thinking energy is recycled like matter (it flows and is lost).', 'Ignoring producers as the energy source.'],
      tricks: ['Food-chain arrows point the way energy flows (eaten → eater).', 'Producers start every chain by capturing light.', 'Energy is lost as heat at each level, so chains are short.'],
      memory: ['"Arrows follow the energy."', '"Producers first, energy lost each step."', 'Webs link many chains.'],
      board: { CBSE: ['Cl.10 Our Environment'], ICSE: ['Cl.7-8 Ecosystems'], IB: ['DP Ecology'] },
      comp: ['NEET'], keywords: ['food chain', 'food web', 'energy flow', 'producers', 'ecosystem'],
      quiz: [
        { lvl: 1, type: 'mcq', prompt: 'In a food chain, arrows point:', choices: ['in the direction energy flows', 'from predator to prey', 'randomly', 'toward the sun'], answer: 0, explanation: 'Arrows go from the eaten to the eater — the energy direction.' },
        { lvl: 2, type: 'mcq', prompt: 'Every food chain begins with a:', choices: ['producer', 'carnivore', 'decomposer', 'herbivore'], answer: 0, explanation: 'Producers capture energy to start the chain.' },
      ] },

    // ================= F2 =================
    { tier: 'F2', order: 1, slug: 'cells-to-organisms', title: 'Cells to Organisms',
      summary: 'The hierarchy from cells to tissues, organs and systems.',
      outcomes: ['Describe the levels of organisation', 'Relate structure to function', 'Give examples of tissues and organs'],
      concepts: [
        ['Levels of organisation', 'Cells group into tissues, tissues into organs, organs into systems, systems into an organism. Each level does a job the level below cannot alone.'],
        ['Specialisation', 'Cells specialise for their role (nerve cells long, red blood cells packed with haemoglobin). Structure fits function throughout biology.'],
      ],
      mistakes: ['Confusing tissue with organ.', 'Ignoring how specialised structure serves function.', 'Skipping a level in the hierarchy.'],
      tricks: ['Cells → tissues → organs → systems → organism.', 'Specialised shape reveals the cell\'s job.', 'Structure fits function at every level.'],
      memory: ['"Cells → tissues → organs → systems."', '"Structure fits function."', 'Each level adds capability.'],
      board: { CBSE: ['Cl.8-9 Tissues'], ICSE: ['Cl.8-9 Organisation'], IB: ['DP Cell Biology'] },
      comp: ['NEET'], keywords: ['tissue', 'organ', 'system', 'organisation', 'specialisation'],
      xprereqs: ['biology.F1.the-cell'],
      quiz: [
        { lvl: 1, type: 'mcq', prompt: 'The correct order of organisation is:', choices: ['cells → tissues → organs → systems', 'organs → cells → tissues', 'systems → cells → organs', 'tissues → cells → organs'], answer: 0, explanation: 'Cells build tissues, then organs, then systems.' },
        { lvl: 2, type: 'mcq', prompt: 'A red blood cell is packed with haemoglobin because its function is to:', choices: ['carry oxygen', 'fight infection', 'send signals', 'store fat'], answer: 0, explanation: 'Structure (haemoglobin) fits function (oxygen transport).' },
      ] },
    { tier: 'F2', order: 2, slug: 'human-physiology-i', title: 'Human Physiology I',
      summary: 'Respiration, circulation and transport as flow systems in the body.',
      outcomes: ['Describe gas exchange and breathing', 'Explain the circulatory system', 'Relate transport to cell needs'],
      concepts: [
        ['Breathing and respiration', 'Breathing brings oxygen in and removes carbon dioxide; cellular respiration then releases energy from glucose. The two are related but distinct.'],
        ['Circulation as transport', 'The heart pumps blood through vessels to deliver oxygen and nutrients and remove waste — a transport network serving every cell.'],
      ],
      mistakes: ['Using "breathing" and "respiration" interchangeably.', 'Confusing arteries (away from heart) and veins (toward heart).', 'Forgetting blood carries both nutrients and waste.'],
      tricks: ['Breathing = gas exchange; respiration = energy release in cells.', 'Arteries Away from heart; veins toward it.', 'Blood is a delivery-and-collection service.'],
      memory: ['"Breathing ≠ respiration."', '"Arteries Away."', 'Circulation serves every cell.'],
      board: { CBSE: ['Cl.10 Life Processes'], ICSE: ['Cl.9-10 Physiology'], IB: ['DP Physiology'] },
      comp: ['NEET'], keywords: ['respiration', 'circulation', 'heart', 'blood', 'transport'],
      quiz: [
        { lvl: 1, type: 'mcq', prompt: 'Arteries carry blood:', choices: ['away from the heart', 'toward the heart', 'only to the lungs', 'in circles'], answer: 0, explanation: 'Arteries carry blood away from the heart.' },
        { lvl: 2, type: 'mcq', prompt: 'Cellular respiration releases energy from:', choices: ['glucose', 'water', 'carbon dioxide', 'nitrogen'], answer: 0, explanation: 'Glucose is oxidised to release energy.' },
      ] },
    { tier: 'F2', order: 3, slug: 'plant-biology-i', title: 'Plant Biology I',
      summary: 'Photosynthesis as energy capture, and transport in plants.',
      outcomes: ['Describe photosynthesis', 'Explain transport in plants', 'Relate leaves to their function'],
      concepts: [
        ['Photosynthesis', 'Plants capture light energy to make glucose from carbon dioxide and water, releasing oxygen. This is the entry point of energy into most food chains.'],
        ['Plant transport', 'Xylem carries water up from roots; phloem carries sugars around the plant. Leaves are adapted (broad, thin, full of chloroplasts) to capture light.'],
      ],
      mistakes: ['Thinking plants do not respire (they do, all the time).', 'Confusing xylem (water) and phloem (sugars).', 'Believing plants get "food" from the soil rather than making it.'],
      tricks: ['Photosynthesis: light + CO₂ + water → glucose + oxygen.', 'Xylem up (water), phloem all around (sugars).', 'Leaves are solar panels — broad and thin.'],
      memory: ['"Plants make food from light."', '"Xylem = water up; phloem = food around."', 'Plants respire too.'],
      board: { CBSE: ['Cl.7 Nutrition in Plants', 'Cl.10 Life Processes'], ICSE: ['Cl.7-9 Plant Physiology'], IB: ['DP Plant Biology'] },
      comp: ['NEET'], keywords: ['photosynthesis', 'xylem', 'phloem', 'transport', 'plants'],
      xprereqs: ['biology.F1.living-environment-i'],
      quiz: [
        { lvl: 1, type: 'mcq', prompt: 'Photosynthesis releases which gas?', choices: ['oxygen', 'carbon dioxide', 'nitrogen', 'hydrogen'], answer: 0, explanation: 'Oxygen is released as a by-product.' },
        { lvl: 2, type: 'mcq', prompt: 'Water travels up a plant through the:', choices: ['xylem', 'phloem', 'stomata', 'roots hairs only'], answer: 0, explanation: 'Xylem transports water upward.' },
      ] },
    { tier: 'F2', order: 4, slug: 'reproduction', title: 'Reproduction',
      summary: 'Asexual and sexual reproduction, and the human reproductive system.',
      outcomes: ['Compare asexual and sexual reproduction', 'Describe human reproduction', 'Explain variation from sexual reproduction'],
      concepts: [
        ['Two strategies', 'Asexual reproduction makes identical offspring from one parent (fast, no variation). Sexual reproduction combines two parents\' genes, producing variation — the raw material for evolution.'],
        ['Human reproduction', 'Sexual reproduction in humans joins sperm and egg; the resulting variation is why siblings differ. This links directly to later genetics.'],
      ],
      mistakes: ['Thinking asexual offspring show variation (they are clones).', 'Confusing the roles of gametes.', 'Ignoring the link between sexual reproduction and variation.'],
      tricks: ['Asexual = one parent, identical; sexual = two parents, varied.', 'Gametes (sperm, egg) carry half the genes each.', 'Variation comes from mixing two genomes.'],
      memory: ['"Asexual clones; sexual varies."', '"Gametes carry half."', 'Sexual reproduction → variation → evolution.'],
      board: { CBSE: ['Cl.8 Reproduction', 'Cl.10 How Organisms Reproduce'], ICSE: ['Cl.8-10 Reproduction'], IB: ['DP Reproduction'] },
      comp: ['NEET'], keywords: ['reproduction', 'asexual', 'sexual', 'gametes', 'variation'],
      quiz: [
        { lvl: 1, type: 'mcq', prompt: 'Asexual reproduction produces offspring that are:', choices: ['genetically identical to the parent', 'always different', 'from two parents', 'sterile'], answer: 0, explanation: 'One parent → identical clones.' },
        { lvl: 2, type: 'mcq', prompt: 'Sexual reproduction is important for evolution because it produces:', choices: ['variation', 'identical clones', 'fewer offspring', 'no offspring'], answer: 0, explanation: 'Genetic variation is the raw material for natural selection.' },
      ] },
    { tier: 'F2', order: 5, slug: 'health-disease', title: 'Health & Disease',
      summary: 'Pathogens, how disease spreads, immunity and prevention.',
      outcomes: ['Identify types of pathogen', 'Explain how disease spreads', 'Describe immunity and prevention'],
      concepts: [
        ['Pathogens', 'Bacteria, viruses, fungi and parasites cause infectious disease, spreading by air, water, contact or vectors. Understanding the route guides prevention.'],
        ['Immunity', 'The immune system recognises and destroys pathogens; vaccines train it in advance. Hygiene and vaccination are the front line of prevention.'],
      ],
      mistakes: ['Thinking antibiotics work on viruses (they treat bacteria).', 'Confusing the pathogen types.', 'Ignoring transmission routes in prevention.'],
      tricks: ['Antibiotics target bacteria, not viruses.', 'Break the transmission route to prevent spread.', 'Vaccines prime immunity before infection.'],
      memory: ['"Antibiotics ≠ antivirals."', '"Block the route, stop the spread."', 'Vaccines train the immune system.'],
      board: { CBSE: ['Cl.9 Why Do We Fall Ill'], ICSE: ['Cl.8-10 Health & Disease'], IB: ['DP Human Health'] },
      comp: ['NEET'], keywords: ['pathogen', 'disease', 'immunity', 'vaccine', 'prevention'],
      quiz: [
        { lvl: 1, type: 'mcq', prompt: 'Antibiotics are effective against:', choices: ['bacteria', 'viruses', 'all pathogens', 'nothing'], answer: 0, explanation: 'Antibiotics treat bacterial infections, not viral ones.' },
        { lvl: 2, type: 'mcq', prompt: 'A vaccine works by:', choices: ['training the immune system in advance', 'killing all bacteria in the body', 'replacing blood', 'raising body temperature'], answer: 0, explanation: 'It primes immunity so the body responds fast to real infection.' },
      ] },

    // ================= I1 =================
    { tier: 'I1', order: 1, slug: 'cell-processes', title: 'Cell Processes',
      summary: 'Diffusion, osmosis and active transport — how substances cross membranes.',
      outcomes: ['Explain diffusion and osmosis', 'Describe active transport', 'Relate transport to concentration'],
      concepts: [
        ['Passive movement', 'Diffusion moves particles from high to low concentration; osmosis is the diffusion of water across a membrane. Both are passive — no energy needed.'],
        ['Active transport', 'Moving substances against a concentration gradient needs energy (active transport). Cells use it to absorb nutrients even when scarce.'],
      ],
      mistakes: ['Confusing diffusion (any particle) with osmosis (water specifically).', 'Thinking active transport needs no energy.', 'Getting the direction of net movement wrong.'],
      tricks: ['Diffusion & osmosis go high → low (passive).', 'Active transport goes low → high and costs energy.', 'Osmosis is specifically water across a membrane.'],
      memory: ['"Passive: high to low; active: low to high (needs energy)."', '"Osmosis = water only."', 'Concentration gradient sets direction.'],
      board: { CBSE: ['Cl.9-11 Transport across Membranes'], ICSE: ['Cl.9-10 Cell Transport'], IB: ['DP Membrane Transport'] },
      comp: ['NEET'], keywords: ['diffusion', 'osmosis', 'active transport', 'membrane', 'concentration gradient'],
      xprereqs: ['chemistry.I1.solutions-concentration'],
      quiz: [
        { lvl: 1, type: 'mcq', prompt: 'Osmosis is the movement of ___ across a membrane.', choices: ['water', 'glucose', 'oxygen', 'protein'], answer: 0, explanation: 'Osmosis specifically refers to water movement.' },
        { lvl: 2, type: 'mcq', prompt: 'Active transport differs from diffusion because it:', choices: ['requires energy and can go against the gradient', 'is always faster', 'needs no membrane', 'only moves water'], answer: 0, explanation: 'Active transport uses energy to move against the gradient.' },
      ] },
    { tier: 'I1', order: 2, slug: 'enzymes', title: 'Enzymes',
      summary: 'Enzymes as biological catalysts, and the factors that affect their activity.',
      outcomes: ['Explain enzyme action', 'Describe factors affecting enzymes', 'Relate enzymes to reaction rate'],
      concepts: [
        ['Biological catalysts', 'Enzymes speed up reactions by lowering activation energy, binding substrates at an active site (lock-and-key). They are not used up — reusing the catalyst idea from chemistry.'],
        ['Sensitive to conditions', 'Temperature and pH affect enzyme shape; too much denatures them permanently. Each enzyme has an optimum, explaining why body temperature matters.'],
      ],
      mistakes: ['Thinking enzymes are used up in reactions.', 'Confusing denaturation (permanent) with slowing (reversible).', 'Ignoring pH effects on enzymes.'],
      tricks: ['Enzymes lower activation energy (like catalysts).', 'Each enzyme has an optimum temperature and pH.', 'High heat denatures — permanent shape change.'],
      memory: ['"Enzymes are reusable biological catalysts."', '"Lock and key" active site.', 'Denaturation is permanent.'],
      board: { CBSE: ['Cl.11 Biomolecules (Enzymes)'], ICSE: ['Cl.10-11 Enzymes'], IB: ['DP Enzymes'] },
      comp: ['NEET'], keywords: ['enzymes', 'catalyst', 'active site', 'denaturation', 'activation energy'],
      xprereqs: ['chemistry.I1.rates-reaction'],
      quiz: [
        { lvl: 1, type: 'mcq', prompt: 'Enzymes speed up reactions by:', choices: ['lowering activation energy', 'raising temperature', 'adding mass', 'being consumed'], answer: 0, explanation: 'They provide a lower-energy pathway and are reusable.' },
        { lvl: 2, type: 'mcq', prompt: 'High temperature can ___ an enzyme.', choices: ['denature', 'strengthen', 'multiply', 'freeze'], answer: 0, explanation: 'Heat changes the active site shape permanently.' },
      ] },
    { tier: 'I1', order: 3, slug: 'respiration-photosynthesis', title: 'Respiration & Photosynthesis (Biochemical)',
      summary: 'The energy budgets of respiration and photosynthesis, quantitatively.',
      outcomes: ['Write respiration and photosynthesis equations', 'Compare the two processes', 'Relate them to energy flow'],
      concepts: [
        ['Two complementary processes', 'Photosynthesis stores light energy in glucose; respiration releases it. They are near-opposites, and together drive energy flow through ecosystems.'],
        ['Aerobic vs anaerobic', 'Aerobic respiration (with oxygen) releases much more energy than anaerobic. The equations reveal the reactants and products precisely.'],
      ],
      mistakes: ['Thinking only animals respire (all living cells do).', 'Confusing the reactants and products of the two processes.', 'Forgetting anaerobic respiration yields less energy.'],
      tricks: ['Respiration: glucose + oxygen → CO₂ + water + energy.', 'Photosynthesis is essentially the reverse.', 'Aerobic yields far more energy than anaerobic.'],
      memory: ['"Photosynthesis stores, respiration releases."', '"They are near-opposites."', 'Aerobic > anaerobic energy.'],
      board: { CBSE: ['Cl.10 Life Processes', 'Cl.11 Respiration & Photosynthesis'], ICSE: ['Cl.10-11 Biochemistry'], IB: ['DP Bioenergetics'] },
      comp: ['NEET'], keywords: ['respiration', 'photosynthesis', 'aerobic', 'anaerobic', 'glucose'],
      xprereqs: ['biology.F2.plant-biology-i'],
      quiz: [
        { lvl: 2, type: 'mcq', prompt: 'Aerobic respiration produces energy plus carbon dioxide and:', choices: ['water', 'oxygen', 'glucose', 'nitrogen'], answer: 0, explanation: 'Glucose + oxygen → CO₂ + water + energy.' },
        { lvl: 2, type: 'mcq', prompt: 'Compared with aerobic respiration, anaerobic respiration releases:', choices: ['less energy', 'more energy', 'the same energy', 'no products'], answer: 0, explanation: 'Without oxygen, glucose is only partly broken down.' },
      ] },
    { tier: 'I1', order: 4, slug: 'human-physiology-ii', title: 'Human Physiology II',
      summary: 'Nervous and endocrine coordination, and homeostasis as feedback control.',
      outcomes: ['Compare nervous and hormonal control', 'Explain homeostasis', 'Describe negative feedback'],
      concepts: [
        ['Two control systems', 'The nervous system sends fast electrical signals; the endocrine system sends slower, longer-lasting hormones. Together they coordinate the body.'],
        ['Homeostasis', 'The body keeps internal conditions stable (temperature, glucose) using negative feedback — deviations trigger corrections, like a thermostat.'],
      ],
      mistakes: ['Confusing fast nervous signals with slower hormonal ones.', 'Thinking homeostasis means "no change" rather than "controlled change".', 'Reversing negative feedback logic.'],
      tricks: ['Nervous = fast & brief; hormonal = slow & lasting.', 'Negative feedback opposes the change to restore balance.', 'Think thermostat for homeostasis.'],
      memory: ['"Nerves fast, hormones lasting."', '"Negative feedback restores balance."', 'Homeostasis = controlled stability.'],
      board: { CBSE: ['Cl.10 Control & Coordination'], ICSE: ['Cl.10-11 Coordination'], IB: ['DP Homeostasis'] },
      comp: ['NEET'], keywords: ['nervous system', 'hormones', 'homeostasis', 'feedback', 'coordination'],
      xprereqs: ['biology.F2.human-physiology-i'],
      quiz: [
        { lvl: 1, type: 'mcq', prompt: 'Which control system uses hormones?', choices: ['endocrine', 'nervous', 'skeletal', 'digestive'], answer: 0, explanation: 'The endocrine system uses chemical hormones.' },
        { lvl: 2, type: 'mcq', prompt: 'Negative feedback acts to:', choices: ['oppose a change and restore balance', 'amplify a change', 'stop all reactions', 'raise temperature only'], answer: 0, explanation: 'It corrects deviations to keep conditions stable.' },
      ] },
    { tier: 'I1', order: 5, slug: 'ecology-ecosystems', title: 'Ecology & Ecosystems',
      summary: 'Energy pyramids, nutrient cycles and population basics.',
      outcomes: ['Interpret energy pyramids', 'Describe nutrient cycles', 'Explain population change'],
      concepts: [
        ['Energy pyramids', 'Energy decreases up trophic levels (only ~10% passes on), so top predators are few. This explains pyramid shapes and short food chains.'],
        ['Cycles', 'Matter (carbon, nitrogen, water) cycles through ecosystems, unlike energy which flows through and is lost. Decomposers return nutrients to the soil.'],
      ],
      mistakes: ['Thinking energy is recycled like matter.', 'Forgetting decomposers in nutrient cycles.', 'Assuming top predators are abundant.'],
      tricks: ['~10% of energy passes to the next level.', 'Matter cycles; energy flows and is lost.', 'Decomposers recycle nutrients.'],
      memory: ['"10% rule up the pyramid."', '"Matter cycles, energy flows."', 'Decomposers close the loop.'],
      board: { CBSE: ['Cl.10 Our Environment'], ICSE: ['Cl.9-10 Ecology'], IB: ['DP Ecology'] },
      comp: ['NEET'], keywords: ['ecology', 'energy pyramid', 'nutrient cycle', 'trophic level', 'decomposers'],
      xprereqs: ['biology.F1.living-environment-i'],
      quiz: [
        { lvl: 2, type: 'mcq', prompt: 'Roughly what fraction of energy passes to the next trophic level?', choices: ['10%', '50%', '90%', '100%'], answer: 0, explanation: 'About 10%; the rest is lost mainly as heat.' },
        { lvl: 2, type: 'mcq', prompt: 'In ecosystems, matter (like carbon) is:', choices: ['cycled', 'lost forever', 'created', 'converted to energy'], answer: 0, explanation: 'Matter cycles while energy flows through and is lost.' },
      ] },

    // ================= I2 =================
    { tier: 'I2', order: 1, slug: 'genetics-i', title: 'Genetics I: Inheritance',
      summary: 'Mendel\'s laws and monohybrid/dihybrid crosses — genetics as probability.',
      outcomes: ['Use Mendelian ratios', 'Complete Punnett squares', 'Explain dominant and recessive alleles'],
      concepts: [
        ['Genes come in pairs', 'Each trait has two alleles, one from each parent; dominant alleles mask recessive ones. Mendel discovered these inheritance patterns from breeding experiments.'],
        ['Genetics is probability', 'Punnett squares predict offspring ratios (like 3:1) — this is exactly the probability from maths applied to inheritance, an interleaving in action.'],
      ],
      mistakes: ['Confusing genotype (alleles) with phenotype (appearance).', 'Misreading Punnett square ratios.', 'Thinking dominant means "more common".'],
      tricks: ['Use a Punnett square to combine parental alleles.', 'A monohybrid cross of two heterozygotes gives 3:1.', 'Dominant masks recessive — it is not about frequency.'],
      memory: ['"Two alleles, dominant masks recessive."', '"3:1 from Aa × Aa."', 'Genetics = probability.'],
      board: { CBSE: ['Cl.10 Heredity & Evolution', 'Cl.12 Genetics'], ICSE: ['Cl.10-12 Genetics'], IB: ['DP Genetics'] },
      comp: ['NEET'], keywords: ['genetics', 'Mendel', 'Punnett square', 'dominant', 'recessive'],
      xprereqs: ['math.F2.probability-statistics-i'],
      quiz: [
        { lvl: 2, type: 'mcq', prompt: 'A cross Aa × Aa gives a phenotype ratio of:', choices: ['3:1', '1:1', '9:3:3:1', '2:1'], answer: 0, explanation: 'Monohybrid heterozygous cross → 3 dominant : 1 recessive.' },
        { lvl: 1, type: 'mcq', prompt: 'An organism\'s observable traits are its:', choices: ['phenotype', 'genotype', 'alleles', 'chromosomes'], answer: 0, explanation: 'Phenotype = appearance; genotype = allele makeup.' },
      ] },
    { tier: 'I2', order: 2, slug: 'dna-inheritance', title: 'DNA & the Molecular Basis of Inheritance',
      summary: 'DNA structure, replication and the central dogma — information flow in cells.',
      outcomes: ['Describe DNA structure', 'Explain replication', 'State the central dogma'],
      concepts: [
        ['DNA stores information', 'DNA is a double helix; the base sequence encodes instructions. Complementary base pairing (A-T, C-G) lets it copy itself faithfully.'],
        ['Central dogma', 'Information flows DNA → RNA → protein: genes are transcribed to RNA and translated to proteins that do the work. This information model unifies molecular biology.'],
      ],
      mistakes: ['Mispairing bases (A pairs with T, C with G).', 'Confusing transcription with translation.', 'Thinking DNA itself builds structures (proteins do).'],
      tricks: ['Base pairs: A-T and C-G.', 'DNA → RNA (transcription) → protein (translation).', 'Complementary pairing enables faithful copying.'],
      memory: ['"A-T, C-G."', '"DNA → RNA → protein."', 'Genes carry information; proteins do the work.'],
      board: { CBSE: ['Cl.12 Molecular Basis of Inheritance'], ICSE: ['Cl.12 DNA'], IB: ['DP Molecular Biology'] },
      comp: ['NEET'], keywords: ['DNA', 'replication', 'central dogma', 'transcription', 'translation'],
      xprereqs: ['biology.I2.genetics-i'],
      quiz: [
        { lvl: 1, type: 'mcq', prompt: 'In DNA, adenine (A) pairs with:', choices: ['thymine (T)', 'cytosine (C)', 'guanine (G)', 'uracil (U)'], answer: 0, explanation: 'A-T and C-G are the complementary pairs.' },
        { lvl: 2, type: 'mcq', prompt: 'The central dogma describes information flow from:', choices: ['DNA to RNA to protein', 'protein to DNA', 'RNA to DNA only', 'protein to RNA'], answer: 0, explanation: 'DNA → RNA → protein.' },
      ] },
    { tier: 'I2', order: 3, slug: 'evolution-natural-selection', title: 'Evolution & Natural Selection',
      summary: 'The unifying theory of biology: evidence and mechanism of natural selection.',
      outcomes: ['Explain natural selection', 'Cite evidence for evolution', 'Relate variation to adaptation'],
      concepts: [
        ['Natural selection', 'Individuals vary; those better suited to the environment survive and reproduce more, passing on their traits. Over generations, populations adapt.'],
        ['The unifying theory', 'Evolution explains the diversity and relatedness of life. Evidence comes from fossils, anatomy, and DNA — a single framework for all biology.'],
      ],
      mistakes: ['Thinking individuals evolve (populations do, over generations).', 'Believing organisms change to "try" to adapt (variation is random, selection is not).', 'Confusing evidence types.'],
      tricks: ['Variation + selection + inheritance + time → evolution.', 'Selection acts on populations, not individuals.', 'DNA similarity measures relatedness.'],
      memory: ['"Variation, selection, inheritance, time."', '"Populations evolve, not individuals."', 'One theory unifies biology.'],
      board: { CBSE: ['Cl.10 Heredity & Evolution', 'Cl.12 Evolution'], ICSE: ['Cl.10-12 Evolution'], IB: ['DP Evolution'] },
      comp: ['NEET'], keywords: ['evolution', 'natural selection', 'adaptation', 'variation', 'evidence'],
      xprereqs: ['biology.F2.reproduction'],
      quiz: [
        { lvl: 2, type: 'mcq', prompt: 'Natural selection acts most directly on:', choices: ['populations over generations', 'a single individual\'s lifetime', 'non-living matter', 'random atoms'], answer: 0, explanation: 'Allele frequencies shift in populations across generations.' },
        { lvl: 2, type: 'mcq', prompt: 'Which is evidence for evolution?', choices: ['DNA similarities between species', 'the colour of the sky', 'gravity', 'the water cycle'], answer: 0, explanation: 'Molecular, fossil and anatomical evidence all support evolution.' },
      ] },
    { tier: 'I2', order: 4, slug: 'population-biology', title: 'Population Biology',
      summary: 'Exponential and logistic growth, and what limits populations.',
      outcomes: ['Model population growth', 'Explain limiting factors', 'Use exponential/logistic ideas'],
      concepts: [
        ['Growth models', 'Unchecked populations grow exponentially; real ones level off (logistic) as resources limit them at the carrying capacity — reusing exponentials from maths.'],
        ['Limiting factors', 'Food, space, predators and disease limit growth. Understanding them predicts population dynamics and informs conservation.'],
      ],
      mistakes: ['Assuming populations grow forever exponentially.', 'Confusing carrying capacity with maximum ever recorded.', 'Ignoring density-dependent factors.'],
      tricks: ['Exponential early, logistic as limits bite.', 'Carrying capacity is the sustainable ceiling.', 'Limiting factors can be density-dependent (disease) or independent (weather).'],
      memory: ['"Exponential → logistic at carrying capacity."', '"Resources set the ceiling."', 'Population biology reuses exponentials.'],
      board: { CBSE: ['Cl.12 Ecology (Populations)'], ICSE: ['Cl.11-12 Population Ecology'], IB: ['DP Ecology'] },
      comp: ['NEET'], keywords: ['population', 'exponential growth', 'logistic', 'carrying capacity', 'limiting factors'],
      xprereqs: ['math.I2.exponentials-logarithms'],
      quiz: [
        { lvl: 2, type: 'mcq', prompt: 'A population levels off at its:', choices: ['carrying capacity', 'exponential phase', 'starting size', 'minimum'], answer: 0, explanation: 'Carrying capacity is the sustainable maximum.' },
        { lvl: 2, type: 'mcq', prompt: 'Early, unlimited population growth is:', choices: ['exponential', 'linear', 'zero', 'decreasing'], answer: 0, explanation: 'Growth compounds — exponential — until limits apply.' },
      ] },
    { tier: 'I2', order: 5, slug: 'human-systems-capstone', title: 'Human Systems Capstone',
      summary: 'Integrated case studies connecting the body\'s systems.',
      outcomes: ['Integrate multiple body systems', 'Analyse a physiological case', 'Explain system interactions'],
      concepts: [
        ['Systems work together', 'No system acts alone: exercise links muscles, circulation, respiration and the nervous system. Case studies reveal these interactions.'],
        ['Reasoning across systems', 'Given a scenario (e.g., dehydration), predict how several systems respond — the integrative thinking exams and real medicine require.'],
      ],
      mistakes: ['Analysing one system in isolation.', 'Missing feedback links between systems.', 'Forgetting homeostasis ties systems together.'],
      tricks: ['Ask "which systems respond?" for any scenario.', 'Trace feedback loops across systems.', 'Homeostasis is the common thread.'],
      memory: ['"Systems collaborate."', '"Trace the feedback across systems."', 'Homeostasis links everything.'],
      board: { CBSE: ['Cl.10-12 Integrated Physiology'], ICSE: ['Cl.10-12 Physiology'], IB: ['DP Physiology'] },
      comp: ['NEET'], keywords: ['integration', 'body systems', 'case study', 'homeostasis'],
      xprereqs: ['biology.I1.human-physiology-ii'],
      quiz: [
        { lvl: 2, type: 'mcq', prompt: 'During exercise, which systems must work together?', choices: ['muscular, circulatory, respiratory and nervous', 'only the muscular', 'only the digestive', 'none'], answer: 0, explanation: 'Multiple systems coordinate to meet demand.' },
        { lvl: 3, type: 'mcq', prompt: 'The common principle linking the body\'s systems is:', choices: ['homeostasis', 'photosynthesis', 'osmosis only', 'digestion'], answer: 0, explanation: 'Systems cooperate to maintain internal stability.' },
      ] },

    // ================= A1 =================
    { tier: 'A1', order: 1, slug: 'cell-biology-depth', title: 'Cell Biology at Depth',
      summary: 'Membrane transport, the cell cycle, and cell division (mitosis and meiosis).',
      outcomes: ['Detail membrane transport', 'Describe the cell cycle', 'Compare mitosis and meiosis'],
      concepts: [
        ['Cell cycle and division', 'Cells grow and divide in a controlled cycle. Mitosis makes two identical cells (growth, repair); meiosis makes four genetically varied gametes (reproduction).'],
        ['Why meiosis matters', 'Meiosis halves the chromosome number and shuffles genes, creating the variation that Genetics I described. It is the molecular source of inherited diversity.'],
      ],
      mistakes: ['Confusing mitosis (identical) with meiosis (varied, halved).', 'Forgetting meiosis produces gametes.', 'Miscounting chromosome numbers.'],
      tricks: ['Mitosis: 2 identical cells; meiosis: 4 varied gametes.', 'Meiosis halves chromosomes and shuffles genes.', 'Link meiosis to the variation in genetics.'],
      memory: ['"Mitosis mirrors; meiosis mixes and halves."', '"Meiosis → gametes → variation."', 'Division is tightly controlled.'],
      board: { CBSE: ['Cl.11 Cell Cycle & Division'], ICSE: ['Cl.11 Cell Division'], IB: ['DP Cell Biology HL'] },
      comp: ['NEET'], keywords: ['cell cycle', 'mitosis', 'meiosis', 'division', 'membrane transport'],
      xprereqs: ['biology.I1.cell-processes'],
      quiz: [
        { lvl: 2, type: 'mcq', prompt: 'Meiosis produces:', choices: ['four genetically varied gametes', 'two identical cells', 'one giant cell', 'no cells'], answer: 0, explanation: 'Meiosis makes four haploid, varied gametes.' },
        { lvl: 2, type: 'mcq', prompt: 'Mitosis is used for:', choices: ['growth and repair', 'making gametes', 'reducing chromosome number', 'digestion'], answer: 0, explanation: 'Mitosis makes identical cells for growth and repair.' },
      ] },
    { tier: 'A1', order: 2, slug: 'molecular-genetics', title: 'Molecular Genetics',
      summary: 'Transcription, translation and gene regulation in detail.',
      outcomes: ['Detail transcription and translation', 'Explain the genetic code', 'Describe gene regulation'],
      concepts: [
        ['Gene expression', 'Transcription copies a gene to mRNA; translation reads mRNA codons (three bases) to build a protein from amino acids. The genetic code maps codons to amino acids.'],
        ['Regulation', 'Cells switch genes on and off so the right proteins are made at the right time — why a nerve cell and a skin cell differ despite identical DNA.'],
      ],
      mistakes: ['Confusing codons (mRNA) with the DNA template.', 'Thinking all genes are always active.', 'Mixing up transcription and translation locations.'],
      tricks: ['Codon = three bases = one amino acid.', 'Transcription in nucleus, translation at ribosomes.', 'Gene regulation explains cell specialisation.'],
      memory: ['"Three bases = one amino acid."', '"Transcribe then translate."', 'Same DNA, different genes active.'],
      board: { CBSE: ['Cl.12 Molecular Basis of Inheritance'], ICSE: ['Cl.12 Molecular Genetics'], IB: ['DP Molecular Biology HL'] },
      comp: ['NEET'], keywords: ['transcription', 'translation', 'codon', 'gene regulation', 'genetic code'],
      xprereqs: ['biology.I2.dna-inheritance'],
      quiz: [
        { lvl: 2, type: 'mcq', prompt: 'A codon consists of how many bases?', choices: ['three', 'one', 'two', 'four'], answer: 0, explanation: 'Three bases code for one amino acid.' },
        { lvl: 3, type: 'mcq', prompt: 'Why do a nerve cell and skin cell differ despite identical DNA?', choices: ['different genes are switched on', 'they have different DNA', 'they lack nuclei', 'they use different codes'], answer: 0, explanation: 'Gene regulation activates different genes in each.' },
      ] },
    { tier: 'A1', order: 3, slug: 'biochemistry', title: 'Biochemistry',
      summary: 'Biomolecules and an overview of metabolic pathways — shared with chemistry.',
      outcomes: ['Describe major biomolecules', 'Outline metabolism', 'Relate structure to function'],
      concepts: [
        ['Molecules of life', 'Carbohydrates, lipids, proteins and nucleic acids each have structures suiting their roles. This connects directly to chemistry\'s biomolecules topic.'],
        ['Metabolism', 'Metabolic pathways are linked reactions building (anabolism) or breaking down (catabolism) molecules, controlled by enzymes, releasing or storing energy.'],
      ],
      mistakes: ['Confusing anabolism (building) with catabolism (breaking).', 'Ignoring enzymes\' control of pathways.', 'Forgetting structure-function links.'],
      tricks: ['Anabolism builds up; catabolism breaks down.', 'Enzymes control every metabolic step.', 'Structure fits function in every biomolecule.'],
      memory: ['"Anabolism builds, catabolism breaks."', '"Enzymes run metabolism."', 'Structure fits function.'],
      board: { CBSE: ['Cl.11 Biomolecules'], ICSE: ['Cl.11-12 Biochemistry'], IB: ['DP Biochemistry HL'] },
      comp: ['NEET'], keywords: ['biochemistry', 'metabolism', 'anabolism', 'catabolism', 'biomolecules'],
      xprereqs: ['chemistry.I2.organic-intro'],
      quiz: [
        { lvl: 2, type: 'mcq', prompt: 'Reactions that build large molecules from small ones are:', choices: ['anabolic', 'catabolic', 'osmotic', 'ionic'], answer: 0, explanation: 'Anabolism builds; catabolism breaks down.' },
        { lvl: 2, type: 'mcq', prompt: 'Metabolic pathways are controlled by:', choices: ['enzymes', 'gravity', 'sunlight only', 'the nervous system alone'], answer: 0, explanation: 'Enzymes catalyse and regulate each step.' },
      ] },
    { tier: 'A1', order: 4, slug: 'plant-physiology-depth', title: 'Plant Physiology at Depth',
      summary: 'Mechanisms of photosynthesis and respiration, transport and plant hormones.',
      outcomes: ['Detail photosynthesis mechanisms', 'Explain plant transport in depth', 'Describe plant hormones'],
      concepts: [
        ['Photosynthesis mechanism', 'Photosynthesis has light-dependent reactions (capturing energy) and light-independent reactions (fixing carbon). Understanding both explains how plants store energy.'],
        ['Control and transport', 'Transpiration pulls water up; plant hormones (auxins) control growth toward light. Plants sense and respond to their environment.'],
      ],
      mistakes: ['Merging the light and carbon-fixing stages.', 'Confusing transpiration with respiration.', 'Ignoring hormonal control of growth.'],
      tricks: ['Light reactions capture energy; the Calvin cycle fixes carbon.', 'Transpiration is water loss driving uptake.', 'Auxins bend plants toward light.'],
      memory: ['"Light stage then carbon stage."', '"Transpiration pulls water up."', 'Auxins steer growth.'],
      board: { CBSE: ['Cl.11 Plant Physiology'], ICSE: ['Cl.11-12 Plant Physiology'], IB: ['DP Plant Biology HL'] },
      comp: ['NEET'], keywords: ['photosynthesis', 'transpiration', 'auxin', 'plant hormones', 'Calvin cycle'],
      xprereqs: ['biology.I1.respiration-photosynthesis'],
      quiz: [
        { lvl: 2, type: 'mcq', prompt: 'The light-independent reactions of photosynthesis mainly:', choices: ['fix carbon into sugars', 'capture light', 'release oxygen', 'break down glucose'], answer: 0, explanation: 'The Calvin cycle fixes CO₂ into sugar using energy from the light stage.' },
        { lvl: 2, type: 'mcq', prompt: 'Auxins cause a plant shoot to:', choices: ['grow toward light', 'stop growing', 'lose water', 'produce oxygen'], answer: 0, explanation: 'Auxins drive phototropism.' },
      ] },
    { tier: 'A1', order: 5, slug: 'human-physiology-iii', title: 'Human Physiology III',
      summary: 'Detailed digestive, circulatory, excretory and nervous systems.',
      outcomes: ['Detail organ system function', 'Explain excretion and the kidney', 'Describe the neuron and impulse'],
      concepts: [
        ['Systems in detail', 'Each system is examined at organ and tissue level: the kidney filters blood and balances water; neurons transmit electrical impulses across synapses.'],
        ['Integration', 'These detailed mechanisms build on earlier physiology, showing how fine structure achieves function — the recurring biology theme.'],
      ],
      mistakes: ['Confusing filtration and reabsorption in the kidney.', 'Mixing up neuron parts.', 'Ignoring how detailed structure serves function.'],
      tricks: ['Kidney: filter, then reabsorb what the body needs.', 'Neuron: dendrites in, axon out, synapse across.', 'Detailed structure always serves a function.'],
      memory: ['"Filter then reabsorb (kidney)."', '"Dendrite in, axon out."', 'Structure serves function.'],
      board: { CBSE: ['Cl.11 Human Physiology'], ICSE: ['Cl.11-12 Physiology'], IB: ['DP Physiology HL'] },
      comp: ['NEET'], keywords: ['physiology', 'kidney', 'neuron', 'excretion', 'synapse'],
      xprereqs: ['biology.I2.human-systems-capstone'],
      quiz: [
        { lvl: 2, type: 'mcq', prompt: 'The kidney\'s main job is to:', choices: ['filter blood and balance water', 'pump blood', 'digest food', 'produce insulin'], answer: 0, explanation: 'Kidneys filter waste and regulate water/salts.' },
        { lvl: 2, type: 'mcq', prompt: 'A nerve impulse crosses the gap between neurons at the:', choices: ['synapse', 'nucleus', 'axon hillock only', 'dendrite tip only'], answer: 0, explanation: 'Signals pass across synapses via neurotransmitters.' },
      ] },

    // ================= A2 =================
    { tier: 'A2', order: 1, slug: 'genetics-ii', title: 'Genetics II',
      summary: 'Linkage, mutation, genetic disorders and population genetics (Hardy-Weinberg).',
      outcomes: ['Explain linkage and mutation', 'Analyse genetic disorders', 'Apply Hardy-Weinberg'],
      concepts: [
        ['Beyond simple inheritance', 'Genes on the same chromosome are linked; mutations change DNA, sometimes causing disorders. Real inheritance is richer than single-gene ratios.'],
        ['Population genetics', 'Hardy-Weinberg predicts allele frequencies in a stable population — reusing probability and algebra to study evolution quantitatively.'],
      ],
      mistakes: ['Assuming all genes assort independently (linked ones do not).', 'Thinking all mutations are harmful.', 'Algebra errors in Hardy-Weinberg.'],
      tricks: ['Linked genes are inherited together.', 'Hardy-Weinberg: p² + 2pq + q² = 1.', 'Mutations are the ultimate source of variation.'],
      memory: ['"Linked genes travel together."', '"p² + 2pq + q² = 1."', 'Mutation fuels variation.'],
      board: { CBSE: ['Cl.12 Genetics & Evolution'], ICSE: ['Cl.12 Genetics'], IB: ['DP Genetics HL'] },
      comp: ['NEET'], keywords: ['linkage', 'mutation', 'genetic disorders', 'Hardy-Weinberg', 'population genetics'],
      xprereqs: ['math.I2.combinatorics-probability-ii'],
      quiz: [
        { lvl: 2, type: 'mcq', prompt: 'The Hardy-Weinberg equation is:', choices: ['p² + 2pq + q² = 1', 'p + q = 2', 'p² − q² = 0', 'pq = 1'], answer: 0, explanation: 'It gives genotype frequencies in a stable population.' },
        { lvl: 2, type: 'mcq', prompt: 'Genes located close together on the same chromosome tend to be:', choices: ['inherited together (linked)', 'always separated', 'identical', 'non-functional'], answer: 0, explanation: 'Linkage keeps them together during inheritance.' },
      ] },
    { tier: 'A2', order: 2, slug: 'biotechnology', title: 'Biotechnology',
      summary: 'Recombinant DNA, PCR, applications and ethics — linked to argumentation.',
      outcomes: ['Describe genetic engineering tools', 'Explain PCR', 'Weigh ethical issues'],
      concepts: [
        ['Engineering DNA', 'Recombinant DNA technology cuts and pastes genes between organisms; PCR amplifies tiny DNA samples. These tools power medicine, agriculture and forensics.'],
        ['Ethics', 'Powerful tools raise questions — GM crops, gene editing, privacy. Reasoning through them connects to the argumentation skills built in English.'],
      ],
      mistakes: ['Confusing PCR (copying) with sequencing (reading).', 'Ignoring ethical dimensions.', 'Overstating what current technology can do.'],
      tricks: ['PCR makes many copies of a DNA segment.', 'Restriction enzymes cut DNA at specific sites.', 'Argue ethics with evidence, as in English.'],
      memory: ['"PCR copies; sequencing reads."', '"Cut with restriction enzymes."', 'Ethics needs reasoned argument.'],
      board: { CBSE: ['Cl.12 Biotechnology'], ICSE: ['Cl.12 Biotechnology'], IB: ['DP Biotechnology HL'] },
      comp: ['NEET'], keywords: ['biotechnology', 'recombinant DNA', 'PCR', 'genetic engineering', 'ethics'],
      xprereqs: ['biology.A1.molecular-genetics'],
      quiz: [
        { lvl: 2, type: 'mcq', prompt: 'PCR is used to:', choices: ['amplify (copy) DNA', 'destroy DNA', 'read protein', 'cut cells'], answer: 0, explanation: 'PCR makes many copies of a DNA segment.' },
        { lvl: 2, type: 'mcq', prompt: 'Restriction enzymes are used to:', choices: ['cut DNA at specific sequences', 'copy RNA', 'build proteins', 'stain cells'], answer: 0, explanation: 'They cut DNA at recognition sites for engineering.' },
      ] },
    { tier: 'A2', order: 3, slug: 'evolution-depth', title: 'Evolution at Depth',
      summary: 'Speciation, molecular evidence and phylogenetics.',
      outcomes: ['Explain speciation', 'Use molecular evidence', 'Read phylogenetic trees'],
      concepts: [
        ['Speciation', 'New species form when populations become reproductively isolated and diverge — often by geographic separation. This explains life\'s branching diversity.'],
        ['Molecular phylogenetics', 'Comparing DNA sequences reconstructs evolutionary relationships as trees. More similar sequences mean more recent common ancestors.'],
      ],
      mistakes: ['Thinking speciation is instantaneous.', 'Misreading phylogenetic trees.', 'Ignoring molecular evidence in favour of appearance alone.'],
      tricks: ['Isolation + divergence → new species.', 'More DNA similarity → closer relationship.', 'Tree branch points are common ancestors.'],
      memory: ['"Isolate, diverge, speciate."', '"DNA similarity = relatedness."', 'Trees show common ancestry.'],
      board: { CBSE: ['Cl.12 Evolution'], ICSE: ['Cl.12 Evolution'], IB: ['DP Evolution HL'] },
      comp: ['NEET'], keywords: ['speciation', 'phylogenetics', 'molecular evidence', 'evolution'],
      xprereqs: ['biology.I2.evolution-natural-selection'],
      quiz: [
        { lvl: 2, type: 'mcq', prompt: 'Speciation often begins with:', choices: ['reproductive isolation', 'a single mutation instantly', 'extinction', 'hybrid vigour'], answer: 0, explanation: 'Isolated populations diverge into new species.' },
        { lvl: 2, type: 'mcq', prompt: 'On a phylogenetic tree, species sharing a recent branch point are:', choices: ['closely related', 'unrelated', 'identical', 'extinct'], answer: 0, explanation: 'A recent common ancestor means close relationship.' },
      ] },
    { tier: 'A2', order: 4, slug: 'ecology-environment-depth', title: 'Ecology & Environment at Depth',
      summary: 'Biodiversity, conservation and human impact — data-driven, reusing statistics.',
      outcomes: ['Assess biodiversity', 'Evaluate human impact', 'Propose conservation strategies'],
      concepts: [
        ['Biodiversity and impact', 'Biodiversity underpins ecosystem stability; human activity (habitat loss, pollution, climate change) threatens it. Data and statistics quantify these trends.'],
        ['Conservation', 'Conservation weighs evidence and trade-offs to protect species and habitats — an applied, data-driven, and ethical challenge.'],
      ],
      mistakes: ['Treating biodiversity as just species count (it includes genetic and ecosystem diversity).', 'Ignoring data when arguing impact.', 'Overlooking trade-offs in conservation.'],
      tricks: ['Use data and statistics to quantify biodiversity change.', 'Human impacts: habitat loss, pollution, climate change.', 'Conservation weighs evidence and trade-offs.'],
      memory: ['"Biodiversity = genes, species, ecosystems."', '"Argue impact with data."', 'Conservation is evidence + ethics.'],
      board: { CBSE: ['Cl.12 Ecology & Environment'], ICSE: ['Cl.12 Environmental Biology'], IB: ['DP Ecology HL'] },
      comp: ['NEET'], keywords: ['biodiversity', 'conservation', 'human impact', 'ecology', 'environment'],
      xprereqs: ['math.I1.statistics-ii'],
      quiz: [
        { lvl: 2, type: 'mcq', prompt: 'Biodiversity includes diversity of:', choices: ['genes, species and ecosystems', 'only species', 'only genes', 'only habitats'], answer: 0, explanation: 'It spans all three levels.' },
        { lvl: 2, type: 'mcq', prompt: 'A major human threat to biodiversity is:', choices: ['habitat loss', 'photosynthesis', 'natural selection', 'osmosis'], answer: 0, explanation: 'Habitat destruction is a leading cause of biodiversity loss.' },
      ] },
    { tier: 'A2', order: 5, slug: 'human-health-disease', title: 'Human Health & Disease at Depth',
      summary: 'Immunity, reproduction and biotechnology in medicine.',
      outcomes: ['Detail the immune response', 'Explain reproductive health', 'Describe medical biotechnology'],
      concepts: [
        ['Immune response', 'The immune system distinguishes self from non-self, mounting specific responses and memory. Vaccines and immunotherapy exploit this.'],
        ['Medicine and biotech', 'Biotechnology delivers vaccines, insulin and gene therapies. Understanding disease mechanisms guides treatment.'],
      ],
      mistakes: ['Confusing innate and adaptive immunity.', 'Ignoring immune memory in vaccination.', 'Overstating current gene-therapy capabilities.'],
      tricks: ['Innate = fast, general; adaptive = specific, with memory.', 'Vaccines create immune memory.', 'Biotech produces modern medicines.'],
      memory: ['"Innate fast, adaptive specific."', '"Memory is why vaccines last."', 'Biotech powers medicine.'],
      board: { CBSE: ['Cl.12 Human Health & Disease'], ICSE: ['Cl.12 Health'], IB: ['DP Human Physiology HL'] },
      comp: ['NEET'], keywords: ['immunity', 'vaccine', 'disease', 'reproductive health', 'medicine'],
      xprereqs: ['biology.F2.health-disease'],
      quiz: [
        { lvl: 2, type: 'mcq', prompt: 'Adaptive immunity differs from innate immunity because it is:', choices: ['specific and has memory', 'always faster', 'non-cellular', 'unable to respond twice'], answer: 0, explanation: 'Adaptive immunity is specific and remembers pathogens.' },
        { lvl: 2, type: 'mcq', prompt: 'Vaccines provide long-term protection by creating immune:', choices: ['memory', 'antibiotics', 'enzymes', 'hormones'], answer: 0, explanation: 'Memory cells enable a fast response on re-exposure.' },
      ] },
    { tier: 'A2', order: 6, slug: 'investigative-biology', title: 'Investigative Biology Portfolio', core: true,
      summary: 'Experimental design and data analysis — the capstone research strand.',
      outcomes: ['Design controlled experiments', 'Analyse biological data', 'Draw evidence-based conclusions'],
      concepts: [
        ['Experimental design', 'A good biology experiment controls variables, includes replicates and a control group, and defines what is measured — the basis of trustworthy results.'],
        ['Data analysis', 'Biological data is variable, so statistics (means, spread, significance) separate real effects from noise — reusing the maths statistics strand.'],
      ],
      mistakes: ['Omitting a control group.', 'Ignoring variability and drawing conclusions from one trial.', 'Confusing correlation with causation.'],
      tricks: ['Always include a control and replicates.', 'Use statistics to test if a difference is real.', 'Correlation is not causation.'],
      memory: ['"Control, replicate, measure."', '"Statistics separate signal from noise."', 'Correlation ≠ causation.'],
      board: { CBSE: ['Cl.11-12 Practical Biology'], ICSE: ['Cl.11-12 Practical'], IB: ['DP Biology IA'] },
      comp: [], keywords: ['experimental design', 'data analysis', 'control', 'statistics', 'investigation'],
      xprereqs: ['math.I1.statistics-ii'],
      quiz: [
        { lvl: 2, type: 'mcq', prompt: 'A valid experiment must include a:', choices: ['control group', 'guaranteed result', 'single trial only', 'change of many variables at once'], answer: 0, explanation: 'A control isolates the effect of the variable tested.' },
        { lvl: 3, type: 'mcq', prompt: 'Two variables rise together. You can conclude:', choices: ['they are correlated, not necessarily causal', 'one causes the other', 'nothing is related', 'the experiment failed'], answer: 0, explanation: 'Correlation does not prove causation.' },
      ] },
  ],
};
