// Chemistry — full curriculum dataset. Module-level content for every topic.
export default {
  subject: 'chemistry',
  topics: [
    // ================= F1 =================
    { tier: 'F1', order: 1, slug: 'matter-particles-states', title: 'Matter, Particles & States',
      summary: 'The particle model of matter, the three states, and changes of state.',
      outcomes: ['Describe matter using the particle model', 'Explain the three states and changes between them', 'Distinguish pure substances from mixtures'],
      concepts: [
        ['Everything is particles', 'All matter is made of tiny particles in constant motion. How close and how fast they move decides whether something is solid, liquid or gas.'],
        ['Changes of state', 'Heating gives particles energy to move apart (melting, boiling); cooling reverses it. Mass is conserved throughout — nothing is lost, only rearranged.'],
      ],
      mistakes: ['Thinking particles expand when heated (they move faster and apart, they do not grow).', 'Confusing a mixture with a compound.', 'Believing gas has no mass.'],
      tricks: ['Solid → liquid → gas as particle energy and spacing increase.', 'Melting and freezing happen at the same temperature (opposite directions).', 'Mass is conserved in every state change.'],
      memory: ['"Solid, liquid, gas = closer, looser, free."', '"Heat spreads particles apart."', 'Mass never changes on a state change.'],
      board: { CBSE: ['Cl.6-7 Matter', 'Cl.9 Matter in Our Surroundings'], ICSE: ['Cl.6-7 Matter'], IB: ['MYP Sciences'] },
      comp: ['NEET'], keywords: ['matter', 'particle model', 'states', 'melting', 'boiling'],
      quiz: [
        { lvl: 1, type: 'mcq', prompt: 'In which state are particles most closely packed?', choices: ['solid', 'liquid', 'gas', 'plasma'], answer: 0, explanation: 'Solids have the tightest, most ordered packing.' },
        { lvl: 2, type: 'mcq', prompt: 'When ice melts, its mass:', choices: ['stays the same', 'increases', 'decreases', 'becomes zero'], answer: 0, explanation: 'Mass is conserved in a change of state.' },
      ] },
    { tier: 'F1', order: 2, slug: 'separation-techniques', title: 'Separation Techniques',
      summary: 'Filtration, evaporation, distillation and chromatography — separating mixtures by physical properties.',
      outcomes: ['Choose a separation method for a mixture', 'Explain distillation and chromatography', 'Relate method to particle properties'],
      concepts: [
        ['Separate by difference', 'Mixtures separate because their components differ — in particle size (filtration), boiling point (distillation) or how they travel through a medium (chromatography).'],
        ['Physical, not chemical', 'Separation techniques are physical: no new substance forms. Choosing the right one depends on the property that differs most.'],
      ],
      mistakes: ['Using filtration to separate dissolved solids (they pass through).', 'Confusing evaporation with distillation (distillation recovers the liquid).', 'Thinking separation changes the substances chemically.'],
      tricks: ['Filtration separates insoluble solids from liquids.', 'Distillation separates by boiling point and recovers the liquid.', 'Chromatography separates dissolved substances by how far they travel.'],
      memory: ['"Filter the insoluble; distil by boiling point."', '"Chromatography: farther travelled, more soluble/lighter."', 'Separation is physical, not chemical.'],
      board: { CBSE: ['Cl.6 Separation of Substances', 'Cl.9 Is Matter Pure'], ICSE: ['Cl.6-8 Separation'], IB: ['MYP Sciences'] },
      comp: ['NEET'], keywords: ['filtration', 'distillation', 'chromatography', 'evaporation', 'mixtures'],
      quiz: [
        { lvl: 1, type: 'mcq', prompt: 'Best method to get pure water from salt water?', choices: ['distillation', 'filtration', 'chromatography', 'decanting'], answer: 0, explanation: 'Distillation boils off water and condenses it, leaving salt behind.' },
        { lvl: 2, type: 'mcq', prompt: 'Filtration can separate:', choices: ['an insoluble solid from a liquid', 'dissolved salt from water', 'two gases', 'ink colours'], answer: 0, explanation: 'Filtration traps insoluble solids; dissolved solids pass through.' },
      ] },
    { tier: 'F1', order: 3, slug: 'physical-chemical-change', title: 'Physical vs Chemical Change',
      summary: 'Telling physical from chemical changes, evidence of reaction, and conservation of mass.',
      outcomes: ['Distinguish physical and chemical changes', 'Identify signs of a chemical reaction', 'Apply conservation of mass'],
      concepts: [
        ['Two kinds of change', 'A physical change alters form but not the substance (melting, dissolving). A chemical change makes new substances (burning, rusting), often signalled by colour change, gas, heat or a precipitate.'],
        ['Mass is conserved', 'In any chemical reaction, atoms are only rearranged — total mass before equals total mass after. This accounting principle underlies balancing equations later.'],
      ],
      mistakes: ['Calling dissolving a chemical change (it is physical).', 'Assuming mass is lost when gas escapes (it left as a product).', 'Missing subtle signs of reaction like a temperature change.'],
      tricks: ['New substance formed? → chemical. Same substance, new form? → physical.', 'Look for gas, colour change, heat/light, or a precipitate as reaction clues.', 'Total mass is unchanged — account for gases too.'],
      memory: ['"New substance = chemical change."', '"Atoms rearrange, mass stays."', 'Signs: gas, colour, heat, precipitate.'],
      board: { CBSE: ['Cl.7 Physical & Chemical Changes'], ICSE: ['Cl.7 Physical & Chemical Changes'], IB: ['MYP Sciences'] },
      comp: ['NEET'], keywords: ['physical change', 'chemical change', 'conservation of mass', 'reaction'],
      quiz: [
        { lvl: 1, type: 'mcq', prompt: 'Which is a chemical change?', choices: ['iron rusting', 'ice melting', 'sugar dissolving', 'water boiling'], answer: 0, explanation: 'Rusting forms a new substance (iron oxide).' },
        { lvl: 2, type: 'mcq', prompt: 'In a sealed flask, a reaction occurs. The total mass:', choices: ['stays the same', 'increases', 'decreases', 'doubles'], answer: 0, explanation: 'Mass is conserved; nothing escapes a sealed flask.' },
      ] },

    // ================= F2 =================
    { tier: 'F2', order: 1, slug: 'atomic-structure-i', title: 'Atomic Structure I',
      summary: 'Protons, neutrons and electrons; atomic number, mass number and isotopes.',
      outcomes: ['Describe subatomic particles', 'Use atomic number and mass number', 'Explain isotopes'],
      concepts: [
        ['Inside the atom', 'Atoms have a nucleus of protons (positive) and neutrons (neutral), surrounded by electrons (negative). The atomic number (protons) defines the element.'],
        ['Isotopes', 'Atoms of the same element can have different numbers of neutrons — isotopes. They share chemistry but differ in mass, which explains non-whole atomic masses.'],
      ],
      mistakes: ['Confusing atomic number (protons) with mass number (protons + neutrons).', 'Thinking isotopes are different elements.', 'Forgetting neutral atoms have equal protons and electrons.'],
      tricks: ['Atomic number = protons = electrons (neutral atom).', 'Neutrons = mass number − atomic number.', 'Isotopes: same protons, different neutrons.'],
      memory: ['"Protons define the element."', '"Neutrons = mass number − atomic number."', 'Isotopes share chemistry, differ in mass.'],
      board: { CBSE: ['Cl.9 Structure of the Atom'], ICSE: ['Cl.8-9 Atomic Structure'], IB: ['DP Atomic Structure'] },
      comp: ['JEE-Main', 'NEET'], keywords: ['atom', 'proton', 'neutron', 'electron', 'isotope', 'atomic number'],
      quiz: [
        { lvl: 1, type: 'numeric', prompt: 'An atom has 11 protons and 12 neutrons. Mass number?', answer: 23, tolerance: 0, explanation: 'Mass number = protons + neutrons = 11 + 12 = 23.' },
        { lvl: 2, type: 'mcq', prompt: 'Two isotopes of an element differ in their number of:', choices: ['neutrons', 'protons', 'electrons', 'nuclei'], answer: 0, explanation: 'Isotopes have the same protons but different neutrons.' },
      ] },
    { tier: 'F2', order: 2, slug: 'periodic-table', title: 'The Periodic Table as a Map',
      summary: 'Periods and groups as patterns, not a list — organising elements by structure and properties.',
      outcomes: ['Read the periodic table\'s layout', 'Relate group to properties', 'Predict trends across periods and groups'],
      concepts: [
        ['A map, not a list', 'Elements are arranged by increasing atomic number into periods (rows) and groups (columns). Elements in the same group have similar properties because they share outer-electron counts.'],
        ['Trends', 'Properties change predictably: reactivity, size and metallic character trend across periods and down groups. The table lets you predict, not memorise.'],
      ],
      mistakes: ['Memorising elements instead of using group patterns.', 'Confusing groups (columns) with periods (rows).', 'Ignoring that group number links to outer electrons.'],
      tricks: ['Same group → similar chemistry (same outer electrons).', 'Metals on the left, non-metals on the right.', 'Reactivity trends: predict rather than memorise.'],
      memory: ['"Groups = columns = similar families."', '"Periods = rows."', 'Outer electrons drive group behaviour.'],
      board: { CBSE: ['Cl.10 Periodic Classification'], ICSE: ['Cl.8-10 Periodic Table'], IB: ['DP Periodicity'] },
      comp: ['JEE-Main', 'NEET'], keywords: ['periodic table', 'groups', 'periods', 'trends', 'elements'],
      quiz: [
        { lvl: 1, type: 'mcq', prompt: 'Elements in the same group tend to have similar:', choices: ['chemical properties', 'atomic mass', 'number of neutrons', 'colour'], answer: 0, explanation: 'They share the same number of outer electrons.' },
        { lvl: 2, type: 'mcq', prompt: 'A column in the periodic table is called a:', choices: ['group', 'period', 'block', 'shell'], answer: 0, explanation: 'Columns are groups; rows are periods.' },
      ] },
    { tier: 'F2', order: 3, slug: 'mole-concept', title: 'The Mole Concept',
      summary: 'The mole and molar mass — proportional reasoning applied to counting particles (the keystone topic).',
      outcomes: ['Define the mole and Avogadro\'s number', 'Convert between mass, moles and particles', 'Use molar mass'],
      concepts: [
        ['Counting by weighing', 'A mole is a fixed number of particles (Avogadro\'s number, ~6.02×10²³). Because atoms are too small to count, we weigh them: molar mass (g/mol) links mass to number of particles.'],
        ['Ratios of particles', 'The mole turns particle counting into the same proportional reasoning as ratios: moles = mass ÷ molar mass. Every quantitative chemistry calculation flows from here.'],
      ],
      mistakes: ['Confusing molar mass with atomic number.', 'Forgetting to use the correct molar mass for a compound.', 'Mixing up moles and grams.'],
      tricks: ['Moles = mass ÷ molar mass.', 'Number of particles = moles × Avogadro\'s number.', 'Molar mass of a compound = sum of its atoms\' masses.'],
      memory: ['"Moles = mass ÷ molar mass."', '"1 mole = 6.02×10²³ particles."', 'The mole is ratio thinking for particles.'],
      board: { CBSE: ['Cl.9-11 Mole Concept', 'Cl.11 Some Basic Concepts of Chemistry'], ICSE: ['Cl.10 Mole Concept'], IB: ['DP Stoichiometry'] },
      comp: ['JEE-Main', 'JEE-Advanced', 'NEET'], keywords: ['mole', 'Avogadro', 'molar mass', 'stoichiometry'],
      xprereqs: ['math.F2.exponents-scientific-notation'],
      quiz: [
        { lvl: 1, type: 'numeric', prompt: 'How many moles in 36 g of water (molar mass 18 g/mol)?', answer: 2, tolerance: 0, unit: 'mol', explanation: 'Moles = 36 ÷ 18 = 2 mol.' },
        { lvl: 2, type: 'numeric', prompt: 'Mass of 0.5 mol of carbon (molar mass 12 g/mol)?', answer: 6, tolerance: 0, unit: 'g', explanation: 'Mass = moles × molar mass = 0.5 × 12 = 6 g.' },
      ] },
    { tier: 'F2', order: 4, slug: 'chemical-formulae-equations', title: 'Chemical Formulae & Equations',
      summary: 'Writing formulae and balancing equations as conservation-of-mass accounting.',
      outcomes: ['Write formulae from valencies', 'Balance chemical equations', 'Interpret an equation quantitatively'],
      concepts: [
        ['Formulae', 'A formula shows which atoms and how many are combined, set by their combining power (valency). It is a compact recipe for a compound.'],
        ['Balancing', 'A balanced equation has equal atoms of each element on both sides — because atoms are conserved. Coefficients (not subscripts) are adjusted to balance.'],
      ],
      mistakes: ['Changing subscripts instead of coefficients to balance.', 'Forgetting a balanced equation must conserve every element.', 'Miswriting formulae by ignoring valency.'],
      tricks: ['Balance by adjusting coefficients, never subscripts.', 'Balance one element at a time, saving oxygen/hydrogen for last.', 'Check every element\'s atom count on both sides.'],
      memory: ['"Balance coefficients, not subscripts."', '"Atoms in = atoms out."', 'Formula = recipe set by valency.'],
      board: { CBSE: ['Cl.9-10 Chemical Reactions & Equations'], ICSE: ['Cl.8-9 Chemical Equations'], IB: ['DP Stoichiometry'] },
      comp: ['JEE-Main', 'NEET'], keywords: ['formula', 'balancing', 'equation', 'valency'],
      xprereqs: ['chemistry.F1.physical-chemical-change'],
      quiz: [
        { lvl: 2, type: 'mcq', prompt: 'To balance an equation you adjust the:', choices: ['coefficients', 'subscripts', 'atomic numbers', 'symbols'], answer: 0, explanation: 'Coefficients change amounts; subscripts would change the substance.' },
        { lvl: 2, type: 'numeric', prompt: 'Balance H₂ + O₂ → H₂O. What coefficient goes in front of H₂O?', answer: 2, tolerance: 0, explanation: '2H₂ + O₂ → 2H₂O balances all atoms.' },
      ] },
    { tier: 'F2', order: 5, slug: 'stoichiometry-intro', title: 'Introductory Stoichiometry',
      summary: 'Mass-mole-mass calculations from balanced equations.',
      outcomes: ['Use mole ratios from equations', 'Perform mass-to-mass calculations', 'Identify limiting reactants (intro)'],
      concepts: [
        ['Equations give ratios', 'A balanced equation\'s coefficients are mole ratios. They let you predict how much product forms from a given amount of reactant.'],
        ['Mass → mole → mole → mass', 'Convert reactant mass to moles, apply the mole ratio, then convert product moles back to mass. This chain is the core of quantitative chemistry.'],
      ],
      mistakes: ['Using mass ratios directly instead of mole ratios.', 'Forgetting to balance the equation first.', 'Skipping the conversion back to mass.'],
      tricks: ['Always balance first, then read mole ratios from coefficients.', 'Mass → moles → (ratio) → moles → mass.', 'The limiting reactant runs out first and caps the product.'],
      memory: ['"Coefficients are mole ratios."', '"Mass → mole → mole → mass."', 'Limiting reactant caps the yield.'],
      board: { CBSE: ['Cl.11 Some Basic Concepts of Chemistry'], ICSE: ['Cl.10 Mole & Stoichiometry'], IB: ['DP Stoichiometry'] },
      comp: ['JEE-Main', 'JEE-Advanced', 'NEET'], keywords: ['stoichiometry', 'mole ratio', 'limiting reactant'],
      xprereqs: ['chemistry.F2.mole-concept'],
      quiz: [
        { lvl: 2, type: 'mcq', prompt: 'In 2H₂ + O₂ → 2H₂O, the mole ratio of H₂ to H₂O is:', choices: ['1 : 1', '2 : 1', '1 : 2', '2 : 3'], answer: 0, explanation: 'Coefficients 2 and 2 give a 1:1 ratio.' },
        { lvl: 3, type: 'mcq', prompt: 'The reactant that runs out first is called the:', choices: ['limiting reactant', 'excess reactant', 'catalyst', 'product'], answer: 0, explanation: 'It limits how much product can form.' },
      ] },

    // ================= I1 =================
    { tier: 'I1', order: 1, slug: 'bonding-i', title: 'Bonding I',
      summary: 'Ionic, covalent and metallic bonding, and electron-dot structures.',
      outcomes: ['Distinguish ionic, covalent, metallic bonds', 'Draw electron-dot structures', 'Relate bonding to properties'],
      concepts: [
        ['Atoms bond for stable shells', 'Atoms gain, lose or share electrons to reach full outer shells. Metals + non-metals transfer electrons (ionic); non-metals share (covalent); metals pool electrons (metallic).'],
        ['Bonding sets properties', 'Ionic compounds form lattices with high melting points; covalent molecules are often low-melting; metals conduct because their electrons are free.'],
      ],
      mistakes: ['Thinking covalent bonds transfer electrons (they share).', 'Confusing ionic and covalent based on name alone.', 'Forgetting metals conduct due to delocalised electrons.'],
      tricks: ['Metal + non-metal → ionic; non-metal + non-metal → covalent.', 'Count outer electrons to predict bonding.', 'High melting point + conducts when molten → ionic.'],
      memory: ['"Ionic transfers, covalent shares, metallic pools."', '"Full outer shell = stability."', 'Bonding explains melting point and conductivity.'],
      board: { CBSE: ['Cl.10-11 Chemical Bonding'], ICSE: ['Cl.9-10 Chemical Bonding'], IB: ['DP Bonding'] },
      comp: ['JEE-Main', 'NEET'], keywords: ['ionic', 'covalent', 'metallic', 'bonding', 'electron-dot'],
      xprereqs: ['chemistry.F2.atomic-structure-i'],
      quiz: [
        { lvl: 1, type: 'mcq', prompt: 'A bond formed by sharing electrons is:', choices: ['covalent', 'ionic', 'metallic', 'nuclear'], answer: 0, explanation: 'Covalent bonds share electron pairs.' },
        { lvl: 2, type: 'mcq', prompt: 'Sodium chloride (metal + non-metal) is held by ___ bonding.', choices: ['ionic', 'covalent', 'metallic', 'hydrogen'], answer: 0, explanation: 'Electron transfer between metal and non-metal is ionic.' },
      ] },
    { tier: 'I1', order: 2, slug: 'reactions-equations', title: 'Reactions & Equations Deepened',
      summary: 'Reaction types, ionic equations and an introduction to redox.',
      outcomes: ['Classify reaction types', 'Write ionic equations', 'Identify oxidation and reduction'],
      concepts: [
        ['Types of reaction', 'Reactions fall into families: combination, decomposition, displacement, and double displacement. Recognising the type predicts the products.'],
        ['Redox intro', 'Oxidation is loss of electrons, reduction is gain (OIL RIG). Many reactions transfer electrons — the basis of batteries and corrosion.'],
      ],
      mistakes: ['Forgetting redox always pairs oxidation with reduction.', 'Writing molecular equations when ionic ones are asked.', 'Misclassifying displacement vs double displacement.'],
      tricks: ['OIL RIG: Oxidation Is Loss, Reduction Is Gain (of electrons).', 'In ionic equations, cancel spectator ions.', 'A more reactive metal displaces a less reactive one.'],
      memory: ['"OIL RIG."', '"Cancel spectator ions."', 'Every oxidation has a matching reduction.'],
      board: { CBSE: ['Cl.10 Chemical Reactions'], ICSE: ['Cl.10 Reactions'], IB: ['DP Redox'] },
      comp: ['JEE-Main', 'NEET'], keywords: ['reaction types', 'ionic equations', 'redox', 'oxidation', 'reduction'],
      quiz: [
        { lvl: 1, type: 'mcq', prompt: 'Oxidation is the ___ of electrons.', choices: ['loss', 'gain', 'sharing', 'counting'], answer: 0, explanation: 'OIL: Oxidation Is Loss of electrons.' },
        { lvl: 2, type: 'mcq', prompt: 'Ions that appear unchanged on both sides of an ionic equation are:', choices: ['spectator ions', 'reactants', 'catalysts', 'products'], answer: 0, explanation: 'Spectator ions are cancelled out.' },
      ] },
    { tier: 'I1', order: 3, slug: 'acids-bases-salts', title: 'Acids, Bases & Salts',
      summary: 'The pH scale, neutralisation, and an introduction to titration.',
      outcomes: ['Describe acids and bases', 'Use the pH scale', 'Explain neutralisation and titration'],
      concepts: [
        ['Acids and bases', 'Acids release H⁺ ions, bases release OH⁻ (or accept H⁺). The pH scale (0–14) measures acidity; 7 is neutral.'],
        ['Neutralisation', 'Acid + base → salt + water. Titration uses this to find an unknown concentration by adding a known solution until neutral.'],
      ],
      mistakes: ['Thinking higher pH means more acidic (it is less).', 'Forgetting neutralisation always produces water.', 'Reading pH as a linear (not logarithmic) scale.'],
      tricks: ['pH < 7 acidic, = 7 neutral, > 7 basic.', 'Acid + base → salt + water (neutralisation).', 'Each pH unit is a ten-fold change in acidity.'],
      memory: ['"Low pH, high acidity."', '"Acid + base → salt + water."', 'pH is logarithmic — steps of ten.'],
      board: { CBSE: ['Cl.10 Acids, Bases & Salts'], ICSE: ['Cl.9-10 Acids, Bases, Salts'], IB: ['DP Acids & Bases'] },
      comp: ['JEE-Main', 'NEET'], keywords: ['acid', 'base', 'pH', 'neutralisation', 'titration'],
      quiz: [
        { lvl: 1, type: 'mcq', prompt: 'A solution with pH 2 is:', choices: ['acidic', 'neutral', 'basic', 'a salt'], answer: 0, explanation: 'pH below 7 is acidic.' },
        { lvl: 2, type: 'mcq', prompt: 'Acid + base produces salt and:', choices: ['water', 'oxygen', 'hydrogen only', 'a metal'], answer: 0, explanation: 'Neutralisation makes a salt plus water.' },
      ] },
    { tier: 'I1', order: 4, slug: 'solutions-concentration', title: 'Solutions & Concentration',
      summary: 'Molarity, dilution, and expressing concentration — the mole concept reused.',
      outcomes: ['Calculate molarity', 'Perform dilution calculations', 'Relate concentration to moles'],
      concepts: [
        ['Concentration', 'Molarity is moles of solute per litre of solution — again a rate/ratio. It links the mole concept to real solutions used in the lab.'],
        ['Dilution', 'Adding solvent lowers concentration but keeps the moles of solute fixed: C₁V₁ = C₂V₂. This is inverse proportion in action.'],
      ],
      mistakes: ['Confusing moles with molarity.', 'Forgetting volume must be in litres for molarity.', 'Thinking dilution changes the amount of solute (it does not).'],
      tricks: ['Molarity = moles ÷ litres.', 'Dilution: C₁V₁ = C₂V₂ (moles conserved).', 'Convert mL to L before computing molarity.'],
      memory: ['"Molarity = moles per litre."', '"C₁V₁ = C₂V₂."', 'Dilution keeps moles, lowers concentration.'],
      board: { CBSE: ['Cl.11-12 Solutions'], ICSE: ['Cl.10-11 Solutions'], IB: ['DP Stoichiometry'] },
      comp: ['JEE-Main', 'JEE-Advanced', 'NEET'], keywords: ['molarity', 'concentration', 'dilution', 'solution'],
      xprereqs: ['chemistry.F2.mole-concept'],
      quiz: [
        { lvl: 1, type: 'numeric', prompt: 'Molarity of 2 mol in 4 L?', answer: 0.5, tolerance: 0, unit: 'M', explanation: 'M = moles/litres = 2/4 = 0.5 M.' },
        { lvl: 2, type: 'numeric', prompt: 'Dilute 100 mL of 2 M to 200 mL. New molarity?', answer: 1, tolerance: 0, unit: 'M', explanation: 'C₁V₁ = C₂V₂ → 2×100 = C₂×200 → C₂ = 1 M.' },
      ] },
    { tier: 'I1', order: 5, slug: 'rates-reaction', title: 'Rates of Reaction',
      summary: 'What speeds reactions up — concentration, temperature, surface area, catalysts — with rate graphs.',
      outcomes: ['Identify factors affecting rate', 'Interpret rate graphs', 'Explain rate using collision theory'],
      concepts: [
        ['Collision theory', 'Reactions happen when particles collide with enough energy. Anything that increases collision frequency or energy speeds the reaction: higher concentration, temperature, surface area, or a catalyst.'],
        ['Rate graphs', 'Plotting product formed vs time gives a curve whose slope is the rate — steep at first, levelling as reactants run out. This is rate-as-slope, shared with physics and calculus.'],
      ],
      mistakes: ['Thinking a catalyst is used up (it is not).', 'Confusing rate (speed) with yield (amount).', 'Ignoring that rate falls as reactants deplete.'],
      tricks: ['More concentration/temperature/surface area → more collisions → faster.', 'A catalyst lowers the activation energy without being consumed.', 'Rate is the slope of the product-vs-time graph.'],
      memory: ['"Faster = more or harder collisions."', '"Catalyst speeds up, stays unchanged."', 'Rate = slope of the curve.'],
      board: { CBSE: ['Cl.12 Chemical Kinetics (intro)'], ICSE: ['Cl.10-11 Rate of Reaction'], IB: ['DP Kinetics'] },
      comp: ['JEE-Main', 'NEET'], keywords: ['reaction rate', 'collision theory', 'catalyst', 'activation energy'],
      quiz: [
        { lvl: 1, type: 'mcq', prompt: 'A catalyst speeds up a reaction by:', choices: ['lowering activation energy', 'being consumed', 'raising temperature', 'adding mass'], answer: 0, explanation: 'It provides a lower-energy pathway and is not used up.' },
        { lvl: 2, type: 'mcq', prompt: 'Increasing temperature increases rate because particles collide:', choices: ['more often and harder', 'less often', 'with less energy', 'never'], answer: 0, explanation: 'Higher energy and frequency of successful collisions.' },
      ] },

    // ================= I2 =================
    { tier: 'I2', order: 1, slug: 'atomic-structure-ii', title: 'Atomic Structure II',
      summary: 'Electron configuration and quantum shells, treated intuitively.',
      outcomes: ['Write electron configurations', 'Relate configuration to the periodic table', 'Explain energy levels intuitively'],
      concepts: [
        ['Electrons in shells', 'Electrons occupy energy levels (shells and subshells). Filling them in order of energy explains the periodic table\'s shape and each element\'s chemistry.'],
        ['Configuration predicts chemistry', 'The outer-shell configuration determines how an element bonds. Elements in the same group share outer configurations — hence similar behaviour.'],
      ],
      mistakes: ['Filling higher shells before lower ones are complete (follow energy order).', 'Confusing shells with subshells.', 'Forgetting outer electrons drive reactivity.'],
      tricks: ['Fill lowest-energy levels first (aufbau idea).', 'Outer-electron count = group behaviour.', 'Noble gases have full outer shells — hence unreactive.'],
      memory: ['"Fill low energy first."', '"Outer electrons = chemistry."', 'Full shell = stable/unreactive.'],
      board: { CBSE: ['Cl.11 Structure of Atom'], ICSE: ['Cl.11 Atomic Structure'], IB: ['DP Atomic Structure'] },
      comp: ['JEE-Main', 'JEE-Advanced', 'NEET'], keywords: ['electron configuration', 'shells', 'subshells', 'energy levels'],
      xprereqs: ['chemistry.F2.atomic-structure-i'],
      quiz: [
        { lvl: 2, type: 'mcq', prompt: 'Elements with full outer shells (noble gases) are:', choices: ['unreactive', 'highly reactive', 'always metals', 'radioactive'], answer: 0, explanation: 'A full outer shell is stable, so they rarely react.' },
        { lvl: 2, type: 'mcq', prompt: 'What mainly determines an element\'s chemistry?', choices: ['its outer electrons', 'its neutrons', 'its mass number', 'its colour'], answer: 0, explanation: 'Outer (valence) electrons drive bonding and reactivity.' },
      ] },
    { tier: 'I2', order: 2, slug: 'bonding-ii', title: 'Bonding II',
      summary: 'Molecular shapes (VSEPR), polarity, and intermolecular forces.',
      outcomes: ['Predict shapes with VSEPR', 'Determine molecular polarity', 'Explain intermolecular forces'],
      concepts: [
        ['Shape from repulsion', 'Electron pairs around an atom repel and spread out as far as possible (VSEPR), setting the molecule\'s shape — linear, bent, tetrahedral, etc.'],
        ['Polarity and forces', 'Unequal sharing makes bonds polar; molecular shape decides if the whole molecule is polar. Intermolecular forces (including hydrogen bonding) explain boiling points and solubility.'],
      ],
      mistakes: ['Confusing bond polarity with overall molecular polarity.', 'Ignoring lone pairs when predicting shape.', 'Treating intermolecular forces as bonds within molecules.'],
      tricks: ['Electron pairs (including lone pairs) spread to minimise repulsion.', 'Symmetric shapes can be non-polar even with polar bonds.', 'Hydrogen bonding raises boiling points sharply (e.g., water).'],
      memory: ['"Electron pairs push apart" (VSEPR).', '"Shape decides overall polarity."', 'Hydrogen bonds → high boiling points.'],
      board: { CBSE: ['Cl.11 Chemical Bonding & Molecular Structure'], ICSE: ['Cl.11 Bonding'], IB: ['DP Bonding HL'] },
      comp: ['JEE-Main', 'JEE-Advanced', 'NEET'], keywords: ['VSEPR', 'shape', 'polarity', 'intermolecular forces', 'hydrogen bonding'],
      xprereqs: ['chemistry.I1.bonding-i'],
      quiz: [
        { lvl: 2, type: 'mcq', prompt: 'VSEPR predicts molecular shape based on:', choices: ['electron-pair repulsion', 'atomic mass', 'colour', 'temperature'], answer: 0, explanation: 'Electron pairs arrange to minimise repulsion.' },
        { lvl: 3, type: 'mcq', prompt: 'Water has a high boiling point mainly due to:', choices: ['hydrogen bonding', 'ionic bonding', 'metallic bonding', 'low mass'], answer: 0, explanation: 'Strong hydrogen bonds between molecules.' },
      ] },
    { tier: 'I2', order: 3, slug: 'gas-laws-kinetic-theory', title: 'Gas Laws & Kinetic Theory',
      summary: 'Boyle, Charles and the ideal gas equation — the topic shared with physics.',
      outcomes: ['Apply the gas laws', 'Use PV = nRT', 'Relate gas behaviour to particle motion'],
      concepts: [
        ['Gas laws', 'Pressure, volume and temperature are linked. Boyle (P↕V at fixed T) and Charles (V↕T at fixed P) combine into PV = nRT, connecting to the mole concept.'],
        ['Particle picture', 'A gas is fast-moving particles colliding with walls; temperature is their average kinetic energy. The macroscopic laws follow from this microscopic behaviour.'],
      ],
      mistakes: ['Using Celsius instead of Kelvin.', 'Forgetting n (moles) links to the mole concept.', 'Mixing up Boyle and Charles conditions.'],
      tricks: ['PV = nRT ties pressure, volume, moles and temperature.', 'Always use Kelvin.', 'Boyle: P and V inverse; Charles: V and T direct.'],
      memory: ['"PV = nRT, in Kelvin."', '"Boyle inverse, Charles direct."', 'Temperature = average particle KE.'],
      board: { CBSE: ['Cl.11 States of Matter'], ICSE: ['Cl.11 Gas Laws'], IB: ['DP States of Matter'] },
      comp: ['JEE-Main', 'JEE-Advanced', 'NEET'], keywords: ['gas laws', 'ideal gas', 'PV=nRT', 'kinetic theory'],
      xprereqs: ['chemistry.F2.mole-concept'],
      quiz: [
        { lvl: 2, type: 'mcq', prompt: 'In PV = nRT, T must be in:', choices: ['kelvin', 'celsius', 'fahrenheit', 'joules'], answer: 0, explanation: 'Absolute temperature (K) is required.' },
        { lvl: 2, type: 'mcq', prompt: 'At constant temperature, doubling pressure on a gas:', choices: ['halves its volume', 'doubles its volume', 'no change', 'triples volume'], answer: 0, explanation: 'Boyle\'s law: P and V are inversely proportional.' },
      ] },
    { tier: 'I2', order: 4, slug: 'energetics', title: 'Energetics (Thermochemistry)',
      summary: 'Exothermic and endothermic reactions, enthalpy, and an introduction to Hess\'s law.',
      outcomes: ['Classify reactions as exo/endothermic', 'Interpret enthalpy changes', 'Apply Hess\'s law (intro)'],
      concepts: [
        ['Energy in reactions', 'Reactions release energy (exothermic, ΔH negative) or absorb it (endothermic, ΔH positive). Bond breaking costs energy; bond making releases it.'],
        ['Hess\'s law', 'The total enthalpy change is the same regardless of the route taken — because energy is conserved. This lets us add known steps to find unknown enthalpies.'],
      ],
      mistakes: ['Getting the sign of ΔH backwards (exothermic is negative).', 'Thinking breaking bonds releases energy (it absorbs it).', 'Ignoring that Hess\'s law needs a consistent route.'],
      tricks: ['Exothermic → releases heat → ΔH negative.', 'Bonds broken cost energy; bonds formed release it.', 'Hess: total ΔH is route-independent — add steps.'],
      memory: ['"Exo out (negative), endo in (positive)."', '"Break costs, make gives."', 'Hess: energy conserved over any route.'],
      board: { CBSE: ['Cl.11 Thermodynamics'], ICSE: ['Cl.11-12 Thermochemistry'], IB: ['DP Energetics'] },
      comp: ['JEE-Main', 'JEE-Advanced', 'NEET'], keywords: ['enthalpy', 'exothermic', 'endothermic', 'Hess law', 'thermochemistry'],
      xprereqs: ['chemistry.I1.reactions-equations'],
      quiz: [
        { lvl: 2, type: 'mcq', prompt: 'An exothermic reaction has an enthalpy change ΔH that is:', choices: ['negative', 'positive', 'zero', 'infinite'], answer: 0, explanation: 'Heat is released, so ΔH is negative.' },
        { lvl: 2, type: 'mcq', prompt: 'Breaking chemical bonds:', choices: ['absorbs energy', 'releases energy', 'has no energy change', 'creates atoms'], answer: 0, explanation: 'Bond breaking is endothermic; bond making is exothermic.' },
      ] },
    { tier: 'I2', order: 5, slug: 'equilibrium-intro', title: 'Quantitative Equilibrium (Introduction)',
      summary: 'Reversible reactions, dynamic equilibrium, and Le Chatelier\'s principle.',
      outcomes: ['Explain dynamic equilibrium', 'Apply Le Chatelier\'s principle', 'Predict shifts from changes'],
      concepts: [
        ['Dynamic equilibrium', 'Reversible reactions reach a state where forward and backward rates are equal — concentrations stay constant though reactions continue. Nothing has stopped; it is balanced.'],
        ['Le Chatelier', 'If you disturb an equilibrium (concentration, temperature, pressure), it shifts to oppose the change. This predicts how to push a reaction toward products.'],
      ],
      mistakes: ['Thinking equilibrium means the reaction has stopped.', 'Getting the direction of a Le Chatelier shift wrong.', 'Ignoring that catalysts do not shift equilibrium position.'],
      tricks: ['Equilibrium: forward rate = backward rate, not zero.', 'Le Chatelier: the system opposes the imposed change.', 'Adding reactant shifts equilibrium toward products.'],
      memory: ['"Equal rates, not stopped."', '"Disturb it, it pushes back."', 'Catalysts speed both directions — no shift.'],
      board: { CBSE: ['Cl.11 Equilibrium'], ICSE: ['Cl.11-12 Equilibrium'], IB: ['DP Equilibrium'] },
      comp: ['JEE-Main', 'JEE-Advanced', 'NEET'], keywords: ['equilibrium', 'reversible', 'Le Chatelier', 'dynamic'],
      xprereqs: ['chemistry.I1.rates-reaction'],
      quiz: [
        { lvl: 2, type: 'mcq', prompt: 'At dynamic equilibrium, the forward and backward reaction rates are:', choices: ['equal', 'both zero', 'forward faster', 'backward faster'], answer: 0, explanation: 'Equal opposing rates keep concentrations constant.' },
        { lvl: 3, type: 'mcq', prompt: 'Adding more reactant shifts equilibrium toward:', choices: ['products', 'reactants', 'neither', 'a solid only'], answer: 0, explanation: 'Le Chatelier: the system consumes the added reactant.' },
      ] },
    { tier: 'I2', order: 6, slug: 'organic-intro', title: 'Introductory Organic Chemistry',
      summary: 'Hydrocarbons, functional groups and naming — the chemistry of carbon.',
      outcomes: ['Recognise hydrocarbons and functional groups', 'Name simple organic molecules', 'Explain why carbon forms so many compounds'],
      concepts: [
        ['Carbon\'s versatility', 'Carbon forms four bonds and chains with itself, giving millions of compounds. Hydrocarbons (alkanes, alkenes) are the simplest families.'],
        ['Functional groups', 'A functional group (like −OH, −COOH) is the reactive part that defines a molecule\'s chemistry. Naming follows systematic rules based on chain length and group.'],
      ],
      mistakes: ['Confusing alkanes (single bonds) with alkenes (double bonds).', 'Miscounting carbons when naming.', 'Ignoring the functional group\'s role in reactions.'],
      tricks: ['Alkanes: single bonds (-ane); alkenes: a double bond (-ene).', 'Name by counting the longest carbon chain.', 'The functional group drives the reactivity.'],
      memory: ['"Carbon makes four bonds and long chains."', '"-ane single, -ene double."', 'Functional group = the reactive handle.'],
      board: { CBSE: ['Cl.10-11 Carbon Compounds', 'Cl.11 Organic Chemistry Basics'], ICSE: ['Cl.10 Organic Chemistry'], IB: ['DP Organic'] },
      comp: ['JEE-Main', 'JEE-Advanced', 'NEET'], keywords: ['organic', 'hydrocarbon', 'functional group', 'alkane', 'alkene'],
      quiz: [
        { lvl: 1, type: 'mcq', prompt: 'A hydrocarbon with only single C–C bonds is an:', choices: ['alkane', 'alkene', 'alcohol', 'acid'], answer: 0, explanation: 'Alkanes are saturated (single bonds only).' },
        { lvl: 2, type: 'mcq', prompt: 'The reactive part of an organic molecule is the:', choices: ['functional group', 'carbon backbone', 'hydrogen only', 'nucleus'], answer: 0, explanation: 'Functional groups define reactivity.' },
      ] },

    // ================= A1 =================
    { tier: 'A1', order: 1, slug: 'chemical-thermodynamics', title: 'Chemical Thermodynamics',
      summary: 'Enthalpy, entropy and Gibbs free energy — predicting whether reactions happen.',
      outcomes: ['Use enthalpy and entropy', 'Apply Gibbs free energy', 'Predict spontaneity'],
      concepts: [
        ['Enthalpy and entropy', 'Enthalpy (ΔH) tracks heat; entropy (ΔS) tracks disorder. Reactions are favoured by releasing energy and increasing disorder.'],
        ['Gibbs free energy', 'ΔG = ΔH − TΔS decides spontaneity: negative ΔG means the reaction proceeds. This unifies energy and disorder, sharing a spine with physics thermodynamics.'],
      ],
      mistakes: ['Ignoring the temperature term in ΔG = ΔH − TΔS.', 'Assuming exothermic always means spontaneous.', 'Confusing ΔG sign conventions.'],
      tricks: ['ΔG = ΔH − TΔS; negative ΔG → spontaneous.', 'High temperature magnifies the entropy term.', 'Both ΔH negative and ΔS positive → always spontaneous.'],
      memory: ['"ΔG = ΔH − TΔS."', '"Negative ΔG → it goes."', 'Energy down + disorder up = favourable.'],
      board: { CBSE: ['Cl.11 Thermodynamics'], ICSE: ['Cl.12 Thermodynamics'], IB: ['DP Energetics HL'] },
      comp: ['JEE-Main', 'JEE-Advanced', 'NEET'], keywords: ['thermodynamics', 'enthalpy', 'entropy', 'Gibbs free energy', 'spontaneity'],
      xprereqs: ['chemistry.I2.energetics'],
      quiz: [
        { lvl: 2, type: 'mcq', prompt: 'A reaction is spontaneous when ΔG is:', choices: ['negative', 'positive', 'zero', 'very large'], answer: 0, explanation: 'Negative Gibbs free energy means spontaneous.' },
        { lvl: 3, type: 'mcq', prompt: 'In ΔG = ΔH − TΔS, raising temperature increases the influence of:', choices: ['entropy (ΔS)', 'enthalpy (ΔH)', 'neither', 'pressure'], answer: 0, explanation: 'The TΔS term grows with temperature.' },
      ] },
    { tier: 'A1', order: 2, slug: 'chemical-kinetics', title: 'Chemical Kinetics',
      summary: 'Rate laws, reaction order and the Arrhenius equation — how fast and why.',
      outcomes: ['Write and use rate laws', 'Determine reaction order', 'Apply the Arrhenius relationship'],
      concepts: [
        ['Rate laws', 'The rate law relates reaction rate to reactant concentrations raised to their orders (found by experiment, not from the equation). Order reveals the mechanism.'],
        ['Arrhenius', 'Rate constants rise with temperature and fall with activation energy (Arrhenius). Taking logs turns this into a straight line — reusing logarithms from maths.'],
      ],
      mistakes: ['Reading orders from the balanced equation (they are experimental).', 'Confusing rate with rate constant.', 'Forgetting temperature\'s strong effect on rate.'],
      tricks: ['Order comes from experiment, not stoichiometry.', 'Higher activation energy → slower reaction.', 'ln k vs 1/T is linear (Arrhenius plot).'],
      memory: ['"Order is experimental."', '"High Eₐ, slow reaction."', 'Arrhenius plot: ln k vs 1/T.'],
      board: { CBSE: ['Cl.12 Chemical Kinetics'], ICSE: ['Cl.12 Kinetics'], IB: ['DP Kinetics HL'] },
      comp: ['JEE-Main', 'JEE-Advanced', 'NEET'], keywords: ['kinetics', 'rate law', 'order', 'Arrhenius', 'activation energy'],
      xprereqs: ['math.I2.exponentials-logarithms'],
      quiz: [
        { lvl: 3, type: 'mcq', prompt: 'The order of a reaction is determined by:', choices: ['experiment', 'the balanced equation', 'the molar mass', 'the temperature only'], answer: 0, explanation: 'Order is found experimentally, not from coefficients.' },
        { lvl: 2, type: 'mcq', prompt: 'A higher activation energy makes a reaction:', choices: ['slower', 'faster', 'unchanged', 'spontaneous'], answer: 0, explanation: 'Fewer collisions have enough energy, so it is slower.' },
      ] },
    { tier: 'A1', order: 3, slug: 'chemical-equilibrium', title: 'Chemical Equilibrium (Quantitative)',
      summary: 'Equilibrium constants Kc and Kp, and ICE-table calculations.',
      outcomes: ['Write equilibrium expressions', 'Use Kc and Kp', 'Solve with ICE tables'],
      concepts: [
        ['Equilibrium constant', 'Kc expresses the ratio of product to reactant concentrations at equilibrium (each raised to its coefficient). A large K favours products.'],
        ['ICE tables', 'Initial–Change–Equilibrium tables organise the algebra of finding equilibrium concentrations — systematic problem-solving reusing algebra skills.'],
      ],
      mistakes: ['Including pure solids/liquids in the K expression.', 'Forgetting to raise concentrations to their coefficients.', 'Algebra slips in ICE tables.'],
      tricks: ['K = products over reactants, each to its power.', 'Omit pure solids and liquids from K.', 'Use an ICE table to track concentrations.'],
      memory: ['"K = products/reactants (to powers)."', '"Large K favours products."', 'ICE: Initial, Change, Equilibrium.'],
      board: { CBSE: ['Cl.11 Equilibrium'], ICSE: ['Cl.12 Equilibrium'], IB: ['DP Equilibrium HL'] },
      comp: ['JEE-Main', 'JEE-Advanced', 'NEET'], keywords: ['equilibrium constant', 'Kc', 'Kp', 'ICE table'],
      xprereqs: ['chemistry.I2.equilibrium-intro'],
      quiz: [
        { lvl: 2, type: 'mcq', prompt: 'A very large equilibrium constant K means at equilibrium there are mostly:', choices: ['products', 'reactants', 'solids', 'catalysts'], answer: 0, explanation: 'Large K = product-favoured.' },
        { lvl: 3, type: 'mcq', prompt: 'Which is omitted from the Kc expression?', choices: ['pure solids and liquids', 'gases', 'aqueous ions', 'all reactants'], answer: 0, explanation: 'Pure solids and liquids have constant activity and are omitted.' },
      ] },
    { tier: 'A1', order: 4, slug: 'ionic-equilibrium', title: 'Ionic Equilibrium',
      summary: 'pH calculations, buffers, and the solubility product.',
      outcomes: ['Calculate pH of acids/bases', 'Explain buffers', 'Use the solubility product Ksp'],
      concepts: [
        ['pH quantitatively', 'pH = −log[H⁺], so acidity is a logarithm of ion concentration. Strong acids fully dissociate; weak acids only partly, needing equilibrium methods.'],
        ['Buffers and Ksp', 'Buffers resist pH change using a weak acid and its salt. The solubility product Ksp governs how much of a sparingly soluble salt dissolves.'],
      ],
      mistakes: ['Treating weak acids as fully dissociated.', 'Forgetting the negative sign in pH = −log[H⁺].', 'Misapplying Ksp to soluble salts.'],
      tricks: ['pH = −log[H⁺]; each unit is ×10 in concentration.', 'Buffer = weak acid + its conjugate base.', 'Ksp sets the maximum dissolved ion product.'],
      memory: ['"pH = −log[H⁺]."', '"Buffer resists pH change."', 'Ksp caps solubility.'],
      board: { CBSE: ['Cl.11 Equilibrium (Ionic)'], ICSE: ['Cl.12 Ionic Equilibrium'], IB: ['DP Acids & Bases HL'] },
      comp: ['JEE-Main', 'JEE-Advanced', 'NEET'], keywords: ['pH', 'buffer', 'solubility product', 'Ksp', 'ionic equilibrium'],
      xprereqs: ['math.I2.exponentials-logarithms'],
      quiz: [
        { lvl: 2, type: 'numeric', prompt: 'If [H⁺] = 0.001 M, what is the pH?', answer: 3, tolerance: 0, explanation: 'pH = −log(0.001) = 3.' },
        { lvl: 2, type: 'mcq', prompt: 'A buffer solution is made from a weak acid and its:', choices: ['conjugate base (salt)', 'strong base', 'metal', 'catalyst'], answer: 0, explanation: 'Weak acid + conjugate base resists pH change.' },
      ] },
    { tier: 'A1', order: 5, slug: 'electrochemistry', title: 'Electrochemistry',
      summary: 'Galvanic and electrolytic cells, the Nernst equation, and electrolysis.',
      outcomes: ['Describe galvanic and electrolytic cells', 'Use standard electrode potentials', 'Explain electrolysis'],
      concepts: [
        ['Cells from redox', 'A galvanic cell turns a spontaneous redox reaction into electricity; oxidation at the anode, reduction at the cathode. Cell voltage comes from electrode potentials.'],
        ['Electrolysis', 'Electrolytic cells use electricity to drive non-spontaneous reactions — extracting metals, plating. The amount deposited follows Faraday\'s laws (mole-charge ratios).'],
      ],
      mistakes: ['Swapping anode and cathode.', 'Confusing galvanic (spontaneous) with electrolytic (driven).', 'Ignoring the mole-to-charge relationship in electrolysis.'],
      tricks: ['Anode = oxidation, cathode = reduction (both cells).', 'Positive cell potential → spontaneous galvanic cell.', 'Charge = moles of electrons × Faraday constant.'],
      memory: ['"An Ox, Red Cat" (anode oxidation, cathode reduction).', '"Galvanic gives, electrolytic takes energy."', 'Electrolysis follows mole-charge ratios.'],
      board: { CBSE: ['Cl.12 Electrochemistry'], ICSE: ['Cl.12 Electrochemistry'], IB: ['DP Redox HL'] },
      comp: ['JEE-Main', 'JEE-Advanced', 'NEET'], keywords: ['electrochemistry', 'galvanic', 'electrolysis', 'Nernst', 'electrode potential'],
      xprereqs: ['chemistry.I1.reactions-equations'],
      quiz: [
        { lvl: 2, type: 'mcq', prompt: 'In any electrochemical cell, oxidation occurs at the:', choices: ['anode', 'cathode', 'salt bridge', 'wire'], answer: 0, explanation: 'Anode = oxidation; cathode = reduction.' },
        { lvl: 2, type: 'mcq', prompt: 'Electrolysis is used to:', choices: ['drive a non-spontaneous reaction', 'produce spontaneous electricity', 'stop reactions', 'measure pH'], answer: 0, explanation: 'It uses electrical energy to force a reaction.' },
      ] },
    { tier: 'A1', order: 6, slug: 'periodic-properties', title: 'Periodic Properties & s/p-Block',
      summary: 'Trends in atomic radius, ionisation energy and electronegativity, and s- and p-block chemistry.',
      outcomes: ['Explain periodic trends', 'Relate trends to electron structure', 'Survey s- and p-block behaviour'],
      concepts: [
        ['Periodic trends', 'Atomic radius decreases across a period and increases down a group; ionisation energy and electronegativity do the opposite. These follow from nuclear charge and shielding.'],
        ['Block chemistry', 'The s-block (reactive metals) and p-block (varied non-metals and metalloids) show patterns explained by their outer configurations.'],
      ],
      mistakes: ['Reversing the atomic-radius trend.', 'Confusing ionisation energy with electronegativity.', 'Treating trends as arbitrary rather than structure-based.'],
      tricks: ['Across a period: smaller atoms, higher ionisation energy.', 'Down a group: bigger atoms, lower ionisation energy.', 'Trends come from nuclear pull vs electron shielding.'],
      memory: ['"Across → smaller & grippier; down → bigger & looser."', '"Trends follow charge and shielding."', 's-block reactive metals; p-block varied.'],
      board: { CBSE: ['Cl.11 Classification & Periodicity'], ICSE: ['Cl.11 Periodic Properties'], IB: ['DP Periodicity'] },
      comp: ['JEE-Main', 'JEE-Advanced', 'NEET'], keywords: ['periodic trends', 'atomic radius', 'ionisation energy', 'electronegativity'],
      xprereqs: ['chemistry.F2.periodic-table'],
      quiz: [
        { lvl: 2, type: 'mcq', prompt: 'Across a period (left to right), atomic radius generally:', choices: ['decreases', 'increases', 'stays constant', 'doubles'], answer: 0, explanation: 'Increasing nuclear charge pulls electrons in tighter.' },
        { lvl: 2, type: 'mcq', prompt: 'Ionisation energy generally ___ down a group.', choices: ['decreases', 'increases', 'stays the same', 'is zero'], answer: 0, explanation: 'Outer electrons are farther out and easier to remove.' },
      ] },

    // ================= A2 =================
    { tier: 'A2', order: 1, slug: 'organic-mechanisms', title: 'Organic Reaction Mechanisms',
      summary: 'Nucleophiles, electrophiles and key reaction pathways — reasoned, not memorised.',
      outcomes: ['Identify nucleophiles and electrophiles', 'Follow reaction mechanisms', 'Predict organic products by reasoning'],
      concepts: [
        ['Electron flow', 'Organic reactions are electrons moving from electron-rich (nucleophile) to electron-poor (electrophile) sites. Curly arrows track this flow.'],
        ['Mechanism over memory', 'Understanding substitution, addition and elimination pathways lets you predict products instead of memorising thousands of reactions — the compression at the heart of organic chemistry.'],
      ],
      mistakes: ['Memorising products without the mechanism.', 'Confusing nucleophiles (electron donors) and electrophiles.', 'Drawing curly arrows from positive to negative (they go from electrons).'],
      tricks: ['Curly arrows always start from an electron pair.', 'Nucleophile = electron-rich attacker; electrophile = electron-poor target.', 'Classify the pathway (substitution/addition/elimination) to predict products.'],
      memory: ['"Arrows flow from electrons."', '"Nucleophile loves nuclei (positive sites)."', 'Mechanism predicts; memory fails.'],
      board: { CBSE: ['Cl.11-12 Organic Chemistry'], ICSE: ['Cl.12 Organic Mechanisms'], IB: ['DP Organic HL'] },
      comp: ['JEE-Main', 'JEE-Advanced', 'NEET'], keywords: ['mechanism', 'nucleophile', 'electrophile', 'curly arrows', 'organic'],
      xprereqs: ['chemistry.I2.organic-intro'],
      quiz: [
        { lvl: 2, type: 'mcq', prompt: 'A nucleophile is:', choices: ['electron-rich', 'electron-poor', 'always positive', 'a catalyst'], answer: 0, explanation: 'It donates an electron pair to an electrophile.' },
        { lvl: 3, type: 'mcq', prompt: 'In mechanisms, a curly arrow represents the movement of:', choices: ['an electron pair', 'a proton', 'an atom', 'energy'], answer: 0, explanation: 'Curly arrows show electron-pair movement.' },
      ] },
    { tier: 'A2', order: 2, slug: 'functional-groups', title: 'Functional-Group Chemistry',
      summary: 'Alcohols, aldehydes, ketones, carboxylic acids and amines — reactions by group.',
      outcomes: ['Recognise major functional groups', 'Predict characteristic reactions', 'Interconvert functional groups'],
      concepts: [
        ['Groups define reactivity', 'Each functional group has characteristic reactions: alcohols oxidise, acids neutralise bases, amines act as weak bases. Knowing the group predicts the chemistry.'],
        ['Interconversion', 'Functional groups convert into one another along known routes (e.g., alcohol → aldehyde → acid by oxidation), letting chemists build target molecules.'],
      ],
      mistakes: ['Confusing aldehydes and ketones (position of the C=O).', 'Forgetting carboxylic acids are acidic.', 'Mixing up oxidation products of primary vs secondary alcohols.'],
      tricks: ['−OH alcohol, −CHO aldehyde, C=O ketone, −COOH acid, −NH₂ amine.', 'Primary alcohol → aldehyde → carboxylic acid on oxidation.', 'Acids react with bases and carbonates.'],
      memory: ['"Group = predictable reactions."', '"Oxidise up the chain: alcohol→aldehyde→acid."', 'Amines are basic; acids are acidic.'],
      board: { CBSE: ['Cl.12 Alcohols, Aldehydes, Acids, Amines'], ICSE: ['Cl.12 Organic Compounds'], IB: ['DP Organic HL'] },
      comp: ['JEE-Main', 'JEE-Advanced', 'NEET'], keywords: ['functional groups', 'alcohol', 'aldehyde', 'carboxylic acid', 'amine'],
      xprereqs: ['chemistry.A2.organic-mechanisms'],
      quiz: [
        { lvl: 2, type: 'mcq', prompt: 'The −COOH group makes a molecule a(n):', choices: ['carboxylic acid', 'alcohol', 'amine', 'ketone'], answer: 0, explanation: '−COOH is the carboxylic acid group.' },
        { lvl: 2, type: 'mcq', prompt: 'Oxidising a primary alcohol first gives a(n):', choices: ['aldehyde', 'ketone', 'amine', 'alkane'], answer: 0, explanation: 'Primary alcohol → aldehyde → carboxylic acid.' },
      ] },
    { tier: 'A2', order: 3, slug: 'biomolecules-polymers', title: 'Biomolecules & Polymers',
      summary: 'Carbohydrates, proteins, lipids and polymers — chemistry that links to biology.',
      outcomes: ['Describe major biomolecules', 'Explain polymerisation', 'Connect structure to function'],
      concepts: [
        ['Biomolecules', 'Carbohydrates, proteins, lipids and nucleic acids are the molecules of life. They are built from small repeating units — a chemical basis for biology.'],
        ['Polymers', 'Polymers are long chains of repeating monomers, natural (proteins, starch) or synthetic (plastics). Their properties come from chain length and structure.'],
      ],
      mistakes: ['Confusing monomers with polymers.', 'Ignoring how structure dictates biological function.', 'Mixing up condensation and addition polymerisation.'],
      tricks: ['Polymer = many monomers linked.', 'Proteins are polymers of amino acids; starch of glucose.', 'Structure determines function — a theme shared with biology.'],
      memory: ['"Monomer → polymer (many units)."', '"Life\'s molecules: carbs, proteins, lipids, nucleic acids."', 'Structure dictates function.'],
      board: { CBSE: ['Cl.12 Biomolecules', 'Cl.12 Polymers'], ICSE: ['Cl.12 Biomolecules'], IB: ['DP Organic/Biochemistry'] },
      comp: ['NEET', 'JEE-Main'], keywords: ['biomolecules', 'polymer', 'protein', 'carbohydrate', 'monomer'],
      xprereqs: ['chemistry.A2.functional-groups'],
      quiz: [
        { lvl: 1, type: 'mcq', prompt: 'A polymer is made of many repeating:', choices: ['monomers', 'atoms of one element', 'ions', 'catalysts'], answer: 0, explanation: 'Monomers link to form a polymer chain.' },
        { lvl: 2, type: 'mcq', prompt: 'Proteins are polymers of:', choices: ['amino acids', 'glucose', 'fatty acids', 'nucleotides'], answer: 0, explanation: 'Amino acids are the monomers of proteins.' },
      ] },
    { tier: 'A2', order: 4, slug: 'coordination-chemistry', title: 'd-Block & Coordination Chemistry',
      summary: 'Transition metals, complex ions, ligands and colour.',
      outcomes: ['Describe transition-metal properties', 'Explain coordination complexes', 'Relate d-electrons to colour'],
      concepts: [
        ['Transition metals', 'd-block elements show variable oxidation states, form coloured compounds and act as catalysts — all traceable to their partly filled d-orbitals.'],
        ['Complexes', 'A central metal ion bonds to surrounding ligands, forming a coordination complex. Ligand arrangement splits d-orbital energies, producing characteristic colours.'],
      ],
      mistakes: ['Forgetting transition metals have variable oxidation states.', 'Confusing ligands with counter-ions.', 'Ignoring the link between d-electrons and colour.'],
      tricks: ['Variable oxidation states are a d-block signature.', 'Ligands donate electron pairs to the central metal.', 'd-orbital splitting explains complex colours.'],
      memory: ['"d-block: variable states, colour, catalysis."', '"Ligands donate to the metal centre."', 'Colour comes from d-orbital splitting.'],
      board: { CBSE: ['Cl.12 d- and f-Block', 'Cl.12 Coordination Compounds'], ICSE: ['Cl.12 Transition Elements'], IB: ['DP Transition Metals HL'] },
      comp: ['JEE-Main', 'JEE-Advanced', 'NEET'], keywords: ['transition metals', 'coordination', 'ligand', 'complex', 'd-block'],
      xprereqs: ['chemistry.A1.periodic-properties'],
      quiz: [
        { lvl: 2, type: 'mcq', prompt: 'Transition metals commonly show:', choices: ['variable oxidation states', 'only one oxidation state', 'no colour ever', 'no catalytic activity'], answer: 0, explanation: 'Partly filled d-orbitals allow variable states.' },
        { lvl: 2, type: 'mcq', prompt: 'In a complex ion, a ligand:', choices: ['donates an electron pair to the metal', 'removes electrons', 'is always water', 'changes the nucleus'], answer: 0, explanation: 'Ligands are electron-pair donors.' },
      ] },
    { tier: 'A2', order: 5, slug: 'analytical-chemistry', title: 'Analytical & Practical Chemistry Portfolio', core: true,
      summary: 'Qualitative and quantitative analysis, and error treatment — the capstone lab strand.',
      outcomes: ['Perform qualitative tests', 'Carry out quantitative analysis', 'Treat experimental error'],
      concepts: [
        ['Identifying and measuring', 'Qualitative analysis identifies what is present (flame tests, precipitates); quantitative analysis measures how much (titration, gravimetry).'],
        ['Reliable results', 'Good practical chemistry controls variables, repeats measurements and reports uncertainty — reusing the statistics and error skills from maths and physics.'],
      ],
      mistakes: ['Reporting results without uncertainty.', 'Confusing qualitative (what) with quantitative (how much).', 'Poor technique invalidating titration results.'],
      tricks: ['Titrate to a sharp colour change; repeat for concordant results.', 'Flame colours identify metal ions qualitatively.', 'Report measurements with their uncertainty.'],
      memory: ['"Qualitative = what; quantitative = how much."', '"Repeat for concordant titres."', 'Every result carries an uncertainty.'],
      board: { CBSE: ['Cl.11-12 Practical Chemistry'], ICSE: ['Cl.11-12 Practical'], IB: ['DP Chemistry IA'] },
      comp: [], keywords: ['analysis', 'titration', 'qualitative', 'quantitative', 'error'],
      xprereqs: ['math.I1.statistics-ii'],
      quiz: [
        { lvl: 2, type: 'mcq', prompt: 'Titration is used to determine a solution\'s:', choices: ['concentration', 'colour', 'temperature only', 'mass number'], answer: 0, explanation: 'It finds an unknown concentration by neutralisation.' },
        { lvl: 2, type: 'mcq', prompt: 'Qualitative analysis tells you:', choices: ['what is present', 'exactly how much', 'the temperature', 'the pressure'], answer: 0, explanation: 'Qualitative = identity; quantitative = amount.' },
      ] },
  ],
};
