// Chemistry — full curriculum dataset, deepened for JEE/NEET level.
// Each topic carries concepts + key formulas + a worked example (and some diagrams).
export default {
  subject: 'chemistry',
  topics: [
    // ================= F1 =================
    { tier: 'F1', order: 1, slug: 'matter-particles-states', title: 'Matter, Particles & States',
      summary: 'The particle (kinetic-molecular) model of matter, the three states, and changes of state — the microscopic picture behind all of chemistry.',
      outcomes: ['Describe matter using the kinetic-particle model', 'Explain the three states and changes between them by particle arrangement and energy', 'Distinguish pure substances from mixtures'],
      concepts: [
        ['Everything is particles in motion', 'All matter is made of tiny particles (atoms, molecules, ions) in constant motion. Their spacing, arrangement and energy decide the state: solids (fixed, vibrating), liquids (close, sliding), gases (far apart, fast, free).'],
        ['Changes of state are energy changes', 'Heating supplies energy that overcomes the forces holding particles together — melting then boiling. During a state change the temperature stays constant (energy goes into breaking forces, not raising KE). Mass is always conserved.'],
        ['Interparticle forces set properties', 'Stronger interparticle forces mean higher melting and boiling points. This single idea (developed further in bonding) explains why ionic solids melt high and gases condense low.'],
      ],
      formulas: ['Solid → Liquid → Gas : particle energy and spacing increase', 'During melting/boiling: temperature constant (latent heat breaks forces)', 'Mass conserved in every physical change'],
      example: { q: 'Why does the temperature stay constant while ice melts at 0°C even though heat is being added?', solution: 'The added energy (latent heat of fusion) breaks the forces holding water molecules in the rigid ice lattice, not raising their kinetic energy. Temperature (a measure of average KE) stays at 0°C until all the ice has melted.' },
      mistakes: ['Thinking particles expand when heated (they move faster/farther apart, they do not grow).', 'Confusing a mixture with a compound.', 'Believing gases have no mass.'],
      tricks: ['Solid → liquid → gas as particle energy and spacing increase.', 'Melting and freezing occur at the same temperature (opposite directions).', 'Temperature is flat during a change of state.'],
      memory: ['"Solid, liquid, gas = closer, looser, free."', '"Heat spreads particles apart."', 'Latent heat breaks forces — temperature stays flat.'],
      board: { CBSE: ['Cl.6-7 Matter', 'Cl.9 Matter in Our Surroundings'], ICSE: ['Cl.6-7 Matter'], IB: ['MYP Sciences'] },
      comp: ['NEET', 'JEE-Main'], keywords: ['matter', 'particle model', 'states', 'latent heat', 'kinetic theory'],
      quiz: [
        { lvl: 1, type: 'mcq', prompt: 'In which state are particles most closely packed and ordered?', choices: ['solid', 'liquid', 'gas', 'plasma'], answer: 0, explanation: 'Solids have the tightest, most ordered packing.' },
        { lvl: 2, type: 'mcq', prompt: 'While a pure solid melts, its temperature:', choices: ['stays constant', 'rises steadily', 'falls', 'doubles'], answer: 0, explanation: 'Latent heat breaks interparticle forces; temperature is constant during the change of state.' },
      ] },
    { tier: 'F1', order: 2, slug: 'separation-techniques', title: 'Separation Techniques',
      summary: 'Filtration, evaporation, distillation and chromatography — separating mixtures by exploiting differences in physical properties.',
      outcomes: ['Choose a separation method from the property that differs', 'Explain distillation and chromatography', 'Interpret a chromatogram (Rf)'],
      concepts: [
        ['Separate by difference', 'Mixtures separate because components differ — particle size (filtration), boiling point (distillation), or affinity for a moving vs stationary phase (chromatography).'],
        ['Chromatography and Rf', 'In paper chromatography, components travel different distances. The retention factor Rf = (distance moved by spot)/(distance moved by solvent) identifies a component and is always between 0 and 1.'],
      ],
      formulas: ['Rf = (distance moved by substance) / (distance moved by solvent front)', '0 ≤ Rf ≤ 1'],
      example: { q: 'A pigment spot moves 3.0 cm while the solvent front moves 12.0 cm. Find its Rf.', solution: 'Rf = 3.0 / 12.0 = 0.25. Being < 1 and characteristic under those conditions, it helps identify the pigment.' },
      mistakes: ['Using filtration to separate a dissolved solid (it passes through).', 'Confusing evaporation with distillation (distillation recovers the liquid).', 'Reporting Rf greater than 1.'],
      tricks: ['Filtration separates insoluble solids from liquids.', 'Distillation separates by boiling point and recovers the liquid.', 'Rf compares how far the spot travelled versus the solvent.'],
      memory: ['"Filter the insoluble; distil by boiling point."', '"Rf = spot ÷ solvent, always < 1."', 'Separation is physical, not chemical.'],
      board: { CBSE: ['Cl.6 Separation of Substances', 'Cl.9 Is Matter Pure'], ICSE: ['Cl.6-8 Separation'], IB: ['MYP Sciences'] },
      comp: ['NEET'], keywords: ['filtration', 'distillation', 'chromatography', 'Rf', 'mixtures'],
      quiz: [
        { lvl: 1, type: 'mcq', prompt: 'Best method to get pure water from salt water?', choices: ['distillation', 'filtration', 'chromatography', 'decanting'], answer: 0, explanation: 'Distillation boils off and condenses the water, leaving salt behind.' },
        { lvl: 2, type: 'numeric', prompt: 'A spot moves 4 cm; the solvent front moves 16 cm. Rf = ? (2 dp)', answer: 0.25, tolerance: 0.01, explanation: 'Rf = 4/16 = 0.25.' },
      ] },
    { tier: 'F1', order: 3, slug: 'physical-chemical-change', title: 'Physical vs Chemical Change',
      summary: 'Telling physical from chemical changes, the evidence of reaction, and conservation of mass as the accounting law behind balancing.',
      outcomes: ['Distinguish physical and chemical changes', 'Identify signs of a chemical reaction', 'Apply conservation of mass quantitatively'],
      concepts: [
        ['Two kinds of change', 'A physical change alters form but not the substance (melting, dissolving); a chemical change makes new substances (burning, rusting), often signalled by colour change, gas, heat/light, or a precipitate.'],
        ['Conservation of mass', 'Atoms are only rearranged in a reaction, so total mass of reactants = total mass of products. In an open system, escaping gas can make mass appear to fall — account for it.'],
      ],
      formulas: ['Total mass of reactants = total mass of products', 'mass(products) − mass(reactants) = 0 (closed system)'],
      example: { q: '4 g of hydrogen reacts completely with 32 g of oxygen. What mass of water forms?', solution: 'By conservation of mass, mass of water = 4 + 32 = 36 g. Atoms are only rearranged into H₂O.' },
      mistakes: ['Calling dissolving a chemical change (it is physical).', 'Assuming mass is lost when gas escapes (it left as product).', 'Missing subtle signs like a temperature change.'],
      tricks: ['New substance formed? → chemical. Same substance, new form? → physical.', 'Look for gas, colour change, heat/light, or a precipitate.', 'Total mass is unchanged — count gases too.'],
      memory: ['"New substance = chemical change."', '"Atoms rearrange, mass stays."', 'Signs: gas, colour, heat, precipitate.'],
      board: { CBSE: ['Cl.7 Physical & Chemical Changes'], ICSE: ['Cl.7 Physical & Chemical Changes'], IB: ['MYP Sciences'] },
      comp: ['NEET'], keywords: ['physical change', 'chemical change', 'conservation of mass', 'reaction'],
      quiz: [
        { lvl: 1, type: 'mcq', prompt: 'Which is a chemical change?', choices: ['iron rusting', 'ice melting', 'sugar dissolving', 'water boiling'], answer: 0, explanation: 'Rusting forms a new substance (iron oxide).' },
        { lvl: 2, type: 'numeric', prompt: '2 g of carbon burns with 5.33 g of oxygen to form carbon dioxide only. Mass of CO₂ (g)?', answer: 7.33, tolerance: 0.05, explanation: 'Conservation of mass: 2 + 5.33 = 7.33 g.' },
      ] },

    // ================= F2 =================
    { tier: 'F2', order: 1, slug: 'atomic-structure-i', title: 'Atomic Structure I',
      summary: 'Protons, neutrons and electrons; atomic number, mass number, isotopes and relative atomic mass.',
      outcomes: ['Describe subatomic particles and their charges', 'Use atomic number and mass number', 'Explain isotopes and compute relative atomic mass'],
      concepts: [
        ['Inside the atom', 'A tiny dense nucleus of protons (+1) and neutrons (0) is surrounded by electrons (−1). The atomic number Z (protons) defines the element; a neutral atom has equal protons and electrons.'],
        ['Isotopes and relative atomic mass', 'Isotopes are atoms of one element with different neutron numbers — same chemistry, different mass. Relative atomic mass is the abundance-weighted average of isotope masses, which is why it is rarely a whole number.'],
      ],
      diagram: `<svg viewBox="0 0 320 170" role="img" aria-label="Atom with nucleus and two electron shells" xmlns="http://www.w3.org/2000/svg">
  <circle cx="160" cy="80" r="68" fill="none" stroke="#39466a"/>
  <circle cx="160" cy="80" r="42" fill="none" stroke="#39466a"/>
  <circle cx="160" cy="80" r="15" fill="#6366f1"/>
  <text x="160" y="84" font-size="9" fill="#fff" text-anchor="middle">nucleus</text>
  <circle cx="228" cy="80" r="5" fill="#6ee7a8"/><circle cx="92" cy="80" r="5" fill="#6ee7a8"/>
  <circle cx="160" cy="38" r="5" fill="#a8c0ff"/><circle cx="160" cy="122" r="5" fill="#a8c0ff"/>
  <circle cx="202" cy="38" r="5" fill="#a8c0ff"/>
  <text x="160" y="165" font-size="10" fill="#9aa8c4" text-anchor="middle">protons + neutrons in the nucleus; electrons in shells</text>
</svg>`,
      formulas: ['Atomic number Z = protons = electrons (neutral atom)', 'Mass number A = protons + neutrons', 'Neutrons = A − Z', 'Relative atomic mass = Σ(isotope mass × fractional abundance)'],
      example: { q: 'Chlorine is 75% ³⁵Cl and 25% ³⁷Cl. Find its relative atomic mass.', solution: 'Ar = 35(0.75) + 37(0.25) = 26.25 + 9.25 = 35.5. This weighted average is why chlorine\'s Ar is 35.5, not a whole number.' },
      mistakes: ['Confusing atomic number (protons) with mass number.', 'Thinking isotopes are different elements.', 'Averaging isotope masses without weighting by abundance.'],
      tricks: ['Atomic number = protons = electrons (neutral atom).', 'Neutrons = mass number − atomic number.', 'Relative atomic mass is an abundance-weighted average.'],
      memory: ['"Protons define the element."', '"Neutrons = A − Z."', 'Ar is a weighted average → not whole.'],
      board: { CBSE: ['Cl.9 Structure of the Atom'], ICSE: ['Cl.8-9 Atomic Structure'], IB: ['DP Atomic Structure'] },
      comp: ['JEE-Main', 'NEET'], keywords: ['atom', 'proton', 'neutron', 'electron', 'isotope', 'relative atomic mass'],
      quiz: [
        { lvl: 1, type: 'numeric', prompt: 'An atom has 11 protons and 12 neutrons. Mass number?', answer: 23, tolerance: 0, explanation: 'A = protons + neutrons = 11 + 12 = 23.' },
        { lvl: 2, type: 'numeric', prompt: 'Element X is 60% mass-10 and 40% mass-11. Relative atomic mass? (1 dp)', answer: 10.4, tolerance: 0.05, explanation: '10(0.6) + 11(0.4) = 10.4.' },
      ] },
    { tier: 'F2', order: 2, slug: 'periodic-table', title: 'The Periodic Table as a Map',
      summary: 'Periods and groups as patterns arising from electron configuration — a predictive map, not a list to memorise.',
      outcomes: ['Read the periodic table\'s layout', 'Relate group number to valence electrons', 'Predict reactivity trends'],
      concepts: [
        ['A map from electron structure', 'Elements are ordered by increasing atomic number into periods (rows) and groups (columns). Group number equals the number of outer (valence) electrons, which is why a group shares chemistry.'],
        ['Trends are predictable', 'Reactivity, atomic size and metallic character change smoothly across periods and down groups — Group 1 metals get more reactive down the group; Group 17 non-metals less reactive down.'],
      ],
      formulas: ['Group number (main groups) = number of valence electrons', 'Period number = number of occupied electron shells'],
      example: { q: 'Element in Group 2, Period 3. How many valence electrons and shells, and what is it?', solution: '2 valence electrons and 3 shells → magnesium (Mg). Its 2 outer electrons make it a reactive Group-2 metal forming Mg²⁺.' },
      mistakes: ['Memorising elements instead of using group patterns.', 'Confusing groups (columns) with periods (rows).', 'Forgetting group number links to valence electrons.'],
      tricks: ['Same group → similar chemistry (same valence electrons).', 'Metals left, non-metals right.', 'Group 1 reactivity increases down; Group 17 decreases down.'],
      memory: ['"Groups = columns = families (same valence e⁻)."', '"Periods = rows = shells."', 'Predict, don\'t memorise.'],
      board: { CBSE: ['Cl.10 Periodic Classification'], ICSE: ['Cl.8-10 Periodic Table'], IB: ['DP Periodicity'] },
      comp: ['JEE-Main', 'NEET'], keywords: ['periodic table', 'groups', 'periods', 'valence electrons', 'trends'],
      quiz: [
        { lvl: 1, type: 'mcq', prompt: 'Elements in the same group tend to have the same number of:', choices: ['valence electrons', 'neutrons', 'shells', 'protons'], answer: 0, explanation: 'Group number = valence electrons → similar chemistry.' },
        { lvl: 2, type: 'mcq', prompt: 'An element in Group 17, Period 2 is:', choices: ['fluorine', 'oxygen', 'neon', 'chlorine'], answer: 0, explanation: 'Group 17 (7 valence e⁻), Period 2 (2 shells) → fluorine.' },
      ] },
    { tier: 'F2', order: 3, slug: 'mole-concept', title: 'The Mole Concept',
      summary: 'The mole, Avogadro\'s number and molar mass — proportional reasoning applied to counting particles. The keystone of all quantitative chemistry.',
      outcomes: ['Define the mole and Avogadro\'s number', 'Convert between mass, moles and number of particles', 'Compute molar mass of compounds'],
      concepts: [
        ['Counting by weighing', 'Atoms are too small to count, so we weigh them. One mole is Avogadro\'s number (Nₐ ≈ 6.022×10²³) of particles; the molar mass in g/mol equals the relative atomic/molecular mass, linking mass to particle count.'],
        ['The mole is a ratio', 'moles = mass ÷ molar mass — the same proportional reasoning as ratios, now applied to particles. Every stoichiometry, concentration and gas calculation flows from this.'],
      ],
      diagram: `<svg viewBox="0 0 340 120" role="img" aria-label="Mass to moles to particles conversion" xmlns="http://www.w3.org/2000/svg">
  <rect x="16" y="30" width="86" height="60" rx="8" fill="#12182a" stroke="#39466a"/>
  <rect x="127" y="30" width="86" height="60" rx="8" fill="#12182a" stroke="#39466a"/>
  <rect x="238" y="30" width="86" height="60" rx="8" fill="#12182a" stroke="#39466a"/>
  <text x="59" y="58" font-size="13" fill="#e6ecff" text-anchor="middle">mass (g)</text>
  <text x="170" y="58" font-size="13" fill="#8fa0ff" text-anchor="middle">moles n</text>
  <text x="281" y="58" font-size="13" fill="#6ee7a8" text-anchor="middle">particles</text>
  <line x1="102" y1="60" x2="127" y2="60" stroke="#6366f1" stroke-width="1.5" marker-end="url(#a)"/>
  <line x1="213" y1="60" x2="238" y2="60" stroke="#6366f1" stroke-width="1.5" marker-end="url(#a)"/>
  <text x="114" y="24" font-size="9" fill="#9aa8c4" text-anchor="middle">÷ M</text>
  <text x="225" y="24" font-size="9" fill="#9aa8c4" text-anchor="middle">× Nₐ</text>
  <defs><marker id="a" markerWidth="6" markerHeight="6" refX="5" refY="3" orient="auto"><path d="M0,0 L6,3 L0,6 Z" fill="#6366f1"/></marker></defs>
</svg>`,
      formulas: ['n = m / M   (moles = mass ÷ molar mass)', 'Number of particles = n × Nₐ,   Nₐ ≈ 6.022×10^23 /mol', 'Molar mass of a compound = Σ (atomic masses)'],
      example: { q: 'How many water molecules are in 36 g of water? (M = 18 g/mol)', solution: 'n = m/M = 36/18 = 2 mol. Molecules = n × Nₐ = 2 × 6.022×10²³ = 1.2×10²⁴ molecules.' },
      mistakes: ['Confusing molar mass with atomic number.', 'Using the wrong molar mass for a compound.', 'Mixing up moles and grams.'],
      tricks: ['moles = mass ÷ molar mass.', 'particles = moles × Nₐ.', 'Molar mass of a compound = sum of its atoms\' masses.'],
      memory: ['"n = m/M."', '"1 mole = 6.022×10²³ particles."', 'The mole is ratio thinking for particles.'],
      board: { CBSE: ['Cl.9-11 Mole Concept', 'Cl.11 Some Basic Concepts'], ICSE: ['Cl.10 Mole Concept'], IB: ['DP Stoichiometry'] },
      comp: ['JEE-Main', 'JEE-Advanced', 'NEET'], keywords: ['mole', 'Avogadro', 'molar mass', 'stoichiometry'],
      xprereqs: ['math.F2.exponents-scientific-notation'],
      quiz: [
        { lvl: 1, type: 'numeric', prompt: 'Moles in 36 g of water (M = 18 g/mol)?', answer: 2, tolerance: 0, unit: 'mol', explanation: 'n = 36/18 = 2 mol.' },
        { lvl: 2, type: 'numeric', prompt: 'Mass of 0.5 mol of carbon (M = 12 g/mol), in grams?', answer: 6, tolerance: 0, unit: 'g', explanation: 'm = n×M = 0.5×12 = 6 g.' },
      ] },
    { tier: 'F2', order: 4, slug: 'chemical-formulae-equations', title: 'Chemical Formulae & Equations',
      summary: 'Writing formulae from valency and balancing equations as the visible bookkeeping of conservation of mass.',
      outcomes: ['Write formulae from valencies', 'Balance chemical equations', 'Interpret an equation in moles'],
      concepts: [
        ['Formulae from valency', 'A formula shows which atoms combine and in what ratio, set by combining power (valency). Swap-and-drop the valencies (e.g., Al³⁺ and O²⁻ → Al₂O₃).'],
        ['Balancing = conservation', 'A balanced equation has equal atoms of each element on both sides because atoms are conserved. Only coefficients (amounts) are adjusted — never subscripts.'],
      ],
      formulas: ['Atoms of each element: reactant side = product side', 'Coefficients give the mole ratio of the reaction'],
      example: { q: 'Balance: Al + O₂ → Al₂O₃.', solution: '4 Al + 3 O₂ → 2 Al₂O₃. Check: Al 4=4, O 6=6. Adjust coefficients only.' },
      mistakes: ['Changing subscripts instead of coefficients to balance.', 'Forgetting a balanced equation conserves every element.', 'Miswriting formulae by ignoring valency.'],
      tricks: ['Balance coefficients, never subscripts.', 'Save O and H for last.', 'Check every element on both sides.'],
      memory: ['"Balance coefficients, not subscripts."', '"Atoms in = atoms out."', 'Formula = recipe set by valency.'],
      board: { CBSE: ['Cl.9-10 Chemical Reactions & Equations'], ICSE: ['Cl.8-9 Chemical Equations'], IB: ['DP Stoichiometry'] },
      comp: ['JEE-Main', 'NEET'], keywords: ['formula', 'balancing', 'equation', 'valency'],
      xprereqs: ['chemistry.F1.physical-chemical-change'],
      quiz: [
        { lvl: 2, type: 'mcq', prompt: 'To balance an equation you adjust the:', choices: ['coefficients', 'subscripts', 'atomic numbers', 'symbols'], answer: 0, explanation: 'Coefficients change amounts; subscripts would change the substance.' },
        { lvl: 2, type: 'numeric', prompt: 'Balance H₂ + O₂ → H₂O. Coefficient in front of H₂O?', answer: 2, tolerance: 0, explanation: '2H₂ + O₂ → 2H₂O balances all atoms.' },
      ] },
    { tier: 'F2', order: 5, slug: 'stoichiometry-intro', title: 'Introductory Stoichiometry',
      summary: 'Using mole ratios from balanced equations for mass-to-mass calculations, and finding the limiting reactant.',
      outcomes: ['Use mole ratios from equations', 'Perform mass → mole → mole → mass calculations', 'Identify the limiting reactant'],
      concepts: [
        ['Coefficients are mole ratios', 'The coefficients of a balanced equation give the ratio of moles reacting. To go grams-to-grams: convert to moles, apply the mole ratio, convert back to mass.'],
        ['Limiting reactant', 'The reactant that runs out first caps the product. Compare moles ÷ coefficient for each reactant; the smallest is limiting.'],
      ],
      formulas: ['mass → n = m/M → ×(mole ratio) → m = n×M', 'Limiting reactant: smallest of (moles ÷ coefficient)'],
      example: { q: 'For N₂ + 3H₂ → 2NH₃, how many moles of NH₃ from 2 mol N₂ with excess H₂?', solution: 'Mole ratio N₂ : NH₃ = 1 : 2, so 2 mol N₂ → 4 mol NH₃ (H₂ excess, N₂ limiting).' },
      mistakes: ['Using mass ratios directly instead of mole ratios.', 'Forgetting to balance the equation first.', 'Skipping the conversion back to mass.'],
      tricks: ['Balance first, then read mole ratios.', 'mass → mole → mole → mass.', 'Limiting reactant = smallest (moles ÷ coefficient).'],
      memory: ['"Coefficients are mole ratios."', '"Mass → mole → mole → mass."', 'Limiting reactant caps the yield.'],
      board: { CBSE: ['Cl.11 Some Basic Concepts'], ICSE: ['Cl.10 Mole & Stoichiometry'], IB: ['DP Stoichiometry'] },
      comp: ['JEE-Main', 'JEE-Advanced', 'NEET'], keywords: ['stoichiometry', 'mole ratio', 'limiting reactant'],
      xprereqs: ['chemistry.F2.mole-concept'],
      quiz: [
        { lvl: 2, type: 'mcq', prompt: 'In 2H₂ + O₂ → 2H₂O, the mole ratio of H₂ to H₂O is:', choices: ['1 : 1', '2 : 1', '1 : 2', '2 : 3'], answer: 0, explanation: 'Coefficients 2 and 2 give 1:1.' },
        { lvl: 3, type: 'numeric', prompt: 'For N₂ + 3H₂ → 2NH₃, moles of NH₃ from 3 mol H₂ (excess N₂)?', answer: 2, tolerance: 0, unit: 'mol', explanation: 'H₂ : NH₃ = 3 : 2 → 2 mol NH₃.' },
      ] },

    // ================= I1 =================
    { tier: 'I1', order: 1, slug: 'bonding-i', title: 'Bonding I',
      summary: 'Ionic, covalent and metallic bonding from the drive for full outer shells, and how bonding type dictates properties.',
      outcomes: ['Distinguish ionic, covalent, metallic bonds', 'Draw electron-dot (Lewis) structures', 'Relate bonding to physical properties'],
      concepts: [
        ['Atoms bond for stable octets', 'Atoms gain, lose or share electrons to reach a full outer shell. Metal + non-metal transfer → ionic; non-metals share → covalent; metals pool a "sea" of delocalised electrons → metallic.'],
        ['Bonding sets properties', 'Ionic solids form giant lattices (high melting, conduct when molten/aqueous); covalent molecules are often low-melting and non-conducting; metals conduct and are malleable via mobile electrons.'],
      ],
      formulas: ['Ionic: metal (loses e⁻) + non-metal (gains e⁻) → ions', 'Covalent: shared electron pair between non-metals', 'Metallic: cations in a sea of delocalised electrons'],
      example: { q: 'Predict the bonding and a property of MgCl₂.', solution: 'Mg transfers 2 electrons to two Cl → Mg²⁺ and 2Cl⁻: ionic. Property: high melting point; conducts when molten/dissolved (mobile ions).' },
      mistakes: ['Thinking covalent bonds transfer electrons (they share).', 'Judging bonding by name alone.', 'Forgetting metals conduct due to delocalised electrons.'],
      tricks: ['Metal + non-metal → ionic; non-metal + non-metal → covalent.', 'Count valence electrons to predict bonding.', 'High melting + conducts molten → ionic.'],
      memory: ['"Ionic transfers, covalent shares, metallic pools."', '"Full outer shell = stability."', 'Bonding explains melting point and conductivity.'],
      board: { CBSE: ['Cl.10-11 Chemical Bonding'], ICSE: ['Cl.9-10 Chemical Bonding'], IB: ['DP Bonding'] },
      comp: ['JEE-Main', 'NEET'], keywords: ['ionic', 'covalent', 'metallic', 'bonding', 'Lewis structure'],
      xprereqs: ['chemistry.F2.atomic-structure-i'],
      quiz: [
        { lvl: 1, type: 'mcq', prompt: 'A bond formed by sharing electrons is:', choices: ['covalent', 'ionic', 'metallic', 'nuclear'], answer: 0, explanation: 'Covalent bonds share electron pairs.' },
        { lvl: 2, type: 'mcq', prompt: 'MgCl₂ (metal + non-metal) is held by ___ bonding.', choices: ['ionic', 'covalent', 'metallic', 'hydrogen'], answer: 0, explanation: 'Electron transfer between metal and non-metal is ionic.' },
      ] },
    { tier: 'I1', order: 2, slug: 'reactions-equations', title: 'Reactions & Equations Deepened',
      summary: 'Reaction types, net ionic equations, oxidation numbers and the essentials of redox.',
      outcomes: ['Classify reaction types', 'Write net ionic equations', 'Assign oxidation numbers and identify redox'],
      concepts: [
        ['Types of reaction', 'Combination, decomposition, displacement, double displacement (precipitation/neutralisation). The type predicts the products.'],
        ['Redox by electron transfer', 'Oxidation is loss of electrons, reduction is gain (OIL RIG). Oxidation numbers track it: the species whose oxidation number rises is oxidised; the oxidising agent is itself reduced.'],
      ],
      formulas: ['OIL RIG: Oxidation Is Loss, Reduction Is Gain (of electrons)', 'Oxidation number ↑ = oxidised; ↓ = reduced', 'Net ionic equation: cancel spectator ions'],
      example: { q: 'In Zn + Cu²⁺ → Zn²⁺ + Cu, which species is oxidised?', solution: 'Zn: 0 → +2 (loses electrons) → oxidised (reducing agent). Cu²⁺: +2 → 0 (gains electrons) → reduced.' },
      mistakes: ['Forgetting redox pairs oxidation with reduction.', 'Writing molecular when ionic equations are asked.', 'Misassigning oxidation numbers.'],
      tricks: ['OIL RIG for electron transfer.', 'Cancel spectator ions for net ionic equations.', 'A more reactive metal displaces a less reactive one.'],
      memory: ['"OIL RIG."', '"Ox. number up = oxidised."', 'Every oxidation has a matching reduction.'],
      board: { CBSE: ['Cl.10 Chemical Reactions'], ICSE: ['Cl.10 Reactions'], IB: ['DP Redox'] },
      comp: ['JEE-Main', 'NEET'], keywords: ['reaction types', 'ionic equations', 'redox', 'oxidation number'],
      quiz: [
        { lvl: 1, type: 'mcq', prompt: 'Oxidation is the ___ of electrons.', choices: ['loss', 'gain', 'sharing', 'counting'], answer: 0, explanation: 'OIL: Oxidation Is Loss.' },
        { lvl: 2, type: 'mcq', prompt: 'In Zn + Cu²⁺ → Zn²⁺ + Cu, Cu²⁺ is:', choices: ['reduced', 'oxidised', 'a spectator', 'unchanged'], answer: 0, explanation: 'Cu²⁺ gains electrons (→ Cu): reduced.' },
      ] },
    { tier: 'I1', order: 3, slug: 'acids-bases-salts', title: 'Acids, Bases & Salts',
      summary: 'The pH scale as a logarithm of H⁺ concentration, neutralisation, and titration.',
      outcomes: ['Describe acids and bases (Arrhenius/Brønsted)', 'Use the pH scale quantitatively', 'Explain neutralisation and titration'],
      concepts: [
        ['Acids, bases and pH', 'Acids donate H⁺ (Brønsted); bases accept H⁺ (or donate OH⁻). pH = −log[H⁺] compresses a huge range into 0–14; each unit is a ten-fold change in acidity.'],
        ['Neutralisation and titration', 'Acid + base → salt + water. Titration finds an unknown concentration by adding a standard solution to the equivalence point, using n = CV.'],
      ],
      formulas: ['pH = −log[H⁺],  [H⁺] = 10^(−pH)', 'At 25°C: [H⁺][OH⁻] = 1.0×10^(−14)', 'Acid + base → salt + water', 'Titration: n = C × V'],
      example: { q: 'A solution has [H⁺] = 1×10⁻³ mol/L. Find its pH and state if it is acidic.', solution: 'pH = −log(10⁻³) = 3. Since pH < 7, the solution is acidic.' },
      mistakes: ['Thinking higher pH means more acidic (it is less).', 'Forgetting neutralisation produces water.', 'Treating pH as linear (it is logarithmic).'],
      tricks: ['pH < 7 acidic, = 7 neutral, > 7 basic.', 'Each pH unit is ×10 in [H⁺].', 'Titration: n = CV at the equivalence point.'],
      memory: ['"pH = −log[H⁺]."', '"Low pH, high acidity."', '"Acid + base → salt + water."'],
      board: { CBSE: ['Cl.10 Acids, Bases & Salts'], ICSE: ['Cl.9-10 Acids, Bases, Salts'], IB: ['DP Acids & Bases'] },
      comp: ['JEE-Main', 'NEET'], keywords: ['acid', 'base', 'pH', 'neutralisation', 'titration'],
      quiz: [
        { lvl: 1, type: 'numeric', prompt: 'If [H⁺] = 1×10⁻² mol/L, what is the pH?', answer: 2, tolerance: 0, explanation: 'pH = −log(10⁻²) = 2.' },
        { lvl: 2, type: 'mcq', prompt: 'Acid + base produces salt and:', choices: ['water', 'oxygen', 'hydrogen only', 'a metal'], answer: 0, explanation: 'Neutralisation makes a salt plus water.' },
      ] },
    { tier: 'I1', order: 4, slug: 'solutions-concentration', title: 'Solutions & Concentration',
      summary: 'Molarity, dilution and the mole concept applied to real solutions.',
      outcomes: ['Calculate molarity', 'Perform dilution calculations', 'Relate concentration, moles and volume'],
      concepts: [
        ['Concentration as a rate', 'Molarity (M) is moles of solute per litre of solution — again a ratio, bridging the mole concept to practical lab quantities.'],
        ['Dilution conserves moles', 'Adding solvent lowers concentration but keeps moles of solute fixed: C₁V₁ = C₂V₂ — inverse proportion in action.'],
      ],
      formulas: ['Molarity M = n / V(litres)', 'n = M × V', 'Dilution: C₁V₁ = C₂V₂'],
      example: { q: 'What volume of 2 M stock makes 250 mL of 0.5 M solution?', solution: 'C₁V₁ = C₂V₂ → 2 × V₁ = 0.5 × 0.250 → V₁ = 0.0625 L = 62.5 mL, then dilute to 250 mL.' },
      mistakes: ['Confusing moles with molarity.', 'Using mL instead of L for molarity.', 'Thinking dilution changes the amount of solute (it does not).'],
      tricks: ['Molarity = moles ÷ litres.', 'C₁V₁ = C₂V₂ for dilution.', 'Convert mL to L before computing molarity.'],
      memory: ['"M = n/V (litres)."', '"C₁V₁ = C₂V₂."', 'Dilution keeps moles, lowers concentration.'],
      board: { CBSE: ['Cl.11-12 Solutions'], ICSE: ['Cl.10-11 Solutions'], IB: ['DP Stoichiometry'] },
      comp: ['JEE-Main', 'JEE-Advanced', 'NEET'], keywords: ['molarity', 'concentration', 'dilution', 'solution'],
      xprereqs: ['chemistry.F2.mole-concept'],
      quiz: [
        { lvl: 1, type: 'numeric', prompt: 'Molarity of 2 mol in 4 L?', answer: 0.5, tolerance: 0, unit: 'M', explanation: 'M = 2/4 = 0.5 M.' },
        { lvl: 2, type: 'numeric', prompt: 'Dilute 100 mL of 2 M to 200 mL. New molarity (M)?', answer: 1, tolerance: 0, explanation: 'C₁V₁ = C₂V₂ → 2×100 = C₂×200 → 1 M.' },
      ] },
    { tier: 'I1', order: 5, slug: 'rates-reaction', title: 'Rates of Reaction',
      summary: 'Collision theory and the factors that change reaction rate, read from rate graphs.',
      outcomes: ['Identify factors affecting rate', 'Interpret rate graphs', 'Explain rate with collision theory and activation energy'],
      concepts: [
        ['Collision theory', 'Reactions occur when particles collide with energy ≥ activation energy and correct orientation. Concentration, temperature, surface area and catalysts increase the frequency or success of collisions.'],
        ['Rate from graphs', 'Rate = Δ[concentration] ÷ time = the gradient of a concentration-vs-time graph — steep at first, flattening as reactants deplete. Rate-as-slope, shared with physics and calculus.'],
      ],
      formulas: ['Rate = Δ[concentration] / Δt = gradient of the curve', 'Higher T, [conc], surface area, or a catalyst → faster', 'Catalyst lowers activation energy Eₐ (not consumed)'],
      example: { q: 'A reaction produces 20 cm³ of gas in the first 10 s, then slows. Average rate over that interval?', solution: 'Average rate = 20 ÷ 10 = 2 cm³/s. It slows later as reactant concentration falls, reducing collision frequency.' },
      mistakes: ['Thinking a catalyst is used up.', 'Confusing rate (speed) with yield (amount).', 'Ignoring that rate falls as reactants deplete.'],
      tricks: ['More concentration/temperature/surface area → faster.', 'A catalyst lowers Eₐ without being consumed.', 'Rate = slope of the product-vs-time graph.'],
      memory: ['"Faster = more or harder collisions."', '"Catalyst lowers Eₐ, stays unchanged."', 'Rate = slope of the curve.'],
      board: { CBSE: ['Cl.12 Chemical Kinetics (intro)'], ICSE: ['Cl.10-11 Rate of Reaction'], IB: ['DP Kinetics'] },
      comp: ['JEE-Main', 'NEET'], keywords: ['reaction rate', 'collision theory', 'catalyst', 'activation energy'],
      quiz: [
        { lvl: 1, type: 'mcq', prompt: 'A catalyst speeds a reaction by:', choices: ['lowering the activation energy', 'being consumed', 'raising temperature', 'adding mass'], answer: 0, explanation: 'It offers a lower-Eₐ pathway and is not used up.' },
        { lvl: 2, type: 'numeric', prompt: '30 cm³ of gas forms in 15 s. Average rate (cm³/s)?', answer: 2, tolerance: 0, explanation: '30/15 = 2 cm³/s.' },
      ] },

    // ================= I2 =================
    { tier: 'I2', order: 1, slug: 'atomic-structure-ii', title: 'Atomic Structure II',
      summary: 'Electron configuration, subshells and quantum shells — the origin of the periodic table\'s shape.',
      outcomes: ['Write electron configurations (up to ~Z=20)', 'Relate configuration to periodic position', 'Explain shell energies intuitively'],
      concepts: [
        ['Electrons fill by energy', 'Electrons occupy shells and subshells (s, p, d) in order of increasing energy (aufbau). Configuration like 1s² 2s² 2p⁶ 3s¹ (Na) explains an element\'s group and reactivity.'],
        ['Valence controls chemistry', 'The outer-shell configuration determines bonding. Noble gases have full shells (unreactive); Group 1 has one easily-lost outer electron.'],
      ],
      formulas: ['Shell capacity = 2n² electrons (n = shell number)', 'Filling order (aufbau): 1s 2s 2p 3s 3p 4s 3d ...', 'Valence electrons = electrons in the outermost shell'],
      example: { q: 'Write the electron configuration of sodium (Z = 11) and give its group.', solution: '1s² 2s² 2p⁶ 3s¹. One valence electron in shell 3 → Group 1, Period 3. That 3s electron is easily lost to form Na⁺.' },
      mistakes: ['Filling higher shells before lower ones are complete.', 'Confusing shells with subshells.', 'Forgetting valence electrons drive reactivity.'],
      tricks: ['Fill lowest-energy levels first (aufbau).', 'Shell holds 2n² electrons.', 'Full shell = stable/unreactive.'],
      memory: ['"Fill low energy first."', '"Capacity = 2n²."', 'Outer electrons = chemistry.'],
      board: { CBSE: ['Cl.11 Structure of Atom'], ICSE: ['Cl.11 Atomic Structure'], IB: ['DP Atomic Structure'] },
      comp: ['JEE-Main', 'JEE-Advanced', 'NEET'], keywords: ['electron configuration', 'subshells', 'aufbau', 'valence'],
      xprereqs: ['chemistry.F2.atomic-structure-i'],
      quiz: [
        { lvl: 2, type: 'numeric', prompt: 'Maximum electrons in the 3rd shell (n = 3), using 2n²?', answer: 18, tolerance: 0, explanation: '2×3² = 18 electrons.' },
        { lvl: 2, type: 'mcq', prompt: 'Sodium (1s² 2s² 2p⁶ 3s¹) is in group:', choices: ['1', '2', '17', '18'], answer: 0, explanation: 'One valence electron → Group 1.' },
      ] },
    { tier: 'I2', order: 2, slug: 'bonding-ii', title: 'Bonding II',
      summary: 'Molecular shapes from VSEPR, bond and molecular polarity, and intermolecular forces.',
      outcomes: ['Predict shapes with VSEPR', 'Determine molecular polarity', 'Rank intermolecular forces'],
      concepts: [
        ['Shape from electron-pair repulsion', 'Electron pairs (bonding and lone) around a central atom repel and spread as far apart as possible (VSEPR): 2 pairs → linear (180°), 3 → trigonal (120°), 4 → tetrahedral (109.5°); lone pairs bend the shape.'],
        ['Polarity and intermolecular forces', 'Unequal sharing makes polar bonds; symmetry decides overall polarity. Intermolecular forces (London < dipole–dipole < hydrogen bonding) set boiling points and solubility.'],
      ],
      formulas: ['VSEPR: 2 pairs → 180°, 3 → 120°, 4 → 109.5°', 'Strength: London dispersion < dipole–dipole < hydrogen bond', 'Symmetric shape can be non-polar despite polar bonds (CO₂)'],
      example: { q: 'Predict the shape and polarity of CO₂ and of H₂O.', solution: 'CO₂: 2 bonding regions, no lone pairs on C → linear (180°); dipoles cancel → non-polar. H₂O: 2 bonding + 2 lone pairs → bent (~104.5°); dipoles do not cancel → polar (and hydrogen-bonds).' },
      mistakes: ['Confusing bond polarity with overall molecular polarity.', 'Ignoring lone pairs when predicting shape.', 'Treating intermolecular forces as bonds within molecules.'],
      tricks: ['Count all electron pairs (incl. lone) for shape.', 'Symmetric molecules can be non-polar even with polar bonds.', 'Hydrogen bonding gives anomalously high boiling points.'],
      memory: ['"Electron pairs push apart (VSEPR)."', '"Shape decides overall polarity."', 'H-bonds → high boiling points.'],
      board: { CBSE: ['Cl.11 Chemical Bonding & Molecular Structure'], ICSE: ['Cl.11 Bonding'], IB: ['DP Bonding HL'] },
      comp: ['JEE-Main', 'JEE-Advanced', 'NEET'], keywords: ['VSEPR', 'shape', 'polarity', 'intermolecular forces', 'hydrogen bonding'],
      xprereqs: ['chemistry.I1.bonding-i'],
      quiz: [
        { lvl: 2, type: 'mcq', prompt: 'VSEPR predicts shape from:', choices: ['electron-pair repulsion', 'atomic mass', 'colour', 'temperature'], answer: 0, explanation: 'Electron pairs arrange to minimise repulsion.' },
        { lvl: 3, type: 'mcq', prompt: 'CO₂ has polar bonds but is non-polar because it is:', choices: ['linear and symmetric', 'bent', 'ionic', 'metallic'], answer: 0, explanation: 'The two bond dipoles cancel in a linear molecule.' },
      ] },
    { tier: 'I2', order: 3, slug: 'gas-laws-kinetic-theory', title: 'Gas Laws & Kinetic Theory',
      summary: 'Boyle\'s, Charles\'s and the combined/ideal gas laws, grounded in kinetic theory. Shared with physics.',
      outcomes: ['Apply the individual and combined gas laws', 'Use PV = nRT', 'Relate macroscopic behaviour to particle motion'],
      concepts: [
        ['The gas laws', 'For a fixed amount of gas, P, V and T are linked: Boyle (PV constant at fixed T), Charles (V/T constant at fixed P), combined P₁V₁/T₁ = P₂V₂/T₂. Adding amount gives PV = nRT.'],
        ['Kinetic theory', 'A gas is many particles in fast random motion; pressure is their wall collisions, and temperature (in kelvin) is proportional to average kinetic energy.'],
      ],
      formulas: ['PV = nRT,  R = 8.314 J/(mol·K)', 'Boyle: P₁V₁ = P₂V₂ (const T)', 'Charles: V₁/T₁ = V₂/T₂ (const P)', 'Combined: P₁V₁/T₁ = P₂V₂/T₂ (T in kelvin)'],
      example: { q: 'A gas occupies 2.0 L at 300 K. What volume at 450 K, constant pressure?', solution: 'Charles: 2.0/300 = V₂/450 → V₂ = 2.0 × (450/300) = 3.0 L. (Use kelvin.)' },
      mistakes: ['Using Celsius instead of Kelvin.', 'Mixing up which quantity is held constant.', 'Forgetting P and V are inversely related at fixed T.'],
      tricks: ['PV = nRT ties everything together.', 'Always use kelvin.', 'Boyle: P↕V; Charles: V↕T.'],
      memory: ['"PV = nRT, in Kelvin."', '"Boyle inverse, Charles direct."', 'Temperature ∝ average particle KE.'],
      board: { CBSE: ['Cl.11 States of Matter'], ICSE: ['Cl.11 Gas Laws'], IB: ['DP States of Matter'] },
      comp: ['JEE-Main', 'JEE-Advanced', 'NEET'], keywords: ['gas laws', 'ideal gas', 'PV=nRT', 'kinetic theory'],
      xprereqs: ['chemistry.F2.mole-concept'],
      quiz: [
        { lvl: 2, type: 'numeric', prompt: 'Gas at 2 L, 300 K. Volume at 600 K, constant P (in L)?', answer: 4, tolerance: 0, explanation: 'V ∝ T → 2 × (600/300) = 4 L.' },
        { lvl: 2, type: 'mcq', prompt: 'At constant temperature, halving volume:', choices: ['doubles pressure', 'halves pressure', 'no change', 'doubles temperature'], answer: 0, explanation: 'Boyle: P and V inversely proportional.' },
      ] },
    { tier: 'I2', order: 4, slug: 'energetics', title: 'Energetics (Thermochemistry)',
      summary: 'Exothermic and endothermic reactions, enthalpy change, bond energies and Hess\'s law.',
      outcomes: ['Classify reactions by ΔH sign', 'Estimate ΔH from bond energies', 'Apply Hess\'s law'],
      concepts: [
        ['Enthalpy change', 'Reactions release energy (exothermic, ΔH negative) or absorb it (endothermic, ΔH positive). Breaking bonds costs energy; making bonds releases it.'],
        ['Bond energies and Hess', 'ΔH ≈ Σ(bonds broken) − Σ(bonds made). Hess\'s law: total ΔH is the same by any route (energy is conserved), so you can add known steps to find an unknown ΔH.'],
      ],
      formulas: ['ΔH < 0 exothermic; ΔH > 0 endothermic', 'ΔH ≈ Σ(bond energies broken) − Σ(bond energies made)', "Hess's law: ΔH is route-independent (add steps)"],
      example: { q: 'For H₂ + Cl₂ → 2HCl, broken: H–H(436) + Cl–Cl(242); made: 2×H–Cl(431) kJ/mol. Find ΔH.', solution: 'ΔH = (436 + 242) − (2×431) = 678 − 862 = −184 kJ/mol → exothermic.' },
      mistakes: ['Getting the ΔH sign backwards.', 'Thinking breaking bonds releases energy (it absorbs).', 'Ignoring a consistent route in Hess cycles.'],
      tricks: ['Exothermic → ΔH negative.', 'ΔH ≈ bonds broken − bonds made.', 'Hess: add steps; ΔH is route-independent.'],
      memory: ['"Exo out (−), endo in (+)."', '"Break costs, make gives."', 'Hess: energy conserved over any route.'],
      board: { CBSE: ['Cl.11 Thermodynamics'], ICSE: ['Cl.11-12 Thermochemistry'], IB: ['DP Energetics'] },
      comp: ['JEE-Main', 'JEE-Advanced', 'NEET'], keywords: ['enthalpy', 'exothermic', 'endothermic', 'bond energy', 'Hess law'],
      xprereqs: ['chemistry.I1.reactions-equations'],
      quiz: [
        { lvl: 2, type: 'mcq', prompt: 'An exothermic reaction has ΔH that is:', choices: ['negative', 'positive', 'zero', 'infinite'], answer: 0, explanation: 'Heat is released, so ΔH < 0.' },
        { lvl: 3, type: 'numeric', prompt: 'Bonds broken 678 kJ, bonds made 862 kJ. ΔH (kJ)?', answer: -184, tolerance: 1, explanation: 'ΔH = 678 − 862 = −184 kJ.' },
      ] },
    { tier: 'I2', order: 5, slug: 'equilibrium-intro', title: 'Quantitative Equilibrium (Introduction)',
      summary: 'Dynamic equilibrium, the equilibrium constant, and Le Chatelier\'s principle.',
      outcomes: ['Explain dynamic equilibrium', 'Write an equilibrium expression', 'Predict shifts with Le Chatelier'],
      concepts: [
        ['Dynamic equilibrium', 'In a reversible reaction, equilibrium is reached when forward and backward rates are equal — concentrations stay constant though reaction continues.'],
        ['Le Chatelier', 'Disturb an equilibrium (concentration, temperature, pressure) and it shifts to oppose the change. Adding reactant or removing product shifts toward products.'],
      ],
      formulas: ['At equilibrium: forward rate = backward rate', 'For aA + bB ⇌ cC + dD :  K = [C]^c[D]^d / [A]^a[B]^b', 'Le Chatelier: system shifts to oppose the imposed change'],
      example: { q: 'For N₂ + 3H₂ ⇌ 2NH₃ (exothermic), how does increasing pressure affect NH₃ yield?', solution: 'Higher pressure shifts equilibrium to fewer gas moles (4 → 2), i.e., toward NH₃ — the basis of the Haber process.' },
      mistakes: ['Thinking equilibrium means the reaction stopped.', 'Getting the Le Chatelier direction wrong.', 'Believing a catalyst shifts the position (it does not).'],
      tricks: ['Equilibrium: forward rate = backward rate, not zero.', 'System opposes the imposed change.', 'Higher pressure favours fewer gas moles.'],
      memory: ['"Equal rates, not stopped."', '"Disturb it, it pushes back."', 'Catalysts speed both ways — no shift.'],
      board: { CBSE: ['Cl.11 Equilibrium'], ICSE: ['Cl.11-12 Equilibrium'], IB: ['DP Equilibrium'] },
      comp: ['JEE-Main', 'JEE-Advanced', 'NEET'], keywords: ['equilibrium', 'reversible', 'Le Chatelier', 'equilibrium constant'],
      xprereqs: ['chemistry.I1.rates-reaction'],
      quiz: [
        { lvl: 2, type: 'mcq', prompt: 'At dynamic equilibrium, forward and backward rates are:', choices: ['equal', 'both zero', 'forward faster', 'backward faster'], answer: 0, explanation: 'Equal opposing rates keep concentrations constant.' },
        { lvl: 3, type: 'mcq', prompt: 'For N₂+3H₂⇌2NH₃, increasing pressure shifts equilibrium toward:', choices: ['NH₃ (fewer gas moles)', 'reactants', 'neither', 'a solid'], answer: 0, explanation: 'Higher pressure favours the side with fewer gas molecules.' },
      ] },
    { tier: 'I2', order: 6, slug: 'organic-intro', title: 'Introductory Organic Chemistry',
      summary: 'The chemistry of carbon: hydrocarbons, functional groups, homologous series and IUPAC naming.',
      outcomes: ['Recognise hydrocarbons and functional groups', 'Name simple organic molecules (IUPAC)', 'Explain carbon\'s versatility (catenation)'],
      concepts: [
        ['Carbon\'s versatility', 'Carbon forms four covalent bonds and chains/rings with itself (catenation), giving millions of compounds. Alkanes (CₙH₂ₙ₊₂) are saturated; alkenes have a C=C double bond.'],
        ['Functional groups & naming', 'A functional group (–OH, –COOH, C=C) is the reactive site defining a molecule\'s chemistry. IUPAC names use the longest carbon chain (meth-, eth-, prop-, but-) plus a suffix for the group.'],
      ],
      formulas: ['Alkanes: CₙH₂ₙ₊₂ (saturated, single bonds)', 'Alkenes: CₙH₂ₙ (one C=C double bond)', 'Chain roots: meth(1), eth(2), prop(3), but(4)'],
      example: { q: 'Give the molecular formula of the alkane with 3 carbons, and name it.', solution: 'CₙH₂ₙ₊₂ with n = 3 → C₃H₈, propane (a saturated hydrocarbon).' },
      mistakes: ['Confusing alkanes (single bonds) with alkenes (a C=C).', 'Miscounting carbons when naming.', 'Ignoring the functional group\'s role.'],
      tricks: ['Alkane CₙH₂ₙ₊₂ (-ane); alkene CₙH₂ₙ (-ene).', 'Name by the longest carbon chain.', 'The functional group drives reactivity.'],
      memory: ['"Carbon makes four bonds and long chains."', '"-ane single, -ene double."', 'Functional group = reactive handle.'],
      board: { CBSE: ['Cl.10-11 Carbon Compounds', 'Cl.11 Organic Basics'], ICSE: ['Cl.10 Organic Chemistry'], IB: ['DP Organic'] },
      comp: ['JEE-Main', 'JEE-Advanced', 'NEET'], keywords: ['organic', 'hydrocarbon', 'functional group', 'alkane', 'alkene', 'IUPAC'],
      quiz: [
        { lvl: 1, type: 'mcq', prompt: 'A hydrocarbon with only single C–C bonds is an:', choices: ['alkane', 'alkene', 'alcohol', 'acid'], answer: 0, explanation: 'Alkanes are saturated (single bonds only).' },
        { lvl: 2, type: 'mcq', prompt: 'The alkane with formula C₃H₈ is:', choices: ['propane', 'methane', 'ethane', 'butane'], answer: 0, explanation: 'n = 3 (prop-) saturated → propane.' },
      ] },

    // ================= A1 =================
    { tier: 'A1', order: 1, slug: 'chemical-thermodynamics', title: 'Chemical Thermodynamics',
      summary: 'Enthalpy, entropy and Gibbs free energy — the thermodynamic criterion for whether a reaction is spontaneous.',
      outcomes: ['Use enthalpy and entropy changes', 'Apply ΔG = ΔH − TΔS', 'Predict spontaneity and its temperature dependence'],
      concepts: [
        ['Enthalpy and entropy', 'Enthalpy (ΔH) tracks heat exchanged; entropy (ΔS) tracks disorder. Reactions are favoured by releasing energy (ΔH<0) and increasing disorder (ΔS>0).'],
        ['Gibbs free energy', 'ΔG = ΔH − TΔS decides spontaneity: ΔG < 0 spontaneous, = 0 at equilibrium, > 0 non-spontaneous. The T term means some reactions become spontaneous only above/below a certain temperature.'],
      ],
      formulas: ['ΔG = ΔH − TΔS  (T in kelvin)', 'ΔG < 0 spontaneous; = 0 equilibrium; > 0 non-spontaneous', 'ΔG° = −RT ln K'],
      example: { q: 'A reaction has ΔH = +40 kJ/mol and ΔS = +0.100 kJ/(mol·K). Above what temperature is it spontaneous?', solution: 'Spontaneous when ΔH − TΔS < 0 → T > ΔH/ΔS = 40/0.100 = 400 K. So spontaneous above 400 K.' },
      mistakes: ['Ignoring the T term in ΔG = ΔH − TΔS.', 'Assuming exothermic always means spontaneous.', 'Mismatching kJ and J for ΔH vs ΔS.'],
      tricks: ['ΔG = ΔH − TΔS; negative → spontaneous.', 'High T magnifies the entropy term.', 'ΔH<0 and ΔS>0 → always spontaneous.'],
      memory: ['"ΔG = ΔH − TΔS."', '"Negative ΔG → it goes."', 'Energy down + disorder up = favourable.'],
      board: { CBSE: ['Cl.11 Thermodynamics'], ICSE: ['Cl.12 Thermodynamics'], IB: ['DP Energetics HL'] },
      comp: ['JEE-Main', 'JEE-Advanced', 'NEET'], keywords: ['thermodynamics', 'enthalpy', 'entropy', 'Gibbs free energy', 'spontaneity'],
      xprereqs: ['chemistry.I2.energetics'],
      quiz: [
        { lvl: 2, type: 'mcq', prompt: 'A reaction is spontaneous when ΔG is:', choices: ['negative', 'positive', 'zero', 'very large'], answer: 0, explanation: 'Negative Gibbs free energy = spontaneous.' },
        { lvl: 3, type: 'numeric', prompt: 'ΔH = +50 kJ/mol, ΔS = +0.125 kJ/(mol·K). Minimum T for spontaneity (K)?', answer: 400, tolerance: 1, explanation: 'T > ΔH/ΔS = 50/0.125 = 400 K.' },
      ] },
    { tier: 'A1', order: 2, slug: 'chemical-kinetics', title: 'Chemical Kinetics',
      summary: 'Rate laws, order of reaction, half-life and the Arrhenius temperature dependence.',
      outcomes: ['Write and use rate laws', 'Determine order experimentally', 'Apply the Arrhenius relationship'],
      concepts: [
        ['Rate laws and order', 'Rate = k[A]^m[B]^n where m, n (the orders) are found by experiment, not from the equation. Overall order is m+n; units of k depend on the order.'],
        ['Arrhenius', 'k = A e^(−Eₐ/RT): rate constant rises with temperature and falls with activation energy. Logs give ln k = ln A − Eₐ/RT — a straight line (reusing logarithms).'],
      ],
      formulas: ['Rate = k[A]^m[B]^n  (m, n from experiment)', 'First-order half-life: t½ = 0.693 / k', 'Arrhenius: k = A e^(−Eₐ/RT);  ln k = ln A − Eₐ/RT'],
      example: { q: 'A first-order reaction has k = 0.0693 s⁻¹. Find its half-life.', solution: 't½ = 0.693/k = 0.693/0.0693 = 10 s. First-order half-life is constant, independent of starting concentration.' },
      mistakes: ['Reading orders from the balanced equation.', 'Confusing rate with rate constant.', 'Forgetting temperature\'s strong effect on k.'],
      tricks: ['Order comes from experiment, not stoichiometry.', 'First-order t½ is constant (0.693/k).', 'ln k vs 1/T is linear (Arrhenius plot).'],
      memory: ['"Order is experimental."', '"First-order t½ = 0.693/k."', 'Arrhenius plot: ln k vs 1/T.'],
      board: { CBSE: ['Cl.12 Chemical Kinetics'], ICSE: ['Cl.12 Kinetics'], IB: ['DP Kinetics HL'] },
      comp: ['JEE-Main', 'JEE-Advanced', 'NEET'], keywords: ['kinetics', 'rate law', 'order', 'half-life', 'Arrhenius'],
      xprereqs: ['math.I2.exponentials-logarithms'],
      quiz: [
        { lvl: 3, type: 'mcq', prompt: 'The order of a reaction is determined by:', choices: ['experiment', 'the balanced equation', 'the molar mass', 'temperature only'], answer: 0, explanation: 'Order is found experimentally.' },
        { lvl: 2, type: 'numeric', prompt: 'First-order k = 0.1386 s⁻¹. Half-life (s)?', answer: 5, tolerance: 0.1, explanation: 't½ = 0.693/0.1386 = 5 s.' },
      ] },
    { tier: 'A1', order: 3, slug: 'chemical-equilibrium', title: 'Chemical Equilibrium (Quantitative)',
      summary: 'Equilibrium constants Kc and Kp, the reaction quotient Q, and ICE-table calculations.',
      outcomes: ['Write Kc/Kp expressions', 'Use Q to predict direction', 'Solve equilibria with ICE tables'],
      concepts: [
        ['Equilibrium constant', 'Kc = [products]/[reactants], each raised to its coefficient (pure solids/liquids omitted). Large K favours products. Kp uses partial pressures.'],
        ['Q vs K and ICE tables', 'The reaction quotient Q has K\'s form but at any moment. Q < K → forward; Q > K → backward. ICE (Initial–Change–Equilibrium) tables organise the algebra.'],
      ],
      formulas: ['For aA + bB ⇌ cC + dD :  Kc = [C]^c[D]^d / [A]^a[B]^b', 'Q < K → forward; Q > K → backward; Q = K → equilibrium', 'Kp = Kc (RT)^(Δn_gas)'],
      example: { q: 'For H₂ + I₂ ⇌ 2HI, at equilibrium [H₂]=[I₂]=0.10 M and [HI]=0.80 M. Find Kc.', solution: 'Kc = [HI]²/([H₂][I₂]) = (0.80)² / (0.10×0.10) = 0.64/0.01 = 64. K ≫ 1 → products favoured.' },
      mistakes: ['Including pure solids/liquids in K.', 'Forgetting to raise concentrations to their coefficients.', 'Algebra slips in ICE tables.'],
      tricks: ['K = products/reactants, each to its power.', 'Compare Q to K to predict direction.', 'Use an ICE table to track concentrations.'],
      memory: ['"K = products/reactants (to powers)."', '"Q<K forward, Q>K backward."', 'ICE: Initial, Change, Equilibrium.'],
      board: { CBSE: ['Cl.11 Equilibrium'], ICSE: ['Cl.12 Equilibrium'], IB: ['DP Equilibrium HL'] },
      comp: ['JEE-Main', 'JEE-Advanced', 'NEET'], keywords: ['equilibrium constant', 'Kc', 'Kp', 'reaction quotient', 'ICE table'],
      xprereqs: ['chemistry.I2.equilibrium-intro'],
      quiz: [
        { lvl: 3, type: 'numeric', prompt: 'H₂+I₂⇌2HI: [HI]=0.8, [H₂]=[I₂]=0.1 M. Kc = [HI]²/([H₂][I₂])?', answer: 64, tolerance: 0.5, explanation: '0.64/0.01 = 64.' },
        { lvl: 2, type: 'mcq', prompt: 'If Q < K, the reaction proceeds:', choices: ['forward (toward products)', 'backward', 'not at all', 'to a solid'], answer: 0, explanation: 'Q < K → more product must form.' },
      ] },
    { tier: 'A1', order: 4, slug: 'ionic-equilibrium', title: 'Ionic Equilibrium',
      summary: 'pH of strong and weak acids, buffers (Henderson–Hasselbalch), and the solubility product Ksp.',
      outcomes: ['Calculate pH of strong/weak acids', 'Use the Henderson–Hasselbalch equation', 'Apply Ksp to solubility'],
      concepts: [
        ['Weak acids and Ka', 'Strong acids dissociate fully; weak acids only partially, described by Ka. For a weak acid, [H⁺] ≈ √(Ka·C).'],
        ['Buffers and Ksp', 'A buffer (weak acid + its salt) resists pH change: pH = pKa + log([A⁻]/[HA]). The solubility product Ksp sets the maximum ionic product of a sparingly soluble salt.'],
      ],
      formulas: ['pH = −log[H⁺];  Kw = [H⁺][OH⁻] = 10^(−14) at 25°C', 'Weak acid: [H⁺] ≈ √(Ka·C)', 'Henderson–Hasselbalch: pH = pKa + log([A⁻]/[HA])', 'Ksp = [cation]^x[anion]^y at saturation'],
      example: { q: 'Find the pH of 0.10 M acetic acid (Ka = 1.8×10⁻⁵).', solution: '[H⁺] ≈ √(Ka·C) = √(1.8×10⁻⁵ × 0.10) = √(1.8×10⁻⁶) ≈ 1.34×10⁻³. pH = −log(1.34×10⁻³) ≈ 2.87.' },
      mistakes: ['Treating weak acids as fully dissociated.', 'Forgetting the negative sign in pH = −log[H⁺].', 'Misapplying Ksp to soluble salts.'],
      tricks: ['Weak acid [H⁺] ≈ √(Ka·C).', 'Buffer: pH = pKa + log(salt/acid).', 'Ksp caps the dissolved ion product.'],
      memory: ['"[H⁺] ≈ √(Ka·C) for weak acids."', '"pH = pKa + log(A⁻/HA)."', 'Ksp caps solubility.'],
      board: { CBSE: ['Cl.11 Equilibrium (Ionic)'], ICSE: ['Cl.12 Ionic Equilibrium'], IB: ['DP Acids & Bases HL'] },
      comp: ['JEE-Main', 'JEE-Advanced', 'NEET'], keywords: ['pH', 'weak acid', 'Ka', 'buffer', 'Henderson-Hasselbalch', 'Ksp'],
      xprereqs: ['math.I2.exponentials-logarithms'],
      quiz: [
        { lvl: 2, type: 'numeric', prompt: 'If [H⁺] = 1×10⁻⁴ M, the pH is:', answer: 4, tolerance: 0, explanation: 'pH = −log(10⁻⁴) = 4.' },
        { lvl: 3, type: 'mcq', prompt: 'A buffer of equal [A⁻] and [HA] has pH equal to:', choices: ['pKa', '7', '0', '14'], answer: 0, explanation: 'log(1) = 0, so pH = pKa.' },
      ] },
    { tier: 'A1', order: 5, slug: 'electrochemistry', title: 'Electrochemistry',
      summary: 'Galvanic and electrolytic cells, cell potentials, the Nernst equation and Faraday\'s laws of electrolysis.',
      outcomes: ['Describe galvanic and electrolytic cells', 'Use standard electrode potentials', 'Apply Faraday\'s laws'],
      concepts: [
        ['Cells from redox', 'A galvanic cell turns a spontaneous redox reaction into electricity: oxidation at the anode, reduction at the cathode. E°cell = E°cathode − E°anode; positive → spontaneous.'],
        ['Electrolysis and Faraday', 'An electrolytic cell uses electricity to drive a non-spontaneous reaction. Amount deposited follows Faraday: moles of electrons = charge ÷ F, F ≈ 96500 C/mol.'],
      ],
      formulas: ['E°cell = E°cathode − E°anode  (>0 → spontaneous)', 'ΔG° = −nFE°cell', 'Faraday: moles e⁻ = Q/F,  Q = I×t,  F ≈ 96500 C/mol', 'Nernst: E = E° − (RT/nF) ln Q'],
      example: { q: 'A current of 2 A flows for 965 s through molten NaCl. How many moles of electrons pass?', solution: 'Q = I×t = 2 × 965 = 1930 C. Moles e⁻ = Q/F = 1930/96500 = 0.02 mol — deposits 0.02 mol Na at the cathode.' },
      mistakes: ['Swapping anode and cathode.', 'Confusing galvanic (spontaneous) with electrolytic (driven).', 'Forgetting Q = It before dividing by F.'],
      tricks: ['"An Ox, Red Cat": Anode Oxidation, Cathode Reduction.', 'Positive E°cell → spontaneous galvanic cell.', 'moles e⁻ = It/F.'],
      memory: ['"An Ox, Red Cat."', '"E°cell = cathode − anode."', 'Faraday: charge → moles of electrons.'],
      board: { CBSE: ['Cl.12 Electrochemistry'], ICSE: ['Cl.12 Electrochemistry'], IB: ['DP Redox HL'] },
      comp: ['JEE-Main', 'JEE-Advanced', 'NEET'], keywords: ['electrochemistry', 'galvanic', 'electrolysis', 'Nernst', 'Faraday'],
      xprereqs: ['chemistry.I1.reactions-equations'],
      quiz: [
        { lvl: 2, type: 'mcq', prompt: 'In any electrochemical cell, oxidation occurs at the:', choices: ['anode', 'cathode', 'salt bridge', 'wire'], answer: 0, explanation: 'Anode = oxidation; cathode = reduction.' },
        { lvl: 3, type: 'numeric', prompt: 'Q = 9650 C passes. Moles of electrons (F = 96500 C/mol)?', answer: 0.1, tolerance: 0.001, explanation: 'n = Q/F = 9650/96500 = 0.1 mol.' },
      ] },
    { tier: 'A1', order: 6, slug: 'periodic-properties', title: 'Periodic Properties & s/p-Block',
      summary: 'Trends in atomic radius, ionisation energy, electron affinity and electronegativity, explained by nuclear charge and shielding.',
      outcomes: ['Explain periodic trends from structure', 'Compare elements across periods and groups', 'Survey s- and p-block behaviour'],
      concepts: [
        ['Trends from effective nuclear charge', 'Across a period, more protons pull the same shell in → atoms shrink, ionisation energy and electronegativity rise. Down a group, extra shells and shielding → atoms grow, ionisation energy falls.'],
        ['Block chemistry', 'The s-block (reactive metals, +1/+2 ions) and p-block (non-metals, metalloids, varied) show patterns explained by valence configuration.'],
      ],
      formulas: ['Across a period →: radius ↓, ionisation energy ↑, electronegativity ↑', 'Down a group ↓: radius ↑, ionisation energy ↓', 'Effective nuclear charge ≈ protons − shielding'],
      example: { q: 'Which has the larger atomic radius: Na or Cl? Why?', solution: 'Na. Both are Period 3, but Cl has more protons pulling the same shell in (higher effective nuclear charge), so Cl is smaller — radius decreases across a period.' },
      mistakes: ['Reversing the atomic-radius trend.', 'Confusing ionisation energy with electronegativity.', 'Treating trends as arbitrary.'],
      tricks: ['Across a period: smaller, higher ionisation energy.', 'Down a group: bigger, lower ionisation energy.', 'Trends follow nuclear pull vs shielding.'],
      memory: ['"Across → smaller & grippier; down → bigger & looser."', '"Trends follow charge and shielding."', 's-block reactive metals; p-block varied.'],
      board: { CBSE: ['Cl.11 Classification & Periodicity'], ICSE: ['Cl.11 Periodic Properties'], IB: ['DP Periodicity'] },
      comp: ['JEE-Main', 'JEE-Advanced', 'NEET'], keywords: ['periodic trends', 'atomic radius', 'ionisation energy', 'electronegativity', 'effective nuclear charge'],
      xprereqs: ['chemistry.F2.periodic-table'],
      quiz: [
        { lvl: 2, type: 'mcq', prompt: 'Across a period (left→right), atomic radius generally:', choices: ['decreases', 'increases', 'stays constant', 'doubles'], answer: 0, explanation: 'Rising nuclear charge pulls the shell in.' },
        { lvl: 2, type: 'mcq', prompt: 'Ionisation energy generally ___ down a group.', choices: ['decreases', 'increases', 'stays the same', 'is zero'], answer: 0, explanation: 'Outer electrons are farther out and more shielded.' },
      ] },

    // ================= A2 =================
    { tier: 'A2', order: 1, slug: 'organic-mechanisms', title: 'Organic Reaction Mechanisms',
      summary: 'Nucleophiles, electrophiles, curly-arrow mechanisms and the major pathways — reasoned, not memorised.',
      outcomes: ['Identify nucleophiles and electrophiles', 'Follow substitution/addition/elimination mechanisms', 'Predict products by electron flow'],
      concepts: [
        ['Electron flow', 'Organic reactions are electrons moving from electron-rich (nucleophile) to electron-poor (electrophile) sites. Curly arrows show electron-pair movement, always starting from a lone pair or bond.'],
        ['Major pathways', 'Nucleophilic substitution (SN1/SN2), electrophilic addition (to C=C), and elimination. Understanding the pathway predicts products instead of memorising thousands of reactions.'],
      ],
      formulas: ['Curly arrow: starts from an electron pair (lone pair or bond)', 'Nucleophile = electron-pair donor (electron-rich)', 'Electrophile = electron-pair acceptor (electron-poor)'],
      example: { q: 'In OH⁻ + CH₃Br, identify the nucleophile and product.', solution: 'OH⁻ is the electron-rich nucleophile; it attacks the electron-poor carbon bonded to Br, displacing Br⁻ (nucleophilic substitution). Product: CH₃OH.' },
      mistakes: ['Memorising products without the mechanism.', 'Confusing nucleophiles (donors) with electrophiles.', 'Drawing curly arrows from positive to negative (they start from electrons).'],
      tricks: ['Curly arrows start from an electron pair.', 'Nucleophile = electron-rich attacker.', 'Classify the pathway to predict products.'],
      memory: ['"Arrows flow from electrons."', '"Nucleophile loves positive sites."', 'Mechanism predicts; memory fails.'],
      board: { CBSE: ['Cl.11-12 Organic Chemistry'], ICSE: ['Cl.12 Organic Mechanisms'], IB: ['DP Organic HL'] },
      comp: ['JEE-Main', 'JEE-Advanced', 'NEET'], keywords: ['mechanism', 'nucleophile', 'electrophile', 'curly arrows', 'substitution'],
      xprereqs: ['chemistry.I2.organic-intro'],
      quiz: [
        { lvl: 2, type: 'mcq', prompt: 'A nucleophile is:', choices: ['electron-rich (a donor)', 'electron-poor', 'always positive', 'a catalyst'], answer: 0, explanation: 'It donates an electron pair to an electrophile.' },
        { lvl: 3, type: 'mcq', prompt: 'OH⁻ + CH₃Br → CH₃OH + Br⁻ is:', choices: ['nucleophilic substitution', 'electrophilic addition', 'combustion', 'oxidation'], answer: 0, explanation: 'The nucleophile OH⁻ substitutes for Br⁻.' },
      ] },
    { tier: 'A2', order: 2, slug: 'functional-groups', title: 'Functional-Group Chemistry',
      summary: 'Alcohols, aldehydes, ketones, carboxylic acids and amines — characteristic reactions and interconversions.',
      outcomes: ['Recognise major functional groups', 'Predict characteristic reactions', 'Plan functional-group interconversions'],
      concepts: [
        ['Groups define reactivity', 'Each functional group has signature reactions: alcohols oxidise, carboxylic acids neutralise bases, amines act as weak bases. Identify the group and you predict the chemistry.'],
        ['Oxidation ladder', 'Primary alcohol → aldehyde → carboxylic acid on oxidation; secondary alcohol → ketone (no further). These routes build target molecules.'],
      ],
      formulas: ['–OH alcohol, –CHO aldehyde, C=O ketone, –COOH acid, –NH₂ amine', 'Primary alcohol —[O]→ aldehyde —[O]→ carboxylic acid', 'Secondary alcohol —[O]→ ketone (stops)'],
      example: { q: 'What is formed when ethanol (a primary alcohol) is fully oxidised?', solution: 'Ethanol → ethanal (aldehyde) → ethanoic acid. Full oxidation gives the carboxylic acid, ethanoic (acetic) acid.' },
      mistakes: ['Confusing aldehydes and ketones (position of C=O).', 'Forgetting carboxylic acids are acidic.', 'Mixing up oxidation products of primary vs secondary alcohols.'],
      tricks: ['Learn the five handles: –OH/–CHO/C=O/–COOH/–NH₂.', 'Primary alcohol → aldehyde → acid; secondary → ketone.', 'Acids react with bases and carbonates.'],
      memory: ['"Group = predictable reactions."', '"Oxidise: 1° alcohol → aldehyde → acid."', 'Amines basic; acids acidic.'],
      board: { CBSE: ['Cl.12 Alcohols, Aldehydes, Acids, Amines'], ICSE: ['Cl.12 Organic Compounds'], IB: ['DP Organic HL'] },
      comp: ['JEE-Main', 'JEE-Advanced', 'NEET'], keywords: ['functional groups', 'alcohol', 'aldehyde', 'carboxylic acid', 'amine', 'oxidation'],
      xprereqs: ['chemistry.A2.organic-mechanisms'],
      quiz: [
        { lvl: 2, type: 'mcq', prompt: 'The –COOH group makes a molecule a(n):', choices: ['carboxylic acid', 'alcohol', 'amine', 'ketone'], answer: 0, explanation: '–COOH is the carboxylic acid group.' },
        { lvl: 2, type: 'mcq', prompt: 'Oxidising a primary alcohol first gives a(n):', choices: ['aldehyde', 'ketone', 'amine', 'alkane'], answer: 0, explanation: '1° alcohol → aldehyde → carboxylic acid.' },
      ] },
    { tier: 'A2', order: 3, slug: 'biomolecules-polymers', title: 'Biomolecules & Polymers',
      summary: 'Carbohydrates, proteins, lipids, nucleic acids and polymers — the chemistry underlying biology.',
      outcomes: ['Describe major biomolecules', 'Explain condensation and addition polymerisation', 'Connect structure to function'],
      concepts: [
        ['Biomolecules', 'Carbohydrates, proteins, lipids and nucleic acids are built from small repeating monomers (sugars, amino acids, nucleotides) joined by condensation (losing water).'],
        ['Polymers', 'Polymers are long chains of monomers — natural (proteins, starch, DNA) or synthetic (polythene, PVC). Addition polymers form from alkenes; condensation polymers release a small molecule per link.'],
      ],
      formulas: ['Condensation: monomer + monomer → dimer + H₂O', 'Addition: n(CH₂=CH₂) → –(CH₂–CH₂)ₙ–', 'Proteins = polymers of amino acids (peptide bonds)'],
      example: { q: 'What type of polymerisation forms polythene from ethene, and what small molecule (if any) is lost?', solution: 'Addition polymerisation: the C=C bonds open and monomers add with no small molecule lost. n CH₂=CH₂ → –(CH₂–CH₂)ₙ–.' },
      mistakes: ['Confusing monomers with polymers.', 'Mixing up addition and condensation.', 'Ignoring how structure dictates function.'],
      tricks: ['Polymer = many monomers linked.', 'Addition (from alkenes) loses nothing; condensation loses water.', 'Proteins ← amino acids; starch ← glucose.'],
      memory: ['"Monomer → polymer."', '"Addition loses nothing; condensation loses water."', 'Structure dictates function.'],
      board: { CBSE: ['Cl.12 Biomolecules', 'Cl.12 Polymers'], ICSE: ['Cl.12 Biomolecules'], IB: ['DP Organic/Biochemistry'] },
      comp: ['NEET', 'JEE-Main'], keywords: ['biomolecules', 'polymer', 'protein', 'monomer', 'polymerisation'],
      xprereqs: ['chemistry.A2.functional-groups'],
      quiz: [
        { lvl: 1, type: 'mcq', prompt: 'A polymer is made of many repeating:', choices: ['monomers', 'atoms of one element', 'ions', 'catalysts'], answer: 0, explanation: 'Monomers link to form a polymer.' },
        { lvl: 2, type: 'mcq', prompt: 'Polythene from ethene forms by:', choices: ['addition polymerisation', 'condensation', 'neutralisation', 'combustion'], answer: 0, explanation: 'Alkene C=C bonds open and add — no small molecule lost.' },
      ] },
    { tier: 'A2', order: 4, slug: 'coordination-chemistry', title: 'd-Block & Coordination Chemistry',
      summary: 'Transition-metal properties, complex ions, ligands, coordination number and the origin of colour.',
      outcomes: ['Describe transition-metal properties', 'Interpret coordination complexes', 'Relate d-electrons to colour and catalysis'],
      concepts: [
        ['Transition metals', 'd-block elements show variable oxidation states, coloured compounds and catalytic activity — all from partly filled d-orbitals.'],
        ['Complexes and colour', 'A central metal ion bonds to ligands (electron-pair donors); the number of donor atoms is the coordination number. Ligands split the d-orbitals in energy; electrons absorbing specific wavelengths to jump the gap produce colour.'],
      ],
      formulas: ['Coordination number = number of ligand donor atoms', 'Ligand = electron-pair (Lewis base) donor', 'Colour arises from d–d electron transitions (orbital splitting)'],
      example: { q: 'In [Cu(H₂O)₆]²⁺, what is the coordination number and why is it coloured?', solution: 'Six water ligands → coordination number 6. They split Cu²⁺\'s 3d orbitals; a d-electron absorbs part of visible light to jump the gap, so the complex appears blue.' },
      mistakes: ['Forgetting variable oxidation states.', 'Confusing ligands with counter-ions.', 'Ignoring the d-orbital-splitting origin of colour.'],
      tricks: ['Variable oxidation states are a d-block signature.', 'Ligands donate electron pairs to the metal.', 'd-orbital splitting explains complex colours.'],
      memory: ['"d-block: variable states, colour, catalysis."', '"Ligands donate to the metal centre."', 'Colour ← d–d transitions.'],
      board: { CBSE: ['Cl.12 d/f-Block', 'Cl.12 Coordination Compounds'], ICSE: ['Cl.12 Transition Elements'], IB: ['DP Transition Metals HL'] },
      comp: ['JEE-Main', 'JEE-Advanced', 'NEET'], keywords: ['transition metals', 'coordination', 'ligand', 'coordination number', 'colour'],
      xprereqs: ['chemistry.A1.periodic-properties'],
      quiz: [
        { lvl: 2, type: 'mcq', prompt: 'Transition metals commonly show:', choices: ['variable oxidation states', 'only one oxidation state', 'no colour ever', 'no catalysis'], answer: 0, explanation: 'Partly filled d-orbitals allow variable states.' },
        { lvl: 2, type: 'numeric', prompt: 'Coordination number of [Cu(H₂O)₆]²⁺?', answer: 6, tolerance: 0, explanation: 'Six water ligand donor atoms → 6.' },
      ] },
    { tier: 'A2', order: 5, slug: 'analytical-chemistry', title: 'Analytical & Practical Chemistry Portfolio', core: true,
      summary: 'Qualitative and quantitative analysis (including titration calculations) and treatment of experimental error — the capstone lab strand.',
      outcomes: ['Perform qualitative tests', 'Carry out titration calculations', 'Treat experimental uncertainty'],
      concepts: [
        ['Identifying and measuring', 'Qualitative analysis identifies what is present (flame tests, precipitates, gas tests); quantitative analysis measures how much (titration, gravimetry).'],
        ['Titration calculations', 'From a titration, moles of one reactant give moles of the other via the equation, then concentration. Repeat for concordant results and report uncertainty.'],
      ],
      formulas: ['n = C × V (V in litres)', 'At the end point: n(acid)/n(base) = mole ratio from the equation', 'Concordant titres agree within ~0.10 cm³'],
      example: { q: '25.0 cm³ of NaOH is neutralised by 20.0 cm³ of 0.100 M HCl (1:1). Find the NaOH concentration.', solution: 'n(HCl) = 0.100 × 0.0200 = 0.00200 mol. 1:1 → n(NaOH) = 0.00200 mol. C = n/V = 0.00200/0.0250 = 0.080 M.' },
      mistakes: ['Reporting a result without uncertainty.', 'Confusing qualitative (what) with quantitative (how much).', 'Using non-concordant titres.'],
      tricks: ['Titrate to a sharp colour change; use concordant titres.', 'n = CV, then apply the mole ratio.', 'Report measurements with uncertainty.'],
      memory: ['"Qualitative = what; quantitative = how much."', '"n = CV, then mole ratio."', 'Every result carries an uncertainty.'],
      board: { CBSE: ['Cl.11-12 Practical Chemistry'], ICSE: ['Cl.11-12 Practical'], IB: ['DP Chemistry IA'] },
      comp: ['NEET', 'JEE-Main'], keywords: ['analysis', 'titration', 'qualitative', 'quantitative', 'uncertainty'],
      xprereqs: ['math.I1.statistics-ii'],
      quiz: [
        { lvl: 2, type: 'mcq', prompt: 'Titration determines a solution\'s:', choices: ['concentration', 'colour', 'temperature only', 'mass number'], answer: 0, explanation: 'It finds an unknown concentration by reaction to an end point.' },
        { lvl: 3, type: 'numeric', prompt: '20.0 cm³ of 0.100 M HCl neutralises 25.0 cm³ NaOH (1:1). C(NaOH) in M?', answer: 0.08, tolerance: 0.002, explanation: 'n=0.00200 mol; C = 0.00200/0.0250 = 0.080 M.' },
      ] },
  ],
};
