// Computer Science — full curriculum dataset. Python first, then C. Builders, not test-passers.
// The F1 flagship (python-variables-types-expressions) is listed for ordering/linking only.
export default {
  subject: 'cs',
  topics: [
    // ================= F1 =================
    { tier: 'F1', order: 1, slug: 'computational-thinking', title: 'Computational Thinking',
      summary: 'Decomposition, pattern recognition, abstraction and algorithms — thinking before coding.',
      outcomes: ['Break problems into parts (decomposition)', 'Spot patterns and generalise', 'Write algorithms as precise steps'],
      concepts: [
        ['Four pillars', 'Computational thinking is decomposition (break it down), pattern recognition (spot repetition), abstraction (ignore irrelevant detail), and algorithms (precise step-by-step recipes).'],
        ['Algorithms are recipes', 'An algorithm is an unambiguous sequence of steps that solves a problem. Getting the thinking right on paper makes the coding straightforward.'],
      ],
      mistakes: ['Jumping to code before understanding the problem.', 'Writing ambiguous steps a computer could not follow.', 'Trying to solve the whole problem at once instead of decomposing.'],
      tricks: ['Decompose a big problem into small solvable parts.', 'Look for repeated patterns to reuse solutions.', 'Write the algorithm in plain steps before coding.'],
      memory: ['"Decompose, spot patterns, abstract, algorithm."', '"Precise steps, no ambiguity."', 'Think first, code second.'],
      board: { CBSE: ['Cl.6-8 Computational Thinking', 'Cl.11 CS Problem Solving'], ICSE: ['Cl.9 Algorithms'], IB: ['MYP Design', 'DP CS'] },
      comp: [], keywords: ['computational thinking', 'decomposition', 'abstraction', 'algorithm', 'pattern'],
      quiz: [
        { lvl: 1, type: 'mcq', prompt: 'Breaking a big problem into smaller parts is called:', choices: ['decomposition', 'abstraction', 'iteration', 'compilation'], answer: 0, explanation: 'Decomposition splits a problem into manageable pieces.' },
        { lvl: 2, type: 'mcq', prompt: 'An algorithm must be:', choices: ['a precise, unambiguous sequence of steps', 'written in one language', 'always short', 'a kind of computer'], answer: 0, explanation: 'Algorithms are unambiguous step-by-step recipes.' },
      ] },
    { tier: 'F1', order: 2, slug: 'first-programs', title: 'First Programs',
      summary: 'Running Python, printing output, comments, and the edit-run loop.',
      outcomes: ['Run a Python program', 'Use print and comments', 'Understand the edit-run cycle'],
      concepts: [
        ['Your first output', 'print() displays text on screen. Writing, running and seeing the result is the fundamental loop of programming — the fastest way to learn is to run code often.'],
        ['Comments', 'Comments (# in Python) are notes for humans, ignored by the computer. They explain why code does something, aiding the next reader.'],
      ],
      mistakes: ['Forgetting quotes around text in print().', 'Expecting comments to affect the program.', 'Not running code frequently to check progress.'],
      tricks: ['Run early and often — small steps, quick feedback.', 'Use print() to see what your program is doing.', 'Comment the why, not the obvious what.'],
      memory: ['"Edit, run, observe, repeat."', '"# is a note for humans."', 'print() shows output.'],
      board: { CBSE: ['Cl.11 CS: Getting Started with Python'], ICSE: ['Cl.9 Programming Basics'], IB: ['DP CS'] },
      comp: [], keywords: ['print', 'comments', 'edit-run', 'python', 'output'],
      xprereqs: ['cs.F1.computational-thinking'],
      quiz: [
        { lvl: 1, type: 'mcq', prompt: 'What does print("Hi") do?', choices: ['displays Hi on screen', 'saves a file', 'deletes text', 'adds numbers'], answer: 0, explanation: 'print() outputs the text to the screen.' },
        { lvl: 1, type: 'mcq', prompt: 'A line starting with # in Python is:', choices: ['a comment, ignored by the computer', 'an error', 'printed output', 'a variable'], answer: 0, explanation: 'Comments are for humans and ignored when running.' },
      ] },
    { tier: 'F1', order: 3, slug: 'python-variables-types-expressions', title: 'Python: Variables, Types & Expressions',
      summary: 'Flagship deep-dive topic (see full content).', outcomes: [], concepts: [], mistakes: [], tricks: [], memory: [], board: {}, comp: [], keywords: ['python', 'variables'], quiz: [] },
    { tier: 'F1', order: 4, slug: 'input-output', title: 'Input, Output & Simple Interaction',
      summary: 'Reading user input, producing output, and building interactive programs.',
      outcomes: ['Read input with input()', 'Format output clearly', 'Build a simple interactive program'],
      concepts: [
        ['Two-way programs', 'input() pauses and reads what the user types (always as a string). Combined with print(), it makes programs that interact rather than just run.'],
        ['Formatting output', 'f-strings insert values into text cleanly: f"Hello {name}". Clear output makes programs usable.'],
      ],
      mistakes: ['Forgetting input() returns a string (convert for arithmetic).', 'Concatenating numbers and strings with +.', 'Unclear or unlabelled output.'],
      tricks: ['Wrap numeric input: int(input(...)).', 'Use f-strings to mix text and values.', 'Label your output so it is understandable.'],
      memory: ['"input() gives a string."', '"f-strings format cleanly."', 'Interactive = input + output.'],
      board: { CBSE: ['Cl.11 CS: Input/Output'], ICSE: ['Cl.9-10 Input/Output'], IB: ['DP CS'] },
      comp: [], keywords: ['input', 'output', 'f-string', 'interaction'],
      quiz: [
        { lvl: 1, type: 'mcq', prompt: 'input() in Python returns a value of type:', choices: ['str', 'int', 'float', 'bool'], answer: 0, explanation: 'Everything typed by the user comes in as a string.' },
        { lvl: 2, type: 'mcq', prompt: 'To greet a user by a variable name, best use:', choices: ['f"Hello {name}"', '"Hello" + name + 5', '"Hello name"', 'print(name())'], answer: 0, explanation: 'An f-string inserts the value cleanly.' },
      ] },
    { tier: 'F1', order: 5, slug: 'booleans-conditionals', title: 'Booleans & Conditionals',
      summary: 'if/elif/else and boolean logic — making programs decide.',
      outcomes: ['Use if/elif/else', 'Combine conditions with and/or/not', 'Trace which branch runs'],
      concepts: [
        ['Making decisions', 'Conditionals run different code depending on whether a condition is True or False. if/elif/else lets a program choose a path — the basis of all logic.'],
        ['Boolean logic', 'Conditions combine with and, or, not. Understanding truth values (from maths logic) lets you express complex decisions correctly.'],
      ],
      mistakes: ['Using = (assignment) instead of == (comparison) in a condition.', 'Wrong indentation changing which code is inside the if.', 'Misordering elif branches so one is unreachable.'],
      tricks: ['== compares; = assigns.', 'Indent consistently — Python uses it to group code.', 'Order conditions from most specific to most general.'],
      memory: ['"== asks, = assigns."', '"Indentation defines the block."', 'and/or/not combine conditions.'],
      board: { CBSE: ['Cl.11 CS: Conditional Statements'], ICSE: ['Cl.9-10 Selection'], IB: ['DP CS'] },
      comp: [], keywords: ['conditional', 'if', 'boolean', 'logic', 'branch'],
      xprereqs: ['cs.F1.python-variables-types-expressions'],
      quiz: [
        { lvl: 1, type: 'mcq', prompt: 'Which operator tests equality in a condition?', choices: ['==', '=', '=>', '!'], answer: 0, explanation: '== compares; = assigns.' },
        { lvl: 2, type: 'mcq', prompt: 'if x > 0 and x < 10 is True when x is:', choices: ['5', '-5', '10', '20'], answer: 0, explanation: '5 satisfies both conditions.' },
      ] },
    { tier: 'F1', order: 6, slug: 'version-control-i', title: 'Version Control Basics I',
      summary: 'git init, add and commit — why keeping history matters, from the very start.',
      outcomes: ['Initialise a git repository', 'Stage and commit changes', 'Explain why version control matters'],
      concepts: [
        ['A history of your work', 'Version control (git) records snapshots of your project over time. You can see what changed, undo mistakes, and never lose work — a habit built from day one.'],
        ['The core loop', 'git add stages changes, git commit saves a snapshot with a message. Committing often, with clear messages, documents your progress.'],
      ],
      mistakes: ['Committing rarely, losing the ability to undo small steps.', 'Writing vague commit messages.', 'Forgetting to add files before committing.'],
      tricks: ['Commit small, logical changes with clear messages.', 'git status shows what will be committed.', 'A commit is a save point you can return to.'],
      memory: ['"add stages, commit saves."', '"Commit early, commit often."', 'History means you never lose work.'],
      board: { CBSE: ['Cl.11-12 CS: Tools'], ICSE: ['Cl.10 IT Tools'], IB: ['DP CS: Development'] },
      comp: [], keywords: ['git', 'version control', 'commit', 'repository'],
      quiz: [
        { lvl: 1, type: 'mcq', prompt: 'Which git command saves a snapshot of staged changes?', choices: ['git commit', 'git delete', 'git run', 'git print'], answer: 0, explanation: 'git commit records a snapshot with a message.' },
        { lvl: 2, type: 'mcq', prompt: 'The main benefit of version control is:', choices: ['tracking history and undoing mistakes', 'making code run faster', 'writing code for you', 'deleting old files'], answer: 0, explanation: 'It records history so you can review and revert.' },
      ] },

    // ================= F2 =================
    { tier: 'F2', order: 1, slug: 'loops', title: 'Loops',
      summary: 'while and for loops, range, and reasoning about repetition.',
      outcomes: ['Write while and for loops', 'Use range()', 'Avoid infinite loops'],
      concepts: [
        ['Repetition', 'Loops repeat code without rewriting it. for loops iterate a known number of times (often with range); while loops repeat until a condition changes.'],
        ['Loop reasoning', 'A loop must make progress toward stopping, or it runs forever. Thinking about what changes each pass prevents infinite loops.'],
      ],
      mistakes: ['Writing a while loop whose condition never becomes False (infinite loop).', 'Off-by-one errors with range().', 'Forgetting to update the loop variable.'],
      tricks: ['Use for with range() when the count is known.', 'Ensure a while loop moves toward its stop condition.', 'range(n) goes 0 to n−1.'],
      memory: ['"for known counts, while until a condition."', '"Make progress or loop forever."', 'range(n): 0 to n−1.'],
      board: { CBSE: ['Cl.11 CS: Iteration'], ICSE: ['Cl.9-10 Iteration'], IB: ['DP CS'] },
      comp: [], keywords: ['loop', 'while', 'for', 'range', 'iteration'],
      xprereqs: ['cs.F1.booleans-conditionals'],
      quiz: [
        { lvl: 1, type: 'mcq', prompt: 'How many times does for i in range(3) loop?', choices: ['3', '2', '4', 'forever'], answer: 0, explanation: 'range(3) yields 0,1,2 — three iterations.' },
        { lvl: 2, type: 'mcq', prompt: 'A while loop runs forever when its condition:', choices: ['never becomes False', 'is False at the start', 'uses range', 'has a comment'], answer: 0, explanation: 'It must eventually become False to stop.' },
      ] },
    { tier: 'F2', order: 2, slug: 'lists-iteration', title: 'Lists & Iteration',
      summary: 'The list — the first data structure — with indexing, mutation and traversal.',
      outcomes: ['Create and index lists', 'Add, remove and change elements', 'Iterate over a list'],
      concepts: [
        ['Storing many values', 'A list holds an ordered collection. Indexing (starting at 0) accesses elements; lists are mutable, so you can change, add and remove items.'],
        ['Traversal', 'Looping over a list processes each element in turn — the pattern behind searching, summing and transforming collections.'],
      ],
      mistakes: ['Forgetting indexing starts at 0.', 'Index out of range on the last element (length−1).', 'Modifying a list while iterating over it.'],
      tricks: ['First element is index 0; last is len−1.', 'for item in list iterates each element.', 'Use append() to add, pop()/remove() to delete.'],
      memory: ['"Indexing starts at 0."', '"for item in list" traverses.', 'Lists are mutable and ordered.'],
      board: { CBSE: ['Cl.11 CS: Lists'], ICSE: ['Cl.10 Arrays/Lists'], IB: ['DP CS: Data Structures'] },
      comp: [], keywords: ['list', 'index', 'iteration', 'mutable', 'traversal'],
      xprereqs: ['cs.F2.loops'],
      quiz: [
        { lvl: 1, type: 'mcq', prompt: 'In Python, the first element of a list is at index:', choices: ['0', '1', '-1', 'len'], answer: 0, explanation: 'Indexing starts at 0.' },
        { lvl: 2, type: 'mcq', prompt: 'Which adds an item to the end of a list?', choices: ['append()', 'remove()', 'pop()', 'len()'], answer: 0, explanation: 'append() adds to the end.' },
      ] },
    { tier: 'F2', order: 3, slug: 'functions', title: 'Functions',
      summary: 'Defining functions with parameters, return values and scope — decomposition in code.',
      outcomes: ['Define and call functions', 'Use parameters and return values', 'Understand local scope'],
      concepts: [
        ['Reusable blocks', 'A function packages a task under a name so you can reuse it. Parameters pass data in; return sends a result back. Functions are decomposition made concrete.'],
        ['Scope', 'Variables inside a function are local — they do not leak out. This keeps functions independent and predictable, the basis of larger programs.'],
      ],
      mistakes: ['Forgetting to return a value (function returns None).', 'Confusing printing with returning.', 'Expecting local variables to exist outside the function.'],
      tricks: ['Parameters in, return value out.', 'return gives a result; print only displays.', 'Keep functions small and single-purpose.'],
      memory: ['"Parameters in, return out."', '"Local variables stay local."', 'A function does one job.'],
      board: { CBSE: ['Cl.11-12 CS: Functions'], ICSE: ['Cl.10 Functions/Methods'], IB: ['DP CS'] },
      comp: [], keywords: ['function', 'parameter', 'return', 'scope', 'decomposition'],
      xprereqs: ['cs.F2.lists-iteration'],
      quiz: [
        { lvl: 1, type: 'mcq', prompt: 'A function sends a result back with:', choices: ['return', 'print', 'input', 'import'], answer: 0, explanation: 'return passes a value back to the caller.' },
        { lvl: 2, type: 'mcq', prompt: 'A variable defined inside a function is:', choices: ['local to that function', 'global', 'a constant', 'printed automatically'], answer: 0, explanation: 'Local scope keeps it inside the function.' },
      ] },
    { tier: 'F2', order: 4, slug: 'strings-depth', title: 'Strings at Depth',
      summary: 'String methods, slicing and formatting.',
      outcomes: ['Use common string methods', 'Slice strings', 'Format strings'],
      concepts: [
        ['Strings are sequences', 'A string is an ordered sequence of characters. Slicing (s[1:4]) extracts parts; methods like upper() and split() transform text.'],
        ['Immutability', 'Strings cannot be changed in place — methods return new strings. Understanding this avoids a common source of confusion.'],
      ],
      mistakes: ['Expecting a string method to change the original (it returns a new one).', 'Off-by-one errors in slicing.', 'Forgetting slice end is exclusive.'],
      tricks: ['s[a:b] includes a, excludes b.', 'String methods return new strings.', 'split() breaks text into a list.'],
      memory: ['"Slice end is exclusive."', '"Strings are immutable — methods return new."', 'split/join move between text and lists.'],
      board: { CBSE: ['Cl.11 CS: Strings'], ICSE: ['Cl.10 String Handling'], IB: ['DP CS'] },
      comp: [], keywords: ['string', 'slicing', 'methods', 'immutable', 'formatting'],
      xprereqs: ['cs.F1.python-variables-types-expressions'],
      quiz: [
        { lvl: 2, type: 'mcq', prompt: 'For s = "python", what is s[0:3]?', choices: ['"pyt"', '"pyth"', '"yth"', '"python"'], answer: 0, explanation: 'Indices 0,1,2 (end 3 excluded) give "pyt".' },
        { lvl: 2, type: 'mcq', prompt: 'Calling s.upper() on a string:', choices: ['returns a new uppercase string', 'changes s in place', 'deletes s', 'errors'], answer: 0, explanation: 'Strings are immutable; methods return new strings.' },
      ] },
    { tier: 'F2', order: 5, slug: 'dictionaries-sets', title: 'Dictionaries & Sets',
      summary: 'Key-value modelling with dictionaries, and sets for uniqueness.',
      outcomes: ['Use dictionaries for key-value data', 'Use sets for uniqueness', 'Choose the right structure'],
      concepts: [
        ['Dictionaries', 'A dictionary maps keys to values (like a real dictionary maps words to meanings). Lookup by key is fast and expressive — ideal for labelled data.'],
        ['Sets', 'A set stores unique, unordered items. It answers membership and removes duplicates efficiently. Choosing list vs dict vs set is a real design skill.'],
      ],
      mistakes: ['Using a list where key lookup (dict) is needed.', 'Expecting sets to keep order or duplicates.', 'Using an unhashable key in a dict.'],
      tricks: ['Dict for labelled lookup; set for uniqueness; list for order.', 'dict[key] retrieves a value fast.', 'Convert a list to a set to remove duplicates.'],
      memory: ['"Dict = key→value; set = unique items."', '"Choose the structure to fit the job."', 'Sets drop duplicates and order.'],
      board: { CBSE: ['Cl.11 CS: Dictionaries'], ICSE: ['Cl.10-11 Data Structures'], IB: ['DP CS'] },
      comp: [], keywords: ['dictionary', 'set', 'key-value', 'data structure', 'hashing'],
      xprereqs: ['cs.F2.lists-iteration'],
      quiz: [
        { lvl: 1, type: 'mcq', prompt: 'Which structure maps keys to values?', choices: ['dictionary', 'list', 'set', 'tuple'], answer: 0, explanation: 'A dictionary stores key-value pairs.' },
        { lvl: 2, type: 'mcq', prompt: 'To remove duplicates from a list quickly, convert it to a:', choices: ['set', 'string', 'dictionary key list', 'float'], answer: 0, explanation: 'Sets store only unique items.' },
      ] },
    { tier: 'F2', order: 6, slug: 'version-control-ii', title: 'Version Control Basics II',
      summary: 'Branches, remotes and pushing to GitHub — your first published repository.',
      outcomes: ['Create and merge branches', 'Push to a remote (GitHub)', 'Collaborate basics'],
      concepts: [
        ['Branches', 'A branch is a parallel line of work, so you can experiment without breaking the main version. Merging brings changes back together.'],
        ['Remotes', 'A remote (like GitHub) is a shared copy online. Pushing uploads your commits, letting you back up and collaborate — your first public repo.'],
      ],
      mistakes: ['Working directly on the main branch for risky changes.', 'Forgetting to push commits (they stay local).', 'Confusing commit (local) with push (remote).'],
      tricks: ['Branch for new features, merge when done.', 'Push to back up and share your work.', 'Commit is local; push sends to the remote.'],
      memory: ['"Branch to experiment safely."', '"Push shares commits."', 'Local commit ≠ remote push.'],
      board: { CBSE: ['Cl.11-12 CS: Collaboration'], ICSE: ['Cl.10 IT Tools'], IB: ['DP CS: Development'] },
      comp: [], keywords: ['git', 'branch', 'remote', 'GitHub', 'push'],
      xprereqs: ['cs.F1.version-control-i'],
      quiz: [
        { lvl: 2, type: 'mcq', prompt: 'A git branch lets you:', choices: ['work in parallel without breaking main', 'delete history', 'speed up code', 'format output'], answer: 0, explanation: 'Branches isolate work from the main line.' },
        { lvl: 1, type: 'mcq', prompt: 'To upload local commits to GitHub you:', choices: ['push', 'print', 'commit only', 'compile'], answer: 0, explanation: 'git push sends commits to the remote.' },
      ] },
    { tier: 'F2', order: 7, slug: 'project-1', title: 'Project 1', core: true,
      summary: 'Build a complete small program (e.g., a quiz game), committed to git.',
      outcomes: ['Combine variables, loops, functions', 'Build a working program', 'Version-control the project'],
      concepts: [
        ['Putting it together', 'Your first complete program combines everything so far: input, variables, conditionals, loops and functions — decomposed into parts and assembled.'],
        ['Ship it', 'A finished, committed project (a quiz game, a text tool) is proof you can build, not just follow tutorials. Commit as you go.'],
      ],
      mistakes: ['Trying to write it all at once instead of part by part.', 'Not testing each piece before moving on.', 'Forgetting to commit progress.'],
      tricks: ['Build one small feature at a time and test it.', 'Reuse functions to avoid repetition.', 'Commit each working step.'],
      memory: ['"Assemble from tested parts."', '"Build, run, commit."', 'A shipped project proves the skill.'],
      board: { CBSE: ['Cl.11 CS: Project'], ICSE: ['Cl.10 Project'], IB: ['DP CS: Development'] },
      comp: [], keywords: ['project', 'program', 'integration', 'git'],
      xprereqs: ['cs.F2.functions'],
      quiz: [
        { lvl: 2, type: 'mcq', prompt: 'The best way to build a first project is to:', choices: ['add and test one small feature at a time', 'write everything then run once', 'avoid functions', 'skip testing'], answer: 0, explanation: 'Incremental building with testing is reliable.' },
        { lvl: 1, type: 'mcq', prompt: 'Throughout a project you should:', choices: ['commit progress regularly', 'never commit', 'delete old code', 'avoid functions'], answer: 0, explanation: 'Regular commits document and protect progress.' },
      ] },

    // ================= I1 =================
    { tier: 'I1', order: 1, slug: 'file-io-data-formats', title: 'File I/O & Data Formats',
      summary: 'Reading and writing files, and working with CSV and JSON.',
      outcomes: ['Read and write files', 'Parse CSV and JSON', 'Handle data persistently'],
      concepts: [
        ['Persistent data', 'Files let programs save and load data between runs. Opening, reading, writing and closing files (or using with) is the basis of persistence.'],
        ['Structured formats', 'CSV stores tables; JSON stores nested key-value data. Libraries parse them into lists and dictionaries you already know.'],
      ],
      mistakes: ['Forgetting to close files (use with to auto-close).', 'Mismatching read/write modes.', 'Assuming JSON keys keep a specific order historically.'],
      tricks: ['Use with open(...) to auto-close files.', 'CSV → rows; JSON → dicts/lists.', 'Read the whole file or line by line as needed.'],
      memory: ['"with open() auto-closes."', '"CSV tables, JSON nested."', 'Files persist data across runs.'],
      board: { CBSE: ['Cl.12 CS: File Handling'], ICSE: ['Cl.11-12 Files'], IB: ['DP CS: Files'] },
      comp: [], keywords: ['file', 'CSV', 'JSON', 'persistence', 'I/O'],
      xprereqs: ['cs.F2.dictionaries-sets'],
      quiz: [
        { lvl: 2, type: 'mcq', prompt: 'Using with open(...) as f: ensures the file is:', choices: ['closed automatically', 'never read', 'deleted', 'printed'], answer: 0, explanation: 'The with block auto-closes the file.' },
        { lvl: 1, type: 'mcq', prompt: 'JSON is well suited to storing:', choices: ['nested key-value data', 'only numbers', 'images', 'nothing'], answer: 0, explanation: 'JSON represents nested objects and arrays.' },
      ] },
    { tier: 'I1', order: 2, slug: 'error-handling-debugging', title: 'Error Handling & Debugging Discipline',
      summary: 'Exceptions, reading tracebacks, and systematic debugging.',
      outcomes: ['Handle exceptions with try/except', 'Read tracebacks', 'Debug systematically'],
      concepts: [
        ['Exceptions', 'When something goes wrong, Python raises an exception. try/except lets your program respond gracefully instead of crashing.'],
        ['Debugging', 'Debugging is systematic: read the traceback (bottom-up), reproduce the bug, isolate it with prints or asserts, then fix. Guessing wastes time.'],
      ],
      mistakes: ['Catching all exceptions and hiding real bugs.', 'Ignoring the traceback\'s message.', 'Changing code randomly instead of isolating the bug.'],
      tricks: ['Read the traceback bottom-up: last line is the error.', 'Reproduce the bug reliably before fixing.', 'Use prints/asserts to narrow down the cause.'],
      memory: ['"try/except handles errors gracefully."', '"Traceback bottom-up = the diagnosis."', 'Isolate before you fix.'],
      board: { CBSE: ['Cl.12 CS: Exception Handling'], ICSE: ['Cl.11-12 Debugging'], IB: ['DP CS'] },
      comp: [], keywords: ['exception', 'try except', 'traceback', 'debugging'],
      xprereqs: ['cs.F2.project-1'],
      quiz: [
        { lvl: 2, type: 'mcq', prompt: 'The most informative line of a traceback is usually:', choices: ['the last line', 'the first line', 'the middle', 'none'], answer: 0, explanation: 'The last line names the error type and message.' },
        { lvl: 2, type: 'mcq', prompt: 'try/except is used to:', choices: ['handle errors without crashing', 'speed up code', 'create variables', 'format strings'], answer: 0, explanation: 'It catches exceptions and responds gracefully.' },
      ] },
    { tier: 'I1', order: 3, slug: 'modules-organization', title: 'Modules & Program Organization',
      summary: 'Multi-file programs, imports, and the standard library.',
      outcomes: ['Split code across modules', 'Import and reuse code', 'Use the standard library'],
      concepts: [
        ['Organising code', 'As programs grow, splitting them into modules (files) keeps related code together and reusable. import brings a module\'s functions into another file.'],
        ['Standard library', 'Python ships with a rich standard library (math, random, datetime). Reusing it saves you from reinventing common tools.'],
      ],
      mistakes: ['Putting everything in one giant file.', 'Circular imports between modules.', 'Reinventing what the standard library already provides.'],
      tricks: ['Group related functions into modules.', 'import module, then module.function().', 'Check the standard library before writing from scratch.'],
      memory: ['"One module, one responsibility."', '"import to reuse."', 'Standard library saves work.'],
      board: { CBSE: ['Cl.12 CS: Modules'], ICSE: ['Cl.11-12 Modular Programming'], IB: ['DP CS'] },
      comp: [], keywords: ['module', 'import', 'standard library', 'organization'],
      xprereqs: ['cs.F2.functions'],
      quiz: [
        { lvl: 1, type: 'mcq', prompt: 'To use a function from another file you:', choices: ['import it', 'copy the whole file', 'rename it', 'delete it'], answer: 0, explanation: 'import brings the module\'s code in for reuse.' },
        { lvl: 2, type: 'mcq', prompt: 'Splitting a large program into modules mainly improves:', choices: ['organisation and reuse', 'execution speed', 'file size', 'colour'], answer: 0, explanation: 'Modules keep related code together and reusable.' },
      ] },
    { tier: 'I1', order: 4, slug: 'data-structures-basic', title: 'Data Structures: Stacks, Queues, Linked Lists',
      summary: 'Building and using basic data structures, and understanding their trade-offs.',
      outcomes: ['Explain stacks, queues, linked lists', 'Implement them in Python', 'Choose a structure for a task'],
      concepts: [
        ['Ways to organise data', 'A stack is last-in-first-out (LIFO); a queue is first-in-first-out (FIFO); a linked list chains nodes together. Each fits different problems.'],
        ['Trade-offs', 'Structures differ in how fast they add, remove and search. Choosing well is what separates working code from efficient code.'],
      ],
      mistakes: ['Confusing stack (LIFO) with queue (FIFO).', 'Ignoring performance trade-offs.', 'Reimplementing a structure the language already provides.'],
      tricks: ['Stack = LIFO (like plates); queue = FIFO (like a line).', 'Match the structure to the access pattern.', 'Know when a built-in list/deque suffices.'],
      memory: ['"Stack LIFO, queue FIFO."', '"Choose by access pattern."', 'Structures have trade-offs.'],
      board: { CBSE: ['Cl.12 CS: Stacks & Queues'], ICSE: ['Cl.11-12 Data Structures'], IB: ['DP CS: Abstract Data Structures'] },
      comp: ['JEE-Advanced'], keywords: ['stack', 'queue', 'linked list', 'data structure', 'LIFO', 'FIFO'],
      xprereqs: ['cs.F2.dictionaries-sets'],
      quiz: [
        { lvl: 1, type: 'mcq', prompt: 'A stack removes items in ___ order.', choices: ['last-in-first-out', 'first-in-first-out', 'random', 'sorted'], answer: 0, explanation: 'Stacks are LIFO.' },
        { lvl: 2, type: 'mcq', prompt: 'A queue is best described as:', choices: ['first-in-first-out', 'last-in-first-out', 'key-value', 'unordered'], answer: 0, explanation: 'Queues are FIFO, like a line of people.' },
      ] },
    { tier: 'I1', order: 5, slug: 'algorithms-i', title: 'Algorithms I',
      summary: 'Linear and binary search, basic sorting, and correctness reasoning.',
      outcomes: ['Implement linear and binary search', 'Implement a basic sort', 'Reason about correctness'],
      concepts: [
        ['Searching', 'Linear search checks each item; binary search halves a sorted list each step, so it is far faster on large sorted data — a first taste of efficiency.'],
        ['Sorting and correctness', 'Sorting arranges data; simple sorts (bubble, insertion) are easy to reason about. Arguing why an algorithm always works is a transferable rigour.'],
      ],
      mistakes: ['Using binary search on unsorted data.', 'Off-by-one errors in loop bounds.', 'Assuming code is correct without testing edge cases.'],
      tricks: ['Binary search needs sorted data; it halves the range each step.', 'Test edge cases: empty, one element, not found.', 'Trace an algorithm by hand to check correctness.'],
      memory: ['"Binary search halves — needs sorted data."', '"Test the edges."', 'Argue correctness, do not assume it.'],
      board: { CBSE: ['Cl.11-12 CS: Searching & Sorting'], ICSE: ['Cl.11-12 Algorithms'], IB: ['DP CS'] },
      comp: ['JEE-Advanced'], keywords: ['search', 'binary search', 'sorting', 'algorithm', 'correctness'],
      xprereqs: ['cs.I1.data-structures-basic'],
      quiz: [
        { lvl: 2, type: 'mcq', prompt: 'Binary search requires the data to be:', choices: ['sorted', 'unsorted', 'unique', 'numeric only'], answer: 0, explanation: 'It relies on order to halve the search space.' },
        { lvl: 2, type: 'mcq', prompt: 'Compared with linear search on large sorted data, binary search is:', choices: ['much faster', 'slower', 'the same', 'unusable'], answer: 0, explanation: 'It halves the remaining items each step.' },
      ] },
    { tier: 'I1', order: 6, slug: 'complexity-intuition', title: 'Complexity Intuition (Big-O)',
      summary: 'Big-O as "how does work grow with input size" — using logarithms from maths.',
      outcomes: ['Explain Big-O notation', 'Compare algorithm growth rates', 'Estimate scalability'],
      concepts: [
        ['Growth, not seconds', 'Big-O describes how an algorithm\'s work grows with input size n: O(n) linear, O(n²) quadratic, O(log n) logarithmic. It predicts scalability, not exact time.'],
        ['Why it matters', 'An O(log n) search beats O(n) massively on big data — the difference between instant and unusable. This reuses logarithms from maths.'],
      ],
      mistakes: ['Confusing Big-O (growth) with actual runtime in seconds.', 'Ignoring constants only when they matter little (large n).', 'Thinking O(n²) is fine at any scale.'],
      tricks: ['Ask "if input doubles, how does work grow?"', 'O(log n) < O(n) < O(n²) for large n.', 'Nested loops over n often mean O(n²).'],
      memory: ['"Big-O = growth with input size."', '"log < linear < quadratic."', 'Nested loops → n².'],
      board: { CBSE: ['Cl.12 CS: Efficiency'], ICSE: ['Cl.12 Complexity'], IB: ['DP CS'] },
      comp: ['JEE-Advanced'], keywords: ['Big-O', 'complexity', 'scalability', 'growth', 'efficiency'],
      quiz: [
        { lvl: 2, type: 'mcq', prompt: 'Which grows slowest as input size n increases?', choices: ['O(log n)', 'O(n)', 'O(n²)', 'O(n³)'], answer: 0, explanation: 'Logarithmic growth is the slowest here.' },
        { lvl: 2, type: 'mcq', prompt: 'Two nested loops over n items are usually:', choices: ['O(n²)', 'O(n)', 'O(log n)', 'O(1)'], answer: 0, explanation: 'Each of n iterations does n work → n².' },
      ] },
    { tier: 'I1', order: 7, slug: 'project-2', title: 'Project 2', core: true,
      summary: 'A program with persistent data and a clean module structure.',
      outcomes: ['Design a multi-module program', 'Persist data to files', 'Structure code cleanly'],
      concepts: [
        ['A bigger build', 'Project 2 raises the bar: multiple modules, saved data, and error handling. It integrates files, functions and structure into a real tool.'],
        ['Clean structure', 'Organising code into logical modules with clear responsibilities makes a program maintainable — a habit that scales to real software.'],
      ],
      mistakes: ['Cramming everything into one file.', 'No error handling for bad input or missing files.', 'Not committing regularly.'],
      tricks: ['Separate concerns into modules.', 'Handle missing files and bad input gracefully.', 'Commit each working milestone.'],
      memory: ['"Modules with clear jobs."', '"Persist data, handle errors."', 'Commit milestones.'],
      board: { CBSE: ['Cl.12 CS: Project'], ICSE: ['Cl.12 Project'], IB: ['DP CS: Development'] },
      comp: [], keywords: ['project', 'modules', 'persistence', 'structure'],
      xprereqs: ['cs.I1.modules-organization'],
      quiz: [
        { lvl: 2, type: 'mcq', prompt: 'Clean project structure means:', choices: ['modules with clear responsibilities', 'one huge file', 'no functions', 'no comments'], answer: 0, explanation: 'Separation of concerns aids maintenance.' },
        { lvl: 2, type: 'mcq', prompt: 'A robust program should handle:', choices: ['missing files and bad input', 'only perfect input', 'no input', 'nothing'], answer: 0, explanation: 'Real programs anticipate errors.' },
      ] },

    // ================= I2 (Python → C) =================
    { tier: 'I2', order: 1, slug: 'intro-c', title: 'Intro to C',
      summary: 'The compilation model, types and functions in C — contrasting with Python.',
      outcomes: ['Compile and run a C program', 'Use C types and functions', 'Contrast C with Python'],
      concepts: [
        ['Compiled, not interpreted', 'C is compiled to machine code before running, unlike Python\'s interpreter. This is faster but stricter — you must declare types and compile.'],
        ['What Python hid', 'C exposes details Python hides: explicit types, manual structure, and (soon) memory. Learning it deepens your understanding of how programs really run.'],
      ],
      mistakes: ['Forgetting to compile before running.', 'Omitting type declarations.', 'Expecting Python conveniences (like dynamic typing) in C.'],
      tricks: ['Compile then run (e.g., gcc, then ./program).', 'Declare a type for every variable.', 'Think of C as showing what Python does under the hood.'],
      memory: ['"C compiles; Python interprets."', '"Declare every type."', 'C reveals the machine.'],
      board: { CBSE: ['Cl.11-12 CS (C basics)'], ICSE: ['Cl.11 C Programming'], IB: ['DP CS'] },
      comp: [], keywords: ['C', 'compilation', 'types', 'gcc', 'compiled'],
      xprereqs: ['cs.F2.functions'],
      quiz: [
        { lvl: 2, type: 'mcq', prompt: 'Unlike Python, C code must first be:', choices: ['compiled to machine code', 'uploaded online', 'printed', 'interpreted line by line'], answer: 0, explanation: 'C is compiled before it runs.' },
        { lvl: 1, type: 'mcq', prompt: 'In C, each variable must have a declared:', choices: ['type', 'colour', 'comment', 'file'], answer: 0, explanation: 'C is statically typed — types are declared.' },
      ] },
    { tier: 'I2', order: 2, slug: 'control-arrays-c', title: 'Control Flow & Arrays in C',
      summary: 'Conditionals, loops and arrays in C, and how they differ from Python.',
      outcomes: ['Write C conditionals and loops', 'Use C arrays', 'Note differences from Python'],
      concepts: [
        ['Familiar logic, stricter syntax', 'C has if, for and while like Python, but with braces and semicolons, and no automatic bounds checking on arrays.'],
        ['Fixed-size arrays', 'A C array is a fixed block of same-type elements. Unlike Python lists, it does not grow, and going out of bounds is undefined behaviour, not an error.'],
      ],
      mistakes: ['Reading or writing past the end of an array (undefined behaviour).', 'Forgetting semicolons or braces.', 'Assuming C arrays resize like Python lists.'],
      tricks: ['C arrays are fixed size — track the length yourself.', 'Stay within bounds; C will not warn you.', 'Braces group blocks; semicolons end statements.'],
      memory: ['"C arrays are fixed and unchecked."', '"Braces and semicolons required."', 'Out of bounds = undefined behaviour.'],
      board: { CBSE: ['Cl.11-12 CS'], ICSE: ['Cl.11-12 C Programming'], IB: ['DP CS'] },
      comp: [], keywords: ['C', 'arrays', 'control flow', 'loops', 'bounds'],
      xprereqs: ['cs.I2.intro-c'],
      quiz: [
        { lvl: 2, type: 'mcq', prompt: 'Accessing a C array beyond its size is:', choices: ['undefined behaviour', 'a caught exception', 'automatically resized', 'always zero'], answer: 0, explanation: 'C does no bounds checking — it is undefined behaviour.' },
        { lvl: 1, type: 'mcq', prompt: 'Compared with Python lists, C arrays are:', choices: ['fixed size', 'always growable', 'key-value', 'untyped'], answer: 0, explanation: 'C arrays have a fixed length.' },
      ] },
    { tier: 'I2', order: 3, slug: 'pointers-memory', title: 'Pointers & Memory',
      summary: 'The core C idea: addresses, dereferencing, and the stack.',
      outcomes: ['Explain what a pointer is', 'Use addresses and dereferencing', 'Describe the stack'],
      concepts: [
        ['Pointers hold addresses', 'A pointer stores the memory address of a value. & gets an address; * dereferences it (reads the value there). This is the idea Python hid entirely.'],
        ['The stack', 'Local variables live on the stack, which grows and shrinks as functions are called and return. Understanding it demystifies how programs use memory.'],
      ],
      mistakes: ['Confusing a pointer with the value it points to.', 'Dereferencing an uninitialised or null pointer.', 'Mixing up & (address-of) and * (dereference).'],
      tricks: ['& gets an address; * follows it to the value.', 'A pointer is just an address, a number.', 'Local variables live on the stack.'],
      memory: ['"& address-of, * dereference."', '"A pointer holds an address."', 'Locals live on the stack.'],
      board: { CBSE: ['Cl.11-12 CS (Pointers)'], ICSE: ['Cl.12 Pointers'], IB: ['DP CS'] },
      comp: [], keywords: ['pointer', 'memory', 'address', 'dereference', 'stack'],
      xprereqs: ['cs.I2.control-arrays-c'],
      quiz: [
        { lvl: 2, type: 'mcq', prompt: 'In C, the & operator gives a variable\'s:', choices: ['memory address', 'value', 'type', 'size in bits'], answer: 0, explanation: '& is the address-of operator.' },
        { lvl: 2, type: 'mcq', prompt: 'Dereferencing a pointer (*p) gives:', choices: ['the value at the address', 'the address itself', 'a new pointer', 'an error always'], answer: 0, explanation: '* reads the value stored at the pointer\'s address.' },
      ] },
    { tier: 'I2', order: 4, slug: 'strings-memory-c', title: 'Strings & Manual Memory Management in C',
      summary: 'C strings as character arrays, malloc/free, and why Python never needed them.',
      outcomes: ['Handle C strings', 'Allocate and free memory', 'Avoid memory leaks'],
      concepts: [
        ['Strings are char arrays', 'A C string is an array of characters ending in a null terminator (\\0). There is no built-in string type like Python\'s.'],
        ['Manual memory', 'malloc requests memory; free returns it. Forgetting to free causes leaks; using freed memory causes bugs. Python\'s garbage collector did this for you.'],
      ],
      mistakes: ['Forgetting the null terminator on C strings.', 'Memory leaks from not calling free.', 'Using memory after freeing it (use-after-free).'],
      tricks: ['Every C string ends with \\0.', 'Every malloc needs a matching free.', 'Set freed pointers to NULL to avoid reuse.'],
      memory: ['"C strings end in \\0."', '"malloc pairs with free."', 'Python\'s GC did this automatically.'],
      board: { CBSE: ['Cl.12 CS (Memory)'], ICSE: ['Cl.12 Dynamic Memory'], IB: ['DP CS'] },
      comp: [], keywords: ['C strings', 'malloc', 'free', 'memory leak', 'null terminator'],
      xprereqs: ['cs.I2.pointers-memory'],
      quiz: [
        { lvl: 2, type: 'mcq', prompt: 'In C, memory obtained with malloc should later be:', choices: ['freed', 'printed', 'compiled', 'renamed'], answer: 0, explanation: 'free returns the memory to avoid leaks.' },
        { lvl: 2, type: 'mcq', prompt: 'A C string is terminated by a:', choices: ['null character \\0', 'newline', 'space', 'semicolon'], answer: 0, explanation: 'The null terminator marks the string\'s end.' },
      ] },
    { tier: 'I2', order: 5, slug: 'structs-data-structures-c', title: 'Structs & Building Data Structures in C',
      summary: 'Grouping data with structs, and re-implementing a linked list with pointers.',
      outcomes: ['Define and use structs', 'Build a linked list in C', 'Connect structs and pointers'],
      concepts: [
        ['Structs group data', 'A struct bundles related fields under one type (like a record). Combined with pointers, structs build complex data structures from scratch.'],
        ['Linked lists in C', 'Re-implementing a linked list with structs and pointers shows how the abstract structure works at the memory level — the payoff of learning C.'],
      ],
      mistakes: ['Forgetting to allocate memory for struct nodes.', 'Losing the head pointer of a linked list.', 'Not freeing nodes, causing leaks.'],
      tricks: ['A struct is a custom record type.', 'A linked list node holds data plus a pointer to the next.', 'Keep the head pointer safe to not lose the list.'],
      memory: ['"Struct = grouped fields."', '"Node = data + next pointer."', 'C shows the structure at memory level.'],
      board: { CBSE: ['Cl.12 CS (Structures)'], ICSE: ['Cl.12 Structures'], IB: ['DP CS: Data Structures'] },
      comp: [], keywords: ['struct', 'linked list', 'pointers', 'C', 'data structure'],
      xprereqs: ['cs.I2.strings-memory-c'],
      quiz: [
        { lvl: 2, type: 'mcq', prompt: 'A struct in C is used to:', choices: ['group related fields under one type', 'loop over data', 'free memory', 'compile code'], answer: 0, explanation: 'A struct bundles related data.' },
        { lvl: 2, type: 'mcq', prompt: 'A linked-list node typically contains data and:', choices: ['a pointer to the next node', 'the whole list copied', 'a file', 'a string only'], answer: 0, explanation: 'The next-pointer chains nodes together.' },
      ] },
    { tier: 'I2', order: 6, slug: 'how-code-runs', title: 'How Code Becomes Execution',
      summary: 'Memory layout and compilation stages, intuitively.',
      outcomes: ['Describe compilation stages', 'Explain memory layout', 'Connect source to execution'],
      concepts: [
        ['From source to machine', 'Compilation goes source → preprocessing → compiling → assembling → linking → an executable of machine instructions the CPU runs directly.'],
        ['Memory layout', 'A running program uses regions: code, static data, the stack (locals) and the heap (malloc). Knowing the map explains many bugs and behaviours.'],
      ],
      mistakes: ['Thinking source code runs directly (it is compiled first).', 'Confusing stack and heap.', 'Ignoring linking when using libraries.'],
      tricks: ['Remember the pipeline: preprocess, compile, assemble, link.', 'Stack for locals, heap for malloc.', 'Linker errors differ from compile errors.'],
      memory: ['"Preprocess → compile → assemble → link."', '"Stack: locals; heap: malloc."', 'Source becomes machine code.'],
      board: { CBSE: ['Cl.12 CS: Computer Organisation'], ICSE: ['Cl.12 Systems'], IB: ['DP CS: Computer Organisation'] },
      comp: [], keywords: ['compilation', 'memory layout', 'stack', 'heap', 'linking'],
      xprereqs: ['cs.I2.structs-data-structures-c'],
      quiz: [
        { lvl: 2, type: 'mcq', prompt: 'Dynamically allocated memory (malloc) comes from the:', choices: ['heap', 'stack', 'code segment', 'registers'], answer: 0, explanation: 'The heap serves dynamic allocation.' },
        { lvl: 2, type: 'mcq', prompt: 'The final stage that combines compiled parts into an executable is:', choices: ['linking', 'preprocessing', 'printing', 'parsing'], answer: 0, explanation: 'The linker produces the final executable.' },
      ] },

    // ================= A1 =================
    { tier: 'A1', order: 1, slug: 'oop', title: 'Object-Oriented Programming (Python)',
      summary: 'Classes, objects, encapsulation and inheritance — modelling with objects.',
      outcomes: ['Define classes and create objects', 'Use encapsulation', 'Apply inheritance'],
      concepts: [
        ['Objects bundle data and behaviour', 'A class is a blueprint; objects are instances with their own data (attributes) and actions (methods). OOP models real-world entities in code.'],
        ['Inheritance and encapsulation', 'Inheritance lets a class reuse and extend another; encapsulation keeps internal detail hidden behind a clean interface. Both manage complexity in large programs.'],
      ],
      mistakes: ['Confusing a class (blueprint) with an object (instance).', 'Forgetting self in method definitions.', 'Overusing inheritance where composition is simpler.'],
      tricks: ['Class = blueprint; object = instance.', 'Methods take self as the first parameter.', 'Inherit to reuse; encapsulate to hide detail.'],
      memory: ['"Class blueprint, object instance."', '"self refers to the object."', 'Inheritance reuses, encapsulation hides.'],
      board: { CBSE: ['Cl.12 CS: OOP concepts'], ICSE: ['Cl.11-12 OOP'], IB: ['DP CS: OOP'] },
      comp: [], keywords: ['OOP', 'class', 'object', 'inheritance', 'encapsulation'],
      xprereqs: ['cs.I1.project-2'],
      quiz: [
        { lvl: 2, type: 'mcq', prompt: 'A class is best described as:', choices: ['a blueprint for objects', 'a single object', 'a loop', 'a file'], answer: 0, explanation: 'Objects are instances created from a class blueprint.' },
        { lvl: 2, type: 'mcq', prompt: 'Inheritance lets a class:', choices: ['reuse and extend another class', 'run faster', 'avoid functions', 'delete objects'], answer: 0, explanation: 'A subclass inherits and extends a base class.' },
      ] },
    { tier: 'A1', order: 2, slug: 'recursion', title: 'Recursion',
      summary: 'Thinking recursively, base cases, and recursion vs iteration.',
      outcomes: ['Write recursive functions', 'Identify base and recursive cases', 'Compare recursion and iteration'],
      concepts: [
        ['A function that calls itself', 'Recursion solves a problem by reducing it to a smaller version of itself, until a base case stops the recursion. It suits naturally nested problems (trees, factorials).'],
        ['Base case is essential', 'Without a base case, recursion never stops (stack overflow). Every recursion needs a shrinking input and a stopping condition.'],
      ],
      mistakes: ['Forgetting the base case, causing infinite recursion.', 'Not reducing the problem toward the base case.', 'Using recursion where a simple loop is clearer.'],
      tricks: ['Define the base case first, then the recursive step.', 'Ensure each call moves toward the base case.', 'Some problems (trees) are naturally recursive.'],
      memory: ['"Base case stops recursion."', '"Shrink toward the base."', 'Recursion suits nested problems.'],
      board: { CBSE: ['Cl.12 CS: Recursion'], ICSE: ['Cl.12 Recursion'], IB: ['DP CS'] },
      comp: ['JEE-Advanced'], keywords: ['recursion', 'base case', 'iteration', 'stack'],
      xprereqs: ['cs.F2.functions'],
      quiz: [
        { lvl: 2, type: 'mcq', prompt: 'Every recursive function needs a:', choices: ['base case', 'global variable', 'loop', 'class'], answer: 0, explanation: 'The base case stops the recursion.' },
        { lvl: 2, type: 'mcq', prompt: 'Missing a base case in recursion typically causes:', choices: ['a stack overflow', 'faster code', 'a syntax error only', 'nothing'], answer: 0, explanation: 'It recurses endlessly until the stack overflows.' },
      ] },
    { tier: 'A1', order: 3, slug: 'trees-graphs', title: 'Trees & Graphs',
      summary: 'Representing and traversing trees and graphs (BFS/DFS).',
      outcomes: ['Represent trees and graphs', 'Traverse with BFS and DFS', 'Choose a traversal for a task'],
      concepts: [
        ['Nonlinear structures', 'Trees (hierarchies) and graphs (networks) model relationships lists cannot — file systems, maps, social networks. Nodes connect via edges.'],
        ['Traversal', 'BFS explores level by level (using a queue); DFS goes deep first (using a stack/recursion). The right traversal depends on the problem.'],
      ],
      mistakes: ['Confusing BFS (queue) with DFS (stack/recursion).', 'Forgetting to mark visited nodes in a graph (infinite loops).', 'Treating a graph like a simple list.'],
      tricks: ['BFS = queue, level by level; DFS = stack/recursion, deep first.', 'Mark visited nodes to avoid cycles.', 'Trees are graphs without cycles.'],
      memory: ['"BFS queue, DFS stack."', '"Mark visited to avoid loops."', 'Trees = acyclic graphs.'],
      board: { CBSE: ['Cl.12 CS: Trees'], ICSE: ['Cl.12 Data Structures'], IB: ['DP CS: Abstract Data Structures'] },
      comp: ['JEE-Advanced'], keywords: ['tree', 'graph', 'BFS', 'DFS', 'traversal'],
      xprereqs: ['cs.I1.data-structures-basic'],
      quiz: [
        { lvl: 2, type: 'mcq', prompt: 'Breadth-first search (BFS) typically uses a:', choices: ['queue', 'stack', 'dictionary', 'float'], answer: 0, explanation: 'BFS explores level by level using a queue.' },
        { lvl: 2, type: 'mcq', prompt: 'To avoid infinite loops when traversing a graph, you must:', choices: ['mark visited nodes', 'sort the nodes', 'delete edges', 'use recursion only'], answer: 0, explanation: 'Tracking visited nodes prevents revisiting cycles.' },
      ] },
    { tier: 'A1', order: 4, slug: 'algorithms-ii', title: 'Algorithms II',
      summary: 'Divide and conquer, efficient sorting (merge/quick), and hashing.',
      outcomes: ['Apply divide and conquer', 'Explain merge and quick sort', 'Use hashing for fast lookup'],
      concepts: [
        ['Divide and conquer', 'Split a problem, solve the parts, combine — the strategy behind merge sort and binary search. It often turns O(n²) into O(n log n).'],
        ['Hashing', 'A hash maps keys to array positions for near-instant lookup — how dictionaries and sets are fast. Understanding it explains their performance.'],
      ],
      mistakes: ['Assuming any sort is O(n log n) (simple sorts are O(n²)).', 'Ignoring worst cases (e.g., quicksort on sorted data).', 'Thinking hashing guarantees order.'],
      tricks: ['Merge sort is reliably O(n log n).', 'Divide and conquer: split, solve, combine.', 'Hashing gives near O(1) average lookup.'],
      memory: ['"Split, solve, combine."', '"Merge/quick sort: n log n."', 'Hashing → fast lookup.'],
      board: { CBSE: ['Cl.12 CS: Sorting'], ICSE: ['Cl.12 Algorithms'], IB: ['DP CS'] },
      comp: ['JEE-Advanced'], keywords: ['divide and conquer', 'merge sort', 'quick sort', 'hashing', 'algorithms'],
      xprereqs: ['cs.I1.algorithms-i'],
      quiz: [
        { lvl: 2, type: 'mcq', prompt: 'Merge sort has a time complexity of:', choices: ['O(n log n)', 'O(n²)', 'O(n)', 'O(1)'], answer: 0, explanation: 'Divide and conquer gives O(n log n).' },
        { lvl: 2, type: 'mcq', prompt: 'Hashing enables:', choices: ['fast average-case lookup', 'sorted output', 'slower search', 'no storage'], answer: 0, explanation: 'Hash tables give near O(1) average lookup.' },
      ] },
    { tier: 'A1', order: 5, slug: 'algorithmic-problem-solving', title: 'Algorithmic Problem Solving',
      summary: 'Problem-solving patterns and approaching problems under constraints.',
      outcomes: ['Recognise common patterns', 'Approach constrained problems', 'Balance correctness and efficiency'],
      concepts: [
        ['Patterns', 'Many problems fit patterns — two pointers, sliding window, greedy, dynamic programming. Recognising the pattern suggests an approach.'],
        ['Under constraints', 'Competitive and real problems limit time and memory. Choosing an algorithm whose complexity fits the constraints is the key skill.'],
      ],
      mistakes: ['Brute-forcing when a pattern gives a faster solution.', 'Ignoring input-size limits when choosing an approach.', 'Optimising before getting a correct solution.'],
      tricks: ['Match the problem to a known pattern.', 'Check input size to pick an acceptable complexity.', 'Get it correct first, then optimise.'],
      memory: ['"Recognise the pattern."', '"Let input size guide the approach."', 'Correct first, fast second.'],
      board: { CBSE: ['Cl.12 CS: Problem Solving'], ICSE: ['Cl.12 Algorithms'], IB: ['DP CS'] },
      comp: ['JEE-Advanced'], keywords: ['problem solving', 'patterns', 'dynamic programming', 'greedy', 'constraints'],
      xprereqs: ['cs.A1.algorithms-ii'],
      quiz: [
        { lvl: 3, type: 'mcq', prompt: 'The first priority when solving an algorithm problem is usually:', choices: ['a correct solution', 'the fastest possible code', 'the shortest code', 'avoiding functions'], answer: 0, explanation: 'Correctness first, then optimise.' },
        { lvl: 2, type: 'mcq', prompt: 'Input-size limits mainly help you choose:', choices: ['an acceptable time complexity', 'variable names', 'the language', 'the colour'], answer: 0, explanation: 'They tell you which complexities will run in time.' },
      ] },
    { tier: 'A1', order: 6, slug: 'testing', title: 'Testing',
      summary: 'Writing tests and thinking about edge cases.',
      outcomes: ['Write basic tests', 'Identify edge cases', 'Use tests to catch regressions'],
      concepts: [
        ['Tests check behaviour', 'A test runs code with known input and checks the output. Automated tests catch bugs early and prevent regressions when you change code.'],
        ['Edge cases', 'Bugs hide at the edges: empty input, one element, maximum values, invalid input. Thinking about edges is where good testing lives.'],
      ],
      mistakes: ['Only testing the "happy path".', 'Ignoring edge cases like empty or invalid input.', 'Not re-running tests after changes.'],
      tricks: ['Test normal, boundary and invalid inputs.', 'Write a test that reproduces a bug before fixing it.', 'Re-run tests after every change.'],
      memory: ['"Test the edges, not just the happy path."', '"A failing test pins the bug."', 'Re-run tests to catch regressions.'],
      board: { CBSE: ['Cl.12 CS: Testing'], ICSE: ['Cl.12 Testing'], IB: ['DP CS: Development'] },
      comp: [], keywords: ['testing', 'edge cases', 'regression', 'unit test'],
      xprereqs: ['cs.I1.error-handling-debugging'],
      quiz: [
        { lvl: 2, type: 'mcq', prompt: 'Bugs most often hide in:', choices: ['edge cases', 'the middle of normal input', 'comments', 'variable names'], answer: 0, explanation: 'Empty, boundary and invalid inputs expose bugs.' },
        { lvl: 2, type: 'mcq', prompt: 'Automated tests help mainly by:', choices: ['catching regressions when code changes', 'making code shorter', 'removing the need for functions', 'formatting output'], answer: 0, explanation: 'They flag when a change breaks existing behaviour.' },
      ] },

    // ================= A2 =================
    { tier: 'A2', order: 1, slug: 'software-design', title: 'Software Design',
      summary: 'Requirements, decomposition, data modelling and interfaces.',
      outcomes: ['Gather requirements', 'Decompose a system', 'Design data models and interfaces'],
      concepts: [
        ['Design before code', 'Real software starts with understanding requirements, then decomposing the system into components with clear responsibilities and interfaces.'],
        ['Data modelling', 'Deciding how data is structured and how components talk (interfaces) shapes everything. Good design makes code easier to build, test and change.'],
      ],
      mistakes: ['Coding before understanding requirements.', 'Tangled components with unclear responsibilities.', 'Ignoring how the data is modelled.'],
      tricks: ['Clarify requirements first.', 'Give each component one clear responsibility.', 'Define interfaces between components early.'],
      memory: ['"Understand, then design, then code."', '"One responsibility per component."', 'Interfaces decouple parts.'],
      board: { CBSE: ['Cl.12 CS: Software Development'], ICSE: ['Cl.12 SDLC'], IB: ['DP CS: Design'] },
      comp: [], keywords: ['software design', 'requirements', 'decomposition', 'data model', 'interface'],
      xprereqs: ['cs.A1.oop'],
      quiz: [
        { lvl: 2, type: 'mcq', prompt: 'Software design should begin with:', choices: ['understanding requirements', 'writing all the code', 'choosing colours', 'deploying'], answer: 0, explanation: 'Requirements guide the whole design.' },
        { lvl: 2, type: 'mcq', prompt: 'A well-designed component has:', choices: ['one clear responsibility', 'many unrelated jobs', 'no interface', 'no data'], answer: 0, explanation: 'Single responsibility keeps systems maintainable.' },
      ] },
    { tier: 'A2', order: 2, slug: 'web-data-basics', title: 'Web & Data Basics',
      summary: 'A program that talks to the outside world (HTTP/API or a simple UI) and stores data.',
      outcomes: ['Make a basic web request or UI', 'Send and receive data', 'Store results'],
      concepts: [
        ['Talking to the world', 'Programs communicate over HTTP: requesting data from an API and receiving a response (often JSON). This connects your code to real services.'],
        ['Simple interfaces', 'A basic web page or UI lets users interact. Combined with storing data, this turns a script into a usable application.'],
      ],
      mistakes: ['Not handling failed network requests.', 'Ignoring the response status.', 'Storing data without validating it.'],
      tricks: ['Check the response status before using data.', 'APIs often return JSON — parse it into dicts.', 'Handle network errors gracefully.'],
      memory: ['"HTTP request → response (often JSON)."', '"Check status, handle failures."', 'Web + storage = an app.'],
      board: { CBSE: ['Cl.12 CS: Networking basics'], ICSE: ['Cl.12 Web'], IB: ['DP CS: Web'] },
      comp: [], keywords: ['web', 'HTTP', 'API', 'JSON', 'UI'],
      xprereqs: ['cs.I1.file-io-data-formats'],
      quiz: [
        { lvl: 2, type: 'mcq', prompt: 'Data returned from a web API is commonly formatted as:', choices: ['JSON', 'a C struct', 'a spreadsheet image', 'machine code'], answer: 0, explanation: 'JSON is the common web data format.' },
        { lvl: 2, type: 'mcq', prompt: 'Before using an API response you should:', choices: ['check the status/handle errors', 'assume it always works', 'ignore the data', 'delete it'], answer: 0, explanation: 'Network requests can fail; handle that.' },
      ] },
    { tier: 'A2', order: 3, slug: 'working-with-codebase', title: 'Working with a Codebase',
      summary: 'Reading unfamiliar code, git collaboration workflows, and code review.',
      outcomes: ['Read and navigate unfamiliar code', 'Use branch-based collaboration', 'Give and receive code review'],
      concepts: [
        ['Reading code', 'Most professional work is reading and modifying existing code, not writing from scratch. Skimming structure, following functions, and running it build understanding.'],
        ['Collaboration', 'Teams use branches, pull requests and code review to change code safely. Review catches bugs and shares knowledge — a social skill as much as technical.'],
      ],
      mistakes: ['Rewriting code instead of understanding it first.', 'Committing directly to main in a team.', 'Taking code-review feedback personally.'],
      tricks: ['Skim the structure before diving into details.', 'Use branches and pull requests for changes.', 'Review for correctness and clarity, kindly.'],
      memory: ['"Read before you change."', '"Branch, PR, review."', 'Review shares knowledge.'],
      board: { CBSE: ['Cl.12 CS: Collaboration'], ICSE: ['Cl.12 Teamwork'], IB: ['DP CS: Development'] },
      comp: [], keywords: ['codebase', 'code review', 'collaboration', 'pull request', 'git'],
      xprereqs: ['cs.F2.version-control-ii'],
      quiz: [
        { lvl: 2, type: 'mcq', prompt: 'Most professional programming time is spent:', choices: ['reading and modifying existing code', 'writing brand-new code', 'deleting files', 'formatting'], answer: 0, explanation: 'Understanding existing code dominates real work.' },
        { lvl: 2, type: 'mcq', prompt: 'Team changes are safely proposed via:', choices: ['a pull request and review', 'direct commits to main', 'emailing files', 'no process'], answer: 0, explanation: 'Pull requests enable review before merging.' },
      ] },
    { tier: 'A2', order: 4, slug: 'databases-intro', title: 'Databases Intro',
      summary: 'Relational modelling and basic SQL.',
      outcomes: ['Model data in tables', 'Write basic SQL queries', 'Understand keys and relationships'],
      concepts: [
        ['Relational model', 'A database stores data in tables (rows and columns) with keys linking related tables. This structures data far better than files for many applications.'],
        ['SQL', 'SQL queries data: SELECT to read, WHERE to filter, JOIN to combine tables. It is a declarative language — you say what you want, not how to get it.'],
      ],
      mistakes: ['Storing everything in one giant table.', 'Forgetting keys that link tables.', 'Confusing SQL (what) with imperative code (how).'],
      tricks: ['Split data into related tables with keys.', 'SELECT ... WHERE ... filters rows.', 'JOIN combines related tables.'],
      memory: ['"Tables + keys = relational."', '"SELECT reads, WHERE filters, JOIN combines."', 'SQL is declarative.'],
      board: { CBSE: ['Cl.12 CS: Databases & SQL'], ICSE: ['Cl.12 Databases'], IB: ['DP CS: Databases'] },
      comp: [], keywords: ['database', 'SQL', 'relational', 'tables', 'keys'],
      xprereqs: ['cs.I1.file-io-data-formats'],
      quiz: [
        { lvl: 1, type: 'mcq', prompt: 'Which SQL keyword reads data from a table?', choices: ['SELECT', 'DELETE', 'DROP', 'PRINT'], answer: 0, explanation: 'SELECT retrieves rows.' },
        { lvl: 2, type: 'mcq', prompt: 'Related tables in a relational database are linked by:', choices: ['keys', 'colours', 'comments', 'file names'], answer: 0, explanation: 'Primary and foreign keys connect tables.' },
      ] },
    { tier: 'A2', order: 5, slug: 'capstone-project', title: 'Capstone Project', core: true,
      summary: 'An independently designed, built, tested and version-controlled software project — the graduation bar.',
      outcomes: ['Design and build a real project', 'Test and document it', 'Version-control and present it'],
      concepts: [
        ['The graduation project', 'The capstone is a real, useful piece of software you design, build, test and document yourself — the direct proof of the program\'s goal: you can build, not just pass tests.'],
        ['End to end', 'It brings together design, data, code, testing, git and a clear README. Presenting it demonstrates genuine, independent capability.'],
      ],
      mistakes: ['Scoping too big to finish.', 'Skipping tests and documentation.', 'Not using version control throughout.'],
      tricks: ['Scope small enough to finish and polish.', 'Test and document as you build.', 'Commit throughout and write a clear README.'],
      memory: ['"Design, build, test, document, ship."', '"Scope to finish."', 'The capstone proves you can build.'],
      board: { CBSE: ['Cl.12 CS: Practical Project'], ICSE: ['Cl.12 Project'], IB: ['DP CS: Internal Assessment'] },
      comp: [], keywords: ['capstone', 'project', 'software', 'testing', 'README'],
      xprereqs: ['cs.A2.software-design'],
      quiz: [
        { lvl: 2, type: 'mcq', prompt: 'The capstone project mainly demonstrates that you can:', choices: ['independently build real software', 'memorise syntax', 'pass a written test', 'avoid coding'], answer: 0, explanation: 'It is the proof of independent building ability.' },
        { lvl: 2, type: 'mcq', prompt: 'A finished capstone should include tests and:', choices: ['clear documentation (README)', 'no version history', 'one giant file', 'no structure'], answer: 0, explanation: 'Documentation and version control are part of real software.' },
      ] },
  ],
};
