// English — full curriculum dataset. Above-standard: reading, reasoning, writing.
export default {
  subject: 'english',
  topics: [
    // ================= F1 =================
    { tier: 'F1', order: 1, slug: 'reading-for-meaning', title: 'Reading for Meaning',
      summary: 'Finding the main idea, making inferences, and telling fact from opinion.',
      outcomes: ['Identify the main idea and supporting details', 'Make inferences from a text', 'Distinguish fact from opinion'],
      concepts: [
        ['Main idea and inference', 'Every text has a central point supported by details. Inference means reading between the lines — drawing conclusions the text implies but does not state outright.'],
        ['Fact vs opinion', 'Facts can be checked; opinions express a viewpoint. Separating them is the first step toward critical reading and, later, evaluating arguments.'],
      ],
      mistakes: ['Confusing a supporting detail with the main idea.', 'Treating an inference as a wild guess rather than an evidence-based conclusion.', 'Accepting opinions as facts.'],
      tricks: ['Ask "what is this mostly about?" to find the main idea.', 'Support every inference with a phrase from the text.', 'Test a statement: can it be proven? Then it is a fact.'],
      memory: ['"Main idea = what it is mostly about."', '"Inference = evidence + reasoning."', 'Facts check out; opinions are views.'],
      board: { CBSE: ['Cl.6-8 Reading Comprehension'], ICSE: ['Cl.6-8 Comprehension'], IB: ['MYP Language & Literature'] },
      comp: [], keywords: ['reading', 'main idea', 'inference', 'fact', 'opinion', 'comprehension'],
      quiz: [
        { lvl: 1, type: 'mcq', prompt: 'Which statement is a fact rather than an opinion?', choices: ['Water boils at 100°C at sea level.', 'Summer is the best season.', 'This book is boring.', 'Blue is a calming colour.'], answer: 0, explanation: 'A fact can be verified; the others express viewpoints.' },
        { lvl: 2, type: 'mcq', prompt: 'Making an inference means:', choices: ['drawing a conclusion the text implies', 'copying a sentence', 'guessing with no basis', 'summarising every line'], answer: 0, explanation: 'Inference uses textual evidence plus reasoning.' },
      ] },
    { tier: 'F1', order: 2, slug: 'vocabulary-roots', title: 'Vocabulary by Roots',
      summary: 'Building vocabulary through Greek and Latin roots, prefixes and suffixes.',
      outcomes: ['Decode words using roots and affixes', 'Infer meaning of unfamiliar words', 'Build word families'],
      concepts: [
        ['Words have parts', 'Many English words are built from Greek/Latin roots plus prefixes and suffixes. Knowing "bio" (life) and "logy" (study) unlocks "biology" and dozens more — vocabulary that compounds.'],
        ['Inferring meaning', 'Faced with an unknown word, breaking it into known parts often reveals the meaning without a dictionary — a far more powerful strategy than memorising lists.'],
      ],
      mistakes: ['Memorising words one at a time instead of by root.', 'Ignoring prefixes that flip meaning (un-, dis-).', 'Assuming a root always means exactly one thing.'],
      tricks: ['Learn a root and get a whole family of words.', 'Watch prefixes: "un-", "in-", "dis-" often negate.', 'Break a hard word into parts before guessing.'],
      memory: ['"Roots multiply vocabulary."', '"Prefix can flip the meaning."', 'Decode by parts, not by memory.'],
      board: { CBSE: ['Cl.6-8 Vocabulary'], ICSE: ['Cl.6-8 Word Power'], IB: ['MYP Language'] },
      comp: [], keywords: ['vocabulary', 'roots', 'prefix', 'suffix', 'etymology'],
      quiz: [
        { lvl: 1, type: 'mcq', prompt: 'The root "aqua" means:', choices: ['water', 'fire', 'earth', 'air'], answer: 0, explanation: '"Aqua" gives aquarium, aquatic, aqueduct.' },
        { lvl: 2, type: 'mcq', prompt: 'The prefix "un-" in "unhappy" does what to the meaning?', choices: ['reverses it', 'strengthens it', 'has no effect', 'makes it plural'], answer: 0, explanation: 'It negates: not happy.' },
      ] },
    { tier: 'F1', order: 3, slug: 'sentence-craft', title: 'Sentence Craft',
      summary: 'Grammar as a tool for clarity: sentence types and combining sentences well.',
      outcomes: ['Identify sentence types', 'Combine sentences for flow', 'Use grammar for clarity'],
      concepts: [
        ['Sentences as tools', 'A sentence expresses a complete thought. Varying simple, compound and complex sentences controls rhythm and clarity — grammar serves meaning, not the other way round.'],
        ['Combining sentences', 'Joining short, choppy sentences with conjunctions creates flow and shows how ideas relate (cause, contrast, sequence).'],
      ],
      mistakes: ['Writing run-on sentences with no punctuation.', 'Overusing short, choppy sentences.', 'Treating grammar rules as ends in themselves.'],
      tricks: ['Combine short sentences with because, but, so, and.', 'Vary sentence length for rhythm.', 'Every sentence needs a subject and a verb.'],
      memory: ['"Grammar serves clarity."', '"Combine to show how ideas relate."', 'Subject + verb = complete thought.'],
      board: { CBSE: ['Cl.6-8 Grammar'], ICSE: ['Cl.6-8 Grammar'], IB: ['MYP Language'] },
      comp: [], keywords: ['grammar', 'sentences', 'clauses', 'conjunctions', 'clarity'],
      quiz: [
        { lvl: 1, type: 'mcq', prompt: 'Which joins two ideas to show contrast?', choices: ['but', 'and', 'so', 'because'], answer: 0, explanation: '"But" signals contrast between ideas.' },
        { lvl: 2, type: 'mcq', prompt: 'A complete sentence must contain a subject and a:', choices: ['verb', 'noun only', 'adjective', 'comma'], answer: 0, explanation: 'Subject + verb express a complete thought.' },
      ] },
    { tier: 'F1', order: 4, slug: 'paragraph-architecture', title: 'Paragraph Architecture',
      summary: 'Building coherent paragraphs: topic sentence, support and coherence.',
      outcomes: ['Write a clear topic sentence', 'Support it with details', 'Achieve coherence and flow'],
      concepts: [
        ['Paragraph structure', 'A paragraph makes one point: a topic sentence states it, supporting sentences develop it with evidence or detail, and a closing sentence rounds it off.'],
        ['Coherence', 'Linking words (however, therefore, for example) guide the reader through the logic. Coherent paragraphs are the building blocks of every essay.'],
      ],
      mistakes: ['Cramming several ideas into one paragraph.', 'Omitting the topic sentence.', 'Jumping between ideas without linking words.'],
      tricks: ['One paragraph = one main idea.', 'Start with the topic sentence, then support it.', 'Use linking words to guide the reader.'],
      memory: ['"One paragraph, one idea."', '"Topic sentence leads."', 'Linking words carry the logic.'],
      board: { CBSE: ['Cl.6-8 Writing'], ICSE: ['Cl.6-8 Composition'], IB: ['MYP Writing'] },
      comp: [], keywords: ['paragraph', 'topic sentence', 'coherence', 'writing'],
      quiz: [
        { lvl: 1, type: 'mcq', prompt: 'The sentence that states a paragraph\'s main point is the:', choices: ['topic sentence', 'last sentence always', 'longest sentence', 'question'], answer: 0, explanation: 'The topic sentence announces the paragraph\'s idea.' },
        { lvl: 2, type: 'mcq', prompt: 'A well-built paragraph focuses on:', choices: ['one main idea', 'as many ideas as possible', 'no clear idea', 'only questions'], answer: 0, explanation: 'One idea per paragraph keeps writing clear.' },
      ] },
    { tier: 'F1', order: 5, slug: 'narrative-descriptive-writing', title: 'Narrative & Descriptive Writing',
      summary: 'Telling a story and painting a scene with vivid, purposeful detail.',
      outcomes: ['Structure a narrative', 'Use sensory description', 'Show rather than tell'],
      concepts: [
        ['Story shape', 'Narratives have a beginning, rising action, climax and resolution. Structure keeps a reader engaged and gives events meaning.'],
        ['Show, don\'t tell', 'Vivid, sensory detail lets readers experience a scene rather than being told about it. "Her hands trembled" beats "she was nervous".'],
      ],
      mistakes: ['Telling emotions instead of showing them.', 'Piling on detail with no purpose.', 'Neglecting narrative structure.'],
      tricks: ['Show feelings through action and sensory detail.', 'Choose details that serve the mood or point.', 'Give a story a clear beginning, middle and end.'],
      memory: ['"Show, don\'t tell."', '"Purposeful detail only."', 'Story = setup, climax, resolution.'],
      board: { CBSE: ['Cl.6-8 Creative Writing'], ICSE: ['Cl.6-8 Composition'], IB: ['MYP Creative Writing'] },
      comp: [], keywords: ['narrative', 'descriptive', 'show not tell', 'sensory detail', 'writing'],
      quiz: [
        { lvl: 2, type: 'mcq', prompt: 'Which "shows" rather than "tells"?', choices: ['Her hands trembled as she opened the letter.', 'She was very nervous.', 'It was a nervous moment.', 'She felt nervous inside.'], answer: 0, explanation: 'Sensory action lets the reader infer the emotion.' },
        { lvl: 1, type: 'mcq', prompt: 'A narrative\'s turning point of highest tension is the:', choices: ['climax', 'introduction', 'setting', 'title'], answer: 0, explanation: 'The climax is the peak of the story\'s tension.' },
      ] },

    // ================= F2 =================
    { tier: 'F2', order: 1, slug: 'close-reading', title: 'Close Reading of Prose & Poetry',
      summary: 'Analysing figurative language, tone and structure in texts.',
      outcomes: ['Identify figurative language', 'Analyse tone and mood', 'Explain how structure shapes meaning'],
      concepts: [
        ['Figurative language', 'Metaphor, simile, personification and imagery carry meaning beyond the literal. Naming and interpreting them is the core of literary analysis.'],
        ['Tone and structure', 'Tone is the writer\'s attitude; structure is how a text is organised. Both shape how a reader feels and understands — details are chosen, not accidental.'],
      ],
      mistakes: ['Spotting a device without explaining its effect.', 'Confusing tone (attitude) with mood (reader\'s feeling).', 'Ignoring structure\'s role in meaning.'],
      tricks: ['Always link a device to its effect on the reader.', 'Ask "what attitude does the writer take?" for tone.', 'Notice how structure (stanzas, paragraphs) shapes meaning.'],
      memory: ['"Name the device, explain the effect."', '"Tone = writer\'s attitude."', 'Structure is a choice that carries meaning.'],
      board: { CBSE: ['Cl.8-9 Literature'], ICSE: ['Cl.8-9 Literature'], IB: ['MYP Language & Literature'] },
      comp: [], keywords: ['close reading', 'figurative language', 'tone', 'imagery', 'poetry'],
      quiz: [
        { lvl: 1, type: 'mcq', prompt: '"The wind whispered" is an example of:', choices: ['personification', 'simile', 'hyperbole', 'alliteration'], answer: 0, explanation: 'Giving human traits (whispering) to wind is personification.' },
        { lvl: 2, type: 'mcq', prompt: 'A good analysis of a device also explains its:', choices: ['effect on the reader', 'spelling', 'word count', 'font'], answer: 0, explanation: 'Naming is not enough — explain the effect.' },
      ] },
    { tier: 'F2', order: 2, slug: 'structured-exposition', title: 'Structured Exposition',
      summary: 'Writing the multi-paragraph explanatory essay.',
      outcomes: ['Plan a multi-paragraph essay', 'Write clear body paragraphs', 'Introduce and conclude effectively'],
      concepts: [
        ['Essay structure', 'An explanatory essay opens with a thesis, develops it in body paragraphs (each one point), and closes by drawing the threads together — a scalable structure for any topic.'],
        ['Unity and flow', 'Every paragraph serves the thesis; transitions connect them. This is paragraph architecture applied at essay scale.'],
      ],
      mistakes: ['Writing without a clear thesis.', 'Letting paragraphs drift off-topic.', 'Ending abruptly with no conclusion.'],
      tricks: ['State your thesis in the introduction.', 'One clear point per body paragraph, tied to the thesis.', 'Use transitions to link paragraphs.'],
      memory: ['"Thesis, body, conclusion."', '"Every paragraph serves the thesis."', 'Transitions carry the reader.'],
      board: { CBSE: ['Cl.8-9 Writing'], ICSE: ['Cl.8-9 Composition'], IB: ['MYP Writing'] },
      comp: [], keywords: ['essay', 'exposition', 'thesis', 'structure', 'writing'],
      quiz: [
        { lvl: 1, type: 'mcq', prompt: 'The main claim an essay develops is its:', choices: ['thesis', 'title', 'quotation', 'footnote'], answer: 0, explanation: 'The thesis states the essay\'s central point.' },
        { lvl: 2, type: 'mcq', prompt: 'Each body paragraph should:', choices: ['develop one point supporting the thesis', 'introduce a new unrelated topic', 'repeat the introduction', 'contain only a quotation'], answer: 0, explanation: 'One point per paragraph, all serving the thesis.' },
      ] },
    { tier: 'F2', order: 3, slug: 'summarising-paraphrasing', title: 'Summarising & Paraphrasing',
      summary: 'Compressing and restating ideas precisely — a skill that serves every subject.',
      outcomes: ['Write accurate summaries', 'Paraphrase without changing meaning', 'Distinguish summary from paraphrase'],
      concepts: [
        ['Precise compression', 'A summary captures the key ideas of a text in far fewer words. Doing it well means separating the essential from the incidental — the same skill as taking good notes in science.'],
        ['Paraphrasing', 'Paraphrasing restates an idea in your own words at similar length, preserving meaning. It shows understanding and avoids plagiarism.'],
      ],
      mistakes: ['Copying phrases when paraphrasing.', 'Adding your own opinions into a summary.', 'Losing the main idea while trimming detail.'],
      tricks: ['Summarise by keeping only the main ideas.', 'Paraphrase by rebuilding the sentence in your own words.', 'Check your version still means the same thing.'],
      memory: ['"Summary = shorter; paraphrase = restated."', '"Keep meaning, change words."', 'No opinions in a summary.'],
      board: { CBSE: ['Cl.8-9 Comprehension & Note-making'], ICSE: ['Cl.8-9 Précis'], IB: ['MYP Language'] },
      comp: [], keywords: ['summary', 'paraphrase', 'précis', 'note-making'],
      quiz: [
        { lvl: 2, type: 'mcq', prompt: 'A summary differs from a paraphrase mainly in that it is:', choices: ['much shorter', 'longer', 'word-for-word', 'an opinion'], answer: 0, explanation: 'Summaries compress; paraphrases restate at similar length.' },
        { lvl: 2, type: 'mcq', prompt: 'When paraphrasing you must:', choices: ['keep the original meaning', 'add your opinion', 'copy key phrases', 'change the facts'], answer: 0, explanation: 'Paraphrasing preserves meaning in new words.' },
      ] },
    { tier: 'F2', order: 4, slug: 'grammar-for-style', title: 'Grammar for Style',
      summary: 'Clauses, punctuation for effect, and controlling active and passive voice.',
      outcomes: ['Use clauses to vary sentences', 'Punctuate for effect', 'Choose active or passive voice deliberately'],
      concepts: [
        ['Punctuation as control', 'Commas, semicolons and dashes control pace and clarity. Used well, punctuation shapes how a sentence is read, not just whether it is "correct".'],
        ['Active vs passive', 'Active voice ("the dog chased the ball") is usually clearer and more direct; passive ("the ball was chased") suits when the doer is unknown or unimportant.'],
      ],
      mistakes: ['Overusing the passive voice, weakening prose.', 'Comma splices joining full sentences with just a comma.', 'Punctuating by guesswork rather than for effect.'],
      tricks: ['Prefer active voice for directness.', 'Use a semicolon to link two closely related full sentences.', 'A dash adds emphasis or an aside.'],
      memory: ['"Active is direct; passive hides the doer."', '"Semicolon links two full sentences."', 'Punctuation controls pace.'],
      board: { CBSE: ['Cl.8-10 Grammar'], ICSE: ['Cl.8-10 Grammar'], IB: ['MYP Language'] },
      comp: [], keywords: ['grammar', 'punctuation', 'active voice', 'passive voice', 'style'],
      quiz: [
        { lvl: 2, type: 'mcq', prompt: 'Which sentence is in the active voice?', choices: ['The chef cooked the meal.', 'The meal was cooked by the chef.', 'The meal had been cooked.', 'Cooking was done.'], answer: 0, explanation: 'The subject (chef) performs the action.' },
        { lvl: 2, type: 'mcq', prompt: 'A semicolon is best used to:', choices: ['link two closely related complete sentences', 'end every sentence', 'replace all commas', 'start a paragraph'], answer: 0, explanation: 'It joins related independent clauses.' },
      ] },
    { tier: 'F2', order: 5, slug: 'vocabulary-ii', title: 'Vocabulary II',
      summary: 'Connotation, register and academic word choice.',
      outcomes: ['Distinguish denotation and connotation', 'Match register to context', 'Use academic vocabulary'],
      concepts: [
        ['Connotation', 'Words carry emotional colour beyond their dictionary meaning: "thrifty" and "stingy" both mean careful with money, but feel very different. Choosing connotation shapes tone.'],
        ['Register', 'Register is the level of formality. Academic and casual contexts demand different words; matching register makes writing appropriate and persuasive.'],
      ],
      mistakes: ['Ignoring a word\'s connotation.', 'Using slang in formal writing (or vice versa).', 'Treating synonyms as perfectly interchangeable.'],
      tricks: ['Check a synonym\'s connotation before swapping it in.', 'Match formality to your audience and purpose.', 'Prefer precise academic words in formal writing.'],
      memory: ['"Synonyms differ in connotation."', '"Match register to audience."', 'Word colour shapes tone.'],
      board: { CBSE: ['Cl.9-10 Vocabulary'], ICSE: ['Cl.9-10 Word Power'], IB: ['MYP Language'] },
      comp: [], keywords: ['connotation', 'denotation', 'register', 'academic vocabulary'],
      quiz: [
        { lvl: 2, type: 'mcq', prompt: 'Which word has a negative connotation?', choices: ['stingy', 'thrifty', 'careful', 'economical'], answer: 0, explanation: 'All mean careful with money, but "stingy" is negative.' },
        { lvl: 1, type: 'mcq', prompt: 'Register refers to a text\'s level of:', choices: ['formality', 'length', 'font size', 'colour'], answer: 0, explanation: 'Register is how formal or casual the language is.' },
      ] },

    // ================= I1 =================
    { tier: 'I1', order: 1, slug: 'argument-i', title: 'Argument I',
      summary: 'Claim, evidence and warrant — recognising the structure of arguments.',
      outcomes: ['Identify claim, evidence and warrant', 'Analyse an argument\'s structure', 'Evaluate whether evidence supports a claim'],
      concepts: [
        ['The parts of an argument', 'An argument makes a claim, backs it with evidence, and connects the two with a warrant (the reasoning). Naming these parts lets you analyse any argument.'],
        ['Evaluating support', 'Good arguments have relevant, sufficient evidence and sound reasoning. Spotting weak links is the core of critical thinking — and of science data-literacy.'],
      ],
      mistakes: ['Confusing a claim with evidence.', 'Ignoring the warrant (the unstated reasoning).', 'Accepting evidence without checking relevance.'],
      tricks: ['Break an argument into claim + evidence + warrant.', 'Ask "does this evidence actually support the claim?"', 'Look for the unstated assumption (warrant).'],
      memory: ['"Claim, evidence, warrant."', '"Evidence must be relevant and sufficient."', 'Find the hidden assumption.'],
      board: { CBSE: ['Cl.9-10 Reading & Reasoning'], ICSE: ['Cl.9-10 Comprehension'], IB: ['MYP/DP Language'] },
      comp: [], keywords: ['argument', 'claim', 'evidence', 'warrant', 'reasoning'],
      quiz: [
        { lvl: 2, type: 'mcq', prompt: 'The reasoning linking evidence to a claim is the:', choices: ['warrant', 'conclusion', 'title', 'quotation'], answer: 0, explanation: 'The warrant connects evidence to the claim.' },
        { lvl: 2, type: 'mcq', prompt: 'Strong evidence must be:', choices: ['relevant and sufficient', 'long', 'emotional', 'famous'], answer: 0, explanation: 'It must actually and adequately support the claim.' },
      ] },
    { tier: 'I1', order: 2, slug: 'persuasive-essay', title: 'The Persuasive / Argumentative Essay',
      summary: 'Writing an essay that argues a position with evidence and reasoning.',
      outcomes: ['Build a persuasive thesis', 'Support with evidence and reasoning', 'Structure a convincing argument'],
      concepts: [
        ['Arguable thesis', 'A persuasive essay takes a clear, arguable position — one a reasonable person could dispute — and defends it with evidence and logic.'],
        ['Building the case', 'Each paragraph advances one reason, supported and explained. The strongest essays anticipate the reader\'s doubts (setting up counterargument, next).'],
      ],
      mistakes: ['Choosing a thesis nobody would dispute.', 'Asserting without evidence.', 'Ignoring the reader\'s likely objections.'],
      tricks: ['Pick a genuinely arguable thesis.', 'Give each reason its own supported paragraph.', 'Explain why the evidence proves your point.'],
      memory: ['"Thesis must be arguable."', '"Reason + evidence + explanation."', 'Anticipate objections.'],
      board: { CBSE: ['Cl.9-10 Writing'], ICSE: ['Cl.9-10 Composition'], IB: ['DP Written Tasks'] },
      comp: [], keywords: ['persuasive essay', 'argument', 'thesis', 'evidence'],
      quiz: [
        { lvl: 2, type: 'mcq', prompt: 'A good persuasive thesis is:', choices: ['arguable — someone could disagree', 'an obvious fact', 'a question', 'a definition'], answer: 0, explanation: 'Persuasion requires a debatable position.' },
        { lvl: 1, type: 'mcq', prompt: 'Each paragraph of an argument essay should:', choices: ['advance one supported reason', 'list many unrelated facts', 'restate the intro', 'ask questions only'], answer: 0, explanation: 'One reason per paragraph, backed by evidence.' },
      ] },
    { tier: 'I1', order: 3, slug: 'analysing-nonfiction-media', title: 'Analysing Non-Fiction & Media',
      summary: 'Rhetoric, bias and source evaluation — critical reading of real-world texts.',
      outcomes: ['Identify rhetorical techniques', 'Detect bias', 'Evaluate source reliability'],
      concepts: [
        ['Rhetoric', 'Writers persuade using appeals to logic (logos), emotion (pathos) and credibility (ethos). Recognising these reveals how a text tries to move you.'],
        ['Bias and reliability', 'Every source has a perspective; evaluating who wrote it, why, and with what evidence separates trustworthy information from spin — essential for science and citizenship.'],
      ],
      mistakes: ['Missing emotional manipulation (pathos).', 'Treating all sources as equally reliable.', 'Confusing bias with simply having a viewpoint.'],
      tricks: ['Spot logos, pathos, ethos in persuasive texts.', 'Ask who wrote it and why to judge bias.', 'Check the evidence behind a claim.'],
      memory: ['"Logos, pathos, ethos."', '"Who wrote it, and why?"', 'Evidence reveals reliability.'],
      board: { CBSE: ['Cl.9-10 Media Literacy'], ICSE: ['Cl.9-10 Comprehension'], IB: ['DP Language & Media'] },
      comp: [], keywords: ['rhetoric', 'bias', 'media', 'source evaluation', 'ethos pathos logos'],
      quiz: [
        { lvl: 2, type: 'mcq', prompt: 'An appeal to the reader\'s emotions is called:', choices: ['pathos', 'logos', 'ethos', 'syntax'], answer: 0, explanation: 'Pathos is the emotional appeal.' },
        { lvl: 2, type: 'mcq', prompt: 'To judge a source\'s reliability, first ask:', choices: ['who wrote it and why', 'how long it is', 'what font it uses', 'if it is popular'], answer: 0, explanation: 'Author and purpose reveal potential bias.' },
      ] },
    { tier: 'I1', order: 4, slug: 'literature-i', title: 'Literature I',
      summary: 'Short stories and drama: analysing theme and character.',
      outcomes: ['Analyse theme', 'Trace character development', 'Support analysis with textual evidence'],
      concepts: [
        ['Theme', 'A theme is the underlying idea a story explores (justice, growing up). It is inferred from events and characters, not stated outright.'],
        ['Character', 'Characters reveal themselves through actions, words and change over the story. Strong analysis quotes the text to support each claim.'],
      ],
      mistakes: ['Confusing plot (what happens) with theme (what it means).', 'Making claims about character without textual evidence.', 'Stating a theme as a single word rather than an idea.'],
      tricks: ['State theme as a full idea, not one word.', 'Track how a character changes to reveal theme.', 'Quote the text to support every point.'],
      memory: ['"Plot is events; theme is meaning."', '"Support with quotations."', 'Character change reveals theme.'],
      board: { CBSE: ['Cl.9-10 Literature'], ICSE: ['Cl.9-10 Literature'], IB: ['MYP/DP Literature'] },
      comp: [], keywords: ['literature', 'theme', 'character', 'short story', 'drama'],
      quiz: [
        { lvl: 1, type: 'mcq', prompt: 'A story\'s underlying message or idea is its:', choices: ['theme', 'plot', 'setting', 'title'], answer: 0, explanation: 'Theme is the deeper meaning; plot is the events.' },
        { lvl: 2, type: 'mcq', prompt: 'A claim about a character should be supported with:', choices: ['textual evidence', 'personal opinion only', 'the page count', 'the author\'s age'], answer: 0, explanation: 'Analysis must be grounded in the text.' },
      ] },
    { tier: 'I1', order: 5, slug: 'research-citation', title: 'Research & Citation Basics',
      summary: 'Finding, evaluating and attributing sources honestly.',
      outcomes: ['Find and evaluate sources', 'Cite sources correctly', 'Avoid plagiarism'],
      concepts: [
        ['Finding good sources', 'Reliable research favours credible, current, evidence-based sources. Evaluating them reuses the source-evaluation skills from media analysis.'],
        ['Attribution', 'Citing sources credits others\' ideas and lets readers verify them. Failing to cite is plagiarism — an ethical and academic failure.'],
      ],
      mistakes: ['Using unreliable sources uncritically.', 'Copying without citing (plagiarism).', 'Citing inconsistently.'],
      tricks: ['Prefer credible, current, evidence-based sources.', 'Cite every idea that is not your own.', 'Keep track of sources as you research.'],
      memory: ['"Credible, current, evidence-based."', '"Cite what is not yours."', 'No citation = plagiarism.'],
      board: { CBSE: ['Cl.9-10 Project Work'], ICSE: ['Cl.9-10 Research'], IB: ['DP Extended Essay skills'] },
      comp: [], keywords: ['research', 'citation', 'sources', 'plagiarism', 'attribution'],
      quiz: [
        { lvl: 1, type: 'mcq', prompt: 'Using someone\'s ideas without citing them is:', choices: ['plagiarism', 'paraphrasing', 'summarising', 'quoting'], answer: 0, explanation: 'Uncredited use of others\' ideas is plagiarism.' },
        { lvl: 2, type: 'mcq', prompt: 'A reliable source is best judged by its:', choices: ['credibility and evidence', 'popularity', 'length', 'colour scheme'], answer: 0, explanation: 'Credibility and supporting evidence matter most.' },
      ] },

    // ================= I2 =================
    { tier: 'I2', order: 1, slug: 'argument-ii', title: 'Argument II',
      summary: 'Counterargument, rebuttal and spotting logical fallacies.',
      outcomes: ['Address counterarguments', 'Write effective rebuttals', 'Identify common fallacies'],
      concepts: [
        ['Counterargument and rebuttal', 'A strong argument acknowledges the other side (counterargument) and answers it (rebuttal). This makes a case more, not less, convincing.'],
        ['Fallacies', 'Fallacies are flawed reasoning patterns (ad hominem, straw man, false dilemma). Spotting them protects you from bad arguments and strengthens your own.'],
      ],
      mistakes: ['Ignoring counterarguments (weakening your case).', 'Attacking the person instead of the argument (ad hominem).', 'Misrepresenting an opponent (straw man).'],
      tricks: ['Raise and answer the strongest opposing point.', 'Name the fallacy to defeat a weak argument.', 'Attack ideas, not people.'],
      memory: ['"Acknowledge, then rebut."', '"Straw man misrepresents; ad hominem attacks the person."', 'Answering objections strengthens your case.'],
      board: { CBSE: ['Cl.11-12 Argumentative Writing'], ICSE: ['Cl.11-12 Argument'], IB: ['DP Argument'] },
      comp: [], keywords: ['counterargument', 'rebuttal', 'fallacy', 'logic', 'argument'],
      quiz: [
        { lvl: 2, type: 'mcq', prompt: 'Attacking your opponent personally instead of their argument is the ___ fallacy.', choices: ['ad hominem', 'straw man', 'false dilemma', 'slippery slope'], answer: 0, explanation: 'Ad hominem targets the person, not the reasoning.' },
        { lvl: 2, type: 'mcq', prompt: 'Addressing the opposing view in your essay:', choices: ['strengthens your argument', 'weakens it', 'is irrelevant', 'is dishonest'], answer: 0, explanation: 'Answering counterarguments makes your case more convincing.' },
      ] },
    { tier: 'I2', order: 2, slug: 'comparative-analysis', title: 'Comparative Analysis',
      summary: 'Synthesising and comparing multiple texts.',
      outcomes: ['Compare texts on shared aspects', 'Synthesise ideas across sources', 'Structure a comparative essay'],
      concepts: [
        ['Comparing meaningfully', 'Comparison examines how two texts treat a shared theme, technique or idea — noting both similarities and differences, not just listing features of each.'],
        ['Synthesis', 'Synthesis weaves sources together into a new, coherent understanding rather than summarising each in turn — a key academic skill.'],
      ],
      mistakes: ['Describing each text separately with no real comparison.', 'Comparing on trivial rather than meaningful points.', 'Listing instead of synthesising.'],
      tricks: ['Compare point-by-point, not text-by-text.', 'Choose a meaningful basis for comparison.', 'Weave sources together into one argument.'],
      memory: ['"Compare point-by-point."', '"Synthesise, don\'t summarise."', 'Similarities and differences both matter.'],
      board: { CBSE: ['Cl.11-12 Literature'], ICSE: ['Cl.11-12 Comparative Study'], IB: ['DP Comparative Study'] },
      comp: [], keywords: ['comparison', 'synthesis', 'analysis', 'texts'],
      quiz: [
        { lvl: 2, type: 'mcq', prompt: 'A strong comparative essay is organised:', choices: ['point-by-point across texts', 'one whole text then the other', 'randomly', 'by length'], answer: 0, explanation: 'Point-by-point forces genuine comparison.' },
        { lvl: 2, type: 'mcq', prompt: 'Synthesis means:', choices: ['combining sources into a new understanding', 'summarising each separately', 'copying one source', 'ignoring differences'], answer: 0, explanation: 'Synthesis integrates multiple sources.' },
      ] },
    { tier: 'I2', order: 3, slug: 'literature-ii', title: 'Literature II',
      summary: 'The novel: sustained analysis in an extended essay.',
      outcomes: ['Analyse a whole novel', 'Trace development across a text', 'Write an extended literary essay'],
      concepts: [
        ['Reading a whole work', 'Analysing a novel means tracing how theme, character and technique develop across hundreds of pages — sustaining an argument over length.'],
        ['The extended essay', 'A longer analytical essay demands a clear thesis, structured sections, and consistent evidence — scaling all earlier writing skills up.'],
      ],
      mistakes: ['Retelling the plot instead of analysing.', 'Losing the thesis over a long essay.', 'Using evidence from only one part of the novel.'],
      tricks: ['Track a theme across the whole novel.', 'Keep every section tied to the thesis.', 'Draw evidence from beginning, middle and end.'],
      memory: ['"Analyse, don\'t retell."', '"Thesis holds the long essay together."', 'Evidence from across the whole text.'],
      board: { CBSE: ['Cl.11-12 Literature'], ICSE: ['Cl.11-12 Novel Study'], IB: ['DP Literature'] },
      comp: [], keywords: ['novel', 'literary analysis', 'extended essay', 'theme'],
      quiz: [
        { lvl: 2, type: 'mcq', prompt: 'Literary analysis of a novel should focus on:', choices: ['how meaning is created', 'retelling the plot', 'the cover design', 'the author\'s income'], answer: 0, explanation: 'Analysis explains how the text makes meaning.' },
        { lvl: 2, type: 'mcq', prompt: 'Evidence in a novel essay should come from:', choices: ['across the whole book', 'only chapter one', 'the blurb', 'other novels'], answer: 0, explanation: 'Draw from the entire text to support claims.' },
      ] },
    { tier: 'I2', order: 4, slug: 'formal-technical-writing', title: 'Formal & Technical Writing',
      summary: 'Reports and lab-style write-ups — a skill shared with the science portfolios.',
      outcomes: ['Write clear formal reports', 'Structure technical documents', 'Write with precision and objectivity'],
      concepts: [
        ['Technical clarity', 'Reports and lab write-ups value precision and objectivity over flair: clear structure, defined terms, and exactly what was done and found. This directly serves science practicals.'],
        ['Structure', 'Formal documents use headings, logical order and concise language so a reader can find and trust information quickly.'],
      ],
      mistakes: ['Using vague or flowery language in technical writing.', 'Omitting method or results a reader needs.', 'Poor structure making information hard to find.'],
      tricks: ['Prefer precise, objective language.', 'Use headings and logical order.', 'State exactly what was done and found.'],
      memory: ['"Precision over flair."', '"Structure for the reader."', 'Report what was done and found.'],
      board: { CBSE: ['Cl.11-12 Report Writing'], ICSE: ['Cl.11-12 Formal Writing'], IB: ['DP Technical Writing'] },
      comp: [], keywords: ['report', 'technical writing', 'formal', 'objectivity'],
      quiz: [
        { lvl: 2, type: 'mcq', prompt: 'Technical writing values:', choices: ['precision and clarity', 'emotional language', 'ambiguity', 'rhyme'], answer: 0, explanation: 'Reports must be precise and objective.' },
        { lvl: 1, type: 'mcq', prompt: 'Formal reports typically use ___ to organise information.', choices: ['headings and logical order', 'random paragraphs', 'poetry', 'only questions'], answer: 0, explanation: 'Structure helps readers find information fast.' },
      ] },
    { tier: 'I2', order: 5, slug: 'public-speaking', title: 'Public Speaking & Structured Discussion',
      summary: 'Speaking clearly, listening well, and structuring a discussion or debate.',
      outcomes: ['Structure a spoken argument', 'Listen and respond constructively', 'Use delivery techniques'],
      concepts: [
        ['Structuring speech', 'A good talk has a clear opening, structured points and a memorable close — like an essay, but delivered. Signposting helps listeners follow.'],
        ['Discussion and delivery', 'Effective discussion means listening actively and responding to what was actually said. Delivery — pace, volume, eye contact — carries the message.'],
      ],
      mistakes: ['Reading a script in a monotone.', 'Not listening before responding.', 'No clear structure to the talk.'],
      tricks: ['Signpost your points ("first", "finally").', 'Listen and respond to the actual point made.', 'Vary pace and make eye contact.'],
      memory: ['"Open, structure, close."', '"Listen before you respond."', 'Delivery carries the message.'],
      board: { CBSE: ['Cl.11-12 Speaking & Listening'], ICSE: ['Cl.11-12 Oral'], IB: ['DP Oral'] },
      comp: [], keywords: ['public speaking', 'discussion', 'debate', 'delivery', 'listening'],
      quiz: [
        { lvl: 1, type: 'mcq', prompt: 'Signposting in a speech helps the audience to:', choices: ['follow the structure', 'fall asleep', 'ignore the point', 'read faster'], answer: 0, explanation: 'Signposts show where you are in the argument.' },
        { lvl: 2, type: 'mcq', prompt: 'Good discussion requires first:', choices: ['listening to the actual point', 'talking loudest', 'repeating yourself', 'changing the subject'], answer: 0, explanation: 'Respond to what was actually said.' },
      ] },

    // ================= A1 =================
    { tier: 'A1', order: 1, slug: 'rhetoric-style', title: 'Rhetoric & Style at Depth',
      summary: 'Voice, syntax variety and precision in advanced writing.',
      outcomes: ['Develop a distinctive voice', 'Vary syntax for effect', 'Write with precision'],
      concepts: [
        ['Voice and syntax', 'Mature writing has a recognisable voice, built from word choice and sentence rhythm. Deliberately varying sentence structure controls emphasis and pace.'],
        ['Precision', 'Precise word choice removes ambiguity and strengthens argument. Every word earns its place — the mark of advanced style.'],
      ],
      mistakes: ['Monotonous sentence structure.', 'Vague words where precise ones exist.', 'Style over substance — flourish without clarity.'],
      tricks: ['Vary sentence length and structure deliberately.', 'Replace vague words with precise ones.', 'Read aloud to hear your voice and rhythm.'],
      memory: ['"Vary syntax for emphasis."', '"Every word earns its place."', 'Voice is choice plus rhythm.'],
      board: { CBSE: ['Cl.11-12 Advanced Writing'], ICSE: ['Cl.11-12 Style'], IB: ['DP Language'] },
      comp: [], keywords: ['rhetoric', 'style', 'voice', 'syntax', 'precision'],
      quiz: [
        { lvl: 2, type: 'mcq', prompt: 'Varying sentence length in prose mainly affects:', choices: ['rhythm and emphasis', 'spelling', 'the topic', 'word count only'], answer: 0, explanation: 'Syntax variety controls pace and emphasis.' },
        { lvl: 2, type: 'mcq', prompt: 'Precise word choice serves to:', choices: ['remove ambiguity', 'lengthen the essay', 'impress with jargon', 'confuse readers'], answer: 0, explanation: 'Precision sharpens meaning.' },
      ] },
    { tier: 'A1', order: 2, slug: 'literary-criticism', title: 'Literary Criticism',
      summary: 'Critical lenses and close analysis of complex texts.',
      outcomes: ['Apply critical lenses', 'Analyse complex texts closely', 'Support interpretation with theory'],
      concepts: [
        ['Critical lenses', 'Different lenses (historical, feminist, psychological) reveal different meanings in a text. A lens is a deliberate perspective that focuses analysis.'],
        ['Close analysis', 'Sophisticated criticism combines a lens with close attention to language, structure and context, arguing an interpretation rather than asserting it.'],
      ],
      mistakes: ['Applying a lens mechanically without textual support.', 'Confusing interpretation with plot summary.', 'Ignoring context.'],
      tricks: ['Choose a lens that illuminates the text.', 'Ground every interpretation in the language of the text.', 'Consider historical and cultural context.'],
      memory: ['"A lens focuses analysis."', '"Argue interpretation, don\'t assert."', 'Context shapes meaning.'],
      board: { CBSE: ['Cl.11-12 Literature'], ICSE: ['Cl.11-12 Criticism'], IB: ['DP Literary Analysis'] },
      comp: [], keywords: ['literary criticism', 'critical lens', 'interpretation', 'analysis'],
      quiz: [
        { lvl: 2, type: 'mcq', prompt: 'A "critical lens" is:', choices: ['a perspective for interpreting a text', 'a summary tool', 'a grammar rule', 'a type of poem'], answer: 0, explanation: 'It is a deliberate interpretive perspective.' },
        { lvl: 2, type: 'mcq', prompt: 'Literary criticism should be:', choices: ['argued with textual evidence', 'pure plot summary', 'unsupported opinion', 'a word list'], answer: 0, explanation: 'Interpretation must be grounded in the text.' },
      ] },
    { tier: 'A1', order: 3, slug: 'research-paper', title: 'The Research Paper',
      summary: 'Thesis, literature synthesis and sustained argument across a long paper.',
      outcomes: ['Develop a research thesis', 'Synthesise a literature base', 'Sustain an argument at length'],
      concepts: [
        ['Research argument', 'A research paper argues an original thesis supported by evidence from multiple sources, synthesised rather than listed. It scales argument and synthesis to full length.'],
        ['Sustained structure', 'Long papers need a roadmap: sections that each advance the thesis, with citations throughout. This connects to any subject\'s capstone.'],
      ],
      mistakes: ['A thesis that merely reports rather than argues.', 'Stringing summaries together without synthesis.', 'Losing the argument\'s thread over length.'],
      tricks: ['Make the thesis argue, not just describe.', 'Synthesise sources into your own argument.', 'Outline sections that each serve the thesis.'],
      memory: ['"Argue an original thesis."', '"Synthesise, cite throughout."', 'Roadmap the structure.'],
      board: { CBSE: ['Cl.11-12 Research Writing'], ICSE: ['Cl.11-12 Project'], IB: ['DP Extended Essay'] },
      comp: [], keywords: ['research paper', 'thesis', 'synthesis', 'citation', 'argument'],
      quiz: [
        { lvl: 2, type: 'mcq', prompt: 'A research paper\'s thesis should:', choices: ['argue an original position', 'list facts only', 'summarise one source', 'ask a question'], answer: 0, explanation: 'It advances an arguable, evidence-backed claim.' },
        { lvl: 2, type: 'mcq', prompt: 'Handling multiple sources well means:', choices: ['synthesising them into your argument', 'summarising each in turn', 'quoting only one', 'ignoring disagreement'], answer: 0, explanation: 'Synthesis integrates sources into a coherent argument.' },
      ] },
    { tier: 'A1', order: 4, slug: 'persuasion-real-world', title: 'Persuasion in the Real World',
      summary: 'Proposals, op-eds and the ethics of evidence.',
      outcomes: ['Write proposals and op-eds', 'Adapt argument to audience', 'Use evidence ethically'],
      concepts: [
        ['Real-world persuasion', 'Op-eds and proposals persuade a specific audience to think or act. They combine argument with awareness of who is reading and what moves them.'],
        ['Ethics of evidence', 'Persuasion must not distort evidence. Cherry-picking or misrepresenting data is both unethical and, once exposed, unpersuasive.'],
      ],
      mistakes: ['Ignoring the specific audience.', 'Distorting or cherry-picking evidence.', 'Confusing persuasion with manipulation.'],
      tricks: ['Tailor the argument to the audience\'s values.', 'Use evidence honestly — it is more persuasive long-term.', 'Match format (op-ed, proposal) to purpose.'],
      memory: ['"Know your audience."', '"Honest evidence persuades longer."', 'Persuasion ≠ manipulation.'],
      board: { CBSE: ['Cl.11-12 Writing'], ICSE: ['Cl.11-12 Composition'], IB: ['DP Written Tasks'] },
      comp: [], keywords: ['persuasion', 'op-ed', 'proposal', 'audience', 'ethics'],
      quiz: [
        { lvl: 2, type: 'mcq', prompt: 'Effective real-world persuasion adapts to the:', choices: ['audience', 'author\'s mood', 'page colour', 'weather'], answer: 0, explanation: 'Persuasion targets a specific audience\'s values.' },
        { lvl: 2, type: 'mcq', prompt: 'Cherry-picking evidence is:', choices: ['unethical and ultimately unpersuasive', 'always convincing', 'good technique', 'required'], answer: 0, explanation: 'Distorting evidence undermines credibility.' },
      ] },

    // ================= A2 =================
    { tier: 'A2', order: 1, slug: 'advanced-literary-analysis', title: 'Advanced Literary Analysis',
      summary: 'Poetry, drama and the novel analysed at examination depth.',
      outcomes: ['Analyse across genres', 'Handle complex, layered texts', 'Write exam-level literary essays'],
      concepts: [
        ['Depth across genres', 'Advanced analysis reads poetry, drama and prose with equal rigour, attending to form-specific techniques (metre, staging, narration) and their effects.'],
        ['Layered meaning', 'Sophisticated texts carry multiple, sometimes conflicting meanings. Strong essays argue a nuanced reading supported by close evidence.'],
      ],
      mistakes: ['Applying prose techniques to poetry without adjustment.', 'Flattening layered texts to a single meaning.', 'Weak evidence for bold claims.'],
      tricks: ['Attend to form-specific devices per genre.', 'Argue a nuanced, defensible reading.', 'Match strong evidence to bold claims.'],
      memory: ['"Each genre has its own tools."', '"Layered texts, nuanced readings."', 'Bold claim needs strong evidence.'],
      board: { CBSE: ['Cl.12 Literature'], ICSE: ['Cl.12 Literature'], IB: ['DP Literature HL'] },
      comp: [], keywords: ['literary analysis', 'poetry', 'drama', 'novel', 'exam'],
      quiz: [
        { lvl: 2, type: 'mcq', prompt: 'Analysing poetry (vs prose) pays special attention to:', choices: ['form and metre', 'chapter length', 'page numbers', 'the blurb'], answer: 0, explanation: 'Poetry\'s form and sound are central to meaning.' },
        { lvl: 3, type: 'mcq', prompt: 'A sophisticated literary essay argues:', choices: ['a nuanced reading with evidence', 'one obvious meaning', 'the plot summary', 'personal preference'], answer: 0, explanation: 'It defends a nuanced interpretation.' },
      ] },
    { tier: 'A2', order: 2, slug: 'extended-essay', title: 'The Extended Essay / Independent Research Writing', core: true,
      summary: 'A sustained, sourced, argued piece — the writing capstone.',
      outcomes: ['Plan an independent research essay', 'Sustain a long argument', 'Cite and synthesise rigorously'],
      concepts: [
        ['Independent research', 'The extended essay is a self-directed investigation of a focused question, argued over thousands of words with rigorous sourcing — the culmination of every writing skill.'],
        ['Sustained argument', 'Holding one argument across a long piece demands planning, clear sections and disciplined citation. It mirrors the capstones in other subjects.'],
      ],
      mistakes: ['Choosing too broad a question.', 'Losing the argument across length.', 'Weak or inconsistent citation.'],
      tricks: ['Narrow to a focused research question.', 'Outline sections that each advance the argument.', 'Cite consistently and synthesise sources.'],
      memory: ['"Focused question, sustained argument."', '"Plan the sections."', 'Rigorous citation throughout.'],
      board: { CBSE: ['Cl.12 Research Project'], ICSE: ['Cl.12 Project'], IB: ['DP Extended Essay'] },
      comp: [], keywords: ['extended essay', 'research', 'sustained argument', 'capstone'],
      xprereqs: ['english.A1.research-paper'],
      quiz: [
        { lvl: 2, type: 'mcq', prompt: 'A strong extended-essay research question is:', choices: ['focused and answerable', 'as broad as possible', 'a yes/no trivia question', 'unrelated to sources'], answer: 0, explanation: 'A narrow, focused question can be argued in depth.' },
        { lvl: 2, type: 'mcq', prompt: 'Across a long essay, the key challenge is to:', choices: ['sustain one clear argument', 'change topic often', 'avoid citations', 'summarise everything'], answer: 0, explanation: 'Maintaining a coherent argument is the core skill.' },
      ] },
    { tier: 'A2', order: 3, slug: 'critical-reasoning-comprehension', title: 'Critical Reasoning & Comprehension (Exam Level)',
      summary: 'Dense unseen passages under time — serving aptitude sections of entrance exams.',
      outcomes: ['Read dense passages quickly and accurately', 'Answer inference questions under time', 'Evaluate arguments rapidly'],
      concepts: [
        ['Reading under pressure', 'Exam comprehension demands fast, accurate reading of unfamiliar dense text — finding the main idea, inferences and the author\'s stance quickly.'],
        ['Critical reasoning', 'Aptitude sections test evaluating arguments: spotting assumptions, conclusions and flaws under time. It applies all the argument skills at speed.'],
      ],
      mistakes: ['Reading every word slowly and running out of time.', 'Choosing answers not supported by the passage.', 'Missing the author\'s stance.'],
      tricks: ['Skim for structure, then read for the question.', 'Anchor every answer in the passage.', 'Identify the conclusion and assumptions fast.'],
      memory: ['"Skim structure, then target the question."', '"Answers must come from the passage."', 'Speed + accuracy together.'],
      board: { CBSE: ['Cl.12 Reading'], ICSE: ['Cl.12 Comprehension'], IB: ['DP Paper 1'] },
      comp: ['JEE-Main', 'NEET'], keywords: ['critical reasoning', 'comprehension', 'inference', 'aptitude', 'exam'],
      xprereqs: ['english.I2.argument-ii'],
      quiz: [
        { lvl: 3, type: 'mcq', prompt: 'Under time pressure, the best first step on a dense passage is to:', choices: ['skim for structure and main idea', 'read every word slowly', 'answer before reading', 'memorise the passage'], answer: 0, explanation: 'Skimming for structure orients you fast.' },
        { lvl: 2, type: 'mcq', prompt: 'A comprehension answer must be:', choices: ['supported by the passage', 'your personal opinion', 'from general knowledge', 'the longest option'], answer: 0, explanation: 'Answers must be grounded in the text.' },
      ] },
    { tier: 'A2', order: 4, slug: 'communication-portfolio', title: 'Communication Portfolio', core: true,
      summary: 'A body of polished writing across genres — the capstone strand.',
      outcomes: ['Produce polished writing in several genres', 'Reflect on and revise work', 'Demonstrate range and control'],
      concepts: [
        ['Range and control', 'The portfolio gathers a learner\'s best work across genres — narrative, argument, analysis, technical — showing versatility and command of the language.'],
        ['Revision', 'Polish comes from drafting and revising. Reflecting on feedback and revising deliberately is what turns competent writing into excellent writing.'],
      ],
      mistakes: ['Submitting first drafts as finished.', 'Showing only one genre.', 'Ignoring feedback in revision.'],
      tricks: ['Include varied genres to show range.', 'Revise deliberately using feedback.', 'Reflect on what each piece demonstrates.'],
      memory: ['"Range plus control."', '"Revision makes excellence."', 'Reflect, revise, polish.'],
      board: { CBSE: ['Cl.12 Portfolio'], ICSE: ['Cl.12 Portfolio'], IB: ['DP Portfolio'] },
      comp: [], keywords: ['portfolio', 'writing', 'revision', 'genres', 'capstone'],
      xprereqs: ['english.A2.extended-essay'],
      quiz: [
        { lvl: 1, type: 'mcq', prompt: 'A strong writing portfolio demonstrates:', choices: ['range across genres', 'one genre only', 'unrevised drafts', 'no structure'], answer: 0, explanation: 'It shows versatility and command.' },
        { lvl: 2, type: 'mcq', prompt: 'Excellent writing usually comes from:', choices: ['drafting and revising', 'a single quick draft', 'ignoring feedback', 'copying'], answer: 0, explanation: 'Deliberate revision produces polish.' },
      ] },
  ],
};
