// Mathematics — full curriculum dataset. Module-level content for every topic.
// The F1 flagship (ratio-proportion-percentage) is listed for ordering/linking
// only; its directory already exists and the generator skips it.
export default {
  subject: 'math',
  topics: [
    // ================= F1 =================
    { tier: 'F1', order: 1, slug: 'number-sense-estimation', title: 'Number Sense & Estimation',
      summary: 'Place value, negative numbers, orders of magnitude, mental math and the discipline of estimating before computing.',
      outcomes: ['Work fluently with negative numbers and place value', 'Estimate answers using rounding and orders of magnitude', 'Use mental-math strategies to compute quickly'],
      concepts: [
        ['The number line as one model', 'Every number — positive, negative, whole or decimal — lives at one point on the number line. Negatives are mirror images of positives across zero; adding moves right, subtracting moves left. Holding this single picture prevents most sign confusion.'],
        ['Estimation before calculation', 'Rounding each number to one significant figure gives a quick "ballpark" you can compare your exact answer against. If the exact answer is far from the estimate, you slipped a decimal or a sign — estimation is your error detector.'],
        ['Orders of magnitude', 'Thinking in powers of ten (is this in the tens, thousands, millions?) lets you reason about very large or small quantities without getting lost in digits.'],
      ],
      mistakes: ['Dropping or misplacing a minus sign when subtracting a larger number from a smaller one.', 'Confusing place value when adding decimals of different lengths — always align the decimal points.', 'Trusting a calculator answer that is off by a factor of 10 because you never estimated first.'],
      tricks: ['Round to one significant figure to sanity-check every answer.', 'Break awkward sums into friendly parts: 47 + 38 = (47 + 3) + 35 = 85.', 'To subtract, "add up" from the smaller to the larger number instead of borrowing.'],
      memory: ['"Left is less, right is more" — the number line orders everything.', '"Estimate first, compute second" — the habit that catches decimal slips.', 'Negatives are mirror images across zero; two mirrors (−(−x)) bring you back.'],
      board: { CBSE: ['Cl.6 Knowing Our Numbers', 'Cl.6 Integers'], ICSE: ['Cl.6 Number System'], IB: ['MYP Number'] },
      comp: [], keywords: ['place value', 'integers', 'estimation', 'mental math', 'orders of magnitude'],
      quiz: [
        { lvl: 1, type: 'numeric', prompt: 'Compute −7 + 3.', answer: -4, tolerance: 0, explanation: 'Start at −7, move 3 right → −4.' },
        { lvl: 2, type: 'mcq', prompt: 'Estimate 612 × 39 to one significant figure.', choices: ['~24000', '~2400', '~180000', '~6000'], answer: 0, explanation: '600 × 40 = 24000 — the right order of magnitude.' },
      ] },
    { tier: 'F1', order: 2, slug: 'fractions-decimals', title: 'Fractions & Decimals as One System',
      summary: 'Fractions, decimals and division are three views of the same idea — parts of a whole on the number line.',
      outcomes: ['Convert freely between fractions and decimals', 'Add, subtract, multiply and divide fractions', 'Place fractions and decimals correctly on the number line'],
      concepts: [
        ['A fraction is a division', 'The fraction a/b literally means a ÷ b. That is why 3/4 = 0.75 — dividing 3 by 4. Seeing fractions and decimals as the same number written two ways removes the sense that they are separate topics.'],
        ['Common denominators', 'You can only add or compare fractions once the pieces are the same size — a common denominator. Multiplying top and bottom by the same number renames a fraction without changing its value.'],
        ['Multiplying vs dividing', 'Multiplying fractions multiplies the parts (½ of ⅓ = ⅙). Dividing by a fraction multiplies by its reciprocal — "flip and multiply" — because dividing by ½ asks "how many halves fit?".'],
      ],
      mistakes: ['Adding fractions by adding numerators and denominators (1/2 + 1/3 ≠ 2/5).', 'Forgetting to find a common denominator before adding or comparing.', 'Confusing "divide by a fraction" with "divide the fraction" — you multiply by the reciprocal.'],
      tricks: ['To compare fractions quickly, cross-multiply: 3/4 vs 5/7 → 21 vs 20, so 3/4 is bigger.', '"Flip and multiply" turns any fraction division into a multiplication.', 'Simplify before multiplying to keep numbers small (cancel common factors first).'],
      memory: ['"Fraction bar = divide bar" — a/b is a ÷ b.', '"Same-size pieces to add" — common denominator first.', '"Keep–Change–Flip" for dividing fractions.'],
      board: { CBSE: ['Cl.6 Fractions', 'Cl.7 Fractions & Decimals'], ICSE: ['Cl.6-7 Fractions and Decimals'], IB: ['MYP Number'] },
      comp: [], keywords: ['fractions', 'decimals', 'common denominator', 'reciprocal'],
      quiz: [
        { lvl: 1, type: 'mcq', prompt: 'What is 1/2 + 1/3?', choices: ['2/5', '5/6', '1/6', '2/6'], answer: 1, explanation: 'Common denominator 6: 3/6 + 2/6 = 5/6.' },
        { lvl: 2, type: 'mcq', prompt: 'What is (3/4) ÷ (1/2)?', choices: ['3/8', '3/2', '1/2', '6'], answer: 1, explanation: 'Flip and multiply: 3/4 × 2/1 = 6/4 = 3/2.' },
      ] },
    { tier: 'F1', order: 3, slug: 'ratio-proportion-percentage', title: 'Ratio, Proportion & Percentage',
      summary: 'Flagship deep-dive topic (see full content).', outcomes: [], concepts: [], mistakes: [], tricks: [], memory: [], board: {}, comp: ['JEE-Main', 'NEET'], keywords: ['ratio'], quiz: [] },
    { tier: 'F1', order: 4, slug: 'algebra-generalized-arithmetic', title: 'Algebra as Generalized Arithmetic',
      summary: 'Variables are just numbers whose value we have not fixed yet; algebra is arithmetic with letters standing in for numbers.',
      outcomes: ['Write and evaluate algebraic expressions', 'Collect like terms and use the distributive law', 'Translate word statements into expressions'],
      concepts: [
        ['A variable is a placeholder', 'A letter like x simply holds a number we do not yet know. Every rule of arithmetic still applies — algebra generalizes it so one statement covers all numbers at once.'],
        ['Like terms and the distributive law', 'Only terms with the same variable part combine: 3x + 2x = 5x, but 3x + 2 stays as is. The distributive law a(b + c) = ab + ac is the engine for expanding and factoring.'],
      ],
      mistakes: ['Combining unlike terms, e.g. writing 3x + 2 = 5x.', 'Forgetting to distribute to every term: 2(x + 3) = 2x + 6, not 2x + 3.', 'Dropping the sign when moving a term across an equals sign.'],
      tricks: ['Replace the variable with a test number to check an expansion is correct.', 'Line up like terms in columns before adding long expressions.', 'Read 2(x+3) as "two lots of (x+3)" to remember to distribute.'],
      memory: ['"Same letters combine, different letters don\'t."', '"Distribute to everyone inside the bracket."', 'A variable is a box; whatever number is in the box, the rules hold.'],
      board: { CBSE: ['Cl.6 Algebra', 'Cl.7 Algebraic Expressions'], ICSE: ['Cl.6-7 Fundamental Concepts (Algebra)'], IB: ['MYP Algebra'] },
      comp: [], keywords: ['algebra', 'variable', 'like terms', 'distributive law', 'expressions'],
      quiz: [
        { lvl: 1, type: 'mcq', prompt: 'Simplify 3x + 2x + 4.', choices: ['9x', '5x + 4', '5x', '6x + 4'], answer: 1, explanation: 'Combine like terms 3x + 2x = 5x; the 4 stays: 5x + 4.' },
        { lvl: 2, type: 'mcq', prompt: 'Expand 2(x + 3).', choices: ['2x + 3', '2x + 6', 'x + 6', '2x + 5'], answer: 1, explanation: 'Distribute the 2 to both terms: 2x + 6.' },
      ] },
    { tier: 'F1', order: 5, slug: 'linear-equations-one-variable', title: 'Linear Equations in One Variable',
      summary: 'Solving equations by keeping both sides balanced, and using them to model word problems directly.',
      outcomes: ['Solve linear equations by inverse operations', 'Keep an equation balanced at every step', 'Model word problems with a single equation'],
      concepts: [
        ['The balance model', 'An equation is a balance: whatever you do to one side you must do to the other. Undo operations in reverse order (inverse of +, ×, etc.) to isolate the variable.'],
        ['From words to equations', 'Assign a letter to the unknown, translate each phrase into algebra, then solve. This replaces years of arithmetic-only guessing with one reliable method.'],
      ],
      mistakes: ['Doing an operation to one side only, breaking the balance.', 'Forgetting to apply an operation to every term on a side.', 'Sign errors when moving terms across the equals sign.'],
      tricks: ['Always substitute your answer back to check it satisfies the equation.', 'Clear fractions first by multiplying through by the denominator.', 'Get all variable terms on one side, all numbers on the other, in one deliberate move.'],
      memory: ['"Do unto one side as you do unto the other."', '"Undo in reverse order" to isolate x.', 'Check by substitution — the equation should balance.'],
      board: { CBSE: ['Cl.7 Simple Equations', 'Cl.8 Linear Equations in One Variable'], ICSE: ['Cl.7-8 Linear Equations'], IB: ['MYP Algebra'] },
      comp: ['JEE-Main'], keywords: ['linear equation', 'balance', 'solve', 'inverse operations'],
      quiz: [
        { lvl: 1, type: 'numeric', prompt: 'Solve 2x + 5 = 13. What is x?', answer: 4, tolerance: 0, explanation: 'Subtract 5: 2x = 8; divide by 2: x = 4.' },
        { lvl: 2, type: 'numeric', prompt: 'Solve 3(x − 2) = 9. What is x?', answer: 5, tolerance: 0, explanation: 'Divide by 3: x − 2 = 3; add 2: x = 5.' },
      ] },
    { tier: 'F1', order: 6, slug: 'geometry-angles-triangles', title: 'Geometry I: Angles, Triangles & Congruence',
      summary: 'Angle relationships, triangle properties and the reasoning behind congruence — with construction, deferring formal proof.',
      outcomes: ['Use angle relationships (on a line, around a point, in a triangle)', 'Classify triangles and use the angle-sum property', 'Recognise congruent triangles by SSS, SAS, ASA'],
      concepts: [
        ['Angles that add up', 'Angles on a straight line sum to 180°, around a point to 360°, and the three angles of any triangle to 180°. These few facts unlock most elementary angle problems.'],
        ['Congruence conditions', 'Two triangles are congruent (identical in shape and size) if they match by SSS, SAS, ASA or RHS. Congruence is the basis of geometric reasoning — equal parts justify equal conclusions.'],
      ],
      mistakes: ['Assuming a triangle\'s angles sum to something other than 180°.', 'Using AAA as a congruence test (it only gives similarity, not congruence).', 'Mislabelling corresponding vertices when writing a congruence statement.'],
      tricks: ['Mark equal angles and sides on the diagram before reasoning.', 'Look for angles on a line or vertically opposite angles to find unknowns fast.', 'Name congruent triangles in matching vertex order so corresponding parts line up.'],
      memory: ['"Triangle angles make a straight line" — they sum to 180°.', 'SSS, SAS, ASA, RHS — the four congruence keys.', 'Vertically opposite angles are always equal.'],
      board: { CBSE: ['Cl.6-7 Lines & Angles', 'Cl.7 Triangles', 'Cl.9 Congruence'], ICSE: ['Cl.6-8 Geometry'], IB: ['MYP Geometry'] },
      comp: [], keywords: ['angles', 'triangles', 'congruence', 'geometry'],
      quiz: [
        { lvl: 1, type: 'numeric', prompt: 'Two angles of a triangle are 50° and 60°. Find the third angle in degrees.', answer: 70, tolerance: 0, explanation: 'Angles sum to 180°: 180 − 50 − 60 = 70°.' },
        { lvl: 2, type: 'mcq', prompt: 'Which is NOT a valid congruence condition?', choices: ['SSS', 'SAS', 'AAA', 'ASA'], answer: 2, explanation: 'AAA gives similar (same shape) triangles, not necessarily congruent ones.' },
      ] },
    { tier: 'F1', order: 7, slug: 'data-graphs-i', title: 'Data & Graphs I',
      summary: 'Reading and drawing bar charts, pictographs and line graphs — and spotting misleading ones.',
      outcomes: ['Read and construct bar charts, pictographs and line graphs', 'Compute simple averages from data', 'Recognise misleading graphs'],
      concepts: [
        ['Graphs turn numbers into pictures', 'A well-chosen graph makes patterns visible at a glance. Bar charts compare categories; line graphs show change over time; pictographs scale a symbol to a quantity.'],
        ['Misleading graphs', 'A truncated axis or an inconsistent scale can exaggerate or hide a trend. Reading the axes first is the habit that protects you from being fooled — and this data-literacy feeds every science subject.'],
      ],
      mistakes: ['Ignoring the axis scale and misjudging the size of a change.', 'Reading a pictograph without checking what one symbol represents.', 'Confusing the mean with the mode or median.'],
      tricks: ['Always read the axis labels and scale before interpreting a graph.', 'For the mean, sum the values and divide by how many there are.', 'Check whether a value axis starts at zero — if not, differences look bigger than they are.'],
      memory: ['"Read the axes first."', '"Mean = total ÷ count."', 'A cut-off axis is a warning sign of a misleading graph.'],
      board: { CBSE: ['Cl.6-7 Data Handling'], ICSE: ['Cl.6-7 Data Handling'], IB: ['MYP Statistics'] },
      comp: [], keywords: ['data', 'graphs', 'bar chart', 'mean', 'statistics'],
      quiz: [
        { lvl: 1, type: 'numeric', prompt: 'Find the mean of 4, 8, 6, 2.', answer: 5, tolerance: 0, explanation: 'Total 20 ÷ 4 values = 5.' },
        { lvl: 2, type: 'mcq', prompt: 'A bar chart\'s value axis starts at 90 instead of 0. This can:', choices: ['make small differences look large', 'change the actual data', 'make the mean smaller', 'have no effect'], answer: 0, explanation: 'A truncated axis exaggerates differences — a classic misleading technique.' },
      ] },

    // ================= F2 =================
    { tier: 'F2', order: 1, slug: 'exponents-scientific-notation', title: 'Exponents & Scientific Notation',
      summary: 'Powers as repeated multiplication, the laws of exponents, and scientific notation for very large and small numbers.',
      outcomes: ['Apply the laws of exponents', 'Write numbers in scientific notation', 'Handle negative and zero exponents'],
      concepts: [
        ['Exponents count repeated multiplication', 'a^n means a multiplied by itself n times. The laws — a^m·a^n = a^(m+n), (a^m)^n = a^(mn), a^0 = 1 — all follow from just counting the factors.'],
        ['Scientific notation', 'Writing a number as (a value between 1 and 10) × 10^n makes huge and tiny quantities manageable — essential for chemistry (the mole) and physics (measurement).'],
      ],
      mistakes: ['Adding exponents when multiplying bases that differ (only same-base powers combine).', 'Thinking a^0 = 0 (it equals 1).', 'Misplacing the power of ten when converting to scientific notation.'],
      tricks: ['Same base, multiplying → add the exponents; dividing → subtract.', 'Count how many places the decimal moves to find the power of ten.', 'A negative exponent means "reciprocal": a^−n = 1/a^n.'],
      memory: ['"Multiply powers, add exponents."', '"Anything to the zero is one."', '"Negative exponent → flip it."'],
      board: { CBSE: ['Cl.7 Exponents & Powers', 'Cl.8 Exponents & Powers'], ICSE: ['Cl.7-8 Exponents'], IB: ['MYP Number'] },
      comp: ['JEE-Main', 'NEET'], keywords: ['exponents', 'powers', 'scientific notation', 'index laws'],
      quiz: [
        { lvl: 1, type: 'mcq', prompt: 'Simplify 2^3 × 2^4.', choices: ['2^7', '2^12', '4^7', '2^1'], answer: 0, explanation: 'Same base, add exponents: 2^(3+4) = 2^7.' },
        { lvl: 2, type: 'mcq', prompt: 'Write 45000 in scientific notation.', choices: ['4.5 × 10^3', '45 × 10^3', '4.5 × 10^4', '0.45 × 10^5'], answer: 2, explanation: 'Decimal moves 4 places: 4.5 × 10^4.' },
      ] },
    { tier: 'F2', order: 2, slug: 'linear-relationships-coordinate-plane', title: 'Linear Relationships & the Coordinate Plane',
      summary: 'The coordinate plane, and y = mx + c as the mathematics of a constant rate — the direct bridge from ratio thinking.',
      outcomes: ['Plot points and lines on the coordinate plane', 'Interpret slope as a rate and intercept as a starting value', 'Write the equation of a line from a graph'],
      concepts: [
        ['Slope is a rate', 'In y = mx + c, the slope m is "how much y changes per unit x" — exactly a rate. This is ratio/proportion made visual: a straight line is a constant rate of change.'],
        ['Intercept and reading lines', 'c is the value of y when x = 0 — the starting point. Together m and c fully describe a line, and every straight-line story (cost per item, distance per hour) fits this form.'],
      ],
      mistakes: ['Reading slope as rise over run backwards (it is Δy/Δx).', 'Confusing the x- and y-intercepts.', 'Mixing up the roles of m and c in y = mx + c.'],
      tricks: ['Slope = (change in y)/(change in x) between any two points on the line.', 'A steeper line means a bigger rate; a flat line means y does not change.', 'Set x = 0 for the y-intercept, y = 0 for the x-intercept.'],
      memory: ['"m is the rate, c is the start."', '"Rise over run" for slope.', 'y = mx + c is ratio thinking drawn as a line.'],
      board: { CBSE: ['Cl.8 Introduction to Graphs', 'Cl.9 Linear Equations in Two Variables'], ICSE: ['Cl.8-9 Coordinate Geometry'], IB: ['MYP Algebra'] },
      comp: ['JEE-Main'], keywords: ['coordinate plane', 'slope', 'linear', 'y = mx + c', 'rate'],
      xprereqs: ['math.F1.ratio-proportion-percentage'],
      quiz: [
        { lvl: 1, type: 'numeric', prompt: 'For y = 2x + 1, what is y when x = 3?', answer: 7, tolerance: 0, explanation: 'y = 2(3) + 1 = 7.' },
        { lvl: 2, type: 'numeric', prompt: 'A line passes through (0,1) and (2,5). What is its slope?', answer: 2, tolerance: 0, explanation: 'Slope = (5−1)/(2−0) = 4/2 = 2.' },
      ] },
    { tier: 'F2', order: 3, slug: 'systems-linear-equations', title: 'Systems of Linear Equations',
      summary: 'Solving two equations in two unknowns by substitution and elimination, and modelling with them.',
      outcomes: ['Solve systems by substitution and elimination', 'Interpret a solution as the intersection of two lines', 'Model two-condition problems with a system'],
      concepts: [
        ['Two facts, two unknowns', 'A system pins down two unknowns using two independent equations. The solution is the single point where both lines cross.'],
        ['Substitution vs elimination', 'Substitution solves one equation for a variable and plugs it into the other; elimination adds or subtracts equations to cancel a variable. Pick whichever keeps the arithmetic simplest.'],
      ],
      mistakes: ['Adding equations without first matching a coefficient to eliminate.', 'Substituting into the same equation you solved, losing information.', 'Forgetting to find the second variable after finding the first.'],
      tricks: ['Line up equations and scale one so a variable cancels on addition.', 'Substitute back into the simpler equation to find the second unknown.', 'If lines are parallel (same slope), there is no solution — check before grinding.'],
      memory: ['"Two unknowns need two equations."', '"Eliminate by matching coefficients."', 'The solution is where the lines meet.'],
      board: { CBSE: ['Cl.9-10 Pair of Linear Equations'], ICSE: ['Cl.9 Simultaneous Equations'], IB: ['MYP/DP Algebra'] },
      comp: ['JEE-Main'], keywords: ['simultaneous equations', 'substitution', 'elimination', 'system'],
      quiz: [
        { lvl: 1, type: 'numeric', prompt: 'If x + y = 10 and x − y = 4, what is x?', answer: 7, tolerance: 0, explanation: 'Add the equations: 2x = 14, so x = 7.' },
        { lvl: 2, type: 'numeric', prompt: 'From x + y = 10 and x − y = 4, what is y?', answer: 3, tolerance: 0, explanation: 'x = 7, so y = 10 − 7 = 3.' },
      ] },
    { tier: 'F2', order: 4, slug: 'polynomials-factoring', title: 'Polynomials & Factoring Basics',
      summary: 'Adding, multiplying and factoring polynomials, including common factors and simple quadratics.',
      outcomes: ['Add, subtract and multiply polynomials', 'Factor out common factors', 'Factor simple quadratics'],
      concepts: [
        ['Polynomials are number-like', 'Polynomials add, subtract and multiply just like numbers, keeping like terms together. Multiplying uses the distributive law repeatedly (FOIL for two binomials).'],
        ['Factoring reverses expansion', 'Factoring rewrites a sum as a product — pulling out common factors or splitting a quadratic into two binomials. It is the key to solving equations later.'],
      ],
      mistakes: ['Forgetting the middle term when squaring a binomial: (a+b)² = a² + 2ab + b².', 'Missing a common factor before trying to factor a quadratic.', 'Sign errors when factoring x² − 5x + 6 into (x−2)(x−3).'],
      tricks: ['To factor x² + bx + c, find two numbers that multiply to c and add to b.', 'Always pull out the greatest common factor first.', 'Check a factorisation by expanding it back.'],
      memory: ['"(a+b)² = a² + 2ab + b²" — do not lose the middle term.', '"Multiply to c, add to b" for quadratics.', 'Common factor out first, always.'],
      board: { CBSE: ['Cl.8-9 Polynomials', 'Cl.8 Factorisation'], ICSE: ['Cl.8-9 Factorisation'], IB: ['MYP Algebra'] },
      comp: ['JEE-Main'], keywords: ['polynomials', 'factoring', 'FOIL', 'common factor'],
      quiz: [
        { lvl: 1, type: 'mcq', prompt: 'Expand (x + 2)(x + 3).', choices: ['x² + 5x + 6', 'x² + 6x + 5', 'x² + 6', 'x² + 5x + 5'], answer: 0, explanation: 'FOIL: x² + 3x + 2x + 6 = x² + 5x + 6.' },
        { lvl: 2, type: 'mcq', prompt: 'Factor x² − 5x + 6.', choices: ['(x−2)(x−3)', '(x+2)(x+3)', '(x−1)(x−6)', '(x−6)(x+1)'], answer: 0, explanation: 'Two numbers multiplying to 6 and adding to −5 are −2 and −3.' },
      ] },
    { tier: 'F2', order: 5, slug: 'geometry-similarity-pythagoras', title: 'Geometry II: Similarity, Pythagoras & Mensuration',
      summary: 'Similar figures as "ratio applied to shapes", the Pythagorean theorem, and areas and volumes.',
      outcomes: ['Use similarity ratios to find missing lengths', 'Apply the Pythagorean theorem', 'Compute areas and volumes of standard shapes'],
      concepts: [
        ['Similarity is ratio for shapes', 'Similar figures have the same shape but different size — corresponding sides share one ratio (the scale factor). This is exactly the proportional reasoning from F1 applied to geometry.'],
        ['Pythagoras', 'In a right triangle, a² + b² = c², with c the hypotenuse. It links the three sides and underlies distance in coordinate geometry later.'],
      ],
      mistakes: ['Applying a² + b² = c² to a non-right triangle.', 'Putting the hypotenuse in the wrong place (it is always opposite the right angle).', 'Scaling area by the length ratio instead of its square.'],
      tricks: ['For similar shapes, set up length₁/length₂ = scale factor and solve by cross-multiplying.', 'Area scales by the square of the length ratio; volume by the cube.', 'Recognise common Pythagorean triples (3-4-5, 5-12-13) to save time.'],
      memory: ['"Similar = same shape, scaled by a ratio."', '"a² + b² = c², c opposite the right angle."', '"Length ×k → area ×k² → volume ×k³."'],
      board: { CBSE: ['Cl.9-10 Triangles (Similarity)', 'Cl.9 Pythagoras', 'Cl.8-9 Mensuration'], ICSE: ['Cl.9 Similarity & Pythagoras'], IB: ['MYP Geometry'] },
      comp: ['JEE-Main'], keywords: ['similarity', 'pythagoras', 'area', 'volume', 'scale factor'],
      xprereqs: ['math.F1.ratio-proportion-percentage'],
      quiz: [
        { lvl: 1, type: 'numeric', prompt: 'A right triangle has legs 3 and 4. Find the hypotenuse.', answer: 5, tolerance: 0, explanation: '√(3² + 4²) = √25 = 5.' },
        { lvl: 2, type: 'mcq', prompt: 'If a shape is scaled by factor 3, its area scales by:', choices: ['3', '6', '9', '27'], answer: 2, explanation: 'Area scales by the square of the length ratio: 3² = 9.' },
      ] },
    { tier: 'F2', order: 6, slug: 'probability-statistics-i', title: 'Probability & Statistics I',
      summary: 'Probability as a proportion of outcomes, and measures of centre and spread.',
      outcomes: ['Compute simple probabilities', 'Find mean, median and mode', 'Describe spread with range'],
      concepts: [
        ['Probability is a proportion', 'The probability of an event is (favourable outcomes)/(total equally-likely outcomes) — a number between 0 and 1. It is ratio thinking applied to chance.'],
        ['Centre and spread', 'Mean, median and mode summarise where data sits; range and later measures describe how spread out it is. Choosing the right summary depends on the data\'s shape.'],
      ],
      mistakes: ['Giving a probability greater than 1 or less than 0.', 'Confusing median (middle value) with mean (average).', 'Forgetting to order data before finding the median.'],
      tricks: ['P(event) = favourable ÷ total; P(not event) = 1 − P(event).', 'Order the data first, then read off the median.', 'The mode is just the most frequent value — good for categories.'],
      memory: ['"Probability is favourable over total, between 0 and 1."', '"Median = middle of ordered data."', '"Mode = most often."'],
      board: { CBSE: ['Cl.8-9 Data Handling & Probability'], ICSE: ['Cl.8-9 Statistics & Probability'], IB: ['MYP Statistics'] },
      comp: ['JEE-Main', 'NEET'], keywords: ['probability', 'mean', 'median', 'mode', 'range'],
      xprereqs: ['math.F1.ratio-proportion-percentage'],
      quiz: [
        { lvl: 1, type: 'mcq', prompt: 'A fair die is rolled. P(rolling a 4)?', choices: ['1/6', '1/4', '4/6', '1/2'], answer: 0, explanation: 'One favourable outcome out of six: 1/6.' },
        { lvl: 2, type: 'numeric', prompt: 'Find the median of 3, 1, 4, 1, 5.', answer: 3, tolerance: 0, explanation: 'Ordered: 1,1,3,4,5 → middle value is 3.' },
      ] },
    { tier: 'F2', order: 7, slug: 'number-theory-basics', title: 'Integer Number Theory Basics',
      summary: 'Divisibility, primes, factors, HCF and LCM — foundations that also serve computer science.',
      outcomes: ['Test divisibility and identify primes', 'Find HCF and LCM', 'Use prime factorisation'],
      concepts: [
        ['Primes and factorisation', 'Every whole number breaks uniquely into a product of primes — its "atoms". This factorisation is the tool behind HCF, LCM and much of cryptography and algorithms.'],
        ['HCF and LCM', 'The highest common factor is the largest number dividing two values; the lowest common multiple is the smallest number both divide into. Prime factorisation makes both quick to compute.'],
      ],
      mistakes: ['Calling 1 a prime (it is not) or forgetting 2 is prime.', 'Swapping HCF and LCM.', 'Missing a prime factor when factorising.'],
      tricks: ['HCF = product of common prime factors; LCM = product of all primes to their highest power.', 'Divisibility shortcuts: by 3 if digit sum divides by 3; by 9 similarly.', 'HCF × LCM = product of the two numbers.'],
      memory: ['"Primes are the atoms of numbers."', '"HCF is the biggest shared factor; LCM the smallest shared multiple."', '"Digit sum ÷ 3 → number ÷ 3."'],
      board: { CBSE: ['Cl.6 Playing with Numbers', 'Cl.10 Real Numbers'], ICSE: ['Cl.6-8 Number Theory'], IB: ['MYP Number'] },
      comp: [], keywords: ['primes', 'factors', 'HCF', 'LCM', 'divisibility'],
      quiz: [
        { lvl: 1, type: 'numeric', prompt: 'Find the HCF of 12 and 18.', answer: 6, tolerance: 0, explanation: 'Common factors: 1,2,3,6 — the highest is 6.' },
        { lvl: 2, type: 'numeric', prompt: 'Find the LCM of 4 and 6.', answer: 12, tolerance: 0, explanation: 'Smallest number both divide into is 12.' },
      ] },

    // ================= I1 =================
    { tier: 'I1', order: 1, slug: 'quadratics', title: 'Quadratics',
      summary: 'Quadratic expressions and equations — factoring, the quadratic formula, graphs and modelling.',
      outcomes: ['Solve quadratics by factoring and the formula', 'Sketch a parabola and find its vertex', 'Model with quadratic equations'],
      concepts: [
        ['Three ways to solve', 'A quadratic ax² + bx + c = 0 can be solved by factoring, completing the square, or the quadratic formula x = (−b ± √(b²−4ac))/2a. The discriminant b²−4ac tells how many real roots exist.'],
        ['The parabola', 'A quadratic graphs as a parabola. Its vertex is the turning point (a max or min), and the roots are where it crosses the x-axis — a picture that makes modelling intuitive.'],
      ],
      mistakes: ['Forgetting the ± in the quadratic formula, losing a root.', 'Sign slips inside the discriminant.', 'Assuming every quadratic has two real roots (the discriminant can be negative).'],
      tricks: ['Check the discriminant first: positive → two roots, zero → one, negative → none (real).', 'If it factors, factoring is faster than the formula.', 'The vertex x-coordinate is −b/2a.'],
      memory: ['"x = (−b ± √(b²−4ac)) / 2a" — the quadratic formula.', '"Discriminant sign = number of real roots."', 'Vertex at x = −b/2a.'],
      board: { CBSE: ['Cl.10 Quadratic Equations'], ICSE: ['Cl.10 Quadratic Equations'], IB: ['DP Algebra'] },
      comp: ['JEE-Main', 'JEE-Advanced'], keywords: ['quadratic', 'discriminant', 'parabola', 'roots'],
      xprereqs: ['math.F2.polynomials-factoring'],
      quiz: [
        { lvl: 1, type: 'mcq', prompt: 'Solve x² − 5x + 6 = 0.', choices: ['x = 2 or 3', 'x = −2 or −3', 'x = 1 or 6', 'x = 5 or 6'], answer: 0, explanation: 'Factors (x−2)(x−3) = 0 → x = 2 or 3.' },
        { lvl: 3, type: 'mcq', prompt: 'How many real roots does x² + x + 1 = 0 have?', choices: ['0', '1', '2', 'infinite'], answer: 0, explanation: 'Discriminant = 1 − 4 = −3 < 0 → no real roots.' },
      ] },
    { tier: 'I1', order: 2, slug: 'coordinate-geometry', title: 'Coordinate Geometry',
      summary: 'Distance, midpoint and section formulas, and the equations of lines and circles.',
      outcomes: ['Use distance, midpoint and section formulas', 'Find equations of lines in various forms', 'Recognise the equation of a circle'],
      concepts: [
        ['Geometry meets algebra', 'Placing shapes on the coordinate plane turns geometric questions into algebra. Distance between points is Pythagoras: √((x₂−x₁)² + (y₂−y₁)²).'],
        ['Lines and circles', 'A line is y = mx + c or ax + by + c = 0; a circle centred at (h,k) with radius r is (x−h)² + (y−k)² = r². These equations let you compute intersections and tangents.'],
      ],
      mistakes: ['Subtracting coordinates in inconsistent order in the distance formula.', 'Confusing midpoint (average) with section formula (weighted).', 'Forgetting to square the radius in a circle equation.'],
      tricks: ['Distance is just Pythagoras on the coordinate differences.', 'Midpoint = average of the endpoints\' coordinates.', 'Parallel lines share a slope; perpendicular slopes multiply to −1.'],
      memory: ['"Distance = √(Δx² + Δy²)" — Pythagoras in disguise.', '"Midpoint = average the coordinates."', 'Perpendicular slopes multiply to −1.'],
      board: { CBSE: ['Cl.10 Coordinate Geometry'], ICSE: ['Cl.10 Coordinate Geometry'], IB: ['DP Geometry'] },
      comp: ['JEE-Main', 'JEE-Advanced'], keywords: ['coordinate geometry', 'distance', 'midpoint', 'line', 'circle'],
      xprereqs: ['math.F2.geometry-similarity-pythagoras'],
      quiz: [
        { lvl: 1, type: 'numeric', prompt: 'Distance between (0,0) and (3,4)?', answer: 5, tolerance: 0, explanation: '√(3² + 4²) = 5.' },
        { lvl: 2, type: 'mcq', prompt: 'Midpoint of (2,4) and (6,8)?', choices: ['(4,6)', '(8,12)', '(2,2)', '(3,6)'], answer: 0, explanation: 'Average coordinates: ((2+6)/2,(4+8)/2) = (4,6).' },
      ] },
    { tier: 'I1', order: 3, slug: 'trigonometry-i', title: 'Trigonometry I',
      summary: 'Right-triangle ratios (sin, cos, tan) and early unit-circle intuition — the tools physics vectors need.',
      outcomes: ['Use sin, cos and tan in right triangles', 'Solve for unknown sides and angles', 'Understand the unit-circle picture'],
      concepts: [
        ['SOH-CAH-TOA', 'In a right triangle, sine = opposite/hypotenuse, cosine = adjacent/hypotenuse, tangent = opposite/adjacent. These ratios connect angles to side lengths.'],
        ['The unit circle', 'On a circle of radius 1, a point at angle θ has coordinates (cos θ, sin θ). This extends trig beyond right triangles and is the foundation for waves and vectors.'],
      ],
      mistakes: ['Mixing up opposite and adjacent relative to the angle.', 'Using degrees when the calculator is in radians (or vice versa).', 'Forgetting sine and cosine never exceed 1 in magnitude.'],
      tricks: ['SOH-CAH-TOA labels which ratio to use.', 'Draw and label the triangle before choosing a ratio.', 'Know exact values for 30°, 45°, 60° to avoid the calculator.'],
      memory: ['"SOH-CAH-TOA."', '"On the unit circle, x = cos, y = sin."', 'Sine and cosine live between −1 and 1.'],
      board: { CBSE: ['Cl.10 Introduction to Trigonometry'], ICSE: ['Cl.9-10 Trigonometry'], IB: ['DP Trigonometry'] },
      comp: ['JEE-Main', 'JEE-Advanced', 'NEET'], keywords: ['trigonometry', 'sine', 'cosine', 'tangent', 'unit circle'],
      quiz: [
        { lvl: 1, type: 'mcq', prompt: 'In a right triangle, sin θ equals:', choices: ['opposite/hypotenuse', 'adjacent/hypotenuse', 'opposite/adjacent', 'hypotenuse/opposite'], answer: 0, explanation: 'SOH: sine = opposite / hypotenuse.' },
        { lvl: 2, type: 'mcq', prompt: 'What is sin 30°?', choices: ['1/2', '√3/2', '1', '0'], answer: 0, explanation: 'A standard exact value: sin 30° = 1/2.' },
      ] },
    { tier: 'I1', order: 4, slug: 'sequences-series', title: 'Sequences & Series',
      summary: 'Arithmetic and geometric progressions, their sums, and links to growth and finance.',
      outcomes: ['Identify AP and GP and find nth terms', 'Sum arithmetic and geometric series', 'Model compound growth'],
      concepts: [
        ['AP and GP', 'An arithmetic progression adds a fixed difference each step; a geometric progression multiplies by a fixed ratio. Their nth-term formulas let you jump to any term without listing all of them.'],
        ['Sums and growth', 'Series sums have neat closed forms. A GP models compound growth (interest, populations) — the same "multiply by a factor" idea as successive percentages.'],
      ],
      mistakes: ['Confusing the common difference (AP) with the common ratio (GP).', 'Off-by-one errors in the nth-term formula (using n vs n−1).', 'Using the AP sum formula for a GP.'],
      tricks: ['AP nth term: a + (n−1)d. GP nth term: a·r^(n−1).', 'AP sum: n/2 × (first + last). GP sum: a(rⁿ−1)/(r−1).', 'A GP with |r|<1 has a finite infinite-sum a/(1−r).'],
      memory: ['"AP adds d; GP multiplies by r."', '"AP sum = average of ends × count."', 'Compound growth is a GP.'],
      board: { CBSE: ['Cl.10 Arithmetic Progressions'], ICSE: ['Cl.10 Arithmetic Progression', 'Cl.10 Geometric Progression'], IB: ['DP Sequences & Series'] },
      comp: ['JEE-Main', 'JEE-Advanced'], keywords: ['sequences', 'series', 'AP', 'GP', 'compound growth'],
      quiz: [
        { lvl: 1, type: 'numeric', prompt: 'AP with first term 2 and difference 3. What is the 4th term?', answer: 11, tolerance: 0, explanation: 'a + 3d = 2 + 3(3) = 11.' },
        { lvl: 2, type: 'numeric', prompt: 'Sum of the AP 1, 2, 3, …, 10.', answer: 55, tolerance: 0, explanation: '10/2 × (1 + 10) = 55.' },
      ] },
    { tier: 'I1', order: 5, slug: 'geometry-circles-proof', title: 'Geometry III: Circles & Formal Proof',
      summary: 'Circle theorems and deductive proof as a skill in itself — reasoning that transfers to CS correctness.',
      outcomes: ['Apply circle theorems (angles, tangents, chords)', 'Construct a deductive proof', 'Justify each step with a reason'],
      concepts: [
        ['Circle theorems', 'Angles in a circle follow strict rules — the angle at the centre is twice the angle at the circumference on the same arc; angles in a semicircle are right angles. These give powerful shortcuts.'],
        ['What a proof is', 'A proof is a chain of justified steps from given facts to a conclusion, each step backed by a reason. Learning to prove trains the same rigorous reasoning used to argue a program is correct.'],
      ],
      mistakes: ['Assuming a diagram is to scale and reading values off it.', 'Stating a conclusion without a supporting reason.', 'Confusing the angle at the centre with the angle at the circumference.'],
      tricks: ['Mark all equal angles/lengths on the figure before proving.', 'Name the theorem you use at each step as the "reason".', 'Angle in a semicircle is 90° — a frequent shortcut.'],
      memory: ['"Centre angle = twice the circumference angle."', '"Angle in a semicircle is a right angle."', '"Every step needs a reason."'],
      board: { CBSE: ['Cl.9-10 Circles'], ICSE: ['Cl.10 Circles'], IB: ['DP Geometry'] },
      comp: ['JEE-Advanced'], keywords: ['circle theorems', 'proof', 'geometry', 'deduction'],
      quiz: [
        { lvl: 2, type: 'numeric', prompt: 'The angle at the centre on an arc is 80°. The angle at the circumference on the same arc is?', answer: 40, tolerance: 0, explanation: 'Circumference angle is half the centre angle: 40°.' },
        { lvl: 2, type: 'mcq', prompt: 'The angle in a semicircle is always:', choices: ['90°', '60°', '180°', 'variable'], answer: 0, explanation: 'A well-known circle theorem: it is a right angle.' },
      ] },
    { tier: 'I1', order: 6, slug: 'statistics-ii', title: 'Statistics II',
      summary: 'Grouped data, measures of dispersion, and reading real studies critically.',
      outcomes: ['Compute mean/median for grouped data', 'Measure spread with variance and standard deviation (intro)', 'Interpret data from real studies'],
      concepts: [
        ['Grouped data', 'When data comes in intervals, we estimate the mean using midpoints weighted by frequency. This scales statistics to large real datasets.'],
        ['Dispersion', 'Two datasets can share a mean yet differ wildly in spread. Variance and standard deviation quantify that spread — essential for interpreting biology and physics measurements.'],
      ],
      mistakes: ['Using interval endpoints instead of midpoints for grouped means.', 'Reporting only the mean and ignoring spread.', 'Confusing variance (squared units) with standard deviation.'],
      tricks: ['Estimate grouped mean = Σ(midpoint × frequency) ÷ Σfrequency.', 'Standard deviation is the square root of variance — back to original units.', 'Compare datasets by both centre and spread, never centre alone.'],
      memory: ['"Grouped mean uses midpoints."', '"SD = √variance."', '"Centre and spread together tell the story."'],
      board: { CBSE: ['Cl.9-10 Statistics'], ICSE: ['Cl.10 Statistics (Measures of Central Tendency)'], IB: ['DP Statistics'] },
      comp: ['NEET'], keywords: ['statistics', 'grouped data', 'variance', 'standard deviation', 'dispersion'],
      quiz: [
        { lvl: 2, type: 'mcq', prompt: 'Two classes have the same mean score but class A has a larger standard deviation. This means class A\'s scores are:', choices: ['more spread out', 'higher on average', 'lower on average', 'identical'], answer: 0, explanation: 'Larger SD = more spread, even with the same mean.' },
        { lvl: 1, type: 'mcq', prompt: 'Standard deviation is:', choices: ['the square root of variance', 'the square of variance', 'the mean', 'the range'], answer: 0, explanation: 'SD = √variance, restoring the original units.' },
      ] },

    // ================= I2 =================
    { tier: 'I2', order: 1, slug: 'functions', title: 'Functions as Objects',
      summary: 'Function notation, domain and range, composition, inverses and transformations of graphs.',
      outcomes: ['Use function notation and find domain/range', 'Compose and invert functions', 'Transform graphs (shift, stretch, reflect)'],
      concepts: [
        ['A function is a machine', 'A function f takes an input and returns exactly one output, written f(x). Domain is the allowed inputs, range the possible outputs. Thinking of functions as objects you can combine is a big conceptual step.'],
        ['Composition and inverses', 'Composition f(g(x)) feeds one function\'s output into another. The inverse f⁻¹ undoes f. Graph transformations (shifts, stretches, reflections) change a function predictably.'],
      ],
      mistakes: ['Assuming every relation is a function (each input must give one output).', 'Reversing the order in composition: f(g(x)) ≠ g(f(x)) in general.', 'Confusing f⁻¹(x) with 1/f(x).'],
      tricks: ['Use the vertical-line test to check something is a function.', 'To find an inverse, swap x and y and solve for y.', 'Inside the bracket shifts horizontally (opposite sign); outside shifts vertically.'],
      memory: ['"One input, one output" defines a function.', '"Inverse swaps x and y."', '"Inside the bracket = horizontal, opposite sign."'],
      board: { CBSE: ['Cl.11 Relations & Functions'], ICSE: ['Cl.11 Functions'], IB: ['DP Functions'] },
      comp: ['JEE-Main', 'JEE-Advanced'], keywords: ['functions', 'domain', 'range', 'composition', 'inverse'],
      xprereqs: ['math.F2.linear-relationships-coordinate-plane'],
      quiz: [
        { lvl: 1, type: 'numeric', prompt: 'If f(x) = 2x + 1, find f(3).', answer: 7, tolerance: 0, explanation: 'f(3) = 2(3) + 1 = 7.' },
        { lvl: 2, type: 'numeric', prompt: 'If f(x)=x+2 and g(x)=3x, find f(g(2)).', answer: 8, tolerance: 0, explanation: 'g(2)=6, then f(6)=8.' },
      ] },
    { tier: 'I2', order: 2, slug: 'trigonometry-ii', title: 'Trigonometry II',
      summary: 'Identities, trigonometric equations, and the sine and cosine rules for any triangle.',
      outcomes: ['Use key trig identities', 'Solve trigonometric equations', 'Apply the sine and cosine rules'],
      concepts: [
        ['Identities', 'sin²θ + cos²θ = 1 and the addition formulas let you rewrite and simplify trig expressions. Identities are the algebra of trigonometry.'],
        ['Rules for any triangle', 'The sine rule (a/sin A = b/sin B) and cosine rule (c² = a² + b² − 2ab cos C) extend trig to non-right triangles — vital in physics and surveying.'],
      ],
      mistakes: ['Forgetting sin²θ means (sin θ)², not sin(θ²).', 'Losing solutions of a trig equation by ignoring periodicity.', 'Using the sine rule when the cosine rule is needed (and vice versa).'],
      tricks: ['sin²θ + cos²θ = 1 is the identity you will use most.', 'Use the cosine rule when you know two sides and the included angle.', 'Remember trig equations have infinitely many solutions — add 360°k.'],
      memory: ['"sin² + cos² = 1."', '"Sine rule for angle-side pairs; cosine rule for the odd one out."', 'Trig equations repeat every period.'],
      board: { CBSE: ['Cl.11 Trigonometric Functions'], ICSE: ['Cl.11 Trigonometry'], IB: ['DP Trigonometry'] },
      comp: ['JEE-Main', 'JEE-Advanced'], keywords: ['trig identities', 'sine rule', 'cosine rule', 'equations'],
      quiz: [
        { lvl: 2, type: 'mcq', prompt: 'Simplify sin²θ + cos²θ.', choices: ['1', '0', '2', 'tan θ'], answer: 0, explanation: 'The fundamental Pythagorean identity equals 1.' },
        { lvl: 3, type: 'mcq', prompt: 'To find a side opposite a known angle given two sides and the included angle, use:', choices: ['the cosine rule', 'the sine rule', 'Pythagoras only', 'SOH-CAH-TOA'], answer: 0, explanation: 'Two sides + included angle → cosine rule.' },
      ] },
    { tier: 'I2', order: 3, slug: 'derivatives-intuition', title: 'Calculus Intuition: Derivatives',
      summary: 'Rate of change made exact — the derivative as the slope of a curve, taught alongside kinematics.',
      outcomes: ['Interpret the derivative as an instantaneous rate', 'Differentiate simple powers', 'Connect derivative to slope of a tangent'],
      concepts: [
        ['Instantaneous rate', 'The derivative measures how fast a quantity changes at an instant — the slope of the tangent to its graph. It makes the "slope = rate" idea from lines exact for curves.'],
        ['Power rule', 'For f(x) = xⁿ, the derivative is n·x^(n−1). This single rule differentiates polynomials and connects directly to velocity being the derivative of position.'],
      ],
      mistakes: ['Confusing average rate (over an interval) with instantaneous rate (at a point).', 'Forgetting to reduce the power by one in the power rule.', 'Treating the derivative of a constant as anything but zero.'],
      tricks: ['Power rule: bring the exponent down, subtract one from it.', 'The derivative of a constant is 0; of x is 1.', 'A positive derivative means increasing; negative means decreasing.'],
      memory: ['"Derivative = slope of the tangent = instantaneous rate."', '"Bring down the power, drop it by one."', 'Velocity is the derivative of position.'],
      board: { CBSE: ['Cl.11 Limits & Derivatives'], ICSE: ['Cl.11-12 Calculus (Differentiation)'], IB: ['DP Calculus'] },
      comp: ['JEE-Main', 'JEE-Advanced'], keywords: ['derivative', 'rate of change', 'slope', 'power rule'],
      xprereqs: ['math.F2.linear-relationships-coordinate-plane'],
      quiz: [
        { lvl: 2, type: 'mcq', prompt: 'Differentiate f(x) = x³.', choices: ['3x²', 'x²', '3x', 'x⁴/4'], answer: 0, explanation: 'Power rule: 3·x^(3−1) = 3x².' },
        { lvl: 2, type: 'mcq', prompt: 'The derivative of a constant, e.g. f(x)=7, is:', choices: ['0', '7', '1', 'undefined'], answer: 0, explanation: 'A constant does not change, so its rate is 0.' },
      ] },
    { tier: 'I2', order: 4, slug: 'integrals-intuition', title: 'Calculus Intuition: Integrals',
      summary: 'Accumulation and area under a curve — the reverse of differentiation.',
      outcomes: ['Interpret an integral as accumulated area', 'Integrate simple powers', 'Relate integration and differentiation'],
      concepts: [
        ['Area as accumulation', 'The integral adds up infinitely many thin slices to give the area under a curve — which represents total accumulated quantity (e.g., distance from a velocity graph).'],
        ['The reverse of the derivative', 'Integration undoes differentiation: ∫xⁿ dx = x^(n+1)/(n+1) + C. This Fundamental Theorem links the two halves of calculus.'],
      ],
      mistakes: ['Forgetting the constant of integration +C in indefinite integrals.', 'Dividing by the old power instead of the new (n+1).', 'Confusing the area interpretation (definite) with the antiderivative (indefinite).'],
      tricks: ['Integrate a power: raise the exponent by one, divide by the new exponent.', 'Area under a velocity–time graph = distance travelled.', 'Differentiate your answer to check the integral.'],
      memory: ['"Integral = area = accumulation."', '"Raise the power, divide by the new power, add C."', 'Integration and differentiation are inverses.'],
      board: { CBSE: ['Cl.12 Integrals'], ICSE: ['Cl.12 Integration'], IB: ['DP Calculus'] },
      comp: ['JEE-Main', 'JEE-Advanced'], keywords: ['integral', 'area', 'accumulation', 'antiderivative'],
      quiz: [
        { lvl: 2, type: 'mcq', prompt: 'Find ∫ x² dx.', choices: ['x³/3 + C', '2x + C', 'x³ + C', '3x³ + C'], answer: 0, explanation: 'Raise power to 3, divide by 3, add C.' },
        { lvl: 2, type: 'mcq', prompt: 'The area under a velocity–time graph represents:', choices: ['distance', 'acceleration', 'speed', 'time'], answer: 0, explanation: 'Accumulating velocity over time gives distance.' },
      ] },
    { tier: 'I2', order: 5, slug: 'exponentials-logarithms', title: 'Exponentials & Logarithms',
      summary: 'Exponential growth and decay, logarithms as the inverse, and their laws — used across chemistry, biology and CS.',
      outcomes: ['Work with exponential functions', 'Use logarithms and their laws', 'Model growth and decay'],
      concepts: [
        ['Exponential change', 'Exponential functions grow or decay by a constant factor per step — populations, radioactive decay, compound interest. The rate of change is proportional to the current amount.'],
        ['Logarithms invert exponentials', 'log_b(x) answers "what power of b gives x?". Log laws (log(ab)=log a+log b) turn multiplication into addition — the reason logs simplify pH, decibels and algorithmic complexity.'],
      ],
      mistakes: ['Thinking log(a+b) = log a + log b (it is log(ab) that splits).', 'Forgetting logs are only defined for positive arguments.', 'Confusing the base of a logarithm.'],
      tricks: ['log(ab) = log a + log b; log(aⁿ) = n log a.', 'A log turns exponential equations into linear ones — take logs of both sides.', 'ln and e are inverse; log base 10 for orders of magnitude.'],
      memory: ['"A log asks: what power gives this number?"', '"log(ab) = log a + log b."', 'Exponential growth ↔ logarithmic inverse.'],
      board: { CBSE: ['Cl.11 Logarithms (foundations)'], ICSE: ['Cl.9-11 Logarithms'], IB: ['DP Exponentials & Logs'] },
      comp: ['JEE-Main', 'JEE-Advanced', 'NEET'], keywords: ['exponential', 'logarithm', 'growth', 'decay', 'log laws'],
      xprereqs: ['math.F2.exponents-scientific-notation'],
      quiz: [
        { lvl: 1, type: 'numeric', prompt: 'Evaluate log base 2 of 8.', answer: 3, tolerance: 0, explanation: '2³ = 8, so log₂8 = 3.' },
        { lvl: 2, type: 'mcq', prompt: 'log(ab) equals:', choices: ['log a + log b', 'log a × log b', 'log a − log b', 'log(a+b)'], answer: 0, explanation: 'The product law turns multiplication into addition.' },
      ] },
    { tier: 'I2', order: 6, slug: 'combinatorics-probability-ii', title: 'Combinatorics & Probability II',
      summary: 'Counting principles, permutations and combinations, and conditional probability.',
      outcomes: ['Count with permutations and combinations', 'Use the multiplication principle', 'Compute conditional probability'],
      concepts: [
        ['Counting systematically', 'The multiplication principle counts multi-step choices; permutations count ordered arrangements, combinations count unordered selections. Choosing the right one is the whole skill.'],
        ['Conditional probability', 'P(A|B) is the probability of A given B has happened. It corrects naive counting when events depend on one another — the heart of genetics and risk.'],
      ],
      mistakes: ['Using permutations when order does not matter (should be combinations).', 'Double-counting arrangements.', 'Assuming events are independent when they are not.'],
      tricks: ['Order matters → permutation (nPr); order does not → combination (nCr).', 'Break a count into independent steps and multiply.', 'For conditional probability, restrict to the "given" outcomes first.'],
      memory: ['"Order matters → permute; order not → combine."', '"Multiply independent choices."', 'P(A|B) restricts the sample space to B.'],
      board: { CBSE: ['Cl.11 Permutations & Combinations', 'Cl.12 Probability'], ICSE: ['Cl.11 Permutations & Combinations'], IB: ['DP Probability'] },
      comp: ['JEE-Main', 'JEE-Advanced'], keywords: ['combinatorics', 'permutation', 'combination', 'conditional probability'],
      xprereqs: ['math.F2.probability-statistics-i'],
      quiz: [
        { lvl: 1, type: 'numeric', prompt: 'How many ways to arrange 3 distinct books in a row?', answer: 6, tolerance: 0, explanation: '3! = 3×2×1 = 6.' },
        { lvl: 2, type: 'numeric', prompt: 'How many ways to choose 2 items from 4 (order irrelevant)?', answer: 6, tolerance: 0, explanation: '4C2 = 6.' },
      ] },

    // ================= A1 =================
    { tier: 'A1', order: 1, slug: 'calculus-limits-differentiation', title: 'Calculus: Limits & Differentiation',
      summary: 'Limits made precise, the rules of differentiation, and applications like optimisation and related rates.',
      outcomes: ['Evaluate limits', 'Differentiate using product, quotient and chain rules', 'Solve optimisation and related-rate problems'],
      concepts: [
        ['Limits underpin calculus', 'A limit describes what a function approaches near a point, even where it is undefined. The derivative is formally a limit of average rates.'],
        ['Differentiation rules', 'The product, quotient and chain rules extend the power rule to any combination. The chain rule — differentiate outer, times derivative of inner — is the workhorse for composite functions.'],
      ],
      mistakes: ['Forgetting the chain rule\'s inner derivative.', 'Applying the power rule to composite functions directly.', 'Sign errors in the quotient rule.'],
      tricks: ['Chain rule: "derivative of the outside × derivative of the inside."', 'At a maximum or minimum, the derivative is zero — set f\'(x)=0.', 'For related rates, differentiate the relating equation with respect to time.'],
      memory: ['"Outside-in" for the chain rule.', '"Max/min → f\'(x) = 0."', 'Derivative is a limit of average rates.'],
      board: { CBSE: ['Cl.12 Continuity & Differentiability', 'Cl.12 Application of Derivatives'], ICSE: ['Cl.12 Differentiation'], IB: ['DP Calculus HL'] },
      comp: ['JEE-Main', 'JEE-Advanced'], keywords: ['limits', 'differentiation', 'chain rule', 'optimisation'],
      xprereqs: ['math.I2.derivatives-intuition'],
      quiz: [
        { lvl: 2, type: 'mcq', prompt: 'Differentiate (2x + 1)³ using the chain rule.', choices: ['3(2x+1)² · 2', '3(2x+1)²', '6x²', '(2x+1)²'], answer: 0, explanation: 'Outer 3(2x+1)² times inner derivative 2.' },
        { lvl: 3, type: 'mcq', prompt: 'At a local maximum of a smooth function, f\'(x) is:', choices: ['0', 'positive', 'negative', 'undefined'], answer: 0, explanation: 'The tangent is horizontal, so the derivative is zero.' },
      ] },
    { tier: 'A1', order: 2, slug: 'integration-techniques', title: 'Integration Techniques & Applications',
      summary: 'Substitution and by-parts integration, definite integrals, and areas and volumes.',
      outcomes: ['Integrate by substitution and by parts', 'Evaluate definite integrals', 'Find areas and volumes of revolution'],
      concepts: [
        ['Techniques', 'Substitution reverses the chain rule; integration by parts reverses the product rule. Recognising which to use is pattern recognition built by practice.'],
        ['Definite integrals and applications', 'A definite integral gives an exact accumulated total between limits — area under a curve, volume of revolution, total displacement. It turns "adding infinitely many pieces" into one number.'],
      ],
      mistakes: ['Forgetting to change the limits when substituting in a definite integral.', 'Choosing the wrong parts in integration by parts.', 'Dropping the negative when a curve dips below the axis.'],
      tricks: ['Substitution: let u be the inner function whose derivative also appears.', 'For by-parts, use LIATE to pick which factor to differentiate.', 'Change limits to the new variable to avoid back-substituting.'],
      memory: ['"Substitution undoes the chain rule."', '"By-parts undoes the product rule."', 'LIATE orders the by-parts choice.'],
      board: { CBSE: ['Cl.12 Integrals', 'Cl.12 Application of Integrals'], ICSE: ['Cl.12 Integration'], IB: ['DP Calculus HL'] },
      comp: ['JEE-Main', 'JEE-Advanced'], keywords: ['integration', 'substitution', 'by parts', 'definite integral', 'area'],
      xprereqs: ['math.I2.integrals-intuition'],
      quiz: [
        { lvl: 2, type: 'mcq', prompt: 'Best method for ∫ 2x·cos(x²) dx?', choices: ['substitution (u = x²)', 'by parts', 'partial fractions', 'none'], answer: 0, explanation: 'The inner function x² has derivative 2x present — substitute u = x².' },
        { lvl: 3, type: 'mcq', prompt: 'A definite integral ∫ from a to b of f(x) dx gives:', choices: ['the net area between a and b', 'the slope at b', 'the average of a and b', 'the derivative'], answer: 0, explanation: 'It accumulates signed area over [a,b].' },
      ] },
    { tier: 'A1', order: 3, slug: 'vectors-3d-geometry', title: 'Vectors & 3-D Geometry',
      summary: 'Vector algebra, dot and cross products, and lines and planes in three dimensions — the shared spine with physics.',
      outcomes: ['Add, scale and resolve vectors', 'Use the dot and cross products', 'Describe lines and planes in 3-D'],
      concepts: [
        ['Vectors carry direction', 'A vector has magnitude and direction; you add them tip-to-tail and scale them by numbers. This formalises the scalar/vector idea met in F1 motion.'],
        ['Dot and cross products', 'The dot product measures alignment (and gives work in physics); the cross product gives a perpendicular vector (and torque). 3-D lines and planes are built from vectors.'],
      ],
      mistakes: ['Adding vectors like scalars, ignoring direction.', 'Confusing the dot product (a scalar) with the cross product (a vector).', 'Mismatching components when resolving a vector.'],
      tricks: ['Dot product a·b = |a||b|cos θ — zero when perpendicular.', 'Cross product magnitude = |a||b|sin θ — zero when parallel.', 'Resolve vectors into x, y, z components and work component-wise.'],
      memory: ['"Dot = alignment (cos); cross = perpendicular (sin)."', '"Perpendicular → dot is zero."', 'Add vectors tip-to-tail.'],
      board: { CBSE: ['Cl.12 Vector Algebra', 'Cl.12 Three-Dimensional Geometry'], ICSE: ['Cl.12 Vectors'], IB: ['DP Vectors HL'] },
      comp: ['JEE-Main', 'JEE-Advanced'], keywords: ['vectors', 'dot product', 'cross product', '3D geometry'],
      xprereqs: ['math.I1.trigonometry-i'],
      quiz: [
        { lvl: 2, type: 'numeric', prompt: 'Dot product of (1,2,0) and (3,0,0)?', answer: 3, tolerance: 0, explanation: '1×3 + 2×0 + 0×0 = 3.' },
        { lvl: 2, type: 'mcq', prompt: 'If a·b = 0 (nonzero vectors), the vectors are:', choices: ['perpendicular', 'parallel', 'equal', 'opposite'], answer: 0, explanation: 'A zero dot product means the angle is 90°.' },
      ] },
    { tier: 'A1', order: 4, slug: 'matrices-determinants', title: 'Matrices & Determinants',
      summary: 'Matrix operations, determinants, and solving linear systems — with links to CS graphics and data.',
      outcomes: ['Add and multiply matrices', 'Compute determinants and inverses (2×2, 3×3)', 'Solve systems with matrices'],
      concepts: [
        ['Matrices transform and store', 'A matrix packages numbers in a grid; matrix multiplication composes linear transformations and is how graphics and data pipelines move information.'],
        ['Determinants', 'The determinant tells whether a matrix is invertible (nonzero) and scales area/volume under the transformation. It is the gatekeeper for unique solutions of linear systems.'],
      ],
      mistakes: ['Assuming matrix multiplication commutes (AB ≠ BA generally).', 'Multiplying element-wise instead of row-by-column.', 'Trying to invert a matrix with zero determinant.'],
      tricks: ['Matrix multiply: row of the first dotted with column of the second.', 'A 2×2 determinant is ad − bc.', 'Zero determinant → no unique inverse or solution.'],
      memory: ['"Row × column" for matrix products.', '"det = ad − bc" for 2×2.', '"Zero determinant, no inverse."'],
      board: { CBSE: ['Cl.12 Matrices', 'Cl.12 Determinants'], ICSE: ['Cl.12 Matrices'], IB: ['DP (Applications)'] },
      comp: ['JEE-Main', 'JEE-Advanced'], keywords: ['matrices', 'determinant', 'inverse', 'linear systems'],
      quiz: [
        { lvl: 2, type: 'numeric', prompt: 'Determinant of [[2,3],[1,4]]?', answer: 5, tolerance: 0, explanation: 'ad − bc = 2×4 − 3×1 = 5.' },
        { lvl: 2, type: 'mcq', prompt: 'A matrix has determinant 0. It is:', choices: ['not invertible', 'always invertible', 'the identity', 'symmetric'], answer: 0, explanation: 'Zero determinant means no inverse exists.' },
      ] },
    { tier: 'A1', order: 5, slug: 'complex-numbers', title: 'Complex Numbers',
      summary: 'The imaginary unit, the complex plane, modulus-argument form and De Moivre\'s theorem.',
      outcomes: ['Do arithmetic with complex numbers', 'Plot them on the Argand plane', 'Use modulus-argument form'],
      concepts: [
        ['Extending the number line to a plane', 'Defining i with i² = −1 lets every polynomial have roots. Complex numbers live on the Argand plane, with a real and imaginary axis.'],
        ['Modulus and argument', 'A complex number has a modulus (distance from origin) and argument (angle). This polar view makes multiplication a rotation-and-scale, and powers easy via De Moivre.'],
      ],
      mistakes: ['Treating i² as +1 instead of −1.', 'Forgetting to rationalise by the conjugate when dividing.', 'Mixing up real and imaginary parts.'],
      tricks: ['Multiply by the conjugate to divide complex numbers.', 'In polar form, multiply moduli and add arguments.', 'i cycles: i, −1, −i, 1, then repeats.'],
      memory: ['"i² = −1."', '"Multiply → multiply moduli, add arguments."', 'Conjugate to divide.'],
      board: { CBSE: ['Cl.11 Complex Numbers'], ICSE: ['Cl.11 Complex Numbers'], IB: ['DP Complex Numbers HL'] },
      comp: ['JEE-Main', 'JEE-Advanced'], keywords: ['complex numbers', 'imaginary unit', 'Argand plane', 'modulus', 'argument'],
      quiz: [
        { lvl: 1, type: 'mcq', prompt: 'What is i²?', choices: ['−1', '1', 'i', '0'], answer: 0, explanation: 'By definition of the imaginary unit, i² = −1.' },
        { lvl: 2, type: 'mcq', prompt: '(2 + 3i) + (1 − i) = ?', choices: ['3 + 2i', '3 + 4i', '1 + 2i', '3 − 2i'], answer: 0, explanation: 'Add real and imaginary parts: (2+1) + (3−1)i = 3 + 2i.' },
      ] },
    { tier: 'A1', order: 6, slug: 'permutations-combinations-binomial', title: 'Permutations, Combinations & Binomial Theorem',
      summary: 'Advanced counting and the binomial expansion of (a + b)ⁿ.',
      outcomes: ['Apply advanced counting arguments', 'Expand binomials with the binomial theorem', 'Find specific terms in an expansion'],
      concepts: [
        ['Binomial theorem', '(a + b)ⁿ expands with coefficients nCr — the same combinations from counting. Pascal\'s triangle lists these coefficients row by row.'],
        ['Choosing terms', 'The general term nCr·a^(n−r)·b^r lets you pick any single term (e.g., the x³ coefficient) without expanding everything.'],
      ],
      mistakes: ['Mismatching the powers of a and b (they sum to n).', 'Using nPr instead of nCr for coefficients.', 'Off-by-one in the term index r.'],
      tricks: ['General term: nCr·a^(n−r)·b^r.', 'Pascal\'s triangle gives coefficients quickly for small n.', 'Powers of a decrease while powers of b increase across the expansion.'],
      memory: ['"Coefficients are nCr (Pascal\'s triangle)."', '"Powers of a and b add to n."', 'General term picks any single term.'],
      board: { CBSE: ['Cl.11 Binomial Theorem'], ICSE: ['Cl.11 Binomial Theorem'], IB: ['DP Binomial'] },
      comp: ['JEE-Main', 'JEE-Advanced'], keywords: ['binomial theorem', 'permutations', 'combinations', 'Pascal triangle'],
      xprereqs: ['math.I2.combinatorics-probability-ii'],
      quiz: [
        { lvl: 2, type: 'mcq', prompt: 'The coefficient of the x² term in (1 + x)⁴ is:', choices: ['6', '4', '1', '12'], answer: 0, explanation: '4C2 = 6.' },
        { lvl: 1, type: 'mcq', prompt: 'Binomial coefficients come from:', choices: ['Pascal\'s triangle (nCr)', 'nPr', 'the quadratic formula', 'logarithms'], answer: 0, explanation: 'They are combinations, shown in Pascal\'s triangle.' },
      ] },

    // ================= A2 =================
    { tier: 'A2', order: 1, slug: 'differential-equations', title: 'Differential Equations (Introductory)',
      summary: 'Modelling change with equations involving derivatives, and solving separable first-order equations.',
      outcomes: ['Recognise and classify simple ODEs', 'Solve separable first-order equations', 'Model growth/decay with ODEs'],
      concepts: [
        ['Equations about rates', 'A differential equation relates a quantity to its own rate of change. dy/dx = ky models anything growing in proportion to its size — populations, decay, cooling.'],
        ['Separation of variables', 'Many first-order ODEs solve by gathering y-terms on one side and x-terms on the other, then integrating both sides. This directly reuses integration skills.'],
      ],
      mistakes: ['Forgetting the constant of integration (fixed by an initial condition).', 'Not fully separating variables before integrating.', 'Losing the exponential form of growth/decay solutions.'],
      tricks: ['dy/dx = ky solves to y = A·e^(kx).', 'Use the initial condition to pin down the constant.', 'Separate: all y with dy on one side, all x with dx on the other.'],
      memory: ['"Rate ∝ amount → exponential."', '"Separate, then integrate both sides."', 'Initial condition fixes the constant.'],
      board: { CBSE: ['Cl.12 Differential Equations'], ICSE: ['Cl.12 Differential Equations'], IB: ['DP Calculus HL'] },
      comp: ['JEE-Main', 'JEE-Advanced'], keywords: ['differential equations', 'separable', 'growth', 'decay'],
      xprereqs: ['math.A1.integration-techniques'],
      quiz: [
        { lvl: 2, type: 'mcq', prompt: 'The solution of dy/dx = ky is:', choices: ['y = A e^{kx}', 'y = kx + c', 'y = x^k', 'y = k/x'], answer: 0, explanation: 'Proportional growth gives exponential solutions.' },
        { lvl: 3, type: 'mcq', prompt: 'To solve dy/dx = xy you first:', choices: ['separate variables', 'use the quadratic formula', 'differentiate again', 'take logs of x only'], answer: 0, explanation: 'Separate: dy/y = x dx, then integrate.' },
      ] },
    { tier: 'A2', order: 2, slug: 'probability-distributions', title: 'Probability Distributions & Statistics III',
      summary: 'Random variables, the binomial and normal distributions, and the basics of inference.',
      outcomes: ['Work with random variables and expectation', 'Use binomial and normal distributions', 'Understand inference intuitively'],
      concepts: [
        ['Random variables', 'A random variable assigns numbers to outcomes; its expectation is the long-run average. Distributions describe how probability spreads over values.'],
        ['Binomial and normal', 'The binomial counts successes in fixed trials; the normal (bell curve) models continuous measurements and approximates many distributions — the backbone of statistical inference.'],
      ],
      mistakes: ['Using the binomial when trials are not independent or fixed in number.', 'Forgetting the normal is continuous (probabilities are areas, not heights).', 'Confusing standard deviation with variance in the normal.'],
      tricks: ['Binomial mean = np; a quick sanity check.', 'For the normal, convert to z-scores to use standard tables.', 'About 68% of normal data lies within one standard deviation of the mean.'],
      memory: ['"Binomial mean = np."', '"Normal probabilities are areas."', '"68–95–99.7 rule" for the bell curve.'],
      board: { CBSE: ['Cl.12 Probability (Distributions)'], ICSE: ['Cl.12 Probability'], IB: ['DP Statistics'] },
      comp: ['JEE-Main', 'NEET'], keywords: ['distributions', 'binomial', 'normal', 'random variable', 'inference'],
      xprereqs: ['math.I2.combinatorics-probability-ii'],
      quiz: [
        { lvl: 2, type: 'numeric', prompt: 'A fair coin is flipped 10 times. Expected number of heads?', answer: 5, tolerance: 0, explanation: 'Binomial mean np = 10 × 0.5 = 5.' },
        { lvl: 2, type: 'mcq', prompt: 'In a normal distribution, roughly what fraction lies within 1 SD of the mean?', choices: ['68%', '50%', '95%', '99%'], answer: 0, explanation: 'The empirical rule: about 68%.' },
      ] },
    { tier: 'A2', order: 3, slug: 'conics', title: 'Advanced Coordinate Geometry: Conics',
      summary: 'Parabolas, ellipses and hyperbolas as slices of a cone, with their equations and properties.',
      outcomes: ['Recognise conic equations', 'Identify foci, axes and eccentricity', 'Apply conics to real situations (orbits, reflectors)'],
      concepts: [
        ['One family, sliced differently', 'Circle, ellipse, parabola and hyperbola all arise as slices of a cone. Their standard equations share a structure, and eccentricity measures how "stretched" each is.'],
        ['Foci and applications', 'Each conic has focal points with reflective properties — parabolas focus parallel rays (satellite dishes), ellipses model planetary orbits.'],
      ],
      mistakes: ['Confusing the standard forms of ellipse and hyperbola (sign of the y² term).', 'Misidentifying which axis is major.', 'Forgetting eccentricity ranges: 0 (circle) to ≥1 (hyperbola).'],
      tricks: ['Sign between x² and y² terms: plus → ellipse, minus → hyperbola.', 'Eccentricity e: 0 circle, <1 ellipse, 1 parabola, >1 hyperbola.', 'Locate foci from a and b in the standard form.'],
      memory: ['"Plus → ellipse, minus → hyperbola."', '"Eccentricity grows: circle→ellipse→parabola→hyperbola."', 'Parabolas focus parallel rays.'],
      board: { CBSE: ['Cl.11 Conic Sections'], ICSE: ['Cl.11 Conics'], IB: ['DP (Applications)'] },
      comp: ['JEE-Main', 'JEE-Advanced'], keywords: ['conics', 'parabola', 'ellipse', 'hyperbola', 'eccentricity'],
      xprereqs: ['math.I1.coordinate-geometry'],
      quiz: [
        { lvl: 2, type: 'mcq', prompt: 'x²/9 − y²/4 = 1 is a:', choices: ['hyperbola', 'ellipse', 'parabola', 'circle'], answer: 0, explanation: 'The minus sign between the squared terms marks a hyperbola.' },
        { lvl: 1, type: 'mcq', prompt: 'A circle has eccentricity:', choices: ['0', '1', '>1', 'between 0 and 1'], answer: 0, explanation: 'A circle is the special conic with eccentricity 0.' },
      ] },
    { tier: 'A2', order: 4, slug: 'advanced-problem-solving', title: 'Advanced Problem-Solving Portfolio',
      summary: 'Multi-topic, competition-style structured problems that build transfer and stamina.',
      outcomes: ['Combine techniques across topics', 'Plan a multi-step solution', 'Communicate reasoning clearly'],
      concepts: [
        ['Problem-solving as a skill', 'Hard problems rarely name their method. The skill is recognising which tools apply, trying a strategy, and adjusting — exactly what competitive exams test.'],
        ['Structured attack', 'Restate the problem, note what is given and wanted, try a simpler case, and look for an invariant or symmetry. A deliberate process beats staring.'],
      ],
      mistakes: ['Jumping to compute before understanding what is asked.', 'Abandoning a promising approach too early.', 'Not checking the answer against the problem\'s constraints.'],
      tricks: ['Solve a smaller version first to find the pattern.', 'Look for symmetry, invariants, or a clever substitution.', 'Write the plan before the algebra; it prevents dead ends.'],
      memory: ['"Understand → plan → do → check" (Pólya).', '"Try a simpler case."', 'Look for invariants and symmetry.'],
      board: { CBSE: ['Integrated (all Cl.11-12 topics)'], ICSE: ['Integrated'], IB: ['DP problem-solving'] },
      comp: ['JEE-Advanced'], keywords: ['problem solving', 'transfer', 'strategy', 'competition'],
      quiz: [
        { lvl: 3, type: 'mcq', prompt: 'A good first step on an unfamiliar problem is often to:', choices: ['solve a simpler version to find a pattern', 'give up if no formula is obvious', 'guess a numeric answer', 'skip reading the constraints'], answer: 0, explanation: 'Reducing to a simpler case exposes the structure.' },
        { lvl: 3, type: 'mcq', prompt: 'Pólya\'s four steps are understand, plan, do, and:', choices: ['check', 'memorise', 'repeat', 'submit'], answer: 0, explanation: 'The final step is to look back and check.' },
      ] },
    { tier: 'A2', order: 5, slug: 'modeling-capstone', title: 'Mathematical Modeling Capstone', core: true,
      summary: 'A real modelling project: turn a messy real-world situation into mathematics, solve, and write it up.',
      outcomes: ['Translate a real situation into a model', 'Solve and interpret the model', 'Communicate assumptions and limitations'],
      concepts: [
        ['Modelling cycle', 'Modelling loops: simplify reality with assumptions, build equations, solve, then check against reality and refine. The write-up must state assumptions honestly.'],
        ['Judgement over technique', 'The hard part is deciding what to include and ignore. A simple model you understand beats a complex one you cannot justify — and this links directly to English argumentation and CS implementation.'],
      ],
      mistakes: ['Hiding assumptions instead of stating them.', 'Over-complicating the model beyond what the data supports.', 'Failing to check the model against real observations.'],
      tricks: ['State every assumption explicitly — it is part of the answer.', 'Start with the simplest model, then add realism only if needed.', 'Sanity-check outputs against known real values.'],
      memory: ['"Assume, build, solve, check, refine."', '"Simplest useful model wins."', 'State assumptions — they are the argument.'],
      board: { CBSE: ['Integrated application'], ICSE: ['Project work'], IB: ['DP Mathematics: exploration/IA'] },
      comp: [], keywords: ['modelling', 'capstone', 'assumptions', 'application'],
      quiz: [
        { lvl: 3, type: 'mcq', prompt: 'The most important thing to state in a model write-up is:', choices: ['the assumptions made', 'the author\'s name', 'the software used', 'the page count'], answer: 0, explanation: 'Assumptions define what the model means and its limits.' },
        { lvl: 2, type: 'mcq', prompt: 'Between two models that fit equally well, prefer:', choices: ['the simpler one you understand', 'the most complex', 'the one with more variables', 'either at random'], answer: 0, explanation: 'Parsimony: the simplest adequate model is best.' },
      ] },
  ],
};
