// Physics — full curriculum dataset. Module-level content for every topic.
// The F1 flagship (motion) is listed for ordering/linking only; its directory
// already exists and the generator skips it.
export default {
  subject: 'physics',
  topics: [
    // ================= F1 =================
    { tier: 'F1', order: 1, slug: 'measurement-units-estimation', title: 'Measurement, Units & Estimation',
      summary: 'SI units, unit conversion as ratio reasoning, significant figures and Fermi estimation.',
      outcomes: ['Use SI units and convert between them', 'Apply significant figures', 'Make order-of-magnitude estimates'],
      concepts: [
        ['Measurement needs units', 'A number without a unit is meaningless in physics. SI units (metre, kilogram, second) form a consistent system, and converting between units is just scaling a ratio.'],
        ['Significant figures and estimation', 'Significant figures communicate precision honestly. Fermi estimation — breaking a hard quantity into rough factors — gives a defensible ballpark and checks detailed answers.'],
      ],
      mistakes: ['Dropping units mid-calculation and losing track of what a number means.', 'Reporting more significant figures than the data justifies.', 'Converting units by guessing the direction of the factor.'],
      tricks: ['Carry units through every step — they cancel like algebra and flag errors.', 'Convert by multiplying by a fraction equal to 1 (e.g., 1000 m / 1 km).', 'Estimate by rounding each factor to one significant figure.'],
      memory: ['"Every quantity carries a unit."', '"Units cancel like algebra."', 'Fermi estimate = product of rough factors.'],
      board: { CBSE: ['Cl.11 Units & Measurement'], ICSE: ['Cl.9 Measurements'], IB: ['DP Measurement & Uncertainty'] },
      comp: ['JEE-Main', 'NEET'], keywords: ['units', 'SI', 'measurement', 'significant figures', 'estimation'],
      xprereqs: ['math.F1.ratio-proportion-percentage'],
      quiz: [
        { lvl: 1, type: 'numeric', prompt: 'Convert 2.5 km to metres.', answer: 2500, tolerance: 0, unit: 'm', explanation: '2.5 × 1000 = 2500 m.' },
        { lvl: 2, type: 'mcq', prompt: 'How many significant figures in 0.00340?', choices: ['3', '2', '5', '6'], answer: 0, explanation: 'Leading zeros do not count; 3, 4 and the trailing 0 do → 3.' },
      ] },
    { tier: 'F1', order: 2, slug: 'motion-speed-velocity-acceleration', idOverride: 'physics.F1.motion', title: 'Motion: Speed, Velocity & Acceleration',
      summary: 'Flagship deep-dive topic (see full content).', outcomes: [], concepts: [], mistakes: [], tricks: [], memory: [], board: {}, comp: ['JEE-Main', 'NEET'], keywords: ['motion'], quiz: [] },
    { tier: 'F1', order: 3, slug: 'force-newtons-laws', title: 'Force & Newton\'s Laws (Introductory)',
      summary: 'Forces as pushes and pulls, and Newton\'s three laws applied quantitatively in one dimension.',
      outcomes: ['State and apply Newton\'s three laws', 'Use F = ma in 1-D', 'Identify action-reaction pairs'],
      concepts: [
        ['The three laws', 'A body stays at rest or constant velocity unless a net force acts (1st law); force equals mass times acceleration, F = ma (2nd law); every force has an equal and opposite reaction (3rd law).'],
        ['Net force decides motion', 'It is the net (resultant) force that causes acceleration. Balanced forces mean no acceleration — not necessarily no motion.'],
      ],
      mistakes: ['Thinking a moving object needs a continuous force (it does not — only to accelerate).', 'Adding forces without regard to direction.', 'Pairing action and reaction on the same object (they act on different bodies).'],
      tricks: ['Draw a free-body diagram and find the net force first.', 'F = ma: solve for whichever of F, m, a is unknown.', 'Action and reaction always act on two different objects.'],
      memory: ['"No net force, no acceleration."', '"F = ma."', '"Every action has an equal, opposite reaction — on the other body."'],
      board: { CBSE: ['Cl.9 Force & Laws of Motion', 'Cl.11 Laws of Motion'], ICSE: ['Cl.9-10 Force & Motion'], IB: ['DP Mechanics'] },
      comp: ['JEE-Main', 'NEET'], keywords: ['force', 'Newton laws', 'F=ma', 'free-body diagram'],
      quiz: [
        { lvl: 1, type: 'numeric', prompt: 'A 2 kg object accelerates at 3 m/s². Net force?', answer: 6, tolerance: 0, unit: 'N', explanation: 'F = ma = 2 × 3 = 6 N.' },
        { lvl: 2, type: 'mcq', prompt: 'A ball rolls at constant velocity on a frictionless floor. The net force is:', choices: ['zero', 'forward', 'backward', 'downward only'], answer: 0, explanation: 'Constant velocity means zero net force (1st law).' },
      ] },
    { tier: 'F1', order: 4, slug: 'energy-i', title: 'Energy I',
      summary: 'Work, kinetic and potential energy, and conservation of energy as an accounting principle.',
      outcomes: ['Calculate work, KE and PE', 'Apply conservation of energy', 'Relate work done to energy change'],
      concepts: [
        ['Work transfers energy', 'Work = force × distance in the direction of the force. Doing work on an object changes its energy — the work-energy link.'],
        ['Conservation as accounting', 'Energy is neither created nor destroyed, only transformed. Total energy before = total after; tracking KE (½mv²) and PE (mgh) like a ledger solves many problems without forces.'],
      ],
      mistakes: ['Including force perpendicular to motion in work (it does zero work).', 'Forgetting the ½ in kinetic energy ½mv².', 'Not accounting for energy lost to friction/heat.'],
      tricks: ['Use energy conservation to skip messy force analysis.', 'KE = ½mv², PE = mgh — memorise both.', 'Only the component of force along the motion does work.'],
      memory: ['"Energy is conserved — it just changes form."', '"KE = ½mv², PE = mgh."', '"Work = force along the motion × distance."'],
      board: { CBSE: ['Cl.9 Work & Energy', 'Cl.11 Work, Energy & Power'], ICSE: ['Cl.9-10 Work, Energy'], IB: ['DP Energy'] },
      comp: ['JEE-Main', 'NEET'], keywords: ['work', 'energy', 'kinetic', 'potential', 'conservation'],
      quiz: [
        { lvl: 1, type: 'numeric', prompt: 'KE of a 2 kg object moving at 3 m/s?', answer: 9, tolerance: 0, unit: 'J', explanation: '½mv² = ½·2·9 = 9 J.' },
        { lvl: 2, type: 'numeric', prompt: 'Work done lifting 5 N through 2 m (against gravity)?', answer: 10, tolerance: 0, unit: 'J', explanation: 'W = F·d = 5 × 2 = 10 J.' },
      ] },

    // ================= F2 =================
    { tier: 'F2', order: 1, slug: 'pressure-density', title: 'Pressure & Density',
      summary: 'Density as mass per volume, pressure in fluids, and buoyancy — more ratio reasoning applied.',
      outcomes: ['Compute density and pressure', 'Explain pressure in fluids', 'Apply buoyancy and floating'],
      concepts: [
        ['Density and pressure are rates', 'Density = mass/volume and pressure = force/area — both are ratios. Pressure in a fluid increases with depth and acts equally in all directions.'],
        ['Buoyancy', 'A submerged object feels an upthrust equal to the weight of fluid it displaces (Archimedes). It floats when upthrust balances weight.'],
      ],
      mistakes: ['Confusing mass with weight, or density with pressure.', 'Forgetting pressure increases with depth.', 'Thinking heavier objects always sink (it depends on density).'],
      tricks: ['Density = mass ÷ volume; pressure = force ÷ area.', 'An object floats if its density is less than the fluid\'s.', 'Fluid pressure depends on depth, not container shape.'],
      memory: ['"Density = mass/volume; pressure = force/area."', '"Upthrust = weight of displaced fluid."', 'Float if less dense than the fluid.'],
      board: { CBSE: ['Cl.8-9 Force & Pressure', 'Cl.9 Gravitation (Buoyancy)'], ICSE: ['Cl.8-9 Pressure & Upthrust'], IB: ['DP Fluids'] },
      comp: ['JEE-Main', 'NEET'], keywords: ['pressure', 'density', 'buoyancy', 'Archimedes'],
      xprereqs: ['math.F1.ratio-proportion-percentage'],
      quiz: [
        { lvl: 1, type: 'numeric', prompt: 'Density of 200 g in 100 cm³ (in g/cm³)?', answer: 2, tolerance: 0, unit: 'g/cm^3', explanation: '200/100 = 2 g/cm³.' },
        { lvl: 2, type: 'mcq', prompt: 'An object floats when its density is:', choices: ['less than the fluid', 'greater than the fluid', 'equal to zero', 'equal to its mass'], answer: 0, explanation: 'Lower density than the fluid means it floats.' },
      ] },
    { tier: 'F2', order: 2, slug: 'heat-temperature', title: 'Heat & Temperature',
      summary: 'The particle model of heat, temperature vs thermal energy, transfer methods and specific heat.',
      outcomes: ['Distinguish heat from temperature', 'Describe conduction, convection, radiation', 'Use specific heat capacity'],
      concepts: [
        ['Heat vs temperature', 'Temperature measures average particle kinetic energy; heat is energy transferred due to a temperature difference. A spark is hot but carries little heat.'],
        ['Specific heat', 'Specific heat capacity is the energy to raise 1 kg by 1°C. Q = mcΔT lets you compute heating and cooling quantitatively.'],
      ],
      mistakes: ['Using "heat" and "temperature" interchangeably.', 'Forgetting ΔT is a difference, not an absolute temperature.', 'Ignoring the mass in Q = mcΔT.'],
      tricks: ['Q = mcΔT for heating/cooling calculations.', 'Metals conduct well; gases insulate — think particle spacing.', 'Convection needs a fluid; radiation needs no medium.'],
      memory: ['"Temperature = average KE; heat = energy in transit."', '"Q = mcΔT."', 'Conduction, convection, radiation — three transfer routes.'],
      board: { CBSE: ['Cl.7 Heat', 'Cl.11 Thermal Properties'], ICSE: ['Cl.7-9 Heat'], IB: ['DP Thermal Physics'] },
      comp: ['JEE-Main', 'NEET'], keywords: ['heat', 'temperature', 'specific heat', 'conduction', 'convection'],
      quiz: [
        { lvl: 2, type: 'numeric', prompt: 'Heat to raise 2 kg of water (c=4200) by 5°C?', answer: 42000, tolerance: 0, unit: 'J', explanation: 'Q = mcΔT = 2×4200×5 = 42000 J.' },
        { lvl: 1, type: 'mcq', prompt: 'Which transfer method needs no medium?', choices: ['radiation', 'conduction', 'convection', 'none'], answer: 0, explanation: 'Radiation travels through vacuum as electromagnetic waves.' },
      ] },
    { tier: 'F2', order: 3, slug: 'light-i', title: 'Light I',
      summary: 'Light as rays: reflection, refraction and simple lenses, using the geometry of similar triangles.',
      outcomes: ['Apply the laws of reflection and refraction', 'Trace rays through mirrors and lenses', 'Explain image formation'],
      concepts: [
        ['Rays and reflection', 'Light travels in straight rays; on reflection the angle of incidence equals the angle of reflection. This explains mirrors and shadows.'],
        ['Refraction and lenses', 'Light bends when it changes medium (refraction), which is how lenses form images. Ray diagrams predict image position, size and orientation.'],
      ],
      mistakes: ['Measuring angles from the surface instead of the normal.', 'Confusing real and virtual images.', 'Mixing up converging and diverging lenses.'],
      tricks: ['Always measure angles from the normal, not the surface.', 'Convex lens converges; concave diverges.', 'Use two standard rays to locate an image.'],
      memory: ['"Angle in = angle out" (from the normal).', '"Convex converges, concave diverges."', 'Refraction = bending on changing medium.'],
      board: { CBSE: ['Cl.7-8 Light', 'Cl.10 Light: Reflection & Refraction'], ICSE: ['Cl.8-10 Light'], IB: ['DP Waves/Optics'] },
      comp: ['JEE-Main', 'NEET'], keywords: ['light', 'reflection', 'refraction', 'lens', 'ray diagram'],
      xprereqs: ['math.F2.geometry-similarity-pythagoras'],
      quiz: [
        { lvl: 1, type: 'numeric', prompt: 'A ray hits a mirror at 30° to the normal. Angle of reflection?', answer: 30, tolerance: 0, unit: '°', explanation: 'Reflection angle equals incidence angle: 30°.' },
        { lvl: 2, type: 'mcq', prompt: 'A convex lens is:', choices: ['converging', 'diverging', 'flat', 'reflective'], answer: 0, explanation: 'Convex lenses bring parallel rays to a focus.' },
      ] },
    { tier: 'F2', order: 4, slug: 'sound-waves-i', title: 'Sound & Waves I',
      summary: 'Wave parameters, the wave equation v = fλ, and properties of sound.',
      outcomes: ['Define frequency, wavelength, amplitude', 'Use v = fλ', 'Explain how sound travels'],
      concepts: [
        ['Wave anatomy', 'A wave has wavelength (length of one cycle), frequency (cycles per second) and amplitude (size). Speed, frequency and wavelength are linked by v = fλ — another rate relationship.'],
        ['Sound needs a medium', 'Sound is a pressure wave that needs particles to travel; it cannot cross a vacuum. Pitch relates to frequency, loudness to amplitude.'],
      ],
      mistakes: ['Confusing frequency with wavelength.', 'Thinking sound travels through vacuum.', 'Mixing up amplitude (loudness) and frequency (pitch).'],
      tricks: ['v = fλ links the three wave quantities.', 'Higher frequency → higher pitch; bigger amplitude → louder.', 'Sound travels faster in solids than gases (particles closer).'],
      memory: ['"v = f λ."', '"Frequency = pitch; amplitude = loudness."', 'No medium, no sound.'],
      board: { CBSE: ['Cl.8-9 Sound'], ICSE: ['Cl.8-9 Sound'], IB: ['DP Waves'] },
      comp: ['JEE-Main', 'NEET'], keywords: ['sound', 'waves', 'frequency', 'wavelength', 'v=fλ'],
      quiz: [
        { lvl: 1, type: 'numeric', prompt: 'A wave has f = 50 Hz and λ = 2 m. Speed?', answer: 100, tolerance: 0, unit: 'm/s', explanation: 'v = fλ = 50 × 2 = 100 m/s.' },
        { lvl: 2, type: 'mcq', prompt: 'Sound cannot travel through:', choices: ['a vacuum', 'air', 'water', 'steel'], answer: 0, explanation: 'It is a mechanical wave needing a medium.' },
      ] },
    { tier: 'F2', order: 5, slug: 'electricity-i', title: 'Electricity I',
      summary: 'Current, voltage, resistance and Ohm\'s law, with series and parallel circuits.',
      outcomes: ['Define current, voltage, resistance', 'Apply Ohm\'s law V = IR', 'Analyse series and parallel circuits'],
      concepts: [
        ['Ohm\'s law', 'Voltage drives current through resistance: V = IR. It is the central relationship of simple circuits and, like many physics laws, a proportionality.'],
        ['Series vs parallel', 'In series, current is the same and resistances add; in parallel, voltage is the same and currents split. These rules follow from conservation of charge and energy.'],
      ],
      mistakes: ['Swapping the roles of voltage and current.', 'Adding parallel resistances as if in series.', 'Forgetting current is the same throughout a series circuit.'],
      tricks: ['V = IR — cover the unknown to solve.', 'Series resistances add; parallel add as reciprocals.', 'Current splits in parallel, stays whole in series.'],
      memory: ['"V = IR."', '"Series adds R; parallel adds 1/R."', 'Same current in series, same voltage in parallel.'],
      board: { CBSE: ['Cl.10 Electricity'], ICSE: ['Cl.9-10 Current Electricity'], IB: ['DP Electricity'] },
      comp: ['JEE-Main', 'NEET'], keywords: ['current', 'voltage', 'resistance', 'Ohm law', 'circuits'],
      xprereqs: ['math.F1.linear-equations-one-variable'],
      quiz: [
        { lvl: 1, type: 'numeric', prompt: '3 V across a 6 Ω resistor. Current?', answer: 0.5, tolerance: 0, unit: 'A', explanation: 'I = V/R = 3/6 = 0.5 A.' },
        { lvl: 2, type: 'mcq', prompt: 'In a series circuit, the current is:', choices: ['the same everywhere', 'different in each part', 'zero', 'largest at the battery'], answer: 0, explanation: 'Charge is conserved, so series current is uniform.' },
      ] },
    { tier: 'F2', order: 6, slug: 'magnetism-i', title: 'Magnetism I',
      summary: 'Magnetic fields, electromagnets and the link between electricity and magnetism.',
      outcomes: ['Describe magnetic fields and poles', 'Explain electromagnets', 'Relate current to magnetism'],
      concepts: [
        ['Fields and poles', 'Magnets have north and south poles; like poles repel, unlike attract. Field lines run from north to south and show the field\'s direction and strength.'],
        ['Electromagnetism', 'A current creates a magnetic field around it. Coiling wire into a solenoid concentrates the field, making an electromagnet — the basis of motors and relays.'],
      ],
      mistakes: ['Thinking magnetic poles can be isolated (they always come in pairs).', 'Reversing field-line direction (north to south outside the magnet).', 'Forgetting current is needed for an electromagnet.'],
      tricks: ['Field lines go north → south outside the magnet.', 'More turns or more current → stronger electromagnet.', 'Right-hand grip rule gives the field direction around a wire.'],
      memory: ['"Like poles repel, unlike attract."', '"Current makes magnetism."', 'Right-hand grip rule for field direction.'],
      board: { CBSE: ['Cl.10 Magnetic Effects of Current'], ICSE: ['Cl.10 Magnetism'], IB: ['DP Fields'] },
      comp: ['JEE-Main', 'NEET'], keywords: ['magnetism', 'magnetic field', 'electromagnet', 'poles'],
      quiz: [
        { lvl: 1, type: 'mcq', prompt: 'Two north poles brought together will:', choices: ['repel', 'attract', 'do nothing', 'cancel'], answer: 0, explanation: 'Like poles repel.' },
        { lvl: 2, type: 'mcq', prompt: 'An electromagnet gets stronger if you:', choices: ['add more coil turns', 'remove the battery', 'shorten the wire only', 'cool it to zero current'], answer: 0, explanation: 'More turns (and more current) increase field strength.' },
      ] },

    // ================= I1 =================
    { tier: 'I1', order: 1, slug: 'kinematics-2d', title: 'Kinematics in Two Dimensions',
      summary: 'Vectors applied to motion — resolving into components and analysing projectiles.',
      outcomes: ['Resolve velocity into components', 'Analyse projectile motion', 'Treat horizontal and vertical motion independently'],
      concepts: [
        ['Independence of components', 'Horizontal and vertical motion are independent: gravity affects only the vertical. Splitting a velocity into x and y components (using trig) turns 2-D motion into two 1-D problems.'],
        ['Projectiles', 'A projectile has constant horizontal velocity and vertical acceleration g. Combining the two components gives its parabolic path, range and time of flight.'],
      ],
      mistakes: ['Applying gravity to the horizontal component.', 'Forgetting to resolve the launch velocity into components.', 'Mixing the horizontal and vertical equations.'],
      tricks: ['Split velocity: vₓ = v cos θ, v_y = v sin θ.', 'Horizontal motion is constant-velocity; vertical is free-fall.', 'Time of flight is set by the vertical motion.'],
      memory: ['"Horizontal and vertical are independent."', '"Resolve with cos and sin."', 'Gravity acts only vertically.'],
      board: { CBSE: ['Cl.11 Motion in a Plane'], ICSE: ['Cl.11 Kinematics'], IB: ['DP Mechanics'] },
      comp: ['JEE-Main', 'JEE-Advanced', 'NEET'], keywords: ['projectile', 'components', 'vectors', 'kinematics'],
      xprereqs: ['math.I1.trigonometry-i'],
      quiz: [
        { lvl: 2, type: 'mcq', prompt: 'For a projectile, the horizontal velocity (no air resistance):', choices: ['stays constant', 'decreases with g', 'increases with g', 'is zero'], answer: 0, explanation: 'Gravity acts only vertically, so horizontal velocity is constant.' },
        { lvl: 2, type: 'numeric', prompt: 'A velocity of 10 m/s at 30°: horizontal component (cos30≈0.87)?', answer: 8.7, tolerance: 0.2, unit: 'm/s', explanation: 'vₓ = 10 cos30° ≈ 8.7 m/s.' },
      ] },
    { tier: 'I1', order: 2, slug: 'newtons-laws-deepened', title: 'Newton\'s Laws Deepened',
      summary: 'Friction, inclined planes and connected systems of bodies.',
      outcomes: ['Include friction in force analysis', 'Solve inclined-plane problems', 'Analyse connected bodies'],
      concepts: [
        ['Friction', 'Friction opposes relative motion and is proportional to the normal force (F ≤ μN). It converts kinetic energy to heat and must be added to force diagrams.'],
        ['Inclines and systems', 'On a slope, resolve weight into components along and perpendicular to the surface. For connected bodies, apply F = ma to each and to the system.'],
      ],
      mistakes: ['Using the full weight instead of its component along the incline.', 'Forgetting friction acts opposite to motion.', 'Treating a connected system without consistent acceleration.'],
      tricks: ['Resolve weight on an incline: mg sinθ along, mg cosθ into the surface.', 'Friction magnitude = μ × normal force.', 'For linked masses, the whole system shares one acceleration.'],
      memory: ['"mg sinθ down the slope, mg cosθ into it."', '"Friction = μN, opposing motion."', 'Connected bodies share an acceleration.'],
      board: { CBSE: ['Cl.11 Laws of Motion (Friction)'], ICSE: ['Cl.11 Dynamics'], IB: ['DP Mechanics'] },
      comp: ['JEE-Main', 'JEE-Advanced', 'NEET'], keywords: ['friction', 'inclined plane', 'connected bodies', 'normal force'],
      quiz: [
        { lvl: 2, type: 'numeric', prompt: 'Friction with μ=0.2 and normal force 50 N?', answer: 10, tolerance: 0, unit: 'N', explanation: 'F = μN = 0.2 × 50 = 10 N.' },
        { lvl: 2, type: 'mcq', prompt: 'On a frictionless incline, the force pulling a block down the slope is:', choices: ['mg sinθ', 'mg cosθ', 'mg', 'zero'], answer: 0, explanation: 'The along-slope component of weight is mg sinθ.' },
      ] },
    { tier: 'I1', order: 3, slug: 'momentum-collisions', title: 'Momentum & Collisions',
      summary: 'Momentum, impulse and the conservation of momentum in collisions.',
      outcomes: ['Compute momentum and impulse', 'Apply conservation of momentum', 'Distinguish elastic and inelastic collisions'],
      concepts: [
        ['Momentum and impulse', 'Momentum p = mv; impulse (force × time) changes momentum. A small force over a long time can produce the same change as a large brief force.'],
        ['Conservation in collisions', 'With no external force, total momentum is conserved in any collision. Elastic collisions also conserve kinetic energy; inelastic ones do not.'],
      ],
      mistakes: ['Forgetting momentum is a vector (direction matters).', 'Assuming kinetic energy is conserved in all collisions.', 'Ignoring external forces when applying conservation.'],
      tricks: ['Total momentum before = total after (closed system).', 'Impulse = force × time = change in momentum.', 'Perfectly inelastic: objects stick and move together.'],
      memory: ['"Momentum is conserved when no external force acts."', '"p = mv; impulse = Δp."', 'Elastic keeps KE; inelastic loses it.'],
      board: { CBSE: ['Cl.11 Laws of Motion (Momentum)'], ICSE: ['Cl.11 Momentum'], IB: ['DP Momentum'] },
      comp: ['JEE-Main', 'JEE-Advanced', 'NEET'], keywords: ['momentum', 'impulse', 'collisions', 'conservation'],
      quiz: [
        { lvl: 1, type: 'numeric', prompt: 'Momentum of 3 kg at 4 m/s?', answer: 12, tolerance: 0, unit: 'kg·m/s', explanation: 'p = mv = 12 kg·m/s.' },
        { lvl: 2, type: 'mcq', prompt: 'In a perfectly inelastic collision, the colliding objects:', choices: ['stick together', 'bounce with no energy loss', 'reverse at equal speed', 'gain kinetic energy'], answer: 0, explanation: 'They move as one afterwards; KE is not conserved.' },
      ] },
    { tier: 'I1', order: 4, slug: 'circular-motion-gravitation', title: 'Circular Motion & Gravitation',
      summary: 'Centripetal acceleration, orbits and Newton\'s law of gravitation.',
      outcomes: ['Explain centripetal force', 'Use the gravitation law', 'Describe orbital motion'],
      concepts: [
        ['Centripetal force', 'Circular motion at constant speed still accelerates — toward the centre. A net centripetal force (mv²/r) is required; remove it and the object flies off tangentially.'],
        ['Gravitation', 'Every mass attracts every other with F = Gm₁m₂/r². This same force keeps planets in orbit, balancing the centripetal requirement.'],
      ],
      mistakes: ['Thinking there is an outward "centrifugal force" on the object.', 'Forgetting circular motion is accelerated even at constant speed.', 'Using r linearly instead of r² in gravitation.'],
      tricks: ['Centripetal acceleration = v²/r, directed inward.', 'Gravity follows an inverse-square law: double r → quarter force.', 'Orbits balance gravity against the centripetal requirement.'],
      memory: ['"Centripetal force points inward, = mv²/r."', '"Gravity ∝ 1/r²."', 'Constant speed on a circle still means acceleration.'],
      board: { CBSE: ['Cl.11 Gravitation', 'Cl.11 Motion in a Plane'], ICSE: ['Cl.11 Circular Motion & Gravitation'], IB: ['DP Circular Motion & Gravitation'] },
      comp: ['JEE-Main', 'JEE-Advanced', 'NEET'], keywords: ['circular motion', 'centripetal', 'gravitation', 'orbits'],
      quiz: [
        { lvl: 2, type: 'mcq', prompt: 'The centripetal force on an orbiting satellite points:', choices: ['toward the planet', 'along its velocity', 'away from the planet', 'backward'], answer: 0, explanation: 'It is directed toward the centre — gravity provides it.' },
        { lvl: 3, type: 'mcq', prompt: 'If distance doubles, gravitational force becomes:', choices: ['one quarter', 'half', 'double', 'four times'], answer: 0, explanation: 'Inverse-square: F ∝ 1/r², so ×1/4.' },
      ] },
    { tier: 'I1', order: 5, slug: 'energy-ii', title: 'Energy II',
      summary: 'Power, efficiency and energy resources, treated quantitatively.',
      outcomes: ['Calculate power and efficiency', 'Track energy through transformations', 'Compare energy resources'],
      concepts: [
        ['Power and efficiency', 'Power is the rate of doing work (P = W/t). Efficiency is useful output ÷ total input — always below 100% because some energy dissipates as heat.'],
        ['Energy in the real world', 'Every device transforms energy with losses. Comparing resources means comparing energy density, renewability and conversion efficiency.'],
      ],
      mistakes: ['Confusing energy (joules) with power (watts).', 'Reporting efficiency above 100%.', 'Ignoring wasted heat in an energy balance.'],
      tricks: ['Power = work ÷ time; 1 watt = 1 joule per second.', 'Efficiency = useful ÷ total, as a percentage.', 'Track where "lost" energy goes — usually heat.'],
      memory: ['"Power is energy per second."', '"Efficiency = useful/total ≤ 100%."', 'Lost energy becomes heat.'],
      board: { CBSE: ['Cl.11 Work, Energy & Power'], ICSE: ['Cl.10-11 Work, Power, Energy'], IB: ['DP Energy'] },
      comp: ['JEE-Main', 'NEET'], keywords: ['power', 'efficiency', 'energy resources'],
      quiz: [
        { lvl: 1, type: 'numeric', prompt: '100 J of work in 5 s. Power?', answer: 20, tolerance: 0, unit: 'W', explanation: 'P = W/t = 100/5 = 20 W.' },
        { lvl: 2, type: 'numeric', prompt: 'Useful output 40 J from 50 J input. Efficiency (%)?', answer: 80, tolerance: 0, unit: '%', explanation: '40/50 × 100 = 80%.' },
      ] },

    // ================= I2 =================
    { tier: 'I2', order: 1, slug: 'kinematics-calculus', title: 'Kinematics with Calculus',
      summary: 'Position, velocity and acceleration as derivatives and integrals — co-taught with calculus.',
      outcomes: ['Relate position, velocity, acceleration by calculus', 'Differentiate/integrate motion functions', 'Handle non-uniform acceleration'],
      concepts: [
        ['Motion is calculus', 'Velocity is the derivative of position; acceleration is the derivative of velocity. Integrating reverses this. This makes the "slope = rate, area = distance" idea exact.'],
        ['Non-uniform acceleration', 'When acceleration varies, the SUVAT equations fail but calculus still works — integrate the actual acceleration function to get velocity and position.'],
      ],
      mistakes: ['Using SUVAT when acceleration is not constant.', 'Forgetting the constant of integration (set by initial conditions).', 'Confusing the derivative and integral directions.'],
      tricks: ['v = dx/dt, a = dv/dt; integrate to reverse.', 'Initial conditions fix the integration constants.', 'Area under a(t) gives change in velocity.'],
      memory: ['"Differentiate position → velocity → acceleration."', '"Integrate to go back."', 'Non-constant a → use calculus, not SUVAT.'],
      board: { CBSE: ['Cl.11 Motion (calculus)'], ICSE: ['Cl.11-12 Kinematics'], IB: ['DP Mechanics HL'] },
      comp: ['JEE-Main', 'JEE-Advanced'], keywords: ['kinematics', 'derivative', 'integral', 'calculus'],
      xprereqs: ['math.I2.derivatives-intuition'],
      quiz: [
        { lvl: 2, type: 'mcq', prompt: 'Velocity is the derivative of:', choices: ['position', 'acceleration', 'force', 'mass'], answer: 0, explanation: 'v = dx/dt.' },
        { lvl: 3, type: 'mcq', prompt: 'When acceleration varies with time, you should:', choices: ['integrate a(t)', 'use v = u + at', 'assume a = 0', 'use averages only'], answer: 0, explanation: 'SUVAT needs constant a; otherwise integrate.' },
      ] },
    { tier: 'I2', order: 2, slug: 'oscillations-shm', title: 'Oscillations (Simple Harmonic Motion)',
      summary: 'Simple harmonic motion: restoring force, period, and energy exchange in oscillators.',
      outcomes: ['Define SHM conditions', 'Relate period to system parameters', 'Describe energy in oscillation'],
      concepts: [
        ['Restoring force', 'SHM happens when the restoring force is proportional to displacement and directed back to equilibrium (F = −kx). Springs and small-angle pendulums are examples.'],
        ['Period and energy', 'The period depends on the system (mass and stiffness), not the amplitude. Energy sloshes between kinetic and potential twice per cycle.'],
      ],
      mistakes: ['Thinking period depends on amplitude in ideal SHM.', 'Forgetting the restoring force points back to equilibrium.', 'Confusing frequency and period (reciprocals).'],
      tricks: ['SHM needs F = −kx (proportional, restoring).', 'Period T = 1/frequency.', 'Max KE at equilibrium, max PE at the extremes.'],
      memory: ['"Restoring force ∝ −displacement."', '"Period is independent of amplitude (ideal SHM)."', 'KE and PE trade off each cycle.'],
      board: { CBSE: ['Cl.11 Oscillations'], ICSE: ['Cl.11 SHM'], IB: ['DP Oscillations HL'] },
      comp: ['JEE-Main', 'JEE-Advanced', 'NEET'], keywords: ['oscillation', 'SHM', 'period', 'restoring force'],
      quiz: [
        { lvl: 2, type: 'mcq', prompt: 'The defining condition of SHM is a restoring force proportional to:', choices: ['displacement', 'velocity', 'acceleration squared', 'time'], answer: 0, explanation: 'F = −kx: proportional to displacement, opposite in direction.' },
        { lvl: 2, type: 'mcq', prompt: 'In ideal SHM, increasing the amplitude changes the period:', choices: ['not at all', 'increases it', 'decreases it', 'doubles it'], answer: 0, explanation: 'Period is independent of amplitude in SHM.' },
      ] },
    { tier: 'I2', order: 3, slug: 'waves-ii', title: 'Waves II',
      summary: 'Superposition, standing waves, resonance and the Doppler effect.',
      outcomes: ['Apply the principle of superposition', 'Explain standing waves and resonance', 'Describe the Doppler effect'],
      concepts: [
        ['Superposition', 'When waves overlap, displacements add. This produces interference — constructive (in phase) or destructive (out of phase) — and standing waves on strings and in pipes.'],
        ['Doppler effect', 'Relative motion between source and observer shifts the observed frequency: approaching raises pitch, receding lowers it. It applies to sound and light.'],
      ],
      mistakes: ['Thinking overlapping waves collide rather than add.', 'Confusing nodes (no motion) with antinodes (max motion).', 'Getting the Doppler direction backwards.'],
      tricks: ['Add displacements point by point for superposition.', 'Standing wave: fixed nodes and antinodes; resonance at natural frequencies.', 'Approaching source → higher observed frequency.'],
      memory: ['"Waves add, they don\'t collide."', '"Nodes still, antinodes swinging."', '"Approach → higher pitch (Doppler)."'],
      board: { CBSE: ['Cl.11 Waves'], ICSE: ['Cl.11-12 Waves'], IB: ['DP Wave Phenomena HL'] },
      comp: ['JEE-Main', 'JEE-Advanced', 'NEET'], keywords: ['superposition', 'standing waves', 'resonance', 'Doppler'],
      quiz: [
        { lvl: 2, type: 'mcq', prompt: 'Two waves perfectly out of phase produce:', choices: ['destructive interference', 'constructive interference', 'a higher frequency', 'no wave motion ever'], answer: 0, explanation: 'Opposite displacements cancel — destructive interference.' },
        { lvl: 2, type: 'mcq', prompt: 'A siren approaching you sounds:', choices: ['higher pitched', 'lower pitched', 'unchanged', 'silent'], answer: 0, explanation: 'Doppler effect raises observed frequency on approach.' },
      ] },
    { tier: 'I2', order: 4, slug: 'electricity-ii', title: 'Electricity II',
      summary: 'EMF and internal resistance, Kirchhoff\'s laws, and capacitors (introductory).',
      outcomes: ['Use EMF and internal resistance', 'Apply Kirchhoff\'s laws', 'Explain capacitor basics'],
      concepts: [
        ['Real sources', 'A real cell has internal resistance, so its terminal voltage drops under load. EMF is the total energy per charge; some is lost inside the source.'],
        ['Kirchhoff\'s laws', 'Charge conservation gives the junction (current) law; energy conservation gives the loop (voltage) law. Together they solve any circuit.'],
      ],
      mistakes: ['Ignoring internal resistance in real cells.', 'Sign errors when summing voltages around a loop.', 'Confusing capacitance with resistance.'],
      tricks: ['Junction law: currents in = currents out.', 'Loop law: voltages around a loop sum to zero.', 'A capacitor stores charge Q = CV.'],
      memory: ['"Current in = current out" (junctions).', '"Voltages round a loop sum to zero."', '"Q = CV" for capacitors.'],
      board: { CBSE: ['Cl.12 Current Electricity'], ICSE: ['Cl.12 Electricity'], IB: ['DP Electricity HL'] },
      comp: ['JEE-Main', 'JEE-Advanced', 'NEET'], keywords: ['EMF', 'internal resistance', 'Kirchhoff', 'capacitor'],
      xprereqs: ['math.F2.systems-linear-equations'],
      quiz: [
        { lvl: 2, type: 'mcq', prompt: 'Kirchhoff\'s current law expresses conservation of:', choices: ['charge', 'energy', 'momentum', 'mass'], answer: 0, explanation: 'Current in equals current out — charge is conserved.' },
        { lvl: 2, type: 'numeric', prompt: 'Charge on a 2 F capacitor at 3 V?', answer: 6, tolerance: 0, unit: 'C', explanation: 'Q = CV = 2 × 3 = 6 C.' },
      ] },
    { tier: 'I2', order: 5, slug: 'thermal-physics', title: 'Thermal Physics',
      summary: 'The gas laws and kinetic theory — a topic shared with chemistry, taught once.',
      outcomes: ['Apply the gas laws', 'Relate temperature to particle motion', 'Use the ideal gas equation'],
      concepts: [
        ['Gas laws', 'Pressure, volume and temperature of a gas are linked: PV/T is constant, giving the ideal gas equation PV = nRT. Each individual law (Boyle, Charles) is a special case.'],
        ['Kinetic theory', 'A gas is countless particles in random motion; temperature measures their average kinetic energy. This microscopic picture explains the macroscopic gas laws.'],
      ],
      mistakes: ['Using Celsius instead of Kelvin in gas-law calculations.', 'Mixing up which quantity is held constant.', 'Forgetting pressure and volume are inversely related at fixed T.'],
      tricks: ['Always convert temperature to Kelvin for gas laws.', 'PV = nRT ties everything together.', 'Boyle: P↑ when V↓ (fixed T); Charles: V↑ when T↑ (fixed P).'],
      memory: ['"PV = nRT."', '"Use Kelvin, always."', 'Temperature = average particle KE.'],
      board: { CBSE: ['Cl.11 Kinetic Theory', 'Cl.11 Thermodynamics'], ICSE: ['Cl.11 Gas Laws'], IB: ['DP Thermal Physics'] },
      comp: ['JEE-Main', 'JEE-Advanced', 'NEET'], keywords: ['gas laws', 'kinetic theory', 'ideal gas', 'PV=nRT'],
      quiz: [
        { lvl: 2, type: 'mcq', prompt: 'Gas-law temperatures must be in:', choices: ['kelvin', 'celsius', 'fahrenheit', 'any unit'], answer: 0, explanation: 'Absolute temperature (K) is required.' },
        { lvl: 2, type: 'mcq', prompt: 'At fixed temperature, halving a gas\'s volume:', choices: ['doubles its pressure', 'halves its pressure', 'no change', 'doubles its temperature'], answer: 0, explanation: 'Boyle\'s law: P and V are inversely proportional.' },
      ] },

    // ================= A1 =================
    { tier: 'A1', order: 1, slug: 'mechanics-rigor', title: 'Mechanics at Full Rigor',
      summary: 'Dynamics with calculus, the work-energy theorem, and rotational motion of rigid bodies.',
      outcomes: ['Apply the work-energy theorem', 'Analyse rotational dynamics', 'Use torque and moment of inertia'],
      concepts: [
        ['Work-energy theorem', 'The net work done on a body equals its change in kinetic energy. With calculus, this handles varying forces that SUVAT cannot.'],
        ['Rotation', 'Rotating bodies have angular versions of every linear quantity: torque (force), moment of inertia (mass), angular momentum. Newton\'s laws reappear in rotational form.'],
      ],
      mistakes: ['Forgetting torque depends on the distance from the axis.', 'Using linear formulas where rotational ones are needed.', 'Ignoring the moment of inertia\'s dependence on mass distribution.'],
      tricks: ['Net work = ΔKE, even for variable forces.', 'Torque = force × perpendicular distance from the axis.', 'Angular momentum is conserved with no external torque.'],
      memory: ['"Net work = change in KE."', '"Torque = force × lever arm."', 'Angular momentum conserved without external torque.'],
      board: { CBSE: ['Cl.11 Systems of Particles & Rotational Motion'], ICSE: ['Cl.11-12 Rotational Dynamics'], IB: ['DP Mechanics HL'] },
      comp: ['JEE-Main', 'JEE-Advanced'], keywords: ['work-energy', 'rotation', 'torque', 'angular momentum'],
      xprereqs: ['math.A1.calculus-limits-differentiation'],
      quiz: [
        { lvl: 3, type: 'mcq', prompt: 'The net work done on an object equals its change in:', choices: ['kinetic energy', 'momentum', 'mass', 'temperature'], answer: 0, explanation: 'The work-energy theorem: W_net = ΔKE.' },
        { lvl: 2, type: 'mcq', prompt: 'Torque increases if you apply the force:', choices: ['farther from the axis', 'closer to the axis', 'along the axis', 'at the axis'], answer: 0, explanation: 'Torque = force × distance from the pivot.' },
      ] },
    { tier: 'A1', order: 2, slug: 'gravitation-field', title: 'Gravitation (Field Treatment)',
      summary: 'Gravitational fields, potential and energy, and orbital mechanics at depth.',
      outcomes: ['Use gravitational field strength and potential', 'Compute gravitational PE', 'Analyse orbits energetically'],
      concepts: [
        ['Fields and potential', 'A gravitational field g = F/m describes the force per unit mass at each point. Gravitational potential and PE track the energy of a mass in the field.'],
        ['Orbital energy', 'An orbit\'s total energy (kinetic + potential) determines its shape and whether it is bound. Escape velocity is the speed needed to reach zero total energy.'],
      ],
      mistakes: ['Confusing field strength (per mass) with force.', 'Sign errors — gravitational PE is negative (bound systems).', 'Forgetting the inverse-square dependence.'],
      tricks: ['Field strength g = GM/r².', 'Bound orbits have negative total energy.', 'Escape velocity = √(2GM/r).'],
      memory: ['"Field = force per unit mass."', '"Bound systems have negative energy."', 'Escape velocity from energy balance.'],
      board: { CBSE: ['Cl.11 Gravitation'], ICSE: ['Cl.11 Gravitation'], IB: ['DP Fields HL'] },
      comp: ['JEE-Main', 'JEE-Advanced'], keywords: ['gravitational field', 'potential', 'orbits', 'escape velocity'],
      xprereqs: ['physics.I1.circular-motion-gravitation'],
      quiz: [
        { lvl: 2, type: 'mcq', prompt: 'Gravitational field strength is defined as force per unit:', choices: ['mass', 'volume', 'area', 'charge'], answer: 0, explanation: 'g = F/m, the force per unit mass.' },
        { lvl: 3, type: 'mcq', prompt: 'A bound (closed) orbit has total mechanical energy that is:', choices: ['negative', 'positive', 'zero', 'infinite'], answer: 0, explanation: 'Bound systems have negative total energy.' },
      ] },
    { tier: 'A1', order: 3, slug: 'fluids-advanced', title: 'Fluids at A-Level',
      summary: 'Fluid pressure, viscosity and an introduction to Bernoulli\'s principle.',
      outcomes: ['Analyse pressure in static and moving fluids', 'Explain viscosity and flow', 'Apply Bernoulli qualitatively'],
      concepts: [
        ['Static and moving fluids', 'Pressure in a static fluid rises with depth (P = ρgh). In steady flow, the continuity equation says a narrower pipe means faster flow.'],
        ['Bernoulli', 'Where a fluid moves faster, its pressure drops. This explains lift, spray guns and curveballs — energy conservation for flowing fluids.'],
      ],
      mistakes: ['Assuming pressure depends on container shape, not depth.', 'Forgetting continuity: speed increases where area decreases.', 'Misapplying Bernoulli to very viscous or turbulent flow.'],
      tricks: ['Static pressure P = ρgh with depth.', 'Continuity: area × velocity is constant along a pipe.', 'Faster flow ↔ lower pressure (Bernoulli).'],
      memory: ['"Pressure grows with depth: ρgh."', '"Narrower pipe → faster flow."', '"Fast fluid, low pressure."'],
      board: { CBSE: ['Cl.11 Mechanical Properties of Fluids'], ICSE: ['Cl.11 Fluids'], IB: ['DP Fluids HL'] },
      comp: ['JEE-Main', 'JEE-Advanced', 'NEET'], keywords: ['fluids', 'pressure', 'viscosity', 'Bernoulli', 'continuity'],
      xprereqs: ['physics.F2.pressure-density'],
      quiz: [
        { lvl: 2, type: 'mcq', prompt: 'In a narrowing pipe, the fluid speed:', choices: ['increases', 'decreases', 'stays the same', 'drops to zero'], answer: 0, explanation: 'Continuity: smaller area means higher speed.' },
        { lvl: 3, type: 'mcq', prompt: 'By Bernoulli, faster-moving fluid has:', choices: ['lower pressure', 'higher pressure', 'more mass', 'more viscosity'], answer: 0, explanation: 'Speed up ↔ pressure down.' },
      ] },
    { tier: 'A1', order: 4, slug: 'thermodynamics', title: 'Thermodynamics',
      summary: 'The laws of thermodynamics, heat engines and entropy — sharing a spine with chemistry.',
      outcomes: ['State the laws of thermodynamics', 'Analyse heat engines and efficiency', 'Explain entropy intuitively'],
      concepts: [
        ['First and second laws', 'The first law is energy conservation: ΔU = Q − W. The second says entropy (disorder) of an isolated system never decreases — setting a direction for time and limits on engines.'],
        ['Heat engines', 'Engines convert heat to work but never fully; the second law caps their efficiency. This links directly to chemistry\'s energetics.'],
      ],
      mistakes: ['Sign confusion in ΔU = Q − W (work done by vs on the gas).', 'Thinking an engine can be 100% efficient.', 'Treating entropy as merely "messiness" without the energy meaning.'],
      tricks: ['First law: ΔU = Q − W (heat in, work out).', 'No engine beats the Carnot efficiency.', 'Entropy of the universe increases in any real process.'],
      memory: ['"ΔU = Q − W."', '"Entropy never decreases (isolated system)."', 'No perfect engine.'],
      board: { CBSE: ['Cl.11 Thermodynamics'], ICSE: ['Cl.12 Thermodynamics'], IB: ['DP Thermodynamics HL'] },
      comp: ['JEE-Main', 'JEE-Advanced', 'NEET'], keywords: ['thermodynamics', 'entropy', 'heat engine', 'first law'],
      xprereqs: ['physics.I2.thermal-physics'],
      quiz: [
        { lvl: 2, type: 'mcq', prompt: 'The first law of thermodynamics is a statement of:', choices: ['energy conservation', 'entropy increase', 'momentum conservation', 'charge conservation'], answer: 0, explanation: 'ΔU = Q − W conserves energy.' },
        { lvl: 3, type: 'mcq', prompt: 'The entropy of an isolated system in a real process:', choices: ['increases', 'decreases', 'stays exactly constant', 'becomes negative'], answer: 0, explanation: 'The second law: entropy never decreases.' },
      ] },
    { tier: 'A1', order: 5, slug: 'electrostatics', title: 'Electrostatics',
      summary: 'Electric charge, fields, potential and capacitance, using calculus and vectors.',
      outcomes: ['Use Coulomb\'s law and electric fields', 'Relate field and potential', 'Analyse capacitance'],
      concepts: [
        ['Charge and field', 'Like charges repel, unlike attract, with force F = kq₁q₂/r² (an inverse-square law like gravity). The electric field E = F/q describes force per unit charge.'],
        ['Potential and capacitance', 'Electric potential is energy per unit charge; the field points from high to low potential. Capacitance measures stored charge per volt.'],
      ],
      mistakes: ['Confusing electric field with potential.', 'Sign errors with positive/negative charges.', 'Forgetting the inverse-square distance dependence.'],
      tricks: ['Coulomb\'s law mirrors gravity: F ∝ 1/r².', 'Field points from + to − (high to low potential).', 'C = Q/V for capacitance.'],
      memory: ['"Like repels, unlike attracts."', '"E = force per unit charge."', '"C = Q/V."'],
      board: { CBSE: ['Cl.12 Electric Charges & Fields', 'Cl.12 Electrostatic Potential'], ICSE: ['Cl.12 Electrostatics'], IB: ['DP Fields HL'] },
      comp: ['JEE-Main', 'JEE-Advanced', 'NEET'], keywords: ['electrostatics', 'Coulomb', 'electric field', 'potential', 'capacitance'],
      xprereqs: ['math.A1.vectors-3d-geometry'],
      quiz: [
        { lvl: 2, type: 'mcq', prompt: 'Coulomb\'s law force between charges varies with distance as:', choices: ['1/r²', '1/r', 'r', 'r²'], answer: 0, explanation: 'Inverse-square, like gravity.' },
        { lvl: 2, type: 'mcq', prompt: 'Electric field is force per unit:', choices: ['charge', 'mass', 'area', 'volume'], answer: 0, explanation: 'E = F/q.' },
      ] },

    // ================= A2 =================
    { tier: 'A2', order: 1, slug: 'current-electricity-advanced', title: 'Current Electricity & Circuits (Full Rigor)',
      summary: 'DC circuits at depth: networks, power dissipation, and measurement.',
      outcomes: ['Analyse complex resistor networks', 'Compute electrical power', 'Use measurement circuits'],
      concepts: [
        ['Networks and power', 'Combining series and parallel rules solves any resistor network; Kirchhoff\'s laws handle the rest. Power dissipated is P = I²R = VI.'],
        ['Measurement', 'Ammeters (low resistance, in series) and voltmeters (high resistance, in parallel) measure without disturbing the circuit much — a design consequence of the circuit laws.'],
      ],
      mistakes: ['Placing an ammeter in parallel or a voltmeter in series.', 'Using the wrong power formula for the known quantities.', 'Losing track of series/parallel structure in a network.'],
      tricks: ['Power: P = VI = I²R = V²/R — pick the form matching your knowns.', 'Ammeter in series, voltmeter in parallel.', 'Reduce networks stepwise: combine obvious series/parallel groups first.'],
      memory: ['"P = VI = I²R = V²/R."', '"Ammeter series, voltmeter parallel."', 'Reduce networks in stages.'],
      board: { CBSE: ['Cl.12 Current Electricity'], ICSE: ['Cl.12 Electricity'], IB: ['DP Electricity HL'] },
      comp: ['JEE-Main', 'JEE-Advanced', 'NEET'], keywords: ['circuits', 'power', 'ammeter', 'voltmeter', 'networks'],
      xprereqs: ['physics.I2.electricity-ii'],
      quiz: [
        { lvl: 2, type: 'numeric', prompt: 'Power dissipated by 2 A through 3 Ω?', answer: 12, tolerance: 0, unit: 'W', explanation: 'P = I²R = 4 × 3 = 12 W.' },
        { lvl: 2, type: 'mcq', prompt: 'A voltmeter should be connected:', choices: ['in parallel', 'in series', 'in place of the battery', 'across the ammeter'], answer: 0, explanation: 'It measures potential difference across a component, in parallel.' },
      ] },
    { tier: 'A2', order: 2, slug: 'electromagnetic-induction', title: 'Magnetic Effects & Electromagnetic Induction',
      summary: 'Magnetic forces, Faraday\'s and Lenz\'s laws, and AC circuits — using differential equations.',
      outcomes: ['Compute magnetic force on currents/charges', 'Apply Faraday\'s and Lenz\'s laws', 'Analyse simple AC circuits'],
      concepts: [
        ['Induction', 'A changing magnetic flux induces an EMF (Faraday); the induced current opposes the change (Lenz). This is how generators and transformers work.'],
        ['AC circuits', 'Alternating current varies sinusoidally; inductors and capacitors respond to its rate of change, described naturally by differential equations.'],
      ],
      mistakes: ['Getting the direction of the induced current wrong (Lenz opposes the change).', 'Forgetting that only changing flux induces EMF.', 'Treating AC like DC in reactive components.'],
      tricks: ['Induced EMF = −rate of change of flux (Faraday/Lenz).', 'Steady flux → no induction; change is essential.', 'Inductors resist current changes; capacitors resist voltage changes.'],
      memory: ['"Changing flux induces EMF."', '"Lenz opposes the change."', 'AC is calculus in a circuit.'],
      board: { CBSE: ['Cl.12 Electromagnetic Induction', 'Cl.12 Alternating Current'], ICSE: ['Cl.12 Electromagnetism'], IB: ['DP Fields HL'] },
      comp: ['JEE-Main', 'JEE-Advanced', 'NEET'], keywords: ['induction', 'Faraday', 'Lenz', 'AC', 'flux'],
      xprereqs: ['math.A2.differential-equations'],
      quiz: [
        { lvl: 2, type: 'mcq', prompt: 'An EMF is induced in a coil only when the magnetic flux:', choices: ['changes', 'is large', 'is zero', 'is constant'], answer: 0, explanation: 'Faraday\'s law: induction requires changing flux.' },
        { lvl: 3, type: 'mcq', prompt: 'Lenz\'s law says the induced current:', choices: ['opposes the change causing it', 'adds to the change', 'is always clockwise', 'is zero'], answer: 0, explanation: 'It opposes the flux change — energy conservation.' },
      ] },
    { tier: 'A2', order: 3, slug: 'optics-advanced', title: 'Optics at Full Rigor',
      summary: 'Wave optics: interference, diffraction and the wave nature of light.',
      outcomes: ['Explain interference and diffraction', 'Analyse the double-slit experiment', 'Relate path difference to fringes'],
      concepts: [
        ['Wave optics', 'Light\'s wave nature shows up as interference (double-slit fringes) and diffraction (spreading around edges). Path difference of a whole wavelength gives bright fringes.'],
        ['Evidence for waves', 'These effects cannot be explained by rays alone — they were the historic proof that light is a wave, later refined by quantum theory.'],
      ],
      mistakes: ['Using ray optics to explain interference.', 'Confusing constructive (whole-λ path difference) and destructive conditions.', 'Forgetting diffraction increases as the gap approaches the wavelength.'],
      tricks: ['Bright fringe when path difference = whole number of wavelengths.', 'Narrower slits diffract (spread) more.', 'Fringe spacing grows with wavelength and screen distance.'],
      memory: ['"Whole λ path difference → bright fringe."', '"Narrow slit, wide spread."', 'Interference proves light is a wave.'],
      board: { CBSE: ['Cl.12 Wave Optics'], ICSE: ['Cl.12 Wave Optics'], IB: ['DP Wave Phenomena HL'] },
      comp: ['JEE-Main', 'JEE-Advanced', 'NEET'], keywords: ['wave optics', 'interference', 'diffraction', 'double slit'],
      xprereqs: ['physics.I2.waves-ii'],
      quiz: [
        { lvl: 2, type: 'mcq', prompt: 'Double-slit bright fringes occur where the path difference is:', choices: ['a whole number of wavelengths', 'half a wavelength', 'zero only', 'any value'], answer: 0, explanation: 'Constructive interference needs nλ path difference.' },
        { lvl: 2, type: 'mcq', prompt: 'Diffraction is most pronounced when the gap is:', choices: ['comparable to the wavelength', 'much larger than the wavelength', 'infinite', 'zero'], answer: 0, explanation: 'Spreading is strongest when slit width ≈ wavelength.' },
      ] },
    { tier: 'A2', order: 4, slug: 'modern-physics', title: 'Modern Physics',
      summary: 'The photoelectric effect, atomic models, nuclei and radioactivity, and semiconductor basics.',
      outcomes: ['Explain the photoelectric effect', 'Describe atomic and nuclear models', 'Understand radioactivity and half-life'],
      concepts: [
        ['Quantum beginnings', 'The photoelectric effect shows light comes in packets (photons) with energy E = hf. This launched quantum physics and explained atomic spectra.'],
        ['Nuclei and radioactivity', 'Unstable nuclei decay (alpha, beta, gamma), each decay halving the sample over one half-life. Mass converts to energy via E = mc².'],
      ],
      mistakes: ['Thinking brighter light (not higher frequency) ejects electrons in the photoelectric effect.', 'Confusing the three decay types.', 'Treating half-life as the total lifetime.'],
      tricks: ['Photon energy E = hf; only frequency above threshold ejects electrons.', 'After n half-lives, 1/2ⁿ of the sample remains.', 'Alpha = helium nucleus, beta = electron, gamma = photon.'],
      memory: ['"E = hf." "E = mc²."', '"Half-life halves the sample each time."', 'Photoelectric: frequency, not brightness, matters.'],
      board: { CBSE: ['Cl.12 Dual Nature', 'Cl.12 Atoms & Nuclei', 'Cl.12 Semiconductors'], ICSE: ['Cl.12 Modern Physics'], IB: ['DP Atomic/Nuclear HL'] },
      comp: ['JEE-Main', 'JEE-Advanced', 'NEET'], keywords: ['photoelectric', 'atom', 'nucleus', 'radioactivity', 'half-life'],
      quiz: [
        { lvl: 2, type: 'mcq', prompt: 'In the photoelectric effect, electrons are ejected only if light\'s ___ is high enough.', choices: ['frequency', 'brightness', 'wavelength', 'speed'], answer: 0, explanation: 'Photon energy E = hf; frequency must exceed a threshold.' },
        { lvl: 2, type: 'numeric', prompt: 'After 3 half-lives, what fraction of a sample remains? (as a decimal)', answer: 0.125, tolerance: 0.001, explanation: '(1/2)³ = 1/8 = 0.125.' },
      ] },
    { tier: 'A2', order: 5, slug: 'experimental-physics', title: 'Experimental Physics Portfolio', core: true,
      summary: 'Error analysis, real measurement and scientific write-ups — the capstone lab strand.',
      outcomes: ['Estimate and propagate uncertainty', 'Design and record experiments', 'Write clear lab reports'],
      concepts: [
        ['Uncertainty is unavoidable', 'Every measurement has an uncertainty; reporting it honestly is part of the result. Uncertainties combine by defined rules when quantities are added or multiplied.'],
        ['From data to conclusion', 'Good experiments control variables, repeat for reliability, and use graphs (often straight-line fits) to extract results. The write-up must let another person reproduce it.'],
      ],
      mistakes: ['Reporting a result without its uncertainty.', 'Confusing precision (repeatability) with accuracy (closeness to true).', 'Cherry-picking data instead of reporting all of it.'],
      tricks: ['Repeat measurements and average to reduce random error.', 'Plot data and fit a line to extract gradients as results.', 'Add absolute uncertainties when adding; add relative ones when multiplying.'],
      memory: ['"No result without an uncertainty."', '"Precision ≠ accuracy."', 'Reproducibility is the standard.'],
      board: { CBSE: ['Cl.11-12 Practical Physics'], ICSE: ['Cl.11-12 Practical'], IB: ['DP Physics IA'] },
      comp: [], keywords: ['error analysis', 'uncertainty', 'measurement', 'lab report'],
      xprereqs: ['math.I1.statistics-ii'],
      quiz: [
        { lvl: 2, type: 'mcq', prompt: 'A set of measurements is precise but not accurate. This means they are:', choices: ['close to each other but off the true value', 'close to the true value but scattered', 'both correct and scattered', 'random'], answer: 0, explanation: 'Precision = repeatability; accuracy = closeness to truth.' },
        { lvl: 2, type: 'mcq', prompt: 'To reduce random error you should:', choices: ['repeat and average', 'measure once carefully', 'ignore outliers silently', 'use a bigger ruler'], answer: 0, explanation: 'Averaging repeats reduces random error.' },
      ] },
  ],
};
